### ISSUE TITLE
Error when trying to use gina in gina buffers

### ISSUE THREAD

**Issue by SanchayanMaity** [lewis6991/gitsigns.nvim#1]
First of all thank you for your work on this. Been using it since 2 days.

I notice an error when trying to use [gina](https://github.com/lambdalisue/gina.vim).

![2020-10-28-111111_3838x2126_scrot](https://user-images.githubusercontent.com/5573968/97397436-39365d00-190f-11eb-9b37-975db7e92825.png)

Not sure why this occurs. Do you think this could be because of gitsigns running on a buffer which should not be handled by gitsigns?

Am on neovim nightly and gitsigns is at latest commit.

**Comment by lewis6991** [comment]
Thanks for reporting this. Been working on this and hopefully the latest changed should address this. Please report otherwise.

**Comment by SanchayanMaity** [comment]
Seems fixed now. Thank you very much :+1: .

Closing the issue.
