### ISSUE TITLE
Incorrect sign placed for delete/topdelete

### ISSUE THREAD

**Issue by sunjon** [lewis6991/gitsigns.nvim#10]
I've configured the sign characters, but there seems to be an erroneous character being placed (line 2, window 2):

![signs](https://raw.githubusercontent.com/sunjon/images/master/signs.png)

I had a brief look through the code, but it wasn't immediatly obvious what the cause was.

**Comment by lewis6991** [comment]
This looks like a terminal problem to me. You can't overlap characters in a terminal so my guess is that this is some artifact caused from a combination of terminal, symbols and font.

Can you try changing one of those (symbol, font, terminal) to see if the issue persists?

**Comment by sunjon** [comment]
Found the culprit:
`:verb hi DiffSignDelete                                                                                                                                                                                                                                                                 
DiffSignDelete xxx gui=strikethrough guibg=#202020 guisp=#fb4934                                                                                                                                                                                                                        
        Last set from ~/.config/nvim/after/plugin/gruvbox8.vim line 118 
``
I 'inherited' the strikethrough property when copying the highlight group for regular diffs.
Apologies for the noise!
