### ISSUE TITLE
Sign column not respecting colors from gruvbox

### ISSUE THREAD

**Issue by ChocolateOverflow** [lewis6991/gitsigns.nvim#1006]
### Description

Before c02516144a4f, my sign column colors were from [Gruvbox](https://github.com/morhetz/gruvbox) and my use of [`g:gruvbox_invert_signs`](https://github.com/morhetz/gruvbox/wiki/Configuration#ggruvbox_invert_signs) made the signs obvious. However, after applying c02516144a4f, my signs have different colors & no inversion.

### Neovim version

NVIM v0.10.0-dev-2954+g13ebfafc9

### Operating system and version

Arch Linux 6.8.7-arch1-1

### Expected behavior

My color configs for gruvbox are used, including the color inversion between foreground & background

### Actual behavior

Different colors from my gruvbox config (though gruvbox hasn't changed in a long time)

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  gruvbox = 'https://github.com/morhetz/gruvbox',
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

vim.g.gruvbox_invert_signs = 1
vim.g.gruvbox_contrast_dark = 'hard'
vim.cmd.colorscheme 'gruvbox'

require('gitsigns').setup{
  debug_mode = true,
}
```

### Steps to reproduce

1. Find/create a file with git changes
2. `nvim --clean -u minimal.lua file_with_changes`
3. Look at the git sign colors

**Comment by lewis6991** [comment]
Please follow the template as provided and do not use lazy.nvim.

**Comment by ChocolateOverflow** [comment]
@lewis6991 I've updated to use your install method, but I don't know why it's failing to `require('gruvbox')`. I also don't know enough about theming to just put in some hard-coded values generated from my usual configs.

**Comment by ChocolateOverflow** [comment]
Nevermind, I figured it out.
I just had to set the `vim.g` stuff before calling `require('gitsigns').setup()`, but `vim.cmd.colorscheme 'gruvbox'` after sourcing the `gruvbox` plugin`, so I just put those in a script/function called when sourcing `gruvbox`.
