### ISSUE TITLE
If a line of code is too long and breaks, the gitsign lines should be continuous.

### ISSUE THREAD

**Issue by w1475963** [lewis6991/gitsigns.nvim#1014]
If a line of code is too long and breaks, the gitsign lines should be continuous.
![IMG_20240508_031557](https://github.com/lewis6991/gitsigns.nvim/assets/46069701/d81b20f1-3c57-450f-ae90-16d85f4ed8a0)

``` bash
nvim --version
NVIM v0.10.0-dev-3086+g783c1e596
```

**Comment by lewis6991** [comment]
This is an issue with neovim. Cannot be fixed here.
