### ISSUE TITLE
signs still persisting after comming and pushing the code

### ISSUE THREAD

**Issue by Antony-AXS** [lewis6991/gitsigns.nvim#1043]
git added, removed and committed signs parallelly aligned with the number-line should go away after pushing the code , but it's not, its still persisting

**Comment by Antony-AXS** [comment]
git added, removed and committed signs parallelly aligned with the number-line should go away after pushing the code , but it's not, its still persisting

**Comment by xiuxiubiu** [comment]
same problem

**Comment by lkzz** [comment]
same problem

**Comment by lewis6991** [comment]
Issue template ignored. Closing until information is provided.

**Comment by eshepelyuk** [comment]
@Antony-AXS @xiuxiubiu 
try to pin to this commit - looks like v0.9.0 completely broke hunks navigation and hunks stage\unstage

https://github.com/lewis6991/gitsigns.nvim/commit/de18f6b749f6129eb9042a2038590872df4c94a9
