### ISSUE TITLE
Deriving highlight doesn't work when switching colorscheme

### ISSUE THREAD

**Issue by meatcar** [lewis6991/gitsigns.nvim#105]
**Describe the bug**
Changing colorscheme makes the sign column markers plain and gray. 

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.local/share/nvim/pack/packager/start'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

"https://github.com/gruvbox-community/gruvbox sets GitGutter*
set runtimepath^=$PLUGIN_DIRECTORY/gruvbox         
"https://github.com/NLKNguyen/papercolor-theme sets SignifySign*
set runtimepath^=$PLUGIN_DIRECTORY/PaperColor      

" re-setup gitsigns after every colorscheme change
autocmd ColorScheme * lua require('gitsigns').setup{debug_mode = true}
```

1. Run `nvim -u init.vim --noplugin <somefile>`
1. Run `:colorscheme gruvbox`, then `:w` to show the signs in beautiful color. 
2. Run `:colorscheme PaperColor`, see the signs are now gray.

**Observed output**
```vim
:colorscheme gruvbox

:lua require('gitsigns').debug_messages()
dprint(nil): Deriving GitSignsAdd from GitGutterAdd
dprint(nil): Deriving GitSignsChange from GitGutterChange
dprint(nil): Deriving GitSignsDelete from GitGutterDelete
:highlight GitSignsAdd
GitSignsAdd    xxx links to GitGutterAdd
:highlight GitGutterAdd
GitGutterAdd   xxx links to GruvboxGreenSign

:colorscheme PaperColor

:lua require('gitsigns').debug_messages()
dprint(nil): Deriving GitSignsAdd from GitGutterAdd
dprint(nil): Deriving GitSignsChange from GitGutterChange
dprint(nil): Deriving GitSignsDelete from GitGutterDelete
dprint(nil): Deriving GitSignsAdd from DiffAdd
dprint(nil): Deriving GitSignsChange from DiffChange
dprint(nil): Deriving GitSignsDelete from DiffDelete
dprint(nil): Deriving GitSignsChange from DiffChange
dprint(nil): Deriving GitSignsDelete from DiffDelete
:highlight GitSignsAdd
GitSignsAdd    xxx links to GitGutterAdd
:highlight GitGutterAdd
GitGutterAdd   xxx links to GruvboxGreenSign
```

**Additional context**
System: Linux (NixOS)
Neovim version: NVIM v0.5.0-dev (nightly)

**Comment by lewis6991** [comment]
Thanks for raising. I can see why this wouldn't work. Highlights are defined during setup(). Just need to add an autocmd to redefine them when the colorscheme changes.

**Comment by meatcar** [comment]
An autocmd would be nice, however I don't think that's the root issue here. An autocmd is set up to call `setup()` whenever the colorscheme changes in the init.vim above, and the debug messages show that highlight redefinition is attempted.

My best guess is the derivation flow [short-circuits here](https://github.com/lewis6991/gitsigns.nvim/blob/2e371a3b89a85ea74afcd2f2926b23919a96e1c8/teal/gitsigns/highlight.tl#L23).  `pcall(vim.api.nvim_get_hl_by_name)` returns true even if the highlight is reset. 

There is no way for a colorscheme to remove a highlight once it is set. `:help :hi-link` advises to set it to `NONE`, but inspecting the highlight shows a different message than when it doesn't exist:

```vim
:highlight asdf
E411: highlight group not found: asdf
:highlight link asdf DiffAdd
:highlight asdf
asdf           xxx links to DiffAdd
:highlight link asdf NONE
:highlight asdf
asdf           xxx cleared
```
Subsequently, the suspiciouns are confirmed with lua:
```vim
:lua print(vim.inspect(pcall(vim.api.nvim_get_hl_by_name, "asdf", false)))
true
:lua print(vim.inspect(vim.api.nvim_get_hl_by_name("asdf", false)))
{
  [true] = 6
}
```

Naively changing [the if statement](https://github.com/lewis6991/gitsigns.nvim/blob/2e371a3b89a85ea74afcd2f2926b23919a96e1c8/lua/gitsigns/highlight.lua#L21..L24) seems to fix the issue, but I'm not sure if there is a more nuanced approach. I can PR this if it looks acceptable.
```lua
local to_exists, to_hl = pcall(api.nvim_get_hl_by_name, to, false)
if to_exists and to_hl[true] ~= 6 then
   return
end
```

**Comment by lewis6991** [comment]
Ah I missed that you added an autocommand to call setup. I should have pointed out that setup isn't designed to be called more than once (yet), and the highlight code isn't either. But as you've found it probably only requires a few tweaks to get it right.

I was going to refactor the highlight code into a function (separated out from signs) and fix it so it can be reapplied and then throw it into a colorscheme autocommand.

Since you've already taken a look at the code a PR would be greatly appreciated.

**Comment by lewis6991** [comment]
Also checking non equality with `6` won't work. I bet that's the highlight ID or something. A cleared highlight group probably returns something you can check against though, just need to figure out what.

**Comment by meatcar** [comment]
That's the nuanced approach I was looking for :) PR coming shortly.
