### ISSUE TITLE
Feature Request: Unstage Changes on Current Line

### ISSUE THREAD

**Issue by hsayed21** [lewis6991/gitsigns.nvim#1051]
## Description

I would like to request a feature that allows users to unstage changes on the current line where the cursor is focused. This functionality would complement the existing `stage_hunk`, `reset_hunk`, and `undo_stage_hunk` functions by providing more granular control over staging and unstaging changes.

## Proposed Solution

A new function, `unstage_hunk`, could be introduced with the following behavior:
- Unstages changes on the line where the cursor is focused.
- If the line is part of a hunk, only the changes on that specific line are removed from the staging area, while the rest of the hunk remains staged.

Thank you for considering this feature request. I believe it would be a valuable addition to the `gitsigns.nvim` plugin, enhancing its utility and user experience.

### Neovim version

_

### Operating system and version

_

### Expected behavior

_

### Actual behavior

_

### Minimal config

```Lua
_
```

### Steps to reproduce

 _

### Gitsigns debug messages

_

**Comment by lewis6991** [comment]
This is already possible with `stage_hunk` which toggles the stage status.

**Comment by hsayed21** [comment]
I tried it nothing changed in two modes normal or visual
```lua
_map("n", "<leader>gs", gs.stage_hunk, "Stage hunk")
_map("v", "<leader>gs", function() gs.stage_hunk({ vim.fn.line("."), vim.fn.line("v") }) end, "Stage hunk")
```

**Comment by hsayed21** [comment]
https://github.com/lewis6991/gitsigns.nvim/assets/47378309/0d58fd7b-67bd-4f85-904a-7bbd6497c15a

**Comment by lewis6991** [comment]
You need to pull in the latest changes to include https://github.com/lewis6991/gitsigns.nvim/commit/b8cf5e8efaa0036d493a2e2dfed768c3a03fac73

**Comment by hsayed21** [comment]
Sorry, but I don't understand what I should do. Do you mean I need to update the plugin?

**Comment by lewis6991** [comment]
Yes. Make sure to always have the latest version installed before raising issues on a tracker.

**Comment by hsayed21** [comment]
Sorry for not paying attention. 
I did the update and it worked, but there's a problem in visual mode where 'unstage' doesn't work

**Comment by xzbdmw** [comment]
Yeah unstage does not work in visual mode
```lua
                map("v", "<leader>sh", function()
                    gs.stage_hunk({ vim.fn.line("."), vim.fn.line("v") })
                end)
```

**Comment by lewis6991** [comment]
> @lewis6991 this should be reopen?

That won't fix it. A PR might.
