### ISSUE TITLE
[Proposal] Sapling signs

### ISSUE THREAD

**Issue by dmtrKovalenko** [lewis6991/gitsigns.nvim#1063]
I would be happy to contribute an adapter to use this plugin with sapling https://sapling-scm.com/ which is unfortunately is not git compatible which is a pain in neovim ecosystem. 

But this will require some refactoring making a standard interface for getting hunks and implementing a new adapter. Please let me know what do you think about this and if it worth to open a PR for. that.

**Comment by lewis6991** [comment]
Sorry but this is an explicit non-goal: https://github.com/lewis6991/gitsigns.nvim?tab=readme-ov-file#support-for-other-vcs

**Comment by lewis6991** [comment]
You might have better luck creating an adapter for https://github.com/echasnovski/mini.diff
