### ISSUE TITLE
Globals from `teal/gitsigns/types.lua` end up as globals elsewhere

### ISSUE THREAD

**Issue by YaBoiBurner** [lewis6991/gitsigns.nvim#107]
The types from https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns/types.tl are loaded at https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns.tl#L1.
As a result, https://github.com/lewis6991/gitsigns.nvim/blob/main/lua/gitsigns.lua#L1 also ends up loading https://github.com/lewis6991/gitsigns.nvim/blob/main/lua/gitsigns/types.lua, which creates the `CacheEntry`, `SignName`, `SignsConfig`, `StatusObj`, `Config`, `SignType`, `Sign`, and `Hunk` globals.

Said globals are never referenced in the code, so there's no need to set them.

**Comment by lewis6991** [comment]
Thanks for raising. Globals should all be cleaned up now.
