### ISSUE TITLE
When scrolling line by line, the blame window does not scroll with the main window

### ISSUE THREAD

**Issue by ofseed** [lewis6991/gitsigns.nvim#1071]
### Description

`:Gitsigns blame` add gaps to the main window when the diff is smaller than two lines. I found that when scrolling line by line using `j` or `<C-e>`, the blame window will not follow the scroll when the one gap is scrolled out of the screen.

[Example.webm](https://github.com/lewis6991/gitsigns.nvim/assets/61115159/5cf83ea3-ae30-4b78-98e8-efa35920cf8b)

### Neovim version

NVIM v0.11.0-dev-3461+g9e436251d (latest master currently)

### Operating system and version

6.9.6-arch1-1

### Expected behavior

The two windows should scroll together and be always aligned.

### Actual behavior

If it is a gap rather than a line of text be scrolled out the screen, the blame window will not be scroll following the main window.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
end
vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Clone gitsigns.nvim
2. Create `minimal.lua` in place and save it after copying its content
3. Open a file of the `gitsigns.nvim` repo by `nvim -u minimal.lua lua/gitsigns.lua`
4. Scroll line by line

**Comment by lewis6991** [comment]
This is probably a limitation of virtual_lines in Neovim. Not sure if we can fix that exactly.

**Comment by ofseed** [comment]
I also guessed that it might be an upstream problem, but there will not be this issue when just using `diff-mode`, which utilizes `set scrollbind` too. I have no idea how to make it work properly.

**Comment by lewis6991** [comment]
Diff mode doesn't use extmarks and injects filler lines directly.

**Comment by lewis6991** [comment]
Raised https://github.com/neovim/neovim/issues/29751 . Not sure what we can do to mitigate this in the meantime other than removing the virtual lines.

**Comment by ofseed** [comment]
The [upstream fix](https://github.com/neovim/neovim/issues/29751) works well, thank you for your great work!
