### ISSUE TITLE
Be able to get git repository status from global variable

### ISSUE THREAD

**Issue by Aryonal** [lewis6991/gitsigns.nvim#1075]
### Description

Thanks to `vim.b.gitsigns_*` variables, it's really easy to get git status for a buffer. However, I don't find a similar way to fetch the repository git status. I think it would be helpful if we could get the info from a global variable.

### Proposal

Create global variables for repository git status, e.g. `vim.g.gitsigns_status`, and `vim.g.gitsigns_status_dict`.

#### Stored information

On different verbosity levels, I would imagine the following information could be stored, from low to high

1. A flag whether the repo has changed
2. The number of changed files in total
3. Sophisticated information on numbers of files in different statuses, like modified, added, staged, etc.

**Comment by lewis6991** [comment]
Sorry but I'll pass, Gitsigns isn't needed for this.

**Comment by Aryonal** [comment]
@lewis6991 Thank you for responding!

Can I know why isn't Gitsigns needed for this? My apologise if I missed some obvious reasons, or existing implementations.

The reason I ask is that I tried to implement it on my local and it's working, if it's an acceptable feature, I would like to raise a PR if it's allowed.

**Comment by WieeRd** [comment]
I was about to request the same feature and discovered this issue.
The main reason I wanted this feature is to use it in a global statusline (`laststatus=3` or tabline).
If I were to use buffer-local variables in this situation, they would return nil when the window focus is on files outside the repository, such as help page.
I would really appreciate `g:` variants of currently provided `b:` variables that represent the git repository status of current `$PWD`.

Like @Aryonal asked, are we missing something? Is there a trivial way to fetch this information already?
Also, I'd like to point out that while `g:gitsigns_head` is documented on the help page, they are not actually supported by gitsigns. Perhaps it has been removed and the docs are outdated?

**Comment by lewis6991** [comment]
> Also, I'd like to point out that while g:gitsigns_head is documented on the help page, they are not actually supported by gitsigns. Perhaps it has been removed and the docs are outdated?

`g:gitsigns_head` is supported. I don't know why you think it isn't.

Gitsigns does it contain any code for parsing `git status`, and there is no plans to add any.

**Comment by WieeRd** [comment]
> Gitsigns does it contain any code for parsing `git status`, and there is no plans to add any.

That's unfortunate. Didn't expect it to involve implementing a whole new feature, though.
Wouldn't it be possible to adjust the existing code that updates the `b:` variables to check if `$PWD` is under `b:gitsigns_status_dict["root"]`, and if it is, update the `g:` variables with the information just acquired for the buffer local variables?

> `g:gitsigns_head` is supported. I don't know why you think it isn't.

I forgot that the repositories I was on is a bit unconventional.
I checked again and `g:gitsigns_head` is indeed available on ordinary repositories.

However, `:echo g:gitsigns_head` seems to always fail when:

1. `$GIT_DIR` and `$GIT_WORK_TREE` are explicitly set. I use bare repository to manage my dotfiles and set these variables before launching neovim when I want to edit my dotfiles.
3. When inside a worktree.

In both cases, gitsigns correctly shows the diff signs and `b:` variables are available. However, `g:gitsigns_head` is not. Is this supposed to happen? Are separate git dirs and worktrees not supported in gitsigns?

**Comment by lewis6991** [comment]
> $GIT_DIR and $GIT_WORK_TREE are explicitly set. I use bare repository to manage my dotfiles and set these variables before launching neovim when I want to edit my dotfiles.

Possibly a bug or missing feature, supporting those variables are in scope. Same for work trees.
