### ISSUE TITLE
attempt to index local 'info' (a nil value )

### ISSUE THREAD

**Issue by alichtman** [lewis6991/gitsigns.nvim#1085]
### Description

When I am making a verbose git commit, `gitsigns` immediately throws an error. Pinning to `v0.9.0` resolves the error.

```
Error executing luv callback:
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...an/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:34: attempt to index local 'info' (a nil value
)
stack traceback:
        ...an/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua: in function 'get_gitdir_and_head'
        ...an/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:54: in function <...an/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:37>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function 'on_exit'
        /usr/local/share/nvim/runtime/lua/vim/_system.lua:300: in function </usr/local/share/nvim/runtime/lua/vim/_system.lua:270>
```
 

### Neovim version

NVIM v0.11.0-dev-401+gbcb17689d

### Operating system and version

Linux alpenglow 6.9.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 27 18:11:45 UTC 2024 x86_64 GNU/Linux

### Expected behavior

I expect not to see an error. It appears to blame to this line: https://github.com/lewis6991/gitsigns.nvim/blame/main/lua/gitsigns.lua#L32

### Actual behavior

I see an error.

### Steps to reproduce

I was not able to repro with a minimal config, however, this seems to blame to 220446c8c86a280180d852efac60991eaf1a21d4. Pinning to the commit directly before it also resolves the issue.

**Comment by Kaiser-Yang** [comment]
This seem the same with mine #1086
