### ISSUE TITLE
Error occurs  when using nvim as git editor with git signs

### ISSUE THREAD

**Issue by Kaiser-Yang** [lewis6991/gitsigns.nvim#1086]
### Description

I use nvim as my git editor, when I use `git commit`, it gives me:
![image](https://github.com/user-attachments/assets/40e5cae6-4032-4039-83e3-7ab89ddafee7)

I've tested that when removing the `gitsigns` plugin, the error messages will be gone.

### Neovim version

0.10.0

### Operating system and version

Ubuntu 22.04

### Actual behavior

Error executing luv callback: 
 ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this messa 
 age: ...er/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:34: attempt to index local 'info' ( 
 (a nil value) 
 stack traceback: 
 ...er/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua: in function 'get_gitdir_and_head' 
 ...er/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:54: in function <...er/.local/share/nvi 
 im/lazy/gitsigns.nvim/lua/gitsigns.lua:37> 
 stack traceback: 
 [C]: in function 'error' 
 ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'cb' 
 ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:127: in function 'on_exit' 
 /opt/nvim-linux64/share/nvim/runtime/lua/vim/_system.lua:300: in function </opt/nvim-linux64/share/ 
 /nvim/runtime/lua/vim/_system.lua:270> 
 [C]: in function 'ui_attach' 
 .../.local/share/nvim/lazy/noice.nvim/lua/noice/ui/init.lua:77: in function 'enable' 
 ...ser/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:69: in function 'enable' 
 ...ser/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:23: in function <...ser/.local/share/nv 
 vim/lazy/noice.nvim/lua/noice/init.lua:19> 
 [C]: in function 'xpcall' 
 ...local/share/nvim/lazy/noice.nvim/lua/noice/util/call.lua:149: in function 'try' 
 ...ser/.local/share/nvim/lazy/noice.nvim/lua/noice/init.lua:19: in function <...ser/.local/share/nv 
 vim/lazy/noice.nvim/lua/noice/init.lua:18> 

### Minimal config

```Lua
require('gitsigns').setup()
```

### Steps to reproduce

use `git commit` to open nvim with gitcommit files.

**Comment by lewis6991** [comment]
Repro doesn't work.

**Comment by Kaiser-Yang** [comment]
> Repro doesn't work.

All the configurations are available [here](https://github.com/Kaiser-Yang/dotfiles/tree/temp)

**Comment by Kaiser-Yang** [comment]
My git config:
```
[core]
	editor = nvim
	filemode = false
```

**Comment by Kaiser-Yang** [comment]
> Repro doesn't work.

Oh, I've make a minimal to reproduce this: [git-signs-reproduce](https://github.com/Kaiser-Yang/dotfiles/tree/git-signs-reproduce)

**Comment by Kaiser-Yang** [comment]
Just copy the .config to home diretory:
![image](https://github.com/user-attachments/assets/f464abbe-1548-4349-bdbd-74fd923503b9)

Then make sure git editor is nvim, use `git commit` will reproduce:
![image](https://github.com/user-attachments/assets/8e4612a8-bac5-4223-8f33-60b78bf2a4bc)

**Comment by lewis6991** [comment]
Fixed in https://github.com/lewis6991/gitsigns.nvim/commit/e784e5a078f993f7218b8a857cb581d5b9ca42dc
