### ISSUE TITLE
WARN: gitsigns: Ignoring invalid configuration field 'signs_staged' 

### ISSUE THREAD

**Issue by sergiomb2** [lewis6991/gitsigns.nvim#1092]
### Description

after latest updates https://www.reddit.com/r/neovim/comments/1drxdoy/warn_gitsigns_ignoring_invalid_configuration/

### Neovim version

NVIM v0.9.5

### Operating system and version

Fedora e Ubutun 

### Expected behavior

not warning every time that we open neovim

### Actual behavior

warning every time that we open neovim

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
end
vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

nvim file

**Comment by sergiomb2** [comment]
I'm newbie  on neovim , neovim by default updates all from git, which is terrible in my POV , as I reported at least this happened to 3 persons see the reddit link , I which I know restore the previous configuration , I use Lazyvim

**Comment by sergiomb2** [comment]
the commit just after tag [v0.9.0](https://github.com/lewis6991/gitsigns.nvim/releases/tag/v0.9.0) fix this issue https://github.com/lewis6991/gitsigns.nvim/commit/b8cf5e8efaa0036d493a2e2dfed768c3a03fac73

**Comment by grantwforsythe** [comment]
I was facing this issue on my work computer which runs Windows, but was not on my personal laptop that runs Ubuntu. I was pinned to https://github.com/lewis6991/gitsigns.nvim/commit/0b04035bb7b3c83e999b9676e2fb46fd0aa9f910 where the issue was present. After pinning to https://github.com/lewis6991/gitsigns.nvim/commit/b8cf5e8efaa0036d493a2e2dfed768c3a03fac73 as @sergiomb2 suggested, the issue is resolved!
```lua
{
  "lewis6991/gitsigns.nvim",
  -- https://github.com/lewis6991/gitsigns.nvim/issues/1092#issuecomment-2403266376
  commit = "b8cf5e8efaa0036d493a2e2dfed768c3a03fac73",
  -- version = "v0.*",
  opts = {}
}

```


Specs:
- Windows OS Build19045.5131

**Comment by sergiomb2** [comment]
JFYI this issue is closed , maybe open a new one IDK
