### ISSUE TITLE
Gitsigns is messing with Intro.

### ISSUE THREAD

**Issue by hiddenruins** [lewis6991/gitsigns.nvim#111]
**Describe the bug**
When `nvim` is started the intro screen flashes quickly and an empty buffer is shown. This is happening since  9e1f431b39cb38731f5c06e392b4737fc6c530da. I think gitsigns should not attach when just `nvim` is run. Going back to older commit solves it.

1. From the terminal enter `nvim`
3. See error

**Problem**
https://user-images.githubusercontent.com/5569621/112794540-c03a5d80-9086-11eb-81ef-f5d03c25ff38.mp4

**Expected**
https://user-images.githubusercontent.com/5569621/112794566-ca5c5c00-9086-11eb-85b5-76c369a40ee0.mp4

**Observed output**
Include the output of `:lua require('gitsigns').debug_messages()`
```
dprint(nil): Deriving GitSignsChange from GitGutterChange
dprint(nil): Deriving GitSignsDelete from GitGutterDelete
dprint(nil): Deriving GitSignsAdd from GitGutterAdd
```

**Additional context**
System: Arch Linux
NVIM v0.5.0-dev+1186-g8665a96b9
Build type: Release
LuaJIT 2.1.0-beta3

**Comment by fbunt** [comment]
This has started happening again.
