### ISSUE TITLE
How to reresolve highlights?

### ISSUE THREAD

**Issue by simonmandlik** [lewis6991/gitsigns.nvim#1112]
### Description

Whenever I'm
- loading gitsigns before a colorscheme,
- or trying out different colorscheme interactively (after loading gitsigns) that newly defines e.g. `GitGutterAdd` highlight group,

highlight groups are not updated after executing `setup_highlights`. This has now become more annoying because neovim defines its own theme, and thus `Added` highlight group is always defined. This means that, as a consequence of https://github.com/lewis6991/gitsigns.nvim/issues/780, gitsigns will associate `GitSignsAdd` with `Added`, and even if the colorscheme is changed, the highlight group is not updated.

The two solutions are
- loading colorscheme always before gitsigns, and
- redefining all highlight groups manually.

The latter feels quite unnecessary and complicated. And the first solutions doesn't work for people that like to frequently manually change the colorscheme, or programatically change the colorscheme (e.g. following system light / dark appearance)

Would it be possible to add a parameter to `setup_highlights` that would ignore already defined highlight groups and reset everything from scratch?

Thanks!

**Comment by lewis6991** [comment]
No config. Changing colour schemes during the same session is pretty niche. Will accept a PR if you can figure out how to workaround this.

If this is really important to you, it's probably better not to rely on Gitsigns' fallback links and thus should define them yourself.
