### ISSUE TITLE
Gitsigns setqflist should work for the whole repo

### ISSUE THREAD

**Issue by konradmalik** [lewis6991/gitsigns.nvim#1119]
Hey all, I guess this is a feature request or an enhancement proposition.

What I wanted to do in neovim is to have a next/prev hunk behavior but for the whole repository, not just for the current buffer.
Gitsigns has `Gitsigns setqflist` and `Gitsigns setloclist` commands, so I logically thought that loclist would fill location list with hunks from current buffer and qflist would fill quickfix list with hunks from the whole repo. Unfortunately, this is not the case as both work only in the scope of a single buffer, they only differ with the target list.

So my questions are:
- what do you think about changing this behavior? In my opinion, as qflist is global, it should handle hunks from the whole repo, while loc list should stay as it is.
- is this something relatively simple to implement?

**Comment by xzbdmw** [comment]
gs.setqflist(‘all’)
