### ISSUE TITLE
error out on a fresh repo with no add and commit operation

### ISSUE THREAD

**Issue by jdhao** [lewis6991/gitsigns.nvim#112]
**Describe the bug**

gitsigns.nvim will error out on a freshly-created repo with no add and commit operation.

**To Reproduce**

init.vim:

```vim
set runtimepath+=/root/plenary.nvim
set runtimepath+=/root/gitsigns.nvim
                                                           
lua << EOF
require('gitsigns').setup {
  signs = {
    add          = {text = '+'},
    change       = {text = '~'},
    delete       = {text = '_', show_count=true},
    topdelete    = {text = '‾', show_count=true},
    changedelete = {text = '~', show_count=true},
  },
  debug_mode = true
}
EOF
```

1. Create a dir `git_test` and go to it `cd git_test`
2. Initialize a repo here: `git init`
3. Create a new file: `touch test.md`.
4. Open test.md: `nvim -u init.vim test.md`
5. You will see errors.

**Observed output**

> Error executing luv callback:                                                                                                           
/root/gitsigns.nvim/lua/gitsigns/async.lua:56: /root/gitsigns.nvim/lua/gitsigns.lua:422: Error detected in index watcher for buffer 1:
ENOENT

Include the output of `:lua require('gitsigns').debug_messages()`.

```
dprint(nil): Deriving GitSignsAdd from DiffAdd                                                               
dprint(nil): Deriving GitSignsChange from DiffChange
dprint(nil): Deriving GitSignsDelete from DiffDelete
attach(1): Attaching
dprint(nil): Running: git rev-parse --show-toplevel --git-dir --abbrev-ref HEAD
dprint(nil): Running: git --no-pager ls-files --stage --others --exclude-standard /root/git_test/test.md
watch_index(1): Watching index
dprint(nil): Running: git --no-pager show :0:test.md
update(1): updates: 1, jobs: 4
```

**Additional context**
System: Linux CentOS 7.4
Neovim version: v0.5.0-dev+1182-gb79596eb5

**Comment by lewis6991** [comment]
Does this fix it for you?

**Comment by jdhao** [comment]
@lewis6991  Works fine for me now. Thanks!
