### ISSUE TITLE
Question about on_attach being called early

### ISSUE THREAD

**Issue by tronikelis** [lewis6991/gitsigns.nvim#1147]
Hello, 

I see in the docs it states 

> Custom mappings can be defined in the `on_attach` callback

And in the readme I see examples of setting a lot of keymaps in the `on_attach` callback.

### Problem

What does not make sense to me is that at the time of calling `vim.keymap` or any other keymap adding api, those keymaps wouldn't work, because `on_attach` is called before actually computing hunks

It's called here https://github.com/lewis6991/gitsigns.nvim/blob/ac5aba6dce8c06ea22bea2c9016f51a2dbf90dc7/lua/gitsigns/attach.lua#L329

But for keymaps to work this `update` needs to finish https://github.com/lewis6991/gitsigns.nvim/blob/ac5aba6dce8c06ea22bea2c9016f51a2dbf90dc7/lua/gitsigns/attach.lua#L366-L367

As I understand it now the on_attach is meant to be used to skip attaching to some buffers, so moving it under update wouldn't make sense at this point, thus I propose adding a new config, which I tried to do in this PR https://github.com/lewis6991/gitsigns.nvim/pull/1146

**Comment by xzbdmw** [comment]
I think GitSignsUpdate would be called after attaching first time.

**Comment by tronikelis** [comment]
Yep, GitSignsUpdate works thanks @xzbdmw , I am closing this then
