### ISSUE TITLE
Untraked signs of git-signs be same when after tracked signes

### ISSUE THREAD

**Issue by Kaiser-Yang** [lewis6991/gitsigns.nvim#1159]
### Description

The untracked sign should look like this:

![image](https://github.com/user-attachments/assets/4df20ee5-75f3-4b12-ae9b-f0b3c7af8ac9)

But when it be after the tracked signs, it becomes same with the tracked signs:

![image](https://github.com/user-attachments/assets/b142a110-1562-45c7-b791-40b1448495a8)

### Neovim version

NVIM v0.10.1

### Operating system and version

WSL2 and Ubuntu 22.04 LTS

### Expected behavior

The new added line should be signed with untracked signs

### Actual behavior

Untraked signs of git-signs be same when after tracked signes

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
if vim.fn.isdirectory(install_path) == 0 then
vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
end
vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Tracked all changes
2. Add new lines after a tracked block

**Comment by lewis6991** [comment]
Sorry, don't understand you're English and reproduction steps are insufficient.

**Comment by Kaiser-Yang** [comment]
> Sorry, don't understand you're English and reproduction steps are insufficient.

In the first picture, I add some lines in a tracked file, the green is brighter.

Then after I use `git add .` to track all the files in current directory, all the added lines will be tracked, so the color will be darker. Then after I add some new lines after these tracked lines, the lined added now are untracked by `git` (because I have not use `git add` to track these lines), the color should be brighter not darker.

**Comment by gegoune** [comment]
Perhaps it's a duplicate of #929?

**Comment by Kaiser-Yang** [comment]
> Perhaps it's a duplicate of #929?

It seems so.

**Comment by lewis6991** [comment]
Both signs are there. You need to set `signcolumn` accordingly to see both.
