### ISSUE TITLE
Indicate number of deleted lines in sign

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#12]
One thing I like about https://github.com/mhinz/vim-signify is that the sign for deletion also indicates the number of lines, as in 
<img width="44" alt="Screenshot 2020-11-16 at 18 35 10" src="https://user-images.githubusercontent.com/2361214/99287391-77ea7380-283a-11eb-9add-39e11ba4a1b5.png">

Would this be possible for gitsigns as well (optionally, at least)?

**Comment by lewis6991** [comment]
I don't see why not, question is how difficult it would be. From the screenshot it looks like it uses two separate sign columns which makes it a little more effort but probably not that hard.

Another idea would be to allow the deletion sign to be the number of line deletions which can be optionally underlined which would sort of emulate the default sign of underscore?

**Comment by lewis6991** [comment]
Just to confirm, vim-signify does indeed use two sign columns:

```vim
  if a:type =~# 'SignifyDelete'
    execute printf('sign define %s text=%s texthl=SignifySignDelete linehl=%s',
          \ a:type,
          \ a:1,
          \ s:delete_highlight[g:signify_line_highlight])
  endif
  execute printf('sign place %d line=%d name=%s %s buffer=%s',
        \ id,
        \ a:line,
        \ a:type,
        \ s:sign_priority,
        \ a:sy.buffer)

  return id
```

**Comment by clason** [comment]
> I don't see why not, question is how difficult it would be. From the screenshot it looks like it uses two separate sign columns which makes it a little more effort but probably not that hard.

Hmm, it looks like it's the same width as the gitsigns column, still...

> Another idea would be to allow the deletion sign to be the number of line deletions which can be optionally underlined which would sort of emulate the default sign of underscore?

To be honest, I'd prefer the signify way (or not at all).

**Comment by lewis6991** [comment]
@clason any chance you could try out https://github.com/lewis6991/gitsigns.nvim/pull/17 ? Config looks like this:
```lua
require('gitsigns').setup {
  signs = {
    add          = {hl = 'DiffAdd'   , text = '│'},
    change       = {hl = 'DiffChange', text = '│'},
    delete       = {hl = 'DiffDelete', text = '_', show_count=true},
    topdelete    = {hl = 'DiffDelete', text = '‾', show_count=true},
    changedelete = {hl = 'DiffChange', text = '~', show_count=true},
  },
  count_chars = {
    [1]   = '1', -- '₁',
    [2]   = '2', -- '₂',
    [3]   = '3', -- '₃',
    [4]   = '4', -- '₄',
    [5]   = '5', -- '₅',
    [6]   = '6', -- '₆',
    [7]   = '7', -- '₇',
    [8]   = '8', -- '₈',
    [9]   = '9', -- '₉',
    ['+'] = '' , -- '₊',
  }
}
```

Turns out neovim allows signs to occupy two columns hence why the default config only support 1-9. You can configure 10+ if you have appropriate characters to use for them. This would allow someone with a patched font to configure a much larger range.

**Comment by clason** [comment]
Nice! I checked how Signify displays them, and it's almost the same but

1. for 10-99 lines, it omits the symbol (`text`) to make room for the second digit,
2. for >100 lines, it just shows a `>` character.

Whether 1. is actually better than your approach is up for debate (there are arguments in favor for both; my feeling is that the symbol is the most important so would slightly prefer your way), but I think 2. is a good idea. So I'd suggest replacing the empty char as default with `+` or `>`.

**Comment by lewis6991** [comment]
I used `>` for testing but decided to make it empty as default so it can't be misinterpreted. I don't actually mind as it's fully configurable. I guess since signify uses `>` that might be the better option to make transitioning from that plugin more seamless.

In regards to the extra digit, I'd rather leave it for now unless someone really wants it. It might even encourage people to be more creative with the config.
