### ISSUE TITLE
Hunk preview text is cut off if it contains tabs

### ISSUE THREAD

**Issue by danbyl** [lewis6991/gitsigns.nvim#120]
**Describe the bug**
The preview window width calculation doesn't seem to take tabstop into account, which leads to the text being cut off if it contains tabs. Additionally, the tabstop value of the diff filetype is used for the preview window which might not look consistent with the file being edited.

**To Reproduce**
1. Run ':lua require"gitsigns".preview_hunk()' on a hunk that contains tabs

**Screenshots**
![gitsigns](https://user-images.githubusercontent.com/51373899/113461140-e5bec280-940a-11eb-9bcd-72725a64a4b2.jpg)

**Comment by lewis6991** [comment]
@danbyl can you give #121 a spin? I get confused with the differences between `tabstop` and `softtabstop`, but `softtabstop` seems to me the one we need to use to calculate the width.

**Comment by danbyl** [comment]
`softtabsstop` only affects what happens when you insert tabs or delete whitespace and can be zero or negative, so using it directly doesn't work.

Anyway, I noticed that there already is a vim function called `strdisplaywidth` that deals with tabs. I think using that should do the trick, if we set the popup window's `tabstop` to be the same as the current window.

**Comment by lewis6991** [comment]
Thanks for pointing out `strdisplaywidth`. I've pushed another change which should solve this.
