### ISSUE TITLE
`blame_line` fails with set signcolumn

### ISSUE THREAD

**Issue by nihilistkitten** [lewis6991/gitsigns.nvim#126]
**Describe the bug**
When signcolumn is true, `blame_line()` fails to print the commit message:

<img width="276" alt="Screen Shot 2021-04-04 at 5 07 48 PM" src="https://user-images.githubusercontent.com/25715464/113525173-4a436400-9568-11eb-8b3d-a9ffccdebcf1.png">

**To Reproduce**

init.lua:

```lua
vim.cmd 'packadd paq-nvim'
paq = require'paq-nvim'.paq
paq{'savq/paq-nvim', opt=true}

paq 'nvim-lua/plenary.nvim'

paq 'lewis6991/gitsigns.nvim'
require('gitsigns').setup()

vim.wo.signcolumn = "yes"
```

1. Open any git-versioned file
2. Run `:lua require"gitsigns".blame_line()`

**Observed output**
```
setup_highlight: Deriving GitSignsAdd from DiffAdd
setup_highlight: Deriving GitSignsChange from DiffChange
setup_highlight: Deriving GitSignsDelete from DiffDelete
run_job: git --version
attach(1): Attaching
run_job: git rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager ls-files --stage --others --exclude-standard /home/rileyshahar/nvim-linux64/bin/min.lua
run_job: git config user.name
watch_index(1): Watching index
run_job: git --no-pager show :0:min.lua
update(1): updates: 1, jobs: 5
run_job: git --no-pager blame --contents - -L 1,+1 --line-porcelain /home/rileyshahar/nvim-linux64/bin/min.lua
```

**Additional context**
System: Ubuntu 18.04
Neovim version: v0.5.0-dev+1216-g8e496b9df

I also reproduced this with the same init.lua on MacOS 11.2.2 with nvim vv0.5.0-dev+992-gf3a8c930a.

**Comment by nihilistkitten** [comment]
Weirdly, without me doing anything, this seems to have fixed itself. No clue how, especially because I originally reproduced it across two machines. I'll leave it open in case you want to do anything with it, but I'm satisfied.

**Comment by lewis6991** [comment]
I think there might be other stuff in your `init.lua` causing this. Maybe `set wrap` related?

**Comment by lewis6991** [comment]
Last commit should fix. Please reopen if you still see the issue.
