### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by gbaranski** [lewis6991/gitsigns.nvim#129]
Hi, how do I change colors like in readme? For me everything is white, even after adding 
```lua
vim.api.nvim_exec(
[[
  hi GitSignsAdd guifg=red
  hi GitSignsChange guifg=red
  hi GitSignsDelete guifg=red
]], false)
```
to my config, however if I do `:hi GitSignsAdd guifg=red` after opening neovim, it works just fine

**Comment by lewis6991** [comment]
How are you loading the plugin? If you're using packer.nvim you can do:

```lua
use {
  'lewis6991/gitsigns.nvim',
  requires = {
    'nvim-lua/plenary.nvim'
  },
  config = function()
    -- Setup highlights before calling setup()
    vim.cmd[[ highlight GitSignsAdd    guifg=red ]]
    vim.cmd[[ highlight GitSignsChange guifg=red ]]
    vim.cmd[[ highlight GitSignsDelete guifg=red ]]
    require('gitsigns').setup()
  end
}
```

**Comment by lewis6991** [comment]
Also make sure you set `set termguicolors`

**Comment by lewis6991** [comment]
If it still doesn't work trying paste the output of `:Gitsigns debug_messages`

**Comment by gbaranski** [comment]
> How are you loading the plugin? If you're using packer.nvim you can do:
> 
> ```lua
> use {
>   'lewis6991/gitsigns.nvim',
>   requires = {
>     'nvim-lua/plenary.nvim'
>   },
>   config = function()
>     -- Setup highlights before calling setup()
>     vim.cmd[[ highlight GitSignsAdd    guifg=red ]]
>     vim.cmd[[ highlight GitSignsChange guifg=red ]]
>     vim.cmd[[ highlight GitSignsDelete guifg=red ]]
>     require('gitsigns').setup()
>   end
> }
> ```

It works :D, thank you very much.

**Comment by willfish** [comment]
So that's not working for me unless I require once vim has initialized. Possibly something strange with my config?

**Comment by lewis6991** [comment]
It could be the colorscheme being loaded after gitsigns causing the issue? Or something related to the ordering?

**Comment by willfish** [comment]
Very possibly

**Comment by tiagovla** [comment]
I have the same problem as @willfish. It is indeed related to the colorscheme.

**Comment by lewis6991** [comment]
If you can share configs, I can take a look into it.

**Comment by gbaranski** [comment]
https://github.com/gbaranski/dotfiles/tree/master/dot_config/nvim

**Comment by lewis6991** [comment]
Hmm, that config seems to work fine for me. Onedark has `GitGutter*` highlights so gitsigns just uses those.

**Comment by gbaranski** [comment]
> Hmm, that config seems to work fine for me. Onedark has `GitGutter*` highlights so gitsigns just uses those.

Yeah now it works.

**Comment by tiagovla** [comment]
In my case, I wasn't able to change the highlights because my theme uses ``highlight clear``.
The solution was to change it inside an autogroup triggered by ``ColorScheme``:
```lua 
vim.api.nvim_exec([[
  augroup custom_theme_highlights
    autocmd!
    au ColorScheme * highlight GitSignsAdd       guifg=red
    au ColorScheme * highlight GitSignsChange    guifg=red
    au ColorScheme * highlight GitSignsDelete    guifg=red
  augroup END
]], false)
```
