### ISSUE TITLE
Float window placement issue

### ISSUE THREAD

**Issue by cloggier** [lewis6991/gitsigns.nvim#130]
**Describe the bug**
Hunk preview or blame float window requested while cursor is close to bottom of the window causes float window overlap status line and cuts lower part of the float.

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require "gitsigns".setup {
  debug_mode = true,
  signs = {
    add = {text = "▏"},
    change = {text = "▏"},
    delete = {text = "_", show_count = true},
    topdelete = {text = "‾", show_count = true},
    changedelete = {text = "▏", show_count = true}
  },
  count_chars = {
    [1] = "",
    [2] = "₂",
    [3] = "₃",
    [4] = "₄",
    [5] = "₅",
    [6] = "₆",
    [7] = "₇",
    [8] = "₈",
    [9] = "₉",
    ["+"] = "₊"
  }
}
EOF
```

1. Add new line to the end of tracked file; make sure it's one or two lines above statusline
2. Press `<leader>hp`
3. See floating window overlap status line and being cut off.

**Observed output**

```
setup_highlight: Deriving GitSignsAdd from GitGutterAdd
setup_highlight: Deriving GitSignsChange from GitGutterChange
setup_highlight: Deriving GitSignsDelete from GitGutterDelete
run_job: git --version
attach(3): Attaching
run_job: git rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager ls-files --stage --others --exclude-standard /Users/<me>/test/a
run_job: git config user.name
watch_index(3): Watching index
run_job: git --no-pager show :0:a
update(3): updates: 1, jobs: 5
```

**Screenshots**
<img width="181" alt="Screenshot 2021-04-05 at 22 06 01" src="https://user-images.githubusercontent.com/69750637/113614406-1e54db00-965b-11eb-8d92-3d18af15b378.png">

**Additional context**
System: Mac
Neovim version: `v0.5.0-dev+76f5c7286`

**Comment by tomaskallup** [comment]
Would the desired solution here be to just check if hunk size > lines to bottom of screen -> flip the window? I'm not that familiar with the floating windows and seems like you use the native neovim api, so I guess that would be doable.
I'm just wondering if [plenarys popup](https://github.com/nvim-lua/plenary.nvim#plenarypopup) (or perhaps [popup.nvim](https://github.com/nvim-lua/popup.nvim)) could handle this for us.

**Comment by lewis6991** [comment]
Maybe and maybe. Last time I checked plenarys popup was pretty rough. Maybe it's better now. Not sure about popup.nvim as I'd like to avoid another dependency.

**Comment by lewis6991** [comment]
I've just tried to recreate this on a recent master and it seems the floats are no longer cut. It still overlaps with the statusline but I'm not sure that is really a problem. Arguably it is desirable in the case you have a horizontal split, the float will straddle the stausline:

(preview triggered from the top split: straddles statusline)
![Screenshot 2021-04-22 at 17 08 54](https://user-images.githubusercontent.com/7904185/115747784-7b57cd00-a38d-11eb-83cc-a4a1f3e5d2f1.png)

(preview triggered from the bottom split: isn't cut)
![Screenshot 2021-04-22 at 17 09 09](https://user-images.githubusercontent.com/7904185/115747888-932f5100-a38d-11eb-9fd3-2a9f962c4cce.png)


Ok if I close?

**Comment by cloggier** [comment]
Definitely. Didn't look into that issue for a while but will try to confirm shortly and reopen if necessary. Thanks!
