### ISSUE TITLE
Background for popup or border?

### ISSUE THREAD

**Issue by fedoranvar** [lewis6991/gitsigns.nvim#131]
**Describe the bug**
Hunk Preview background is blending with neovim's background

Is it possible to toggle border for popup or change background for popup?

**To Reproduce**

just preview hunk

init.vim:
```
require('gitsigns').setup()

```

**Screenshots**
![image](https://user-images.githubusercontent.com/52028706/113705337-bd7ae080-96f6-11eb-8511-a56768af6dd7.png)

**Additional context**
Void Linux
Neovim: v0.5.0-dev+1160-g0f7b6b2ef

**Comment by lewis6991** [comment]
Didn't know that was even possible. Is this with a tui nvim or are you using a GUI client. If it's tui, what terminal are you using?

**Comment by fedoranvar** [comment]
> Didn't know that was even possible. Is this with a tui nvim or are you using a GUI client. If it's tui, what terminal are you using?

It's a TUI in Alacritty

**Comment by lewis6991** [comment]
Ok cool, I'll see if I can reproduce.

The floating window borders are in active development in neovim core so this may be something that just fixes itself. Otherwise we may need to raise an issue upstream.

**Comment by lewis6991** [comment]
I can't seem to recreate the issue. Does your alacritty config have anything specific to enable to behaviour of the red border? What colorscheme are you using?

**Comment by fedoranvar** [comment]
> I can't seem to recreate the issue. Does your alacritty config have anything specific to enable the behaviour of the red border? What colorscheme are you using?

Oh, sorry for confusion.

This red border was made in flameshot (screenshot), not by plugin.

My point was, that background of floatwindow is linked to Normal highlight (so changing Normal Background changes hunk preview background)

**Comment by lewis6991** [comment]
If you try the latest, the background should be as it used to be. If you upgrade your neovim to nightly you'll see a border similar to the red box.

**Comment by fedoranvar** [comment]
confirm
![image](https://user-images.githubusercontent.com/52028706/113832145-c1b00800-97a1-11eb-86c3-6fa3cdfde517.png)

Thank you very much!
