### ISSUE TITLE
Error at initialization: "The coroutine failed with this message: .../gitsigns.nvim/lua/gitsigns/git.lua:256: attempt to concatenate field 'gitdir' (a nil value)"

### ISSUE THREAD

**Issue by kdav5758** [lewis6991/gitsigns.nvim#135]
**Describe the bug**
Couroutine error, breaks and shows error message after initiating an nvim. Everything after latest commit on main branch update

**To Reproduce**

1. Update the plugin (`:PackerUpdate` if using packer.nvim)
2. Start a new nvim instace
3. See error

**Observed output**
![image](https://user-images.githubusercontent.com/58336662/114252924-69c5fc80-996d-11eb-88a8-5a5624d91cdc.png)

**Gif**
![gitsigns_error](https://user-images.githubusercontent.com/58336662/114252984-b7426980-996d-11eb-9459-7e93fdea89fe.gif)

**Additional context**
System: Ubuntu Linux 20.10
Neovim version: NVIM v0.5.0-dev+1231-g48e805728
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by lewis6991** [comment]
I've reverted the latest commit (https://github.com/lewis6991/gitsigns.nvim/commit/fd4e283efb798ed9493a658d7f5d2d0ef34e92e4) that causes this, obviously it wasn't quite ready.

I've been able to reproduce the issue but found this only happens when openeing files outside of a git repository. Do you get the same problem when opening tracked files?

**Comment by lewis6991** [comment]
I've opened #137. Can anyone this issue affects test that out before I merge it. Thanks.

**Comment by kdav5758** [comment]
Hello @lewis6991, thanks for the fast reply.

I found the issue when:
    + Opening untracked files
    + Opening files outside of a git repo

I didn't see the issue when:
     + Opening a new file in a git repo
     + Opening a tracked file

Hope that help. If needed, I can help you with further testing.

**Comment by lewis6991** [comment]
@kdav5758 thanks! Have you tried #137? Does that resolves the issues?

**Comment by kdav5758** [comment]
@lewis6991 yes, that resolves the issue.
1. Tested latest commit on the main branch and since you reverted it, it's now working as expected.
2. Tested latest commit on the refactor branch and it was working as intended too.
![Peek 2021-04-10 08-57](https://user-images.githubusercontent.com/58336662/114272216-e3480400-99da-11eb-8815-67c54d83f1bb.gif)

**Comment by lewis6991** [comment]
Many thanks for the feedback. I've gone an merged the PR.

**Comment by akinsho** [comment]
Btw @lewis6991 I'm still seeing this issue on the latest commit of gitsigns, I believe I'm seeing this when I switch branches.

**Comment by lewis6991** [comment]
Steps to reproduce -> raise new issue.

If issues can be reproduced, then we can add them to the testsuite. There's at least one testcase already that has some coverage of switching branches.
