### ISSUE TITLE
Show diff or changes only in new buffer

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#14]
Another one from the "nice things Signify does": Open a new buffer with the diff between current state and last commit (`:SignifyDiff`)  or a copy of the current buffer with folding showing only changed locations (`:SignifyFold`) -- might be useful to add if it's not hard?

(Unlike supporting other VCS like `hg` ;))

**Comment by lewis6991** [comment]
This might be slightly out of scope for the plugin but we can still consider it if it's easy to implement.

**Comment by clason** [comment]
Makes sense; I just wanted to put it out there as I was thinking of it. I agree it's only sensible if it's no effort -- otherwise it seems more appropriate for https://github.com/TimUntersberger/neogit

**Comment by lewis6991** [comment]
@clason does #200 satisfy the request of this ticket? Any feedback would be greatly appreciated 😄

**Comment by clason** [comment]
Yep, that was pretty much what I had in mind with `:SignifyDiff`!

**Comment by lewis6991** [comment]
Cool, I've gone ahead and merged. Let me know if it needs any extra polish.
