### ISSUE TITLE
Flickering when typing

### ISSUE THREAD

**Issue by gbaranski** [lewis6991/gitsigns.nvim#145]
**Describe the bug**

Sometimes the vertical line dissapears and after few milliseconds comes back again.

Timestamps of video when this occurs:
- 00:11
- 00:15
- 00:19
- 00:26

https://user-images.githubusercontent.com/34353640/114551068-2f0cde80-9c63-11eb-8459-98d8731b672a.mp4

**To Reproduce**

Vim config: https://github.com/gbaranski/dotfiles/tree/master/dot_config/nvim
Initializing gitsigns: https://github.com/gbaranski/dotfiles/blob/369481c7461a48c6b1c6bdd53c47acba592d8497/dot_config/nvim/lua/plugins.lua#L30

1. Run my config
2. Open some file
3. Spam enter to make new lines

**Observed output**

Include the output of `:lua require('gitsigns').debug_messages()`.
I've received:
```
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'debug_messages' (a nil value)
```

**Additional context**
System: Arch Linux
Neovim version: NVIM v0.5.0-dev+1243-g4a36ec6da
Terminal emulator: Alacritty

**Comment by lewis6991** [comment]
> Include the output of :lua require('gitsigns').debug_messages().
I've received:
>
> E5108: Error executing lua [string ":lua"]:1: attempt to call field 'debug_messages' (a nil value)

You need to set `debug_mode = true` in your config. I need to update the issue template to explain this.

**Comment by lewis6991** [comment]
Also the MP4 file says it is corrupt.

**Comment by gbaranski** [comment]
> Also the MP4 file says it is corrupt.

Here is fixed video(you must open fullscreen to see the git signs)

https://user-images.githubusercontent.com/34353640/114564595-bdd42800-9c70-11eb-8dec-836f96aa61e9.mp4



> > Include the output of :lua require('gitsigns').debug_messages().
> > I've received:
> > E5108: Error executing lua [string ":lua"]:1: attempt to call field 'debug_messages' (a nil value)
> 
> You need to set `debug_mode = true` in your config. I need to update the issue template to explain this.

It keeps saying this a lot of times
```
run_job: git --no-pager --git-dir=/home/gbaranski/code/houseflow/.git show :0:lighthouse/src/tcp_server.rs
update(3): updates: 327, jobs: 331
```

**Comment by lewis6991** [comment]
Try setting `_refresh_staged_on_update = false`. That'll stop it running `git show` on every edit.

**Comment by gbaranski** [comment]
> _refresh_staged_on_update = false

Awesome, that works, thanks :D

**Comment by lewis6991** [comment]
Great! Just be wary that the config field is experimental and will be changed/removed at some point. You may also encounter some issue with it enable (hopefully not) but please raise an issue if you do.

**Comment by ihasdapie** [comment]
I've tried `_refresh_staged_on_update = false` in the config as well however am still also encountering the flickering. Any other fixes I can try?
System info:
Manjaro
NVIM v0.5.0-dev+1233-g82ac44d01
Terminal emulator: kitty

**Comment by lewis6991** [comment]
Maybe try increasing `update_debounce` or maybe setting `use_decoration_api=false`
