### ISSUE TITLE
Gitsigns show sign on wrapped lines

### ISSUE THREAD

**Issue by Famiu** [lewis6991/gitsigns.nvim#148]
**Is your feature request related to a problem? Please describe.**
Gitgutter doesn't seem to properly show signs for wrapped lines, which can be a bit ugly to see. Screenshot of signcolumn:
![image](https://user-images.githubusercontent.com/29580810/114598465-be41e280-9cb3-11eb-8315-f2ccd6d836e0.png)

**Describe the solution you'd like**
If it's possible, make gitgutter show signs on wrapped lines as well. If it isn't possible, then I guess there's nothing to do about it.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by lewis6991** [comment]
Unfortunately this isn't possible since you can only place signs on valid line numbers which doesn't count wrapped lines.
