### ISSUE TITLE
Custom formatter for status

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#15]
Here's a maybe stupid idea: I prefer the status formatted slightly differently (`added changed modified`, with empty changes still shown so that the status line doesn't jump around too much). Of course I can do that myself from `b:gitsigns_status_dict`, but it might be more efficient to do this in Lua.

So I was thinking whether it'd be possible to allow providing (instead or in addition) a function in the setup that builds the status string from the three components (with default as now)?

**Comment by lewis6991** [comment]
Sounds like a good idea.

**Comment by lewis6991** [comment]
TODO: Still needs documenting.

**Comment by clason** [comment]
Works like a charm, thank you!

**Comment by lewis6991** [comment]
Documented with 1fd68f7b5284b51913488cea5515cf86315a95a1
