### ISSUE TITLE
Why are we using loadstring in the config?

### ISSUE THREAD

**Issue by oberblastmeister** [lewis6991/gitsigns.nvim#150]
Is this a teal issue?

**Comment by lewis6991** [comment]
It's purely so the default values in the documentation print nicely with comments.

**Comment by oberblastmeister** [comment]
For me I don't really care about the values in the documentation looking nice. I would rather remove loadstring because it can be very slow and usually shouldn't be used. Why don't you just use `vim.inspect`?

**Comment by oberblastmeister** [comment]
also maybe we can use tj's treesitter docgen for the compiled lua files and some sort of `vim.inspect` combined with `debug.getinfo` stuff to be able to see stuff

**Comment by lewis6991** [comment]
> For me I don't really care about the values in the documentation looking nice. I would rather remove loadstring because it can be very slow and usually shouldn't be used.

Loadstring is only used on a few config fields, mainly functions. I didn't know it was slow, but even so it's only used on a few things during setup. Either way, I'd like to remove it if possible.

If we can use `debug.getinfo` to get the where in a file a value is defined then we can just change `gen_help.lua` to extract the default values directly from source. My memory is hazy, but I think I might have tried that and failed so resorted to loadstring.

>  Why don't you just use `vim.inspect`?

Doesn't work for functions, doesn't have nice formatting and removes comments.
