### ISSUE TITLE
quick fix list from changes list

### ISSUE THREAD

**Issue by JoseConseco** [lewis6991/gitsigns.nvim#154]
Hi, I was wondering if we could load changes into quick-fix list, so user could see changes at an glance (I have to do lots of scrolling right now - and hitting <leader>ghn  - is breaking flow).
This could be per file, or maybe option for whole project too. Something like:
- load current file changes into QFix list.
- load all files changes from project cwd into QF list.

Showing changes on folded code would be nice too - this would be another way to quicky see if  folded code has any changes inside -> then user can unfold code to see the actual changes.

**Comment by lewis6991** [comment]
> This could be per file, or maybe option for whole project too. Something like:

Generally speaking, gitsigns only focuses on buffer contents so I'd prefer to implement this per open buffer.

**Comment by lewis6991** [comment]
> Showing changes on folded code would be nice too - this would be another way to quicky see if folded code has any changes inside -> then user can unfold code to see the actual changes.

Do you mean having a sign of some sort on the folded line? If so then I think that's a great idea. I find myself all the time pressing `zR` just so I can see if there are any changes.

**Comment by JoseConseco** [comment]
yes folded code could be marked as changed like so:
![image](https://user-images.githubusercontent.com/13521338/114888431-82b92c80-9e09-11eb-8c9f-5841ef0c536d.png)
Easy to see there was change inside. In best case scenario - the  changes inside fold would be displayed in proper diff sign (+, -, ! etc).    If folded code has bunch of  - and +  inside, then it could be just marked as changed (!) or something like this.

**Comment by lewis6991** [comment]
>  If folded code has bunch of - and + inside, then it could be just marked as changed (!) or something like this.

We would probably need to add a new sign type for mixed changes, and tbh even if a fold only contains a specific sign I personally might want to give it a different sign. So we would need:

- `add_fold`
- `delete_fold`
- `change_fold`
- `adddelete_fold`
- `addchange_fold`
- `changedelete_fold`
- `addchangedelete_fold`

This would bloat the configuration a bit so need to think about the right way to do it.

**Comment by JoseConseco** [comment]
Well that looks complicated, but if I will be able to setup  +,-,  and ~ for everything else,  then its good to me :)

**Comment by lewis6991** [comment]
Folds implemented with #157

**Comment by JoseConseco** [comment]
Awesome. Cant wait to test it out. Btw I can see the pull request: CI / build (pull_request)  failed - so when I used PackerSynd I cant see the new feature

**Comment by lewis6991** [comment]
The PR isn't merged yet and CI only failed on a test that shouldn't effect most users. You can try out the change by using the `foldsigns` branch.

**Comment by JoseConseco** [comment]
When I open nvim with new GSigns folds branchI get this message at start:
![image](https://user-images.githubusercontent.com/13521338/115031348-56181a00-9ec8-11eb-8661-7cb1efbf1c49.png)

I added : 
```
fold         = {enable = false,
		                    hl = 'GitSignsFold'  , text = '[', numhl='GitSignsFoldNr'  , linehl='GitSignsFoldLn'  },       
``` 
To config but I see no difference:

https://user-images.githubusercontent.com/13521338/115031982-156cd080-9ec9-11eb-8f44-61fa29eba2e2.mp4

**Comment by lewis6991** [comment]
The clue is here:

```
fold         = {enable = false,
		                    hl = 'GitSignsFold'  , text = '[', numhl='GitSignsFoldNr'  , linehl='GitSignsFoldLn'  },
```

Notice that `enable = false`. You need to set that to true.

**Comment by lewis6991** [comment]
> When I open nvim with new GSigns folds branchI get this message at start:
image

There were some print statements accidentally left in. I've removed them in the latest patch.

**Comment by lewis6991** [comment]
This is the absolute minimum you need to enable fold signs:

```lua
require('gitsigns').setup{
  signs = {
    fold = { enable = true }
  }
}
```

All the other fields will get default values.

**Comment by JoseConseco** [comment]
My mad, I just copied code without reading . It works great now.  Thanks for your time. I guess I can close this now
