### ISSUE TITLE
Append key mapping to defaults like the signs

### ISSUE THREAD

**Issue by haooodev** [lewis6991/gitsigns.nvim#155]
It's possible to update signs table within setup, but the keymaps are not updated but replaced. With the following setup, i could see the count of modifications (e.g., add, change) but only the `<leader>hl` mapping exists, all the defaults are gone e.g., `]c`, and `<leader>hs`. Digged through the implementation in **config.lua**, the _deep_extend_ attribute of signs table makes it ok with updating but the lack of this attribute in keymaps table makes it overrides the defaults. Hopefully these behaviors could be consistent.

```
require('gitsigns').setup{
    signs = {
      add = {show_count = true},
      change = {show_count = true},
      delete = {show_count = true},
      topdelete = {show_count = true},
      changedelete = {show_count = true},
    },
    keymaps = {
      noremap = true,
      buffer = true,
      ['n <Leader>hl'] = '<cmd>lua require("gitsigns").toggle_linehl()<CR>',
    },
}
```

**Comment by lewis6991** [comment]
The difference between `signs` and `keymaps` is that `signs` needs to have values for all the fields otherwise gitsigns will error, whereas `keymaps` are purely optional and we need a way for the user to disable keymaps entirely. The complete list of default keymaps is documented so you just need to copy them. I believe telescope works pretty similarly.

**Comment by ZachariasLenz** [comment]
Could you please make this clearer in the documentation then? I also ran into this and was quite surprised that the keymaps got overwritten instead of updated.

**Comment by elkowar** [comment]
I'm noticing the exact opposite behaviour, where keymaps is _not_ getting overridden, meaning i'm unable to remove the keybinds,..... What's happening here?

**Comment by lewis6991** [comment]
> I'm noticing the exact opposite behaviour, where keymaps is _not_ getting overridden, meaning I'm unable to remove the keybinds,..... What's happening here?

Are you running `:PackerCompile` when you make changes to the config? I just tested and the following removes all keymaps:

```lua
  {'~/projects/gitsigns.nvim',
    requires = { 'nvim-lua/plenary.nvim' },
    config = function()
      require('gitsigns').setup{
        keymaps = {}
      }
    end
  }
```

**Comment by lewis6991** [comment]
> Could you please make this clearer in the documentation then? I also ran into this and was quite surprised that the keymaps got overwritten instead of updated.

I agree it makes the config a bit awkward. Ideally all aspects of the config should be handled the same way.

Some alternative ways we can handle this:
1. Change `keymaps` from a table to a function called `on_attach`, just like how the builtin LSP is configured, and expose the default function so you user can call it to extend mappings:
```lua
require('gitsigns').setup{
    on_attach = function(bufnr)
      require('gitsigns.defaults').setup_keymaps() -- Inherit default keymaps

      -- Add our own.
      vim.api.nvim_set_keymap('n', 'm', ':Gitsigns dump_cache<cr>'    , {silent=true})
      vim.api.nvim_set_keymap('n', 'M', ':Gitsigns debug_messages<cr>', {silent=true})    
    end
}
```
With this `config.keymaps` should probably be deprecated.

2. Add a field like `config.apply_default_keymaps` which defaults to `true` and must be disabled to prevent default keymaps being applied.

Either of these ways will make it so we don't need to special-case the keymaps when processing the config which should be less surprising to users.

Thoughts anyone?

**Comment by elkowar** [comment]
I don't have the config block in the packer statement, i have my config in a separate place where it get's sourced afterwards...

still, ran PackerCompile, but no fix.

![image](https://user-images.githubusercontent.com/5300871/116777050-63a6d580-aa6c-11eb-8ca8-6f162c918c6a.png)
This is my config, (it's in fennel, but in the end it compiles down to just calling
```lua
gitsigns.setup {
  signs = { ... }
  keymaps = {
    noremap = true,
    buffer = true
  }
}
```
What you see at the bottom is the output of `:nmap <leader>h` (which is the specific keybind i'm concerned about).

Replacing it with a function seems very sensible to me - i don't really see the need for having a special table for keybinds, people are using other ways of creating keybinds in other places anyways - I prefer the consistency of that over this weird thing.

**Comment by lewis6991** [comment]
I just tried:

```lua
      local gs = require('gitsigns')
      gs.setup {
        keymaps = {
          noremap = true,
          buffer = true
        }
      }
```

And it definitely removes the keymaps.

I suspect the issue may lie in your config. Try adding some `print` statements in `gitsigns.setup` to verify the config being passed is correct.

**Comment by elkowar** [comment]
I did that and,..... figured out that I am, in fact, stupid!
I was doing
```
gisigns.setup(
  { signs = {...} },
  { keymaps = { ...} }
)
```
I'm sorry...

**Comment by lewis6991** [comment]
No problems, happy to help!
