### ISSUE TITLE
Delay with current_line_blame

### ISSUE THREAD

**Issue by WhyNotHugo** [lewis6991/gitsigns.nvim#162]
`current_line_blame` has a delay by default of several seconds.

Would it be possible to have a setting to disable this delay?

**Comment by lewis6991** [comment]
It triggers on `CursorHold` which is configured by `updatetime` which has a default of 4000ms. Try something like `set updatetime=100`

**Comment by WhyNotHugo** [comment]
That works, thanks!

I see that, unlike other plugins, if the repository is huge (e.g. `torvalds/linux`), it just renders with some delay, instead of freezeing vim itself. Cheers to that! :beers:
