### ISSUE TITLE
Disable output on the signcolumn

### ISSUE THREAD

**Issue by Tummetott** [lewis6991/gitsigns.nvim#163]
Hello,

I'm using gitsigns together with galaxyline to see git changes in my statusline. However, I don't like this information in my signcolumn. I could just hide my signcolumn but that I would also hide my LSP errors / warnings. I tried configuring gitsign as follows:

```
require('gitsigns').setup {
    signcolumn = false
}
```
This hides any information in the signcolumn but also hides the linenumbers (for changed lines) when setting:
`set signcolumn=number`

Is there a better way to disable output on the signcolumn all together?

**Comment by lewis6991** [comment]
I think this is an issue with neovim. With `config.signcolumn=false`, `sign_getdefined('GitSignsAdd')` outputs:

```
[{'name': 'GitSignsAdd', 'numhl': 'false', 'texthl': 'GitSignsAdd', 'linehl': 'false'}]
```

Which shows `text` is unset (as we expect). If `signcolumn=number` and `text` is not set on a sign I would expect it not to overwrite the line number as it is doing.

We could workaround this in gitsigns by simply not placing the signs if:
```
config.signcolumn = false and config.numhl == false and config.linehl == false
```
and maybe even add ` and vim.wo.signcolumn == 'number'` in there too for good mesaure.

**Comment by Tummetott** [comment]
Awesome thanks a lot !
