### ISSUE TITLE
Show diff for current buffer compared to saved version

### ISSUE THREAD

**Issue by JoseConseco** [lewis6991/gitsigns.nvim#164]
**Is your feature request related to a problem? Please describe.**
Lets say we do not have tracked file. We we made dome changes to file, and we want to quickly see what lines were edited.

**Describe the solution you'd like**
Gitsign could higlight/mark somehow edited lines (comparing edited file to non edited version on HDD) 

**Describe alternatives you've considered**
We could maybe run diff of  current buffer to original version but signs could be nicer

**Additional context**
Cool implementation in kde Kate text editor:

https://user-images.githubusercontent.com/13521338/115744779-28811400-a393-11eb-8eb9-a7391954ec96.mp4

Modified lines are marked yellow, on save they tun green, and then new additional lines are marked  yellow again. We can repeat save and new changes turn gree.
I know this may be outside the scope of this plug but still it could be nice feature to have..

**Comment by lewis6991** [comment]
This isn't outside the scope, I've been thinking about implementing something like this.

Something I'm a little more interested in is showing signs for changes that are staged which would be useful if you like staging individual hunks which I personally do all the time. So essentially a diff of `HEAD` against `index`.

This suggestion is more of the lines of diffing `tree` against `index`

**Comment by JoseConseco** [comment]
Actually I found this plug:
- https://github.com/chrisbra/changesPlugin  - it does work but user has to  enable it manually each time, and it does not have  as rich customization as gitsigns but works ok (non lua though).  Maybe it could be used for inspiration :)

**Comment by JoseConseco** [comment]
I found this plugin: [footprint](https://github.com/axlebedev/footprints) which is good enough for my needs. I will close this then.

**Comment by lewis6991** [comment]
Using footprint is probably a better option since the requirement of signs for modified lines doesn't require git.

**Comment by lewis6991** [comment]
After some char on Matrix, I'd like to reconsider this at some point.

@clason

**Comment by JoseConseco** [comment]
Thx levis,  somone figured out how to use it?
Something like:
autocmd IF_Buffer_Not_Tracked : attach(bnumb, ctx = {base='FILE'}  ?

**Comment by JoseConseco** [comment]
For now I get something like this : 
```lua
local git_non_tracked = vim.api.nvim_create_augroup("GitSignTrackNonTracked", { clear = true })
vim.api.nvim_create_autocmd({ "BufEnter"}, {
  pattern = "*",
  callback = function()
    print('attaching gitsigngs')
    gitsigns.attach(0, {
      file = vim.fn.expand("%:p"),
      toplevel = vim.fn.expand("%:p"),
      base = 'FILE' })
  end,
  group = git_non_tracked,
})
```
But it does not seem to work. And I have to find way to detect non tracked buffer/files only. ..
