### ISSUE TITLE
[Unconfirmed] It seems that gitsigns may be crashing nvim

### ISSUE THREAD

**Issue by tjdevries** [lewis6991/gitsigns.nvim#166]
**Describe the bug**

On startup, if I make a change to a git-tracked file, it is possible to sometimes segfault neovim.

I think the reason is this: https://stackoverflow.com/questions/25924755/c-and-lua-unprotected-error-bad-callback-how-is-this-possible

My reasoning for thinking it might be this is that it doesn't ALWAYS segfault. So perhaps the JIT sometimes tries to compile some code that uses the FFI, and sometimes doesn't (some weird thing hapening there... not sure). It may be that you need to do `jit.off` inside of where you are doing some FFI things.

OR

I could just be totally wrong :)

Anyways, love the plugin :)

**To Reproduce**

Open a git tracked file and then press 'o'. Works only some of the time.

I'm on Ubuntu 20.04, latest nightly, etc.

**Comment by lewis6991** [comment]
I've had these crashes now and again too and I think you're probably right.

You could try setting `config.use_internal_diff=false` for a while and see if the crash continues to happen. Otherwise your suggestion about `jit.off` sounds like a good one. There isn't much ffi code so should be straightforward to hack in.

**Comment by lewis6991** [comment]
Looking at the FFI docs a bit more I think the hypothesis if probably correct:

>  One thing that's not allowed, is to let an FFI call into a C function get JIT-compiled, which in turn calls a callback, calling into Lua again. Usually this attempt is caught by the interpreter first and the C function is blacklisted for compilation.
>
> However, this heuristic may fail under specific circumstances: e.g. a message polling function might not run Lua callbacks right away and the call gets JIT-compiled. If it later happens to call back into Lua (e.g. a rarely invoked error callback), you'll get a VM PANIC with the message "bad callback". Then you'll need to manually turn off JIT-compilation with jit.off() for the surrounding Lua function that invokes such a message polling function (or similar). 

Even if the crashes aren't because of gitsigns ffi usage, explicitly disabling JIT is probably a good idea.

**Comment by tjdevries** [comment]
Cool, thanks :) I had uninstalled it after sending the issue and I didn't see any more segfaults -- now pulled the update and haven't seen anything now either. I will let you know if I see anything.
