### ISSUE TITLE
Expose `config` for other devs to make integrations with your plugin?

### ISSUE THREAD

**Issue by kdav5758** [lewis6991/gitsigns.nvim#167]
**Is your feature request related to a problem? Please describe.**
I'm working on an integration for [my plugin](https://github.com/kdav5758/TrueZen.nvim) with yours. For the integration, I need to check the state of some stuff your plug-in can do (e.g. config.sings, config.numhl, config.linehl)

**Describe the solution you'd like**
Simply expose the instance of `Config` named `config` from [here](https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns.tl#L43) by returning it. In this way I can access each on of its fields ([like this one](https://github.com/lewis6991/gitsigns.nvim/blob/main/teal/gitsigns.tl#L847)) to determine the state of each one of the elements/features your plugin provides.

**Describe alternatives you've considered**
The solution above is pretty simple a self explanatory. However, you can also create a new table (e.g. `state`) and add all the variables the variables as keys and their values as *values*, and in the end, return it.

**Additional context**
Need this for an integration. In the end it'll be possible for me to simply access each field. For instance:

```
local signcolumn = require("gitsigns.M.config").signcolumn
```

**Comment by lewis6991** [comment]
Sorry for taking a while to reply.

I'd like to expose the config, I've just been struggling to think how to do this nicely. Ideally I'd to expose it as `require('gitsigns.config')`, but that modules needs to expose other functions too.

For the meantime we can expose it as `require('gitsigns')._config` (API unstable). Would that be ok?

**Comment by kdav5758** [comment]
Hello again. Yes, it would be nice to have it exposed as a field for now, which is the simplest solution. However, having `_config` as its own module would be better.

I haven't played around with it much becuase I just saw your message, but I can confirm that this API call is working:
```lua
local gs = require("gitsigns")
local gs_config = gs._get_config()

cmd("echo 'GS signcolumn = "..tostring(gs_config.signcolumn).."'")
```

Congrats! I'll update you if something isn't working as it should.

**Comment by kdav5758** [comment]
Unrelated to the issue but... this was for an integration between your plugin [and mine](https://github.com/kdav5758/TrueZen.nvim). You can go and check it out if you want!

**Comment by lewis6991** [comment]
@Pocco81 btw there's now a stable way of getting the config:

```lua
local gs_config = require('gitsigns.config').config
```

I plan to remove `_get_config()` soon just to be warned.
