### ISSUE TITLE
How to change the color of the sign?

### ISSUE THREAD

**Issue by winston0410** [lewis6991/gitsigns.nvim#169]
Thank you for your effort for this plugin. I want to change the color of the sign generated by this plugin. I have read the doc but I can't find how can I change their color, I guess it is related with the highlight group but I am not sure. What is the recommended way to do so?

**Comment by lewis6991** [comment]
You need to define highlight groups for the plugin to use, this is usually done by the colorscheme. The documentation is a little bit stale, but gitsigns used the following highlights for signs: `GitSignsAdd`, `GitSignsChange`, `GitSignsDelete`.

You can define these with he `highlight` command. Somethling like this should work.

```viml
:highlight GitSignsAdd guifg=Blue
```

See `:help highlight` for more details on how to define highlight groups.

**Comment by zbindenren** [comment]
Is it possible to make the line for `toggle_current_line_blame` a little brighter?

**Comment by lewis6991** [comment]
You need to define the highlight `GitSignsCurrentLineBlame`. By default it is linked `NonText` in which its brightness is completely dependent on your colorscheme.
