### ISSUE TITLE
How to change hl of floating window?

### ISSUE THREAD

**Issue by vilari-mickopf** [lewis6991/gitsigns.nvim#170]
Setting `highlight NormalFloat` doesn't seem to work.
 
[Here](https://github.com/lewis6991/gitsigns.nvim/blob/3d378118e442690e2e15ee6a26917a5c1871f571/lua/gitsigns/popup.lua#L25) you are passing `'NormalFloat:Normal'` to `nvim_win_set_option`, however nvim documentation is suggesting  `'Normal:MyHighlight'`. When I change this argument to `'Normal:NormalFloat'` setting of NormalFloat hl group actually changes the hl of the floating win. I'm not really familiar with this, so I am not sure if I am missing something or is this just a typo?

**Comment by lewis6991** [comment]
We only pass that if you are running an old nvim. Master recently introduced a `border` config which gitsigns tries to use. If it fails it opens a borderless floating window with the highlight you described.

**Comment by vilari-mickopf** [comment]
I am using latest nvim, but I don't like the borders, so I've used `preview_config = {border = 'none'}`.

**Comment by lewis6991** [comment]
Should still mean the highlight command isn't called as the `pcall` should succeed.

**Comment by elianiva** [comment]
I would like to be able to change this as well. Here's how it look currently.

![image](https://user-images.githubusercontent.com/51877647/116836153-aa710880-abef-11eb-8d69-38930c219b3d.png)

I want the `winhl` to be `Normal:NormalFloat` so it would look like this.

![image](https://user-images.githubusercontent.com/51877647/116836212-d8eee380-abef-11eb-9ab1-d1cdb67f0882.png)

**Comment by lewis6991** [comment]
I've raised #172 which reworks the floating window creation. The main difference is that `winhl` is no longer set so you should be able to configure `NormalFloat` as normal.

Could people take a look and let me know if the change is acceptable and resolves the issues here?

**Comment by vilari-mickopf** [comment]
Works fine for me.

**Comment by vilari-mickopf** [comment]
Actually, it seems that it's calculating win height/width only on first call, so when I add some changes to the same hunk or jump to other hunk with different height/width, it will either wrap the changes if wider, or I will need to scroll for the rest.

**Comment by lewis6991** [comment]
Thanks for spotting that. Should be fixed now.

**Comment by vilari-mickopf** [comment]
Looks fine now

**Comment by N1v3x2** [comment]
Hi, would it be possible to allow custom highlight groups to be passed into `preview_configs`? I'd like to configure the highlight groups of my Gitsigns preview window without changing my global `NormalFloat` highlight group.

**Comment by N1v3x2** [comment]
I can see in the source code that you disable all autocmd events when opening the preview window so I can't target your window with custom autocommands

```lua
local function noautocmd(f)
  return function()
    local ei = vim.o.eventignore
    vim.o.eventignore = 'all'
    f()
    vim.o.eventignore = ei
  end
end
```
