### ISSUE TITLE
Blame line: allow to show full commit message

### ISSUE THREAD

**Issue by weilbith** [lewis6991/gitsigns.nvim#173]
**Is your feature request related to a problem? Please describe.**
I'm using the `current_line_blame` option of the plugin. But sometimes the header of a commit message is not too helpful and more details are needed to "understand" a line of code. If I then call `lua require('gitsigns').blame_line()`, I get a nice floating window with coloring, border etc, but still just the commit message header. Looking into the code of this plugin here, it actually seem like the full commit message is actually available, but gets stripped away.

**Describe the solution you'd like**
See the full commit message in the floating window. Maybe an option to enable this feature conditionally (to preserve current behavior). And maybe an option for the maximum height of the floating window. So if the message is very long just into the window as usual and scroll.

**Describe alternatives you've considered**
There are other plugins like `git-messenger.vim` which provide this as a standalone feature. But as I'm already using `gitsigns.nvim` and it basically has this feature, it would be nice to reduce my plugin stack by one redundant plugin. Furthermore the above mentioned plugins does not use the new NeoVim floating window borders which sucks a little.

**Comment by lewis6991** [comment]
Sounds good. Will implement when I get some spare time. Otherwise a PR would be welcome.

**Comment by lewis6991** [comment]
Turns out the full commit message wasn't available, however wasn't too hard to get. #175 adds an option to `blame_line()` to show the full commit message and this is set to true for the default mappings. There isn't anything fancy like scrolling or anything yet, so large commit messages might cause issues.

**Comment by lewis6991** [comment]
@weilbith could you let me know what you think of the PR?

**Comment by lewis6991** [comment]
@joelpalmer thanks so much for the feedback. There was a minor mistake in the code, it should be fixed now.

**Comment by weilbith** [comment]
Hey, sorry that I was so inactive. :see_no_evil:
Thank you very much for this feature. I's amazing! 🙏🏾
