### ISSUE TITLE
[Feature] Stage all hunks in range

### ISSUE THREAD

**Issue by sindrets** [lewis6991/gitsigns.nvim#176]
It would be great to be able to stage all hunks in a given range. When making multiple small edits you can end up with lots of small hunks. It's a bit cumbersome to stage each hunk individually when you don't want to stage the entire file.

**Comment by lewis6991** [comment]
Great idea. I guess we can probably modify `stage_hunk()` to respect the visual selection range.

**Comment by cloggier** [comment]
Awesome! I was hoping `<leader>hs` (and others too maybe) would work in visual mode. 

Asking for an operator, motion pending mapping is probably too much? Would there be an use for it? `hsG` to stage all hunks from cursor position to end of buffer? Just a thought.
