### ISSUE TITLE
Expose get_cursor_hunk method

### ISSUE THREAD

**Issue by jose-elias-alvarez** [lewis6991/gitsigns.nvim#179]
I'm working on a small (and perhaps ill-conceived!) plugin to simplify the process of injecting / modifying LSP code actions, very similar to the solution you describe in #100. I think Git actions would be a great example of how synthetic code actions can improve discoverability / UX, especially when combined with something like Telescope or [nvim-lspfuzzy](https://github.com/ojroques/nvim-lspfuzzy). 

The goal is to have a simple API to allow plugin authors to create integrations themselves, but for now, if gitsigns exposed the `get_cursor_hunk` method defined in `gitsigns.tl`, it would be very straightforward to determine whether to inject the relevant actions, as in the following example (which is working as expected with locally modified code):

```lua
local create_git_actions = function()
    local gitsigns = require("gitsigns")
    local has_hunk = gitsigns.get_cursor_hunk()
    if not has_hunk then return end

    return {
        {title = "Reset hunk", action = gitsigns.reset_hunk},
        {title = "Stage hunk", action = gitsigns.stage_hunk},
        {title = "Preview hunk", action = gitsigns.preview_hunk}
    }
end
```

I imagine other plugins might want to use this method, too, so please let me know if this is something you'd be interested in and I'll put in a PR.

**Comment by lewis6991** [comment]
Exposing the function is trivial, but it has the effect of making it part of the public API which means changing it will break anything that depends on it.

With that said, I am very open to designing an API to enable what you want. Maybe something like `get_actions()` which just returns a list of all the function names that can be applied at the cursor position?

**Comment by jose-elias-alvarez** [comment]
That would be even better, actually. An API to describe the actions available at a given position with the option to pass in a position (to avoid double API calls and to leave it flexible) would be ideal. 

For pseudo-code actions, I imagine the most relevant actions would be the hunk-specific actions as well as `blame-line`, in keeping with the philosophy that code actions should be scoped to the current cursor position. Maybe that's enough for now?

Either way, let me know how I can help, and thanks for taking a look at this.

**Comment by lewis6991** [comment]
@jose-elias-alvarez: can you review #201?
