### ISSUE TITLE
Clarify usage & setup requirements

### ISSUE THREAD

**Issue by please-fix-swapgs** [lewis6991/gitsigns.nvim#181]
I wanted to try this plugin since it looks amazing but unfortunately it doesn't quite seem to work out of the box:
Other than `:Gitsigns blame_line` I could not get anything to work but I don't get any error output either, things
like `:Gitsigns toggle_current_line_blame` simply don't do anything.

Are there additional configuration requirements beyond `require 'gitsigns'.setup()`? I tested the plugin by operating on a single
file opened directly.

**Comment by lewis6991** [comment]
- `require 'gitsigns'.setup()` should be all you need. 
- Make sure you have `plenary.nvim` installed and is up to date.
- Make sure your build of neovim is fairly recent, within the last month or so.

You could try `require('gitsigns').setup{debug_mode=true}` which enables debug messages. Then look at the output of `:Gitsigns debug_messages`. The output of `:Gitsigns dump_cache` may also give a clue to why it's not working.

**Comment by please-fix-swapgs** [comment]
I'm running nvim straight from `HEAD` and have `plenary.nvim` installed. Where can I see the debug messages? `debug_mode = true` doesn't appear to log anything directly.

**Comment by please-fix-swapgs** [comment]
> I'm running nvim straight from `HEAD` and have `plenary.nvim` installed. I'll check the debug log.

```
setup_highlight: Deriving GitSignsDelete from GitGutterDelete
setup_highlight: Deriving GitSignsChange from GitGutterChange
setup_highlight: Deriving GitSignsAdd from GitGutterAdd
setup_highlight: Deriving GitSignsCurrentLineBlame from NonText
run_job: git --no-pager --git-dir=/Users/swapgs/dev/test/.git show :0:main.c
update(1): updates: 2, jobs: 6
```
Does this look abnormal?

**Comment by please-fix-swapgs** [comment]
So it turns out that it actually does work, it's just really really slow. It takes about 2-3 seconds to display the blame results for every line. Is this expected? The repository is very small.

**Comment by lewis6991** [comment]
Ahh. `current_line_blame` is triggered on the `CursorHold` autocmd event which has a delay defined by `updatetime` which defaults to 4 seconds. Usually, people have this set to something much lower. I think I have it set to 100ms.
