### ISSUE TITLE
hunk preview highlight

### ISSUE THREAD

**Issue by onsails** [lewis6991/gitsigns.nvim#182]
In my colorscheme hunk preview looks like this:
![image](https://user-images.githubusercontent.com/107261/117326269-8ee15880-aea2-11eb-8e02-ecefabaa916c.png)

Green deletions don't make sense, I'd like to fix that but I can't find corresponding highlight groups in the doc.

**Comment by lewis6991** [comment]
It just uses the `diff` filetype defined [here](https://github.com/neovim/neovim/blob/master/runtime/syntax/diff.vim).
