### ISSUE TITLE
Emoji support in blame_line

### ISSUE THREAD

**Issue by kiuKisas** [lewis6991/gitsigns.nvim#183]
I use gitmoji in my company for commit, so we have commit as `:lipstick: style(responsive) improvement` for example.
It could be nice to have an option to show emoji, so the previously commit can look like:  `💄style(responsive improvement)`

**Comment by lewis6991** [comment]
You can implement `config.current_line_blame_formatter` to sub the emoji.

Doing this for the project is out of scope unless there exists a tool/plugin to perform the substitutions.
