### ISSUE TITLE
Relative date formatting for current_line_blame_formatter

### ISSUE THREAD

**Issue by CallumHoward** [lewis6991/gitsigns.nvim#186]
**Is your feature request related to a problem? Please describe.**
It is convenient to have relative dates in the current_line_blame to quickly get a sense of how old the blame is.

**Describe the solution you'd like**
I would like a way to use relative date formatting for `current_line_blame`, perhaps just an example Lua code that can be used in `current_line_blame_formatter`.
The date would be formatted similar to the blame line provided by VSCode gitlens extension:
<img width="523" alt="Screen Shot 2021-05-11 at 9 09 47 am" src="https://user-images.githubusercontent.com/7144420/117735738-6908da80-b239-11eb-907b-8c23be98e5bc.png">

[blamer.nvim](https://github.com/APZelos/blamer.nvim) has an implementation here that may be useful for reference:
https://github.com/APZelos/blamer.nvim/commit/c9235dd8c219456f8671a975111c8e6340e6adf5#diff-260a240c28503a5f8b6073b4dd8a79644a815c97148263ee6cc3569f5c28c4a1R29

Looks like:
![image](https://user-images.githubusercontent.com/7144420/117736500-129c9b80-b23b-11eb-9e53-892ee9eef477.png)

Alternatively there may be a way to retrieve the blame in relative form from `git blame --date=relative`.

**Additional context**
When I have some time, I might try to port the Vimscript from `blamer.nvim` to Lua, however I'm still quite new to Lua. I'll update this issue if there is any progress. For now I thought making an issue will be good for visibility, or if anyone else is looking for (or has a solution already) for the same thing.

**Comment by lewis6991** [comment]
I guess we can just add a function to convert the date to relative which can be used in the formatter.

**Comment by danielebra** [comment]
Hey @lewis6991 , this would be a great addition to the plugin. Any updates on this?

**Comment by zapling** [comment]
@lewis6991 I could have a go at implementing if you don't mind

**Comment by lewis6991** [comment]
Go for it.
