### ISSUE TITLE
Diff symbols are shown next to commit message when used for a bare git repository

### ISSUE THREAD

**Issue by maxigaz** [lewis6991/gitsigns.nvim#193]
**Describe the bug**
Diff symbols are shown next to commit message when used for a bare git repository

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.local/share/nvim/plugtest'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
  -- config
}
EOF
```

1. Create a bare git repo with `git init --bare /tmp/gitsigns-test/.dotfiles.git`
2. Add file:
  - `echo "bar" > /tmp/gitsigns-test/foo.txt`
  - `git --git-dir=/tmp/gitsigns-test/.dotfiles.git --work-tree=/tmp/gitsigns-test add foo.txt`
3. Run `GIT_EDITOR="nvim -u ~/.config/nvim/init.test.vim --noplugin" git --git-dir=/tmp/gitsigns-test/.dotfiles.git --work-tree=/tmp/gitsigns-test commit`
4. Notice the symbols left of the line numbers

**Observed output**

`:Gitsigns debug_messages`

```
setup_highlight: Deriving GitSignsDelete from DiffDelete
setup_highlight: Deriving GitSignsChange from DiffChange
setup_highlight: Deriving GitSignsAdd from DiffAdd
run_job: git --no-pager --version
attach(1): Attaching
run_job: git --no-pager config user.name
run_job: git --no-pager rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --git-dir=/tmp/gitsigns-test/.dotfiles.git ls-files --stage --others --exclude-st
andard /tmp/gitsigns-test/.dotfiles.git/COMMIT_EDITMSG
watch_index(1): Watching index
run_job: git --no-pager --git-dir=/tmp/gitsigns-test/.dotfiles.git show :0:COMMIT_EDITMSG
update(1): updates: 1, jobs: 5
```

**Screenshots**

Working with my bare repository set in `$HOME`:

![nvim-gitsigns-2](https://user-images.githubusercontent.com/10419911/118471768-652cfa80-b708-11eb-9457-0ef8b08ca265.png)

The same behaviour, with colours properly set up (using my regular init files):

![nvim-gitsigns-gitcommit](https://user-images.githubusercontent.com/10419911/118357515-dc348880-b57a-11eb-8b54-ee2be10b851d.png)

**Additional context**
System: Manjaro Linux x86-64
Neovim version: 0.5.0-dev+1318-g61aefaf29

I've also tried committing in normal git repos, and the signs don't appear next to the commit message. Also, I don't have this problem at all in vim-gitgutter.

Edit: Included steps for setting up a temporary bare repo.

**Comment by lewis6991** [comment]
Can you please follow the instructions on the bug issue template.

**Comment by maxigaz** [comment]
Weirdly enough, no templates appeared when I opened the issue. I see them now, though.

I've updated the original post.

**Comment by lewis6991** [comment]
Thanks for that. The debug messages makes it clear what is happening.

Can you try #195 and report if that fixes the issue?

**Comment by maxigaz** [comment]
It seems to have fixed it. Thank you!
