### ISSUE TITLE
Set filetype for git_blame window

### ISSUE THREAD

**Issue by seblj** [lewis6991/gitsigns.nvim#196]
I had an idea to fix gitmoji for the git blame window, but my solution depends on setting a few settings in the ftplugin directory. A filetype for the window would help with this. I could fix a PR for this as this would only require one line.

If there is a way for me to set the filetype myself, this would also work! I just couldn't figure out a way to do this

**Comment by lewis6991** [comment]
There have been one or two requests for configuring preview windows so something more general would be preferable. Maybe something like an `on_open_win` callback or something.

**Comment by seblj** [comment]
Yeah I think that's a good idea!

**Comment by lewis6991** [comment]
This should be fulfilled by #622 which sets the window variable `gitsigns_preview` to either `blame` or `hunk`.
