### ISSUE TITLE
blame text is covered by indentlines

### ISSUE THREAD

**Issue by WhyNotHugo** [lewis6991/gitsigns.nvim#197]
**Describe the bug**

I use https://github.com/lukas-reineke/indent-blankline.nvim

It draws indentation lines and does this by drawing virtual text in empty lines.

gitsigns puts the blame lines left-aligned, so is expects to use the same position as the other plug-in. They overlap and the other win gets rendered.

Is there any way I can make these draw aligned with respect to existing virtual text?

Or should indentlines be doing something different?

**To Reproduce**

```lua
  use {
    'lukas-reineke/indent-blankline.nvim',
    branch='lua',
  }

  use {
    'lewis6991/gitsigns.nvim',
    requires = { 'nvim-lua/plenary.nvim' },
    config = [[require('gitsigns').setup{ current_line_blame = true]]
  }
```

1. Use the following sample text:
2. ```lua  signs = {
    add = {hl='GitSignsAdd', text = '▋'},
    change = {hl = 'GitSignsChange',text= '▋'},
    delete = {hl= 'GitSignsDelete', text = '▁ '},
    topdelete = {hl ='GitSignsDelete',text = '▔'},
    changedelete = {hl = 'GitSignsChange', text = '▎'},

  },
  current_line_blame = true
}```
1. Go to line 8.

**Observed output**
1. You'll see:
2. `   |ot Committed Yet`

**Screenshots**
![image](https://user-images.githubusercontent.com/730811/119400795-30054700-bcca-11eb-9794-270195dc4979.png)

![Uploading image.png…]()

**Additional context**
System: Mac, Linux (including dist), Linux
Neovim version: 0.4.0.r3650.g75992f2ad-1 (HEAD)

**Comment by lewis6991** [comment]
indent-blankline.nvim uses `nvim_buf_set_virtual_text` whereas gitsigns uses `nvim_buf_set_extmark` to set virtual text.

`nvim_buf_set_virtual_text` has not `priority` option so we can't control whether it will display over other virtual texts or not. However `nvim_buf_set_extmark` does have a `priority` option although gitsigns currently does not use it.

To resolve this issue both plugins need to use `nvim_buf_set_extmark` with a given `priority` (gitsigns > indentline).

**Comment by WhyNotHugo** [comment]
Thanks for looking into it!

So `indent-blankline.nvim` would need to use `nvim_buf_set_extmark`, likely with a priority of `0`, since it always wants to be on the far left.

`gitsigns` would need to use a higher priority, since it always wants to be on the far right. If that's already the case, then I guess there's nothing to be done here.

I'll cross-post the issue to `indent-blankline.nvim` though. Or maybe figure out if it's simple enough and I can address it.

**Comment by lewis6991** [comment]
Looks like theres activity in core and indent-blankline on this. Going to close this but will reopen on request.
