### ISSUE TITLE
Export the blame line variable

### ISSUE THREAD

**Issue by sangdth** [lewis6991/gitsigns.nvim#199]
**Is your feature request related to a problem? Please describe.**
I need a variable to easily get the blame text, so I can use somewhere like galaxyline in lua

**Describe the solution you'd like**
Something like `b:gitsigns_blame_line`

**Additional context**
Currently I'm using the `galaxyline`, so it would be great if I can write a section like this
```
  GitBlame = {
        provider = require("gitsigns").gitsigns_blame_line,
        condition = require("galaxyline.provider_vcs").check_git_workspace,
        highlight = {colors.red, colors.bg},
    }
```
Thank you.

**Comment by lewis6991** [comment]
Sounds reasonable. I'm guessing `require("gitsigns").gitsigns_blame_line` just needs to be a function that returns a string?

**Comment by sangdth** [comment]
Yes, something like that, `Name | 22 May 2021 | commit message truncated...` is great for me. Would be perfect if I can format it with function somewhere.

**Comment by lewis6991** [comment]
There are a couple of issues related to blame formatting which I think I'll solve by implementing the git format spec so that'll be separate from this issue.

**Comment by sangdth** [comment]
Then I think just return strings with `\n` separator is OK, I can customize it outside.

**Comment by lewis6991** [comment]
@sangdth can you check out #289 . I implemented this by setting the buffer variable `b:gitsigns_blame_line_dict`.
