### ISSUE TITLE
gitsigns overrides lsp signs

### ISSUE THREAD

**Issue by p00f** [lewis6991/gitsigns.nvim#2]
![Screenshot from 2020-10-30 19-39-13](https://user-images.githubusercontent.com/36493671/97715035-e9f75480-1ae7-11eb-988e-230f960d0051.png)
Please decrease the priority, because lsp signs are more important than git signs

**Comment by lewis6991** [comment]
Yes sure. Have been meaning to do this.

**Comment by lewis6991** [comment]
Also FWIW you can `set signcolumn=auto:3` to get 3 signs columns.

**Comment by lewis6991** [comment]
Fixed in 06f0e23f67ce3edfe47b09cb93f017b661a3a435

**Comment by p00f** [comment]
thanks
