### ISSUE TITLE
Disable so you don't get to the first hunk when you are at the last one and do next_hunk()?

### ISSUE THREAD

**Issue by zapling** [lewis6991/gitsigns.nvim#204]
I'm wondering if it's possible to disable the loop back that is done when you are at the last hunk in a file, and do `next_hunk(). Currently you get to the first one, but if possible I would like to disable that and give me a warning about being on the last hunk. Is this possible? If not, maybe something to consider adding a feature flag for?

**Comment by lewis6991** [comment]
See `:help 'wrapscan'`

**Comment by zapling** [comment]
Okay, right. I don't want to disable that globally, so I guess I'll just patch `actions.lua` locally to always have that as false. Thank you :)

**Comment by lewis6991** [comment]
Ah ok, well `next_hunk()` and `prev_hunk()` also take an options table as an argument with the key `wrap` so you can do:

``
:lua require('gitsigns').prev_hunk({wrap=false})
:lua require('gitsigns').next_hunk({wrap=false})
```

**Comment by zapling** [comment]
Ah! I should really get better searching the docs in the future, sorry for wasting your time as you have already thought of this feature. `next_hunk({wrap=false})` is exactly what I'm after :)

**Comment by zapling** [comment]
Although now when testing `:lua require('gitsigns').next_hunk({wrap=false})`, it still wraps around?  :confused: :sweat:

**Comment by lewis6991** [comment]
Ok, I'll  look into this.
