### ISSUE TITLE
bad argument #1 to 'fs_realpath' (string expected, got nil) on git v2.11

### ISSUE THREAD

**Issue by benatouba** [lewis6991/gitsigns.nvim#205]
** Bug **
Thanks for the awesome plugin!
Gitsigns fails plenary coroutine with error on git version 2.11

**To Reproduce**

init.lua:

```lua
vim.cmd 'autocmd BufWritePost plugins.lua PackerCompile' -- Auto compile when there are changes in plugins.lua
-- Only required if you have packer in your `opt` pack
vim.cmd [[packadd packer.nvim]]

return require('packer').startup(function(use)
|   use {'lewis6991/gitsigns.nvim', config = function() require('gitsigns').setup() end}
end
)
```

1. Install git version 2.11
2. Open a file in a git repository with neovim (file should be opened on nvim startup and contain changes)

**Observed output**
```
Error executing luv callback:
...acker/start/plenary.nvim/lua/plenary/async_lib/async.lua:14: The coroutine failed with this message: ...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:178: bad argument #1 to 'fs_realpath' (string expected, got nil)
Error executing luv callback:
cannot resume dead coroutine
Error executing luv callback:
cannot resume dead coroutine
Error executing luv callback:
cannot resume dead coroutine
```

System: Linux (Debian 9.12)
Neovim version: v0.5.0-dev+1374-g7d4f890aa

**Comment by lewis6991** [comment]
Are you able to provide the output of `debug_messages()` as per the issue template describes?

**Comment by benatouba** [comment]
Yes. I skipped that, because I did not immediately find that. but here they are:
```
run_job: git --no-pager --version
attach(1): Attaching
run_job: git --no-pager config user.name
run_job: git --no-pager rev-parse --show-toplevel --git-dir --abbrev-ref HEAD
```

**Comment by lewis6991** [comment]
Are you able to run the commands in your shell? Which ones give you errors? Since you're using git 2.11, gitsigns is probably trying to use an argument not available in that version.

**Comment by benatouba** [comment]
Thank you for the quick reply.

**Comment by lewis6991** [comment]
I think the error is coming from line 178 of `lua/gitsigns/git.lua`. Could you throw `print(vim.inspect(results))` in there to see what's being output by the git command?

**Comment by benatouba** [comment]
Sure. it is an empty table ```{}```

**Comment by lewis6991** [comment]
Whats does `git --no-pager rev-parse --show-toplevel --git-dir --abbrev-ref HEAD 2> /dev/null` do in your shell?

**Comment by lewis6991** [comment]
Also verify `path` is correct, it should be the dirname of your file.

**Comment by benatouba** [comment]
It works fine. It outputs 3 lines: 
<repo path>
.git
<branch>

**Comment by lewis6991** [comment]
And maybe try `supress_stderr = false` to see if there is any stderr.

**Comment by benatouba** [comment]
as an option of the gitsigns setup? That does not add any output. BTW: setting a username also does not help.

**Comment by lewis6991** [comment]
I mean in `lua/gitsigns/git.lua` where you saw the empty table. For some reason that command isn't working correctly.

**Comment by benatouba** [comment]
Yes. Now I saw it and changed it. Unfortunately, it does not add anything.

**Comment by lewis6991** [comment]
Did you verify `path` passed to the command in `git.lua`?

**Comment by benatouba** [comment]
Yes. I changed it. It does not add any output unfortunately.


> Did you verify `path` passed to the command in `git.lua`?

Yes. the path is correct.

**Comment by lewis6991** [comment]
I'm not really sure what else to suggest.

I'll see if I can install git 2.11 and see if I can reproduce, but otherwise you'll need to debug this one yourself.

Let me know if you need any help.

**Comment by benatouba** [comment]
One more thing:
```
.print(vim.inspect(await(command({'rev-parse', '--show-toplevel', git_dir_opt, '--abbrev-ref', 'HEAD'}, { command = 'git', supress_stderr = false, cwd = path}))))
```
outputs the right thing:
```
{ "/root/.local/share/nvim/site/pack/packer/start/gitsigns.nvim", "/root/.local/share/nvim/site/pack/packer/start/gitsigns.nvim/.git", "main" }
```

**Comment by benatouba** [comment]
![image](https://user-images.githubusercontent.com/33120334/120823764-1086dd80-c558-11eb-8014-b528f82a1bdb.png)

**Comment by benatouba** [comment]
![image](https://user-images.githubusercontent.com/33120334/120824212-812dfa00-c558-11eb-87a8-39054aff78d9.png)

**Comment by lewis6991** [comment]
That doesn't make much sense as you said results was an empty table?

**Comment by benatouba** [comment]
yes. That is true. Something with the assignment does not work? See in the screenshot. The output of lines 45-46 are in the command line output.

**Comment by lewis6991** [comment]
What happens if you reorder the commands? The assignment looks ok to me. Something weird is happening

**Comment by benatouba** [comment]
It probably is alright. Could there be async stuff happening and the output is not ready in time?
it works fine, if I just use the ```await(command(....))`` without assigning it to a local variable.

**Comment by lewis6991** [comment]
@benatouba does the above fix work for you?

**Comment by benatouba** [comment]
Unfortunately not. I will deactivate the plugin until I find the time get to the bottom of this. I will make a PR if I can find a fix. Thx for the effort.

**Comment by lewis6991** [comment]
Any update on this? We've recently migrated to a new async implementation which might address this.

**Comment by benatouba** [comment]
Unfortunately still an issue. Only on the server we're using (where git version == 2.11.0), not on my local machine. Even on the server it only occurs on load of some files.

**Comment by DavidEGx** [comment]
Got a very similar error when opening a file that was not in a git repository.

Fixed by updating Git (`sudo apt install git/stretch-backports`).
