### ISSUE TITLE
Error when yadm is enabled and the file is outside of HOME

### ISSUE THREAD

**Issue by ouuan** [lewis6991/gitsigns.nvim#207]
**Describe the bug**

When yadm is enabled in gitsigns, if I open a file outside of HOME, which is the directory maintained by yadm, it shows an error.

I think gitsigns should check whether the file is in the `$HOME` directory before using yadm.

**To Reproduce**

```lua
require('gitsigns').setup {
    yadm = { enable = true },
}
```

1.  `nvim /etc/pacman.conf`

**Observed output**

![screenshot](https://user-images.githubusercontent.com/30581822/120874885-4b7e2500-c5db-11eb-92d5-66b50827b04b.png)

**Additional context**

System: Arch Linux

**Comment by lewis6991** [comment]
@ouuan : Could you test the linked PR?
