### ISSUE TITLE
Relative numbers disappears

### ISSUE THREAD

**Issue by desdic** [lewis6991/gitsigns.nvim#208]
Not really sure why but for some reason my numbers disappears when there are changes
![2021-06-05_081639_268357439](https://user-images.githubusercontent.com/13243026/120882265-c1cc5880-c5d6-11eb-8ed6-427bd025766d.png)

and set numberwidth=10 isn't changing that .. how did you get the numbers and the gitsigns ?

**Comment by desdic** [comment]
After hours of debugging I finally found that if I set
```
vim.wo.signcolumn = "yes"
```

I get the number and gitsigns

**Comment by lewis6991** [comment]
Someone has had this issue before. I'll add something to the FAQ

**Comment by lewis6991** [comment]
Ah just looked into this and I guess you must of have `set signcolumn=number`. I keep forgetting `signcolumn` has this option. Since this is not the default value (`auto` is), I don't think a FAQ for this is worth it.
