### ISSUE TITLE
No longer checking for current_line_blame

### ISSUE THREAD

**Issue by Unoqwy** [lewis6991/gitsigns.nvim#218]
**Describe the bug**
No matter what value `current_line_blame` is set to (by setting in config or trying to toggle), it will always show.

1. Try to toggle current_line_blame, it will always show.

**Additional context**
Since latest commits half an hour ago. [This change](https://github.com/lewis6991/gitsigns.nvim/commit/60b10048ddda8a7ebf3b94db978ab0963742fb0a#diff-ebbc7b3072a4d740d6049c9b65c26d7e4029bfc2c4890f8cde1cf5264b496412L52-R70) is most likely the culprit.

**Comment by lewis6991** [comment]
Whoops sorry about that. I've been a bit too lax on regression tests lately. Will need to add one for this.

Thanks for reporting.
