### ISSUE TITLE
Hunk preview window too small

### ISSUE THREAD

**Issue by cloggier** [lewis6991/gitsigns.nvim#222]
**Describe the bug**
I am not sure how size for preview floating window (if at all) is calculated, but for me it always is too small. It either causes line to wrap or requires scrolling to see remainder of the hunk. There is enough screen available for bigger window.
 
**To Reproduce**
init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
  -- config
}
EOF
```

1. Go to any hunk that is not very small.
2. Invoke hunk preview command.

**Observed output**
Window with wrapped lines and/or requiring scrolling

There are only git commands in debug output, nothing regarding window.

**Screenshots**
<img width="1680" alt="window" src="https://user-images.githubusercontent.com/69750637/122038994-df6f9e00-cdde-11eb-8cdd-d78a5045e9e9.png">

(please ignore search highlight) There is visible wrap, and also `+` line below that replaced `-` line visible in preview.

**Additional context**
System: Mac
Neovim version: v0.5.0-dev+8cdffd42d
Gitsigns is up to date (as of now).

**Comment by lewis6991** [comment]
I can't reproduce this however here's the code that calculates the required width:

```lua
local function bufnr_calc_width(buf: integer, lines: {string}): integer
  return api.nvim_buf_call(buf, function(): integer
    local width = 0
    for _, l in ipairs(lines) do
      local len = vim.fn.strdisplaywidth(l)
      if len > width then
        width = len
      end
    end
    return width
  end)
end
```

For whatever reason, this function is resulting in a width which is 2 characters shorter than it needs to be.

**Comment by lewis6991** [comment]
Also your preview has some whitespace padding at the beginning, this is probably what's causing the issue.

**Comment by lewis6991** [comment]
An output of `:Gitsigns dump_cache` will let us know if that padding is included in the hunk itself or if you have some config causing this.

**Comment by cloggier** [comment]
Aha, good pointer. My border is:
```
{
  {"▎", "NormalFloat"},
  {" ", "NormalFloat"},
  {" ", "NormalFloat"},
  {" ", "NormalFloat"},
  {" ", "NormalFloat"},
  {" ", "NormalFloat"},
  {"▎", "NormalFloat"},
  {"▎", "NormalFloat"}
}
```
Will try without it and report back.

**Comment by cloggier** [comment]
<img width="596" alt="Screenshot 2021-06-15 at 14 29 55" src="https://user-images.githubusercontent.com/69750637/122045245-2a40e400-cde6-11eb-95af-637496c81f97.png">
Unfortunately still the same with distributed border (rounded).

**Comment by lewis6991** [comment]
It won't be the border because that isn't a part of the buffer. Try recreating this without your config as the issue template instructs.

**Comment by cloggier** [comment]
Apologies for the delay @lewis6991, will try to recreate the issue as soon as I get some free time.

**Comment by cloggier** [comment]
Ah, just had a quick look and it seems like `signcolumn = "auto:1-2"` is the culprit.

**Comment by lewis6991** [comment]
Thanks for debugging. I would have thought `style=minimal` would have prevented this but I guess that doesn't consider when `auto` has a min length.

**Comment by lewis6991** [comment]
PR that fixes this issue in core https://github.com/neovim/neovim/pull/15253
