### ISSUE TITLE
Disable on startup

### ISSUE THREAD

**Issue by timsofteng** [lewis6991/gitsigns.nvim#223]
Hello. Can i disable signs on startup and just toggle it when I need? Can't find disable option in readme...

**Comment by lewis6991** [comment]
Just call `setup` when you need it.

**Comment by timsofteng** [comment]
> Just call `setup` when you need it.

Could you please print the command for <Leader>gs map for example?
How can I map it? Sorry I'm not good in lua...

**Comment by lewis6991** [comment]
The command would just be:

```
:lua require(gitsigns).setup()
```

Run this command and gitsigns will run and attach to all open buffers.

**Comment by lewis6991** [comment]
I don't know, it's not something I've ever looked into or even thought about.

Why don't you just use `:Gitsigns toggle_signs` instead?

**Comment by timsofteng** [comment]
> signcolumn=false

Yep! This is exactly what I need. Thanks. Close issue.
