### ISSUE TITLE
Plugin stopped working

### ISSUE THREAD

**Issue by gbrlsnchs** [lewis6991/gitsigns.nvim#23]
Suddenly, this awesome plugin stopped showing signs and its variables return nothing. No errors though. All functions are available, but they do nothing. "Preview" function is a NOP function now, no errors but no effect.

Plugin version: `2218e1ab512c21699a9b42aa73cc56efd9f9ba33`
Neovim version: `71d4f5851f068eeb432af34850dddda8cc1c71e3` from `master`

**Comment by lewis6991** [comment]
Are you able to bisect back to a version that works?

**Comment by gbrlsnchs** [comment]
If you were unable to reproduce with the exact versions I informed, then it's probably an issue on my side. I'll keep fiddling with it in order to find the culprit. Thanks!

**Comment by gbrlsnchs** [comment]
@lewis6991 I think the problem boils down to `run_diff`'s `results` being empty, even when there are diffs to be shown.

I see `run_diff` executes `git diff ...` with some argumentes. Would `GIT_PAGER` interfere with the results? I use Neovim (along with [neovim-remote](https://github.com/mhinz/neovim-remote)) as my pager, so it's not `less` by default. I think maybe it's messing with the diff results, so the plugin works fine but there are never any diffs to be shown by it.

**Comment by lewis6991** [comment]
`git diff` should be run as `git --no-pager diff`. If you set `debug_mode = true` in your config, you can see each system command output in `:messages`

**Comment by lewis6991** [comment]
Call me a liar, `run_diff` seems to be the only git command without `--no-pager`. Can you add the flag and see if it fixes the issue?

**Comment by gbrlsnchs** [comment]
I found the error, we need to pass `--color=never`. Gonna reopen this and then open a PR solving it.

**Comment by gbrlsnchs** [comment]
#27 solves this.

**Comment by lewis6991** [comment]
Thanks for fixing this.

It would be great if we could add a testcase for this. Do you have any idea how we can reproduce the issue on a fresh Ubuntu install?

**Comment by gbrlsnchs** [comment]
My issue was due to having `color.diff` set to `always` in my Git config, so gitsigns tried to parse an output full of escape codes. If you could set an environment with such Git config (`git config --global color.diff always`), it would do the job.

**Comment by lewis6991** [comment]
Thanks, was able to reproduce and a test.
