### ISSUE TITLE
Toggle <del>line_hl</del>word_diff

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#235]
While the `linehl` (especially in combination with the `word_diff`) option is really cool, I feel it is a bit intrusive for languages with heavy syntax highlighting. (In fact, I cannot get `word_diff` to work for such languages like Lua and LaTeX, while it works fine in markdown -- but that is a different issue.)

However, seeing at a glance exactly what was changed in a line without a full (side-by-side or patch-style) diff is very useful every once in a while. So it would be nice to have an option to toggle it with a command (and be able to bind it to a key mapping, of course). An alternative would be to make it behave like `blame` or LSP diagnostics (or conceal) and only show it on `InsertLeave` and `CursorHold`. (Although in fact having vice versa a toggle for `blame` on _all_ lines would be even nicer!)

**Comment by lewis6991** [comment]
Doesn't `:Gitsigns toggle_linehl` fulfill this?

> Although in fact having vice versa a toggle for blame on all lines would be even nicer!

Hmm, I would suggest using fugitives `:Git blame` for now. If you want to view a blame for all lines then I would think you'd also want these blame annotations aligned which is what `:Git blame` does.

**Comment by clason** [comment]
> Doesn't `:Gitsigns toggle_linehl` fulfill this?

Ooops... 🤦🏻  (I tend to look only at the Lua API for Lua plugins and thus too easily miss Vimscript commands.)

Yep, that is exactly what I meant. (The `word_diff` issue remains but is another matter.)

> Hmm, I would suggest using fugitives `:Git blame` for now. If you want to view a blame for all lines then I would think you'd also want these blame annotations aligned which is what `:Git blame` does.

Well, ideally I'd like to replace all my plugins with `gitsigns` :P 

But that's fair (and unrelated to this issue anyway)!

**Comment by lewis6991** [comment]
> Ooops... 🤦🏻 (I tend to look only at the Lua API for Lua plugins and thus too easily miss Vimscript commands.)

All of the gitsigns lua API is mapped as sub-commands of `:Gitsigns` so: `:Gitsign toggle_linehl` is equivalent to `:lua requires'gitsigns'.toggle_linehl()`

> Well, ideally I'd like to replace all my plugins with gitsigns :P

Yeah, `:Git blame` is the last thing I use from fugitive. It does quite a lot so won't be trivial to add to gitsigns.

**Comment by clason** [comment]
Yeah, I was simply blind. My bad!

**Comment by clason** [comment]
Actually, I think I have to come back to this: while there is indeed a `toggle_linehl`, I don't see a way of toggling `word_diff`. I had originally assumed this to option to modify the line highlighting, but it seems to be an independent mode (meaning, it always shows at least for Markdown files, and toggling line highlighting on overrides the word diff)?

**Comment by lewis6991** [comment]
Yeah, they are both orthogonal things at the moment. In fact, no matter what priority I give to the word diff extmarks, the linehl always takes priority. Just one of the quirks between the signs and extmarks api.

To make them both work together, we would need to reimplement linehl to use extmarks instead, and is probably worth doing since extmarks are way more flexible. However currently, word_diff uses the linehl highlights so we would need to replace those with word diff specific highlights so it will be possible to distinguish the two when both used together.

Also, it would be trivial to add `toggle_word_diff` so can do that too.

**Comment by clason** [comment]
Yes, this issue is only about adding `toggle_word_diff` in addition to `toggle_linehl`; the rest was just an explanation of why I was confused in the beginning -- the actual behavior is fine and doesn't have to be changed in my view.

**Comment by clason** [comment]
I've just had occasion to try this out again, and it doesn't seem as robust as it could be. Toggling _to_ `word_diff` doesn't immediately enable it -- you need to manually redraw via `<c-l>` (or typing).

Furthermore, if `word_diff` is enabled, the sign vanishes and doesn't reappear until I type something that force a sign refresh?

**Comment by lewis6991** [comment]
I think this is a regression caused by fc170b4e  which broke the refresh function. Fix is to just invalidate the saved hunks in the buffer. Fix incoming.

**Comment by lewis6991** [comment]
Can you quickly try #323? It fixes all the issues I could reproduce.

**Comment by clason** [comment]
Yes, that works fine! 👍🏻
