### ISSUE TITLE
Display warning message when trying to go to next/previous hunk if there isn't one

### ISSUE THREAD

**Issue by mroavi** [lewis6991/gitsigns.nvim#237]
I think it would be a good idea to display a warning message on the status line saying that there are no more hunks after/before the last/first one (of course, only when the wrap option is set to false). Other popular git sign packages like gitgutter have this functionality. What are your thoughts on this?

**Comment by zapling** [comment]
I have also missed this feature from gitgutter. There is a mention of this kind of feature in the TODOs, so I went ahead and implemented a basic version of this. @lewis6991
