### ISSUE TITLE
attempt to index 'outf' (a nil value)

### ISSUE THREAD

**Issue by JSchrtke** [lewis6991/gitsigns.nvim#239]
**Describe the bug**
Opening a git-controlled file with neovim on windows 10 with the gitsigns plugin enabled yields
```
Error executing luv callback:
C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:339: attempt to index upvalue 'outf' (a nil value)
Press ENTER or type command to continue
Error executing luv callback:
cannot resume dead coroutine
Press ENTER or type command to continue
Error executing luv callback:
...js\.vim\plugged\plenary.nvim\lua\plenary\async\async.lua:14: The coroutine failed with this message: C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:343: attempt to index local 'outf' (a nil value)
Press ENTER or type command to continue
```

**To Reproduce**

init.vim:

```vim
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'lewis6991/gitsigns.nvim'
call plug#end()

lua << EOF
require('gitsigns').setup{
    debug_mode = true,
}
EOF

```

1. Open a git version controlled file with neovim
```
nvim init.vim
```
2. See error

**Observed output**
Error:
```
Error executing luv callback:
C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:339: attempt to index upvalue 'outf' (a nil value)
Press ENTER or type command to continue
Error executing luv callback:
cannot resume dead coroutine
Press ENTER or type command to continue
Error executing luv callback:
...js\.vim\plugged\plenary.nvim\lua\plenary\async\async.lua:14: The coroutine failed with this message: C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:343: attempt to index local 'outf' (a nil value)
Press ENTER or type command to continue
```
`Gitsigns debug_messages` output:
```
run_job: git --no-pager --version
cb: Deriving GitSignsChange from DiffChange
cb: Deriving GitSignsDelete from DiffDelete
cb: Deriving GitSignsAdd from DiffAdd
cb: Highlight GitSignsChange is already defined
cb: Highlight GitSignsDelete is already defined
attach(1): Attaching
run_job: git --no-pager config user.name
run_job: git --no-pager rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --git-dir=C:/Users/js/config/.git ls-files --stage --others --exclude-standard C:\Users\js\config\neovim\init.vim
watch_index(1): Watching index
run_job: git --no-pager --git-dir=C:/Users/js/config/.git show :0:neovim/init.vim
```

**Additional context**
System:
```
Microsoft Windows 10 Pro
10.0.19042 Build 19042
```

Neovim version:
```
NVIM v0.5.0-dev+1414-g8cdffd42d
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: C:/msys64/mingw64/bin/cc.exe -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=always -D__USE_MINGW_ANSI_STDIO -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -IC:/Users/js/develop/neovim/build/config -IC:/Users/js/develop/neovim/src -IC:/Users/js/develop/neovim/.deps/usr/include -IC:/msys64/mingw64/include -IC:/Users/js/develop/neovim/build/src/nvim/auto -IC:/Users/js/develop/neovim/build/include
Compiled by js@tmt

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"
```

**Comment by lewis6991** [comment]
What output do you get from?
```
git --no-pager --git-dir=C:/Users/js/config/.git ls-files --stage --others --exclude-standard C:\Users\js\config\neovim\init.vim
```

Are there `\` or `/` in the paths it outputs?

**Comment by JSchrtke** [comment]
I get a `/` in the output.

Cmd:
```
→ C:\Users\js\config› git --no-pager --git-dir=C:/Users/js/config/.git ls-files --stage --others --exclude-standard C:\Users\js\config\neovim\init.vim

100644 5d6e5161d3f73ae7d233a0413df36febeec7b099 0       neovim/init.vim
```

Powershell:
```
~/config main *1 !1 ❯ git --no-pager --git-dir=C:/Users/js/config/.git ls-files --stage --others --exclude-standard C:\Users\js\config\neovim\init.vim

100644 5d6e5161d3f73ae7d233a0413df36febeec7b099 0       neovim/init.vim
```

**Comment by lewis6991** [comment]
What about:
```
git --no-pager --git-dir=C:/Users/js/config/.git show :0:neovim/init.vim
```

I don't have access to a windows machine so I can't experiment with how it expects path separators to be used.

**Comment by JSchrtke** [comment]
That show's the entire `.\neovim\init.vim` files contents. I'll spare you pasting all that in here, unless you need it. Works fine in both Cmd and Powershell.

**Comment by lewis6991** [comment]
Can you try running #247. It doesn't fix the issue but should provide a more helpful error message. For whatever reason `io.open(output_file, 'wb')` is failing for you.

**Comment by JSchrtke** [comment]
```
Error executing vim.schedule lua callback: ...js\.vim\plugged\plenary.nvim\lua\plenary\async\async.lua:14: The coroutine failed with this message: C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:337: \s8po.: Permission denied
```

The current config is now the following, just so we are on the same page:

```
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'lewis6991/gitsigns.nvim', { 'branch': 'issue239' }
call plug#end()

lua << EOF
require('gitsigns').setup{
    debug_mode = true,
}
EOF
```

**Comment by lewis6991** [comment]
For context `\s8po.` is a temporary file name generated by the lua builtin `os.tmpname()`. On unix systems it generates paths of the form `/tmp/lua_xxxx`. We use this file to store a version of the buffer to compare against.

So for whatever reason, you don't have permission do access the temp path `\s8po.`.

I know nothing about windows so this is where my insights end.

Any ideas? We basically need a way to generate temporary paths that works on windows.

**Comment by JSchrtke** [comment]
I would assume that the `os.tmpname()` probably returns `C:\Windows\Temp` on windows, which is where the os saves it's temporary files. A non-admin user does not have access to that.
However, user software on windows is supposed to use the `AppData` directory for that. So in my case that would be `C:\Users\js\AppData\Local\Temp` .

So you could have a dir in there, like `C:\Users\js\AppData\Local\Temp\gitsigns\`.
There are some environment variables that make finding this easier.
`%USERPROFILE%` is the equivalent of `$HOME`
`%APPDATA%` is said appdata directory (example: `C:\Users\js\AppData`)

Sidenote, depending on the shell (either Cmd or Powershell), the invocation syntax for environment variables is different. Cmd uses a leading and following `%` (`%APPDATA%`), whereas Powershell uses `$` (`$APPDATA`).
And while these variables typically are written in all-caps, they aren't actually case sensitive.

**Comment by lewis6991** [comment]
Some [googling](https://vi.stackexchange.com/questions/11949/how-to-fix-the-tempname-function-on-windows-10) suggests that you might need to have `$TMP` or `$TMPDIR` set for this to work? Do you have these vars set? If not does setting them to AppData fix the issue?

What output do you get from `:echo tempname()` from within nvim?

**Comment by JSchrtke** [comment]
By default `%TMP%` is set, pointing to `C:\Users\js\AppData\Local\Temp`.
`%TEMPDIR% is not set by default, setting that to the same as `%TMP%` does not change the issue at hand, I'm still getting the same error as before.

`:echo tempname()` returns `C:\Users\js\AppData\Local\Temp\nvim9RAhDb\0`

**Comment by lewis6991** [comment]
Ok, one solution would be to use `vim.fn.tempname()` instead of `os.tmpname()` for windows.

**Comment by JSchrtke** [comment]
`os.tempname` is a general lua function and `vim.fn.tempname()` the neovim api?

**Comment by lewis6991** [comment]
Yes,`os.tmpname()` is a lua function, however `vim.fn.tempname()` is a vim (not neovim) function. The neovim API doesn't provide anything for temp paths as far as I know.

**Comment by JSchrtke** [comment]
ah, right. Is there any obvious issue with using `vim.fn.tempname()` for windows? Because it seems that returns the right thing, I reckon that might fix the problem.

**Comment by lewis6991** [comment]
No should be fine. Generally I try to avoid `vim.fn.*` where I can as it has a bit of overhead which is why I will I'll keep unix users on `os.tmpname()`.

**Comment by JSchrtke** [comment]
Alright, cool. Let me know when you need me to test things.

**Comment by lewis6991** [comment]
Give #247 another go.

**Comment by JSchrtke** [comment]
```
Error executing luv callback:
...js\.vim\plugged\plenary.nvim\lua\plenary\async\async.lua:14: The coroutine failed with this message: C:\Users\js\.vim\plugged\gitsigns.nvim\lua\gitsigns\git.lua:215: E5560: vimL function must not be called in a lua loop callback
```

**Comment by lewis6991** [comment]
Thanks. Try again.

**Comment by JSchrtke** [comment]
Right, we have a winner.

![image](https://user-images.githubusercontent.com/31078741/124491471-a0b47e80-ddb3-11eb-87fd-5485b3c25f19.png)

Ugly because of no config, but everything shows up and no errors that  I could provoke for now.
If I find anything else, I'll let you know.

Thanks for the quick fix!

**Comment by JSchrtke** [comment]
![image](https://user-images.githubusercontent.com/31078741/124492333-9941a500-ddb4-11eb-8a73-ab883900d0f6.png)

Full config is working fine aswell, using the branch for this issue. Mappings work, commands work. Cant get it to break right now. Can be closed as far as I'm concerned.

Thanks again, I missed having these indicators :)

**Comment by lewis6991** [comment]
Nice to hear.

We currently don't run windows on CI so it's likely windows support will break from time to time so don't hesitate to raise issues.

**Comment by JSchrtke** [comment]
Will do 👍
