### ISSUE TITLE
Error in fugitive buffer

### ISSUE THREAD

**Issue by anihm136** [lewis6991/gitsigns.nvim#24]
While using gitsigns, opening a fugitive buffer results in the following error -
```
Error executing vim.schedule lua callback: ...dh/.config/nvim/plugged/ple
nary.nvim/lua/plenary/job.lua:358: Failed to spawn process: {
  _additional_on_exit_callbacks = {},
  _shutdown_check = <userdata 1>,
  _stderr_results = {},
  _stdout_results = {},
  _user_on_exit = <function 1>,
  _user_on_stdout = <function 2>,
  args = { "rev-parse", "--show-toplevel", "--absolute-git-dir", "--abbre
v-ref", "HEAD" },
  command = "git",
  cwd = "",
  enable_handlers = true,
  enable_recording = true,
  interactive = true,
  pid = "ENOENT: no such file or directory",
  stderr = <userdata 2>,
  stdin = <userdata 3>,
  stdout = <userdata 4>,
  user_data = {},
  <metatable> = <1>{
    __index = <table 1>,
    _create_uv_options = <function 3>,
    _execute = <function 4>,
    _pipes_are_closed = <function 5>,
    _prepare_pipes = <function 6>,
    _reset = <function 7>,
    _shutdown = <function 8>,
    _stop = <function 9>,
    add_on_exit_callback = <function 10>,
    and_then = <function 11>,
    chain = <function 12>,
    chain_status = <function 13>,
    co_wait = <function 14>,
    is_job = <function 15>,
    join = <function 16>,
    new = <function 17>,
    pid = <function 18>,
    result = <function 19>,
    send = <function 20>,
    shutdown = <function 21>,
    start = <function 22>,
    stderr_result = <function 23>,
    sync = <function 24>,
    wait = <function 25>
  }
}
stack traceback:
        ...dh/.config/nvim/plugged/plenary.nvim/lua/plenary/job.lua:358:
in function '_execute'
        ...dh/.config/nvim/plugged/plenary.nvim/lua/plenary/job.lua:401:
in function 'start'
        ...rudh/.config/nvim/plugged/gitsigns.nvim/lua/gitsigns.lua:83: i
n function 'run_job'
        ...rudh/.config/nvim/plugged/gitsigns.nvim/lua/gitsigns.lua:194:
in function 'ret'
        ...config/nvim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:28: i
n function 'step'
        ...config/nvim/plugged/gitsigns.nvim/lua/gitsigns/async.lua:31: i
n function 'cb'
        vim.lua:234: in function <vim.lua:234>
```
Am I right in understanding this is caused due to gitsigns? Let me know what additional information I can provide.

**Comment by lewis6991** [comment]
Yes it's caused due to gitsigns. What command did you run to cause this?

**Comment by anihm136** [comment]
I just opened a fugitive status buffer, which first triggered the message. All subsequent actions performed in the buffer (staging and committing files) cause the message to repeat

**Comment by lewis6991** [comment]
I am unable to reproduce this. I just opened up a random file and ran `:Gstatus` and appears to work fine. Can you provide more info?

**Comment by lewis6991** [comment]
As the line in the error is `pid = "ENOENT: no such file or directory",`, can you try running:
```viml
:echo nvim_buf_get_name(0)
```
In the buffer that causes the error and confirm that the string that is returned is an existing path.

**Comment by anihm136** [comment]
This is what I get on running that command in the `Gstatus` buffer (in the `telescope.nvim` repo's readme file) - `/home/anirudh/.config/nvim/plugged/telescope.nvim/.git/index`

**Comment by anihm136** [comment]
Just to make sure, I also tried on a minimal config with only plenary, fugitive and gitsigns enabled, and am able to reproduce the issue with that

**Comment by lewis6991** [comment]
Can you confirm the path exists?

**Comment by anihm136** [comment]
Yep it exists. And strangely enough (or maybe as expected?), the same error pops up when I open that file as well

**Comment by lewis6991** [comment]
What about if you run the rev parse command in that .git dir?

**Comment by anihm136** [comment]
This is what I get - `fatal: this operation must be run in a work tree`. I think the git directory itself is not part of the work tree, right?

**Comment by lewis6991** [comment]
Yeah that's right and it's also what I get. Just trying to figure out why I don't get the same nvim error. I guess it could just be down to some difference in our systems. Either way could you try #25 and see if that fixes the issue for you?

**Comment by anihm136** [comment]
Sorry for the extended silence, I was occupied over the last few days. #25 seems to fix the issue for me
