### ISSUE TITLE
Calling 'blame_line(true)' does not display full commit message

### ISSUE THREAD

**Issue by snezhniylis** [lewis6991/gitsigns.nvim#241]
In https://github.com/lewis6991/gitsigns.nvim/commit/57119b72a7ea0608329cd35a31f5f13dee78e471 `blame_line` was moved from `gitsigns.lua` to `actions.lua` with `full` option stripped.

The documentation still states

> blame_line({full})
>
> If {full} is true then the full commit message is displayed instead of just the one-line summary.

which is no longer the case.

**Comment by RhnSharma** [comment]
I would like to take this one. Is this up for grabs?

**Comment by rbrishabh** [comment]
Thanks @RhnSharma!

**Comment by lewis6991** [comment]
Go for it!
