### ISSUE TITLE
Add function to list/export all hunks

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#242]
It would be useful to have function that lists or exports all hunks in the current document. This could be a low-level function that just dumps a simple table with `position`, `oldtext`, `newtext`, and (if this is already pre-calculated and available anyway) `diff` for each hunk.

This would allow users (or plugin authors) to leverage all the impressive work in gitsigns to access these hunks and act on them in a programmatic way (say, using Telescope to fuzzy filter and (un)stage them).

**Comment by lewis6991** [comment]
@clason can you review #290?
