### ISSUE TITLE
No such module plenary.async

### ISSUE THREAD

**Issue by wantyapps** [lewis6991/gitsigns.nvim#246]
**Describe the bug**
Gitsigns requires a non-existing module called "plenary.async", which causes an error

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
  -- config
}
EOF
```

1. Open Neovim
2. See error.

**Observed output**
E5113: Error while calling lua chunk: ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:1: module 'plenary.async
' not found:
        no field package.preload['plenary.async']
        no file './plenary/async.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/luajit-2.1.0-beta3/plenary/async.lua'
        no file '/usr/local/share/lua/5.1/plenary/async.lua'
        no file '/usr/local/share/lua/5.1/plenary/async/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/lua/5.1/plenary/async.lua'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/share/lua/5.1/plenary/async/init.lua'
        no file './plenary/async.so'
        no file '/usr/local/lib/lua/5.1/plenary/async.so'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/lib/lua/5.1/plenary/async.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './plenary.so'
        no file '/usr/local/lib/lua/5.1/plenary.so'
        no file '/usr/local/Cellar/luajit-openresty/20201229_1/lib/lua/5.1/plenary.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'

**Screenshots**

<img width="1440" alt="Screen Shot 2021-07-05 at 0 17 29" src="https://user-images.githubusercontent.com/56798701/124399774-681a9380-dd26-11eb-9f93-f13d58bd4718.png">

**Additional context**
System: macOS Big Sur 11.4
Neovim version: 0.5.0

**Comment by lewis6991** [comment]
Have you tried updating your version of plenary?

**Comment by wantyapps** [comment]
Thanks. It now works.
<img width="1440" alt="Screen Shot 2021-07-05 at 10 14 56" src="https://user-images.githubusercontent.com/56798701/124432072-db012a00-dd79-11eb-9873-f1bf4e62b0ae.png">
