### ISSUE TITLE
Allow the signs column to always be shown, even if no changes have been made to the file

### ISSUE THREAD

**Issue by goronfreeman** [lewis6991/gitsigns.nvim#256]
vim-gitgutter has a config option to allow the sign column to always be shown. This is nice because the text doesn't jump to the right the first time you make a change to a file.

**Describe the solution you'd like**
A new config option to allow the column to always be present.

**Comment by gegoune** [comment]
This is vim/neovim configuration option. Please have a look at `:h 'signcolumn'`. You can set it to `yes:1` to be always present.

**Comment by goronfreeman** [comment]
Thanks! I was unaware of that. That fixed my issue, so I'll close this.
