### ISSUE TITLE
How to configure the default background of the leftside "signs-bar"?

### ISSUE THREAD

**Issue by jantari** [lewis6991/gitsigns.nvim#258]
Hello, thanks for the great plugin.

I'm afraid my noob is showing, but when I added this to my neovim (0.5 stable) I have an ugly light gray background to the leftside "bar" that houses the git signs:

![image](https://user-images.githubusercontent.com/25607767/125106807-5ea37980-e0e0-11eb-9e69-f31e8247b3fa.png)

I know I can set the `hl` for `add`, `change`, `delete` etc. but how do I change the `hl` for "`nothing`"?

When I insert a line the `add` highlight gets applied and that works as expected:

![image](https://user-images.githubusercontent.com/25607767/125106971-8b579100-e0e0-11eb-9c68-9b2e832790a3.png)

I'd just like the *default* bg / ctermbg to be `NONE` personally so that my terminal background color is seen through.

**Comment by lewis6991** [comment]
On mobile so brief reply, but this is most certainly related to your colorscheme. Try other colorschemes to see if the issue persists.

**Comment by jantari** [comment]
Thank you, this issue appears when I don't have any `colorscheme` set. I tried installing and setting `one.vim` and the problem was not present with that theme, but let's say I don't use a vim theme but just my terminals' color palette - is there a specific "named" `highlight` entry or something I could set to control this bars' color?

**Comment by lewis6991** [comment]
You can't just use your terminals color palette by not setting a theme. If you don't set a theme then you just use the default theme which is pretty awful. Any theme with `set notermguicolors` will use your terminal palette, but each theme will use it differently. 

`SignColumn` is the highlight you are looking for. As you can see for the default vim theme, it is set to:

```
SignColumn     xxx ctermfg=14 ctermbg=242 guifg=Cyan guibg=Grey
```

Which means it uses color 14 and 242 from your terminals color palette when `notermguicolors` is set.

You can link it to the number column with `:highlight link SignColumn LineNr`, but I recommend you just use a well maintained theme instead.

**Comment by jantari** [comment]
It was my understanding that `set termguicolors` enables 24-bit TrueColor support, aka fully custom themes that have nothing to do anymore with my terminals palette? Anyway,  thanks, SignColumn is what I needed.

I'll use a theme as soon as I find one that:

- I actually like
- Works with all plugins
- Allows me to override its background so I can see my terminal background (otherwise it looks awful with the terminal padding I use)

So I'm hoping for maybe 2030 😅

**Comment by lewis6991** [comment]
That is correct which is why I said `notermguicolors`. Note the `no`.
