### ISSUE TITLE
Provide git root buffer variable

### ISSUE THREAD

**Issue by gegoune** [lewis6991/gitsigns.nvim#259]
**Is your feature request related to a problem? Please describe.**
Recently realised that Neogit and gitsigns are almost completely negated my need for fugitive. Still evaluating this though.

One use of fugitive I still have is relaying on its `b:git_dir` variable for constructing path relative to git root in my status line.

**Describe the solution you'd like**
It would be nice to get `b:gitsigns_git_dir`, or similar. I assume gitsigns knows each buffer's root. 

**Describe alternatives you've considered**
Carry on using fugitive just for this single variable or run git command and populate buffer variable on each bufenter which would most likely duplicate what gitsings already does.

What do you think?

**Comment by lewis6991** [comment]
Do you want the path to the git dir or the git root? Both are similar but can be very different if a repo is a submodule.

**Comment by gegoune** [comment]
`b:git_dir` is path to `.git` directory. Not the root. I was thinking of the latter though.

I did realise that with changing `cwd` to git root which I do with rooter I do not need that variable any more. Do you think it would be beneficial to have one or both vars added anyway? It could be a table, `b:gitsigns_dirs = { gitdir = "/path/.git", gitroot  = "/path" }`.

**Comment by lewis6991** [comment]
I was thinking of just adding both to `gitsigns_status_dict`. What do you think? There is also a ticket to expose the current line blame info to a variable too, so I was thinking of just packing everything into one place.

**Comment by gegoune** [comment]
The hierarchy is completely up to you. It makes sense to keep it in single place, you are right.

**Comment by gegoune** [comment]
Thank you Lewis!
