### ISSUE TITLE
Doesn't work with obsession 

### ISSUE THREAD

**Issue by timsofteng** [lewis6991/gitsigns.nvim#264]
Hello.
Plugin doesn't work well with `obsession` Tim Pope plugin.

Steps to reproduce.
1. Open few windows with buffers inside of git repo.
2. Trigger obsession to start track the session.
3. :qa
4. nvim -S to start session.

Gitsigns doesn't work with opened buffers. I you manually close it and open in current session it works again.

**Comment by lewis6991** [comment]
I can't reproduce this, appears to work fine for me. Can you double check and provide more specific instructions and follow the issue template by providing a debug log of what gitsigns is doing.

**Comment by timsofteng** [comment]
> Closing due to no update. Will reopen when repro instructions are provided.

Ok. Sorry, can't provide steps right now.
I'll ping you when I'll get it.

**Comment by b0o** [comment]
I can reproduce this with `:mksession`, but only when `:source`ing the session after nvim has started. Only the first buffer (bufnr = 1) loads with correct git signs, the other buffers need to be re-loaded with `:e`. Steps:

1. Open several windows with files containing git changes
2. Run `:mksession /tmp/repro`
3. Quit nvim
4.  Run `:source /tmp/repro`
5. Only buffer 1 will have git signs

This can be reproduced without any session helper plugins, but for the record I do use [Shatur/neovim-session-manager](https://github.com/Shatur/neovim-session-manager).

**Comment by lewis6991** [comment]
Was able to reproduce with the following commands:

```sh
mkdir test
cd test
git init
touch a b c
git add a b c
git commit -m init
echo hi >> a
echo hi >> b
echo hi >> c
nvim -nu minimal.lua -c "edit a" -c "vsplit b" -c "vsplit c" -c "mksession session" -c quitall                                                                                                        
nvim -nu minimal.lua
# Run :source session inside neovim after gitsigns has initialised.                                                                                                                                                           
```

Using `minimal.lua`:

```lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Gitsigns and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

-- Load plugins
require('packer').startup {
  {
    'wbthomason/packer.nvim',
    {
      'lewis6991/gitsigns.nvim',
      requires = { 'nvim-lua/plenary.nvim' },
    },
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
    display = { non_interactive = true },
  },
}

_G.load_config = function()
  require('gitsigns').setup{
    debug_mode = true, -- You must add this to enable debug messages
    -- GITSIGNS CONFIG THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  }

  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- ALSO INCLUDE GITSIGNS DEBUG MESSAGES
  vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by b0o** [comment]
Just following up to say that this did indeed fix the issue for me, thank you @lewis6991!

**Comment by lewis6991** [comment]
You're welcome 😄
