### ISSUE TITLE
Change the branch being diffed against

### ISSUE THREAD

**Issue by stumash** [lewis6991/gitsigns.nvim#268]
**Is your feature request related to a problem? Please describe.**
Diff against other branches, such as `master`

**Describe the solution you'd like**
* A function call that changes the base branch (branch being `diff`ed against) to whatever value the user provides
* A function call that shows the current base branch

**Describe alternatives you've considered**
`gitsigns.nvim` is better than `gitgutter`, so no real alternatives 😏 

I understand that _general_ modification of the `git diff` command this plugin relies on is explicitly not desired, but this is a pretty minimal and limited modification of the underlying `git diff` command that I believe can be excused.

**Additional context**
Probably store the branch being `diff`ed against in a variable (defaults to `HEAD` - which would leave all the current behavior of the `gitsigns` unchanged - but can be set to anything, e.g. `master`). The desired function call would update it to a new value.

**Comment by gegoune** [comment]
`:Gitsigns change_base` is probably what you are after.

**Comment by stumash** [comment]
yup 🤦 big OOOOFF

thanks
