### ISSUE TITLE
Error executing  ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/popup.lua:23: Buffer is not 'modifiable'

### ISSUE THREAD

**Issue by ttys3** [lewis6991/gitsigns.nvim#278]
**Describe the bug**

`nvim -M any-file-under-git-repo.txt`, then try the current line blamer, got the error:

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/popup.lua:23: Buffer is not 'modifiable'

```

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, -- You must add this to enable debug messages
  -- config
}
EOF
```

`nvim -M any-file-under-git-repo.txt`, then try the current line blamer, got the error:

**Observed output**

```
Error executing vim.schedule lua callback: ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/popup.lua:23: Buffer is not 'modifiable'

```

`:Gitsigns debug_messages` got not message

**Screenshots**
If applicable, add screenshots to help explain your problem or to capture error messages.

![image](https://user-images.githubusercontent.com/41882455/126755747-2a637b21-0276-454f-a541-a54fce9eeb19.png)

**Additional context**
System: Linux Ubuntu 21.04 (Hirsute Hippo)
Neovim version: v0.6.0-dev+61-g6f48c018b

**Comment by lewis6991** [comment]
> then try the current line blamer

What do you mean by this. Please be more specific.

**Comment by lewis6991** [comment]
And why are you passing `-M`?
