### ISSUE TITLE
blame_line on unstage file rise an error

### ISSUE THREAD

**Issue by fitrh** [lewis6991/gitsigns.nvim#280]
![20210725_031245_full](https://user-images.githubusercontent.com/55179750/126879144-1c667115-b078-4b72-be5d-97911c0963fa.jpg)
Is this expected behavior when we try to call `blame_line` on unstage file ?

**Comment by lewis6991** [comment]
It obviously shouldn't do anything useful since there's nothing to blame but it shouldn't error.
