### ISSUE TITLE
Updates sign column when code is committed

### ISSUE THREAD

**Issue by cloudhead** [lewis6991/gitsigns.nvim#285]
Lovely plugin, but I have one question: whenever I commit code, I have to manually enter `:e` in vim to make the signs synchronize with the state of the git index.

I've found the `watch_index` option, but using that also changes the contents of my file automatically, which I don't want.

Is there a way to have only the signs update based on the index?

**Comment by lewis6991** [comment]
`watch_index` doesn't update buffer contents, something else is probably happening.

**Comment by lewis6991** [comment]
Just double checked to confirm Gitsigns doesn't alter buffer contents.

Going to close this but happy to help with anything if you need it.

**Comment by cloudhead** [comment]
Thanks, still trying to figure out what's going on.
