### ISSUE TITLE
Error with show_count

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#29]
**Describe the bug**
The commit 4ce590fcc6400c9a0b6aa8903f7a050f9d6c28c2 broke the `show_count` functionality, unfortunately (bisect confirmed).

**To Reproduce**
Set up 
```lua
require 'gitsigns'.setup{
  signs = {
    delete = { show_count = true},
  },
}
```
then in any git repo, delete a line (not the first).

**Observed output**
```
Error executing vim.schedule lua callback: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:21: Vim
:E715: Dictionary required
```

**Comment by Liberatys** [comment]
@clason thank you for reporting the issue. Was here to do the same ^^

**Comment by lewis6991** [comment]
No idea how this worked before, I was passing in garbage to `vim.fn.sign_define`

**Comment by Liberatys** [comment]
@lewis6991 Thanks :D

**Comment by clason** [comment]
Works well, thanks for the quick fix!
