### ISSUE TITLE
Make `b:gitsigns_head` show short commit in detached HEAD state

### ISSUE THREAD

**Issue by echasnovski** [lewis6991/gitsigns.nvim#292]
**Is your feature request related to a problem? Please describe.**
It is clearly stated that `b:gitsigns_head` returns empty string if HEAD is detached. As this is mostly intended to be used in statusline, it might be confusing to see nothing when browsing code in detached state.

**Describe the solution you'd like**
Show short commit (as in output of `git rev-parse --short HEAD`) instead of empty string when HEAD is detached.

**Describe alternatives you've considered**
I implemented locally a possible solution by making extra `git` call when can't resolve HEAD, which seems to work. Update [this line](https://github.com/lewis6991/gitsigns.nvim/blob/27e1e95e1aa8d4ec0aabbf5148013f58a1bc4b40/lua/gitsigns/git.lua#L164) to be an extra call (with adding needed arguments to function):
```lua
head_str = M.command({'rev-parse', '--short', 'HEAD'}, {
   command = cmd or 'git',
   supress_stderr = true,
   cwd = path,
})
return head_str[1] or ''
```

If this change is desirable, happy to make PR.

**Additional context**
My initial logic behind this feature is that option is named `gitsigns_head` and not `gitsigns_branch`. As HEAD always points somewhere, it seems odd to ever have empty string.

**Comment by lewis6991** [comment]
Sounds good to me. Feel free to open a PR.

**Comment by echasnovski** [comment]
Great! I hope that will be around this weekend.
