### ISSUE TITLE
Popup window does't dissapear when switching buffers

### ISSUE THREAD

**Issue by echasnovski** [lewis6991/gitsigns.nvim#296]
**Describe the bug**
The result of `require("gitsigns").preview_hunk()` doesn't disappear after immediate buffer change.

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/autoload/plugged'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup({debug_mode = true})
EOF

set hidden
```

1. Set up git repository and commit any file. In this example this is file 'init-gitsigns.vim'.
2. Open commited file and make any change.
3. Run `lua require("gitsigns").preview_hunk()` command in changed hunk.
4. Type `:enew`.

**Observed output**
Popup doesn't go anywhere.

**Screenshots**
Gif of the issue:

![gitsigns-issue](https://user-images.githubusercontent.com/24854248/128524507-9c1bdb7b-c37c-4661-9cbc-077b003b9c70.gif)

**Additional context**
System: Ubuntu 18.04
Neovim version: 0.5.0

I managed to resolve this issue by adding `BufLeave` event to [this auto command](https://github.com/lewis6991/gitsigns.nvim/blob/8d284060170bcc96987b3c431a7c8fa3aef9e1cc/lua/gitsigns/popup.lua#L46). If this is a valid solution, happy to make PR.

**Comment by lewis6991** [comment]
Sounds like a reasonable solution, go ahead.
