### ISSUE TITLE
Error with debounce and newline 

### ISSUE THREAD

**Issue by SanchayanMaity** [lewis6991/gitsigns.nvim#3]
`Error executing vim.schedule lua callback: ...ack/packer/start/gitsigns.nvim/lua/gitsigns/debounce.lua:12: bad argument #1 to 'start' (number expected, got nil)`

The most recent commit gives this error on loading any file.

neovim version: `NVIM v0.5.0-789-gca7449db4`

Commit `f519122` also seems to introduce an extra new line git diff marker on buffers which do not have any change.

**Comment by lewis6991** [comment]
Sorry about that, I've reverted 7fc3174 and pushed a naive fix (5f2fcc6) for extra diff marker.

**Comment by SanchayanMaity** [comment]
No worries. Thank you for fixing this so quickly.
