### ISSUE TITLE
`fatal: refusing to merge unrelated histories.`

### ISSUE THREAD

**Issue by qazip** [lewis6991/gitsigns.nvim#306]
Doing :PlugUpdate, I am getting the following message for gitsigns:

`fatal: refusing to merge unrelated histories.`

Any idea what this means?

**Comment by lewis6991** [comment]
Try uninstall Gitsigns and installing again.

**Comment by qazip** [comment]
Seems like it fixed.

**Comment by rafikdraoui** [comment]
The reason it did that is that the `main` branch was force-pushed to somehow in the past days, and git won't allow pulling from a remote if the history between local and remote have diverged, since it means local changes would get overwritten (the plugin update function in plugin managers is usually a wrapper around `git pull`).

**Comment by lewis6991** [comment]
It will pull if you do `git pull --rebase`. I have this by default which is
why it didn't cause a problem for me when I updated manually.

**Comment by lockejan** [comment]
Same problem here. I don't get the reason for public rebasing on projects others rely on. There is a place for rebasing, but in this case its a pain for everyone else and not a good practice.

There is also an open issue on packer: https://github.com/wbthomason/packer.nvim/issues/327#issuecomment-831216357

**Comment by lewis6991** [comment]
> Same problem here. I don't get the reason for public rebasing on projects others rely on. There is a place for rebasing, but in this case its a pain for everyone else and not a good practice.

You are totally correct, and I apologize for doing so.

There were a few emails in some commits I wanted to correct/change in the history, and the choices were a rebase or adding a `.mailmap` file. I chose to rebase as `.mailmap` doesn't really change the emails, and I thought (wrongly) that plugin managers would be able to handle it. But I recognize rebasing was the wrong choice. 

It won't happen again. Sorry for any inconvenience this may have caused.
