### ISSUE TITLE
Add persistent diff base setup option

### ISSUE THREAD

**Issue by Saecki** [lewis6991/gitsigns.nvim#309]
The `change_base` function allow to temporarily change the diff base of a buffer temporarily, but is discarded when switching to another file. I would like to have the ability to persistently change the diff base without using an `autocmd` on `BufEnter` for example.

I think an easy solution could be a setup option that specifies a diff base.

**Comment by ajpaon** [comment]
I'd also like this. Gitgutter provides a variable for this and I depend on it during code review, when I want to highlight all changes on the branch.

```
let g:gitgutter_diff_base = '<commit SHA>'
```
