### ISSUE TITLE
Preview of long lines is broken?

### ISSUE THREAD

**Issue by spamwax** [lewis6991/gitsigns.nvim#311]
**Describe the bug**
Hunk preview of very long lines only shows one red line with removed words rather than showing both red and green lines.
I am not sure if this is the intended behavior of `gitgisgns`, nevertheless here are the details.

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/plugged'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  debug_mode = true, 
}
EOF
```

1. Create a file with a long line and commit the file. The line I used is in this [gist](https://gist.github.com/spamwax/b79094d36a4c1d3a4b6f24193d7704cc).
2. Run neovim: `nvim -u init.vim long.sh` and remove one word of the long line. I deleted the first `foo`
3. Run `lua require"gitsigns".preview_hunk()`
4. Preview shows the entire line as red with modify word highlighted but there is no green line showing current content of the line.

**Observed output**

Output of [:Gitsigns debug_messages](https://gist.github.com/spamwax/75a98f8fb15afd4a47c0432210d5de28)
Output of [:Gitsigns dump_cache`](https://gist.github.com/spamwax/63cababfe5ad04ce4db38264c90af89a)

**Screenshots**
gitsign preview with a long line:
<img width="2409" alt="Screen Shot 2021-08-15 at 5 50 45 PM" src="https://user-images.githubusercontent.com/1251233/129493979-6d9e418d-da12-4197-b4e8-d0ab7144bc6c.png">

gitsign preview with short line
<img width="425" alt="Screen Shot 2021-08-15 at 5 58 10 PM" src="https://user-images.githubusercontent.com/1251233/129494006-b68999e4-d0a1-4f68-b1e4-97fba9e65f13.png">

**Additional context**
System: macOS
Neovim version: `NVIM v0.6.0-dev+139-g0f2af87a3`

**Comment by lewis6991** [comment]
This is because if `set wrap`, if you turn that off it should work as expected.

I'll think of a way this can be better handled.
