### ISSUE TITLE
gitgutter signs still shown after switching to gitsigns

### ISSUE THREAD

**Issue by deadlysyn** [lewis6991/gitsigns.nvim#325]
first, thanks for the awesome plugin

i'm sure i'm missing something obvious. as part of rewriting everything in lua i've moved from gitgutter to gitsigns

i've grepped my whole config for anything still relating to gitgutter, e.g. my options for setting custom signs...those are all disabled/deleted, but when loading neovim i see gitsigns' signs flash quickly and then gitgutter's signs overwrite them. it's strange, as if there is some cache of the old config i've not found.

i've restarted everything and went through my configs several times, googling for the obvious thing i've missed...just wondered if anyone else saw this.

**Comment by lewis6991** [comment]
Maybe try opening neovim with `-V`, it'll show you all the files being loaded and where from. From here you'll be able to see where gitgutter is being loaded from.

**Comment by deadlysyn** [comment]
TIL thank you for bothering to reply on a weekend! it was old cache from experimenting with different package managers.
