### ISSUE TITLE
Comparison to vgit.nvim

### ISSUE THREAD

**Issue by figsoda** [lewis6991/gitsigns.nvim#331]
[vgit.nvim](https://github.com/tanvirtin/vgit.nvim) looks like a very similar plugin. How does it compare to this plugin?

Maybe the comparison could be added to [readme](https://github.com/lewis6991/gitsigns.nvim#comparison-with-vim-gitgutter)

**Comment by lewis6991** [comment]
Try both and see how each feel. Both plugins list all their respective features.
