### ISSUE TITLE
Inconsistent background color of current line blame

### ISSUE THREAD

**Issue by yioneko** [lewis6991/gitsigns.nvim#336]
### Description

By default, the highlight group of blame is linked to Nontext, but the background color of the text seems inconsistent though the bg color in highlight group is transparent.

If I add `hl_mode=true` to the extmark setting of the blame, the background color becomes normal.

Perhaps the option should be built in the plugin?

### Neovim version

NVIM v0.6.0-dev+142-g5a111c1b0

### Operating system and version

Linux

### Steps to reproduce

Toggle current line blame provided by the plugin. Then set cursorline or try other methods to render a different color for current line.  In the description, I use `:Gitsigns toggle_linehl` for better contrast.

### Expected behavior

<img src="https://user-images.githubusercontent.com/65551246/130648915-f787bc5f-b78c-4ba1-98f2-d0dbd34a14c6.png" width="600"/>

### Actual behavior

<img src="https://user-images.githubusercontent.com/65551246/130645700-e80962ad-f624-4ca5-b1e8-a15414918ac3.png" width="600"/>

### Minimal config

I've not tested with a minimal config, I just reset the colorscheme but the problem still exists.

**Comment by lewis6991** [comment]
Thanks for reporting, I can reproduce

**Comment by lewis6991** [comment]
Does the above PR fix the issue?

**Comment by yioneko** [comment]
It works well now. Thanks for fixing.
