### ISSUE TITLE
Git Browse

### ISSUE THREAD

**Issue by axieax** [lewis6991/gitsigns.nvim#347]
**Is your feature request related to a problem? Please describe.**
Navigating to the web repo link corresponding to the current buffer often takes a long time.

**Describe the solution you'd like**
Having a Gitsigns browse feature would allow a user to instantly open their browser to the web repo in the right place.

**Describe alternatives you've considered**
This implementation would be similar to tpope/vim-fugitive's GBrowse feature. The corresponding code logic for this can be found [here](https://github.com/tpope/vim-fugitive/blob/46404ad9376f38a0bf8421310373aefbc92e190d/autoload/fugitive.vim#L7242).

**Additional context**
Just thought this would be a nice feature to have in Gitsigns, so some people won't need to have both plugins at the same time. Love Gitsigns btw!

**Comment by akinsho** [comment]
FYI there's a plugin that does this already called https://github.com/ruifm/gitlinker.nvim

**Comment by axieax** [comment]
This is exactly what I was looking for, thank you!
