### ISSUE TITLE
Current version fully breaks fzf.vim

### ISSUE THREAD

**Issue by sQVe** [lewis6991/gitsigns.nvim#352]
### Description

👋🏼 

First a big thank you for all the work put into this plugin. I've been using is without any issues for a long time and really enjoy it!

---

Today after running an update my `fzf` setup (with `fzf.vim`) became fully broken. It outputs an error like this: 

```
Error detected while processing function fzf#vim#files[15]..<SNR>88_fzf[21]..fzf#run[63]..<SNR>31_execute_term[93]..<SNR>31_dopopd:
line   20:
E716: Key not present in Dictionary: "dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))"
```
 I disabled my plugins one by one and as soon as I removed `gitsigns` it started to work. It also worked earlier today so the issue must have been introduced during the day.

### Neovim version

NVIM v0.6.0-dev+220-gdb695cc4c

### Operating system and version

Arch @ 5.13.13

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. Run `:Files` or any other `fzf.vim` based command.

### Expected behavior

`fzf.vim` should work correctly.

### Actual behavior

`fzf.vim` is fully broken and erroring.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
    print("Installing Gitsigns and dependencies.")
    vim.fn.system {
        'git', 'clone', '--depth=1',
        'https://github.com/wbthomason/packer.nvim', install_path
    }
end

-- Load plugins
require('packer').startup {
    {
        'wbthomason/packer.nvim',
        {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}},
        -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
        {'junegunn/fzf', dir = '~/.fzf', run = './install --all'},
        'junegunn/fzf.vim'
    },
    config = {
        package_root = package_root,
        compile_path = install_path .. '/plugin/packer_compiled.lua',
        display = {non_interactive = true}
    }
}

_G.load_config = function()
    require('gitsigns').setup {
        debug_mode = true -- You must add this to enable debug messages
        -- GITSIGNS CONFIG THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
    }

    -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

    -- ALSO INCLUDE GITSIGNS DEBUG MESSAGES
    vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by sQVe** [comment]
The problem was introduced with 7e5a748f341eed78a0e548ad6a06bcfaa5d5cfe4.

**Comment by davidvalaz** [comment]
I can report I too am getting errors when trying to load session files with persistence.nvim. Unrelated but may be helpful:

```
E5108: Error executing lua ...ack/packer/opt/persistence.nvim/lua/persistence/init.lua:69: Vim(lua):E5108: Error executing lua .../site/pack/packer/opt/gitsigns.nvim/lua/gitsigns/git.lua:194: attempt to yield across C-call boundary
```

Reverting back to commit `daa233a` fixes it.

**Comment by lewis6991** [comment]
Sorry, there was a bad autocmd added in the commit that added `g:gitsigns_head`. The fix is simple and will do it as soon as I can.
