### ISSUE TITLE
Blaming line causes errors when repo has no commits

### ISSUE THREAD

**Issue by spindensity** [lewis6991/gitsigns.nvim#355]
### Description

Blaming line causes errors when repo has no commits

### Neovim version

NVIM v0.5.0

### Operating system and version

Windows 10 21H2

### Steps to reproduce

1. Create a repo with no commits:
```bash
mkdir new_repo
cd new_repo
touch README.md
git init
```
2. Write something into `README.md`
```bash
echo "Hello, world" > .\README.md
```
3. Stage `README.md` file:

```bash
git add README.md
```
4. Open `README.md` and press `<leader>hb` to blame the new input line.

### Expected behavior

No errors occur.

### Actual behavior

The following error occurs:
![Snipaste_2021-09-09_15-01-49](https://user-images.githubusercontent.com/33576822/132638847-63955189-262a-42f6-9919-64779a3f1576.png)

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Gitsigns and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

-- Load plugins
require('packer').startup {
  {
    'wbthomason/packer.nvim',
    {
      'lewis6991/gitsigns.nvim',
      requires = { 'nvim-lua/plenary.nvim' },
    },
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
    display = { non_interactive = true },
  },
}

_G.load_config = function()
  require('gitsigns').setup{
    debug_mode = true, -- You must add this to enable debug messages
    -- GITSIGNS CONFIG THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  }

  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- ALSO INCLUDE GITSIGNS DEBUG MESSAGES
  vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by WIttyJudge** [comment]
I have the same error
![pic-window-210910-0000-23](https://user-images.githubusercontent.com/43549900/132762032-a1edb9b6-a06f-4483-9a1f-aa1d495fe4f1.png)

**Comment by zapling** [comment]
I could have a look at this later this weekend.

**Comment by spindensity** [comment]
> I could have a look at this later this weekend.

Thanks.

I forgot some key steps to reproduce the bug before, I have updated my post, now it's 100% reproduced by following the steps above.

**Comment by lewis6991** [comment]
Fixed in https://github.com/lewis6991/gitsigns.nvim/pull/361
