### ISSUE TITLE
Stray debug output

### ISSUE THREAD

**Issue by clason** [lewis6991/gitsigns.nvim#37]
Neovim now prints the message `dwqdqwwqdqw: myers` on startup :)

It's due to the stray https://github.com/lewis6991/gitsigns.nvim/blob/01155f7a1d55e42a7f76f1937032bf32c6e0ce1b/lua/gitsigns/config.lua#L93

**Comment by lewis6991** [comment]
Woops, sorry about that.

**Comment by clason** [comment]
No problem, it just looked funny :) Thanks for the quick fix!
