### ISSUE TITLE
Error when opening neovim as git commit editor

### ISSUE THREAD

**Issue by ruffson** [lewis6991/gitsigns.nvim#376]
### Description

There is probably an easy fix but I searched the issues and could not find anything.

When I attempt to write a commit message with `git commit` (with nvim set as my default editor), I get this error:

```
Error detected while processing /home/myuser/.config/nvim/init.vim:                                                                                                                               
line  234:                                                                                                                                                                                      
E5108: Error executing lua ...ig/nvim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...onfig/nvim/plugged/gitsigns.nvim/lua/gitsigns/config.lua:2
64: attempt to index field 'opt' (a nil value)                                                                                                                                                  
Press ENTER or type command to continue
```

The line in my init is where the lua config for gitsigns starts:

```
lua << EOF                                                                                                                                                                                
require('gitsigns').setup()                                                                                                                                                               
EOF
```

### Neovim version

0.5.0

### Operating system and version

Fedora 34

### Steps to reproduce

1. Enter git repository
2. Make changes
3. Execute `git commit`
4. Observe error

### Expected behavior

No error.

### Actual behavior

Error (see description).

### Minimal config

```Lua
call plug#begin()
Plug 'nvim-lua/plenary.nvim'
Plug 'lewis6991/gitsigns.nvim'
call plug#end()

lua << EOF
require('gitsigns').setup()
EOF
```

**Comment by lewis6991** [comment]
- The provided steps to reproduce are ambiguous, please be more precise with exact commands, etc.
- Your minimal config does not run with `nvim -nu minimal.vim`.
- The provided error message is mis-formatted and indicates running a Neovim version without `vim.opt` which was pre 0.5.

Please see #348 for a good example on how to report issues.

Closing until the above is resolved.

**Comment by ruffson** [comment]
So sorry, I checked my global git config again and it turns out that I still had an nvim as appimage version specifically linked there for when 0.5 was not released. I was not aware of this anymore. 

Sorry to waste people's time with this!

**Comment by lewis6991** [comment]
No problem. Thanks for updating the issue.
