### ISSUE TITLE
`b:gitsigns_head` is not updated after `checkout -b` from Neovim's command line

### ISSUE THREAD

**Issue by echasnovski** [lewis6991/gitsigns.nvim#377]
### Description

When branch is checkout with `checkout -b` from Neovim's command line, `b:gitsigns_head` does not display the current branch. If checkout is done with `checkout`, everything works as expected.

### Neovim version

NVIM v0.5.0

### Operating system and version

Ubuntu 18.04.2

### Steps to reproduce

1. Create git repository and make initial commit.
2. Create any new file (say, 'file.md').
3. `nvim -nu minimal.lua file.md`
4. Check current value with `:echo b:gitsigns_head`. This should have the name of default branch.
5. Run `:!git checkout -b feature`. This should change branch to `feature`. Check it with `!git branch`.
6. Check again the current value with `:echo g:gitsigns_head`. This stayed the same.

NOTE: if instead of one command `:!git checkout -b feature` run two consecutive `:!git branch feature` and `:!git checkout feature`, everything works as expected (`b:gitsigns_head` has value `feature`).

### Expected behavior

Value of `b:gistigns_head` always shows the name of current HEAD.

### Actual behavior

Value of `b:gistigns_head` not always has the name of current HEAD, as it can have the value HEAD before `checkout -b`.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Gitsigns and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

-- Load plugins
require('packer').startup {
  {
    'wbthomason/packer.nvim',
    {
      'lewis6991/gitsigns.nvim',
      requires = { 'nvim-lua/plenary.nvim' },
    },
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
    display = { non_interactive = true },
  },
}

_G.load_config = function()
  require('gitsigns').setup{
    debug_mode = true, -- You must add this to enable debug messages
    -- GITSIGNS CONFIG THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  }

  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- ALSO INCLUDE GITSIGNS DEBUG MESSAGES
  vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by lewis6991** [comment]
This happens because `git checkout -b` doesn't modify `.git/index`.

Solution is to watch a different file.
