### ISSUE TITLE
Disable gitsigns automatically for files with conflict markers

### ISSUE THREAD

**Issue by SanchayanMaity** [lewis6991/gitsigns.nvim#381]
**Is your feature request related to a problem? Please describe.**
When doing rebase or merge, conflicts can happen. Opening such a file shows the region with conflict marker as something which changed.

**Describe the solution you'd like**
gitsigns should not be enabled for a file with conflict markers/files which are with merge conflicts while in the process of resolving a conflict during a rebase or merge.

```
blah
<<<<<<< HEAD
blah2
||||||| 46c4051
=======
conflict1
>>>>>>> con
```
In the above, the lines after blah get the highlight of `GitSignsAdd/Change` in the sign column which should not be the case.

**Describe alternatives you've considered**
Can do a gitsigns toggle manually of course but I think this is better done if gitsigns were to implement it.

**Additional context**
signify and gitgutter already do this?.

**Comment by lewis6991** [comment]
> gitsigns should not be enabled for a file with conflict markers/files which are with merge conflicts while in the process of resolving a conflict during a rebase or merge.

Why?

Having signs during a rebase is useful. Gitsigns explicitly detects when a file has conflicts and picks the correct stage number (`1` which is the common ancestor) for generating signs. You can then use `stage_hunk()` on each hunk, and it will be correctly staged.

If you want to prevent gitsigns from attaching to a buffer you can use `config.on_attach()` to define a handler which can be used to cancel attaching, see `:help gitsigns-config-on_attach`.

**Comment by SanchayanMaity** [comment]
@lewis6991 Understood. Thank you for the explanation. Closing the ticket.
