### ISSUE TITLE
Nvim crashes when file explorer is opened for code bases with many files and folders

### ISSUE THREAD

**Issue by tabot-kevin** [lewis6991/gitsigns.nvim#384]
### Description

when open the file explorer and  open a file, the moment I start moving with the arrow, all the folders in the file tree starts opening up automatically then it seems like there is some sort of file indexing happened, my computer's fan speed increases, then after a while nvim will freeze even quitting it becomes impossible till I click the X to terminate it, then error shown below will show.

<img width="1435" alt="error" src="https://user-images.githubusercontent.com/81575086/135145890-a6d89ef8-0348-4220-8cb3-e5b6412db427.png">

![error2](https://user-images.githubusercontent.com/81575086/135146207-2aceec7e-e22e-44cb-a581-022e5dcebe01.png)

### Neovim version

NVIM v0.6.0-dev+301-g340f77e78

### Operating system and version

macOS big Sur 11.5.2

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

### Actual behavior

<img width="1435" alt="error" src="https://user-images.githubusercontent.com/81575086/135146320-761a4052-5ae4-4c47-99ca-76d0a59174a2.png">

![error2](https://user-images.githubusercontent.com/81575086/135146283-88984898-a54e-494b-b741-0bc9e0ca2cae.png)

### Minimal config

```

return packer.startup(function(use)
    use 'wbthomason/packer.nvim'
    -- Syntax Highlighting and Visual Plugins
    use {'norcalli/nvim-colorizer.lua', disable = not is_enabled('colorizer'), config = "require'colorizer-config'"}
    use {
        'akinsho/nvim-bufferline.lua',
        requires = 'kyazdani42/nvim-web-devicons',
        config = 'require"bufferline-config"',
        disable = not is_enabled('bufferline')
    }
    use {'glepnir/galaxyline.nvim', branch = 'main', disable = not is_enabled('galaxyline'), config = "require'galaxyline-config'"}
    use {'glepnir/dashboard-nvim', disable = not is_enabled('dashboard'), config = "require'dashboard-config'"}
    use {'lukas-reineke/indent-blankline.nvim', disable = not is_enabled('indent_blankline'), config = "require'blankline-config'", event = "BufRead"}

    -- Tree-Sitter
    use {
        'nvim-treesitter/nvim-treesitter',
        event = 'BufWinEnter',
        run = ':TSUpdate',
        disable = not is_enabled('treesitter'),
        config = "require'treesitter-config'"
    }
    use {'p00f/nvim-ts-rainbow', disable = not is_enabled('rainbow_parentheses'), after = 'nvim-treesitter'}
    use {'windwp/nvim-ts-autotag', disable = not is_enabled('closetag'), after = 'nvim-treesitter'}

    -- Colorschemes
    use 'joshdick/onedark.vim'
    use 'gruvbox-community/gruvbox'
    use 'shaunsingh/nord.nvim'
    use 'folke/tokyonight.nvim'

    -- LSP and Autocomplete
    use {'neovim/nvim-lspconfig', event = "BufRead"}
    use 'glepnir/lspsaga.nvim'
    use {
        'hrsh7th/nvim-compe',
        event = "InsertEnter *",
        config = function()
            require 'compe-config'
        end,
        disable = not is_enabled('compe')
    }
    use {'hrsh7th/vim-vsnip', disable = not is_enabled('vsnip')}
    use {'windwp/nvim-autopairs', after = get_compe(), config = "require'autopairs-config'"}

    -- Version Control
    use {'TimUntersberger/neogit', requires = 'nvim-lua/plenary.nvim', config = "require('neogit').setup {}", disable = not is_enabled('neogit')}
    use {'lewis6991/gitsigns.nvim', requires = {'nvim-lua/plenary.nvim'}}

    -- Language Specific
    use {'davidgranstrom/nvim-markdown-preview', disable = not is_enabled('markdown_preview')}

    -- Terminal Integration
    use {'akinsho/nvim-toggleterm.lua', disable = not is_enabled('toggleterm'), config = 'require"toggleterm-config"'}

    -- Navigation
    use {
        'nvim-telescope/telescope.nvim',
        requires = {{'nvim-lua/popup.nvim'}, {'nvim-lua/plenary.nvim'}},
        disable = not is_enabled('telescope'),
        config = "require'telescope-config'"
    }
    use {'kyazdani42/nvim-tree.lua', cmd = "NvimTreeToggle", disable = not is_enabled('nvim_tree'), config = "require'nvimtree-config'"}
    use 'phaazon/hop.nvim'

    -- Other
    use {'terrortylor/nvim-comment', cmd = "CommentToggle", config = "require('nvim_comment').setup()", disable = not is_enabled('nvim_comment')}
    use {'monaqa/dial.nvim', disable = not is_enabled('dial'), config = "require'dial-config'"}
    use {'lukas-reineke/format.nvim', disable = not is_enabled('format'), config = "require'formatting'"}
    use {'folke/which-key.nvim', event = "BufWinEnter"}
    use {'nvim-lua/plenary.nvim'}

    for _, plugin in pairs(Vapour.plugins.user) do use(plugin) end
end)
```

**Comment by lewis6991** [comment]
Your minimal.lua is incomplete. I can't help if I can't reproduce the issue. You haven't even mentioned what file explorer you are using.

**Comment by tabot-kevin** [comment]
The explorer I am using is `nvim-tree` and the screen shorts I shared are from two separate nvim configurations but using `nvim-tree`

**Comment by lewis6991** [comment]
I tried installing `nvim-tree` and opening a large directory but could not reproduce the issue.

Your minimal config does not work with `nvim -nu minimal.lua` and it doesn't appear to be minimal.

From your report, it's not even clear that gitsigns is the issue, rather that you are using lots of plugins which are causing lots of processes to spawn so when gitsigns runs `vim.loop.spawn` fails.

If you had provided gitsigns debug messages, that would have helped.

Can you please be more respectful of other people's time when opening issues and do not ignore the issue template.

**Comment by tabot-kevin** [comment]
Like I said from in my bug report, the two screenshots are taken from two different nvim configs 

1. https://github.com/LunarVim/LunarVim
2. https://github.com/VapourNvim/VapourNvim

This two repository are different, but both have gitsigns as plugins.

I open up a Django project with many folders, files and long migration names. If you have a preferred way you will want me to provide more information can you let me know?

**Comment by lewis6991** [comment]
> Like I said from in my bug report, the two screenshots are taken from two different nvim configs

You should raise issues on those "configs" (I call them distributions). The screenshots just say that you have too many files open (an OS limitation), and doesn't indicate a problem with gitsigns.

> I open up a Django project with many folders, files and long migration names. If you have a preferred way you will want me to provide more information can you let me know?

The issue template contained all the information that was required which hasn't been provided.

I won't spend more time on this until either:
- There is concise and unambiguous instructions on how to produce the issue which is quick to run.
- There is better evidence that this is an issue with this plugin.
