### ISSUE TITLE
Use escape to close hunk preview

### ISSUE THREAD

**Issue by ghost** [lewis6991/gitsigns.nvim#385]
gitgutter has an option to close hunk preview windows on escape. See here : https://github.com/airblade/vim-gitgutter/blob/256702dd1432894b3607d3de6cd660863b331818/doc/gitgutter.txt#L351
Would it be possible to implement it in gitsigns?

**Comment by lewis6991** [comment]
Is moving the cursor not sufficient?

**Comment by gegoune** [comment]
This isn't. ig issue but I caught myself trying to close hunk preview with Esc, just feels natural. I then immediately realise I have to move cursor, so it's fine, but I personally think it would be a good addition.

(While I am here, thanks for all your work on gitsigns and impatient plugins, very appreciated! ❤️)

**Comment by lewis6991** [comment]
Ok we can consider doing this then.

**Comment by oponkork** [comment]
> This isn't big issue but I caught myself trying to close hunk preview with Esc many tines, it just feels natural. I then immediately realise I have to move cursor, so it's fine, but I personally think it would be a good addition.
> 
> (While I am here, thanks for all your work on gitsigns and impatient plugins, very appreciated! heart)

Exactly this.

**Comment by gegoune** [comment]
I don't know nvim internals enough to suggest anything meaningful, but can you maybe get window id when creating preview window, then create mapping that would close that window and delete mapping on window deletion?

If not, that's fine, I am used to moving cursor now so it's not really a deal breaker at all. Just nice to have.

Thanks for the plugin, it's amazing! ❤️

**Comment by lewis6991** [comment]
I think implementing this will be more trouble than it's worth. Will accept any PR's that implement this well.

**Comment by pinbraerts** [comment]
Bind something like this this in `on_attach`
```lua
vim.keymap.set('n', '<esc>', function ()
    for _, id in ipairs(vim.api.nvim_list_wins()) do
        if vim.api.nvim_win_get_config(id).relative ~= "" then
            vim.api.nvim_win_close(id, false)
        end
    end
end, { buffer = buffer })
```
