### ISSUE TITLE
The sign of modified line(s) are wrong when using 'o' to insert a new line.

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/gitsigns.nvim#388]
### Description

1. Hover your cursor on the line containing `*`:
<img src="https://user-images.githubusercontent.com/24765272/136963294-0da83b58-3486-4792-b29b-35a8328bcc71.jpg" width="500">

---

2. Press `o`.
<img src="https://user-images.githubusercontent.com/24765272/136963306-ac7f0270-67ef-4134-a639-28cdfc1634f4.jpg" width="500">

---

3. As the result below.
<img src="https://user-images.githubusercontent.com/24765272/136963320-18190f2c-57d0-4508-b290-ade49f5f2100.jpg" width="500">

### Neovim version

NVIM v0.6.0-dev+454-gee342d3ce Build type: Release LuaJIT 2.1.0-beta3 Compiled by ningwang  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-ee342d3/share/nvim"

### Operating system and version

macOS Big Sur 11.4 (20F71)

### Steps to reproduce

1. Hover your cursor on the line containing `*`:

```
from ..mods import bee_say
from ..mods.server import ser1
[f]rom ..mods.message_utils import *   // [f] means the f is hovered.

```

2. Press `o`.

3. As the result below.

### Expected behavior

The sign should appear at the line where the cursor is inserted.

### Actual behavior

The cursor shows two lines *after* the expected line to be inserted.

### Minimal config

```Lua
use {
  'lewis6991/gitsigns.nvim',
    requires = {
      'nvim-lua/plenary.nvim'
    },
    -- tag = 'release' -- To use the latest release
    config = function()
      require('gitsigns').setup()
    end
  }
```

**Comment by nyngwang** [comment]
OK, but I found another one that does this correctly. I think correctness should be prioritized first for this kind of plugins. Your plugin is beautiful. I'll wait for the fix and migrate to this one then.

**Comment by lewis6991** [comment]
> OK, but I found another one that does this correctly. 

Which is that? AFAIK all plugins use git's xdiff library in some form, so I'd expect all plugins to have this problem. And even if there is a plugin that doesn't have the exact behaviour as reported, finding and edit that does a similar thing to the issue won't be hard; assuming this other plugin doesn't have any additional black magic.

>  I think correctness should be prioritized first for this kind of plugins. 

How can you argue this is incorrect, though? The signs are technically correct. Remember, the diffs are run without any information on where the cursor or last edit is.

> Your plugin is beautiful.

Thank you 😄 

>  I'll wait for the fix and migrate to this one then.

I'm not really sure if a fix is even possible for this. Diff algorithms always have to make decisions on where to place the hunks (this is why there are multiple algorithms) and none of them will take into account where the most recent edit occurred. With this said, I'm happy to hear any suggestions?

**Comment by nyngwang** [comment]
I'm using `mhinz/vim-signify`. I think it's probably much slower than yours, but I can remember that I ran into the bug as OP above, and I was trying to find a plugin that can do it correctly, and I found this one. (I was a hard decision for me since you really do a good job on making it beautiful)

This plugin was what I used before I migrated to `init.lua`, and I have been installed plugins ends in `.nvim` since then with one exception: one to show the git-sign. I will test the same scenario of OP again later. If it works this time, I will change my mind.

**Comment by nyngwang** [comment]
I have to say sorry for your plugin, the problem still exists and `mhinz/vim-signify` still solved it cleanly(while it's much slower). I will still wait for your patches for this bug.

## gitsigns.nvim

https://user-images.githubusercontent.com/24765272/140513729-2702150a-d9ce-43ca-ad50-68190e226893.mov

## mhinz/vim-signify

https://user-images.githubusercontent.com/24765272/140513786-5fb183d2-dbf4-4e5f-a94d-5d4fcb314b2f.mov

**Comment by lewis6991** [comment]
In your example for vim-signify you are inserting the text `testing` as opposed to a blank line which is why you don't see the issue. If you insert a blank line, you will see the exact same behaviour as Gitsigns.

You can install all plugins simultaneously to this is effect better.

Signs in order: gitsigns, vim-gitgutter, vim-signify

![image](https://user-images.githubusercontent.com/7904185/141101994-a73981ae-2074-4dbe-9771-b30affc3a506.png)

>  I'm a bit disappointed because you said all plugins would fail but it's not true.

It is true.
