### ISSUE TITLE
Unadded files don't show the branch indicator

### ISSUE THREAD

**Issue by akinsho** [lewis6991/gitsigns.nvim#39]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for this great plugin 👍🏿 .
I've noticed whilst using it that if a new file is added to a repo the branch indicator doesn't appear for that buffer till it is added to the repo. I imagine there's a check somewhere to see if the file part of the tree and that returns false or something.

**Describe the solution you'd like**
I think if a file is *within* a repository the branch indicator should show regardless. Understandably the changes wouldn't. As a stretch it'd be nice to have an indicator to say the file hasn't been added so you know you still need to do that.

**Comment by lewis6991** [comment]
Sounds reasonable. I'll implement this eventually (probably soonish), otherwise PR's welcome.

**Comment by lewis6991** [comment]
As far as I can tell `b:gitsigns_head` should already be populated for untracked files.

**Comment by akinsho** [comment]
🤔 @lewis6991 I just tested creating a new file and saving it then trying to echo `b:gitsigns_head` and I get undefined variable. I'm using
```lua
    status_formatter = function(status)
      local added = status.added > 0 and "  " .. status.added or ""
      local changed = status.changed > 0 and "  " .. status.changed or ""
      local removed = status.removed > 0 and "  " .. status.removed or ""
      return status.head .. added .. changed .. removed .. " "
    end
```
if that changes anything

**Comment by lewis6991** [comment]
If you run something like:
```
touch newfile1
nvim newfile1
```

Then `b:gitsigns_head` should be defined.

However If you simply do:

```
nvim newfile2
```

Then `b:gitsigns_head` should be undefined.

This is because gitsigns only attaches to buffers via the `BufRead` autocommand trigger. It currently doesn't do anything for new buffers (through the autocommand triggers `BufNew` or `BufNewFile`).

I'm working on a change to populate `b:gitsigns_status` and `b:gitsigns_status_dict` for new files, as well as for gitsigns to attach to new files.

**Comment by akinsho** [comment]
Ah, I almost always end up creating files within nvim via `e 'path/to/new/file'` which is where I encounter this issue, so makes sense if `BufNew` isn't being watched

**Comment by lewis6991** [comment]
@akinsho any chance you can test out #40

**Comment by akinsho** [comment]
Thanks for the fix 👍🏾 will try it out tomorrow, bit near my laptop atm
