### ISSUE TITLE
Git Blame all lines in a visual selection

### ISSUE THREAD

**Issue by harshasrisri** [lewis6991/gitsigns.nvim#390]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a feature request

**Describe the solution you'd like**
Git blame works great for a single line. Please extend it to show blame info for all lines in a visual selection.

**Describe alternatives you've considered**
~~vim-signify used to do this~~ 
[blamer.vim](﻿﻿https://github.com/APZelos/blamer.nvim) does this.

**Additional context**
N/A

**Comment by lewis6991** [comment]
Do you mean `:Gitsigns blame_line` or `config.current_line_blame`? And what kind of output are you expecting?
