### ISSUE TITLE
Add option so that blame virtual text is displayed when user switches to normal mode instead of a delay.

### ISSUE THREAD

**Issue by YashKarthik** [lewis6991/gitsigns.nvim#398]
**Is your feature request related to a problem? Please describe.**
It's irritating when the blame virt text updates while I'm typing. I know there is an option to delay it but that doesn't really fit my needs.

**Describe the solution you'd like**
Instead of updating/displaying the virtual text after a set duration, display it when the user exits the insert mode. That way the buffer wouldn't move when the user pauses while typing.

**Describe alternatives you've considered**
I've set `current_line_blame_delay = 10000` (10 seconds). But that doesn't exactly solve the problem. Just makes it less frequent.

Thanks!

**Comment by lewis6991** [comment]
Can't you just use an autocmd?

**Comment by YashKarthik** [comment]
Oh yeah, thanks for the suggestion. For anyone else wanting to do this:
```
autocmd InsertEnter * :Gitsigns toggle_signs
autocmd InsertLeave * :Gitsigns toggle_signs
```
Thanks

**Comment by lewis6991** [comment]
I think you want `toggle_current_line_blame`?

**Comment by YashKarthik** [comment]
Nono i wanted this only. I wrote about the wrong this in the original post. I actually meant the colored lines that appear next to the line numbers.
