### ISSUE TITLE
Disable plugin in diff mode

### ISSUE THREAD

**Issue by khaveesh** [lewis6991/gitsigns.nvim#4]
Currently, the plugin remains active even in diff mode. So, it hijacks the signs column and the keymappings too. I'm not able to use [c & ]c, to move between the changes.

My request is to disable the signs and unmap the keymappings when in diff mode. You can use the &diff variable to check if diff mode is active or not.

**Comment by lewis6991** [comment]
Could you provide some specific context on the exact way you're using diff mode? Commands, mappings, plugins?

I use it with fugitive so the signs align with the diff changes so `[c` works well for me. Also what signs in diff mode are being hijacked? Gitsigns sets a low priority for signs (which can be configured) so should be able to work ok with other signs.

Currently the mappings are applied globally but maybe we can make them buffer specific depending if the buffer has signs. Then in diff mode we can make gitsigns detach from the buffer?

**Comment by khaveesh** [comment]
Currently, if I do ]c in diff mode, I get the error `E5108: Error executing Lua .... gitsigns.lua:559: attempt to index a nil value`.

> Currently the mappings are applied globally but maybe we can make them buffer specific depending if the buffer has signs. Then in diff mode we can make gitsigns detach from the buffer?

Yes, I think this could be a possible workaround, hopefully I'm correct

P.S: Super awesome plugin, much faster than gitgutter ever was

**Comment by lewis6991** [comment]
Hope that fixes it. Let me know otherwise.
