### ISSUE TITLE
git blame: configurable additional options

### ISSUE THREAD

**Issue by wookayin** [lewis6991/gitsigns.nvim#400]
**Is your feature request related to a problem? Please describe.**

Please allow extra arguments for `git blame` (for `lua require"gitsigns".blame_line(true)`, for example). For example, `git blame -w` is a very commonly used command to ignore whitespace changes.

**Describe the solution you'd like**

We could have some configurations like
```
gitsigns.setup {
   ...
   extra_blame_args = '-w',          -- default is '' (empty)
}
```
or the field name as you wish.

Alternativelty, allow additional opts:
```
gitsigns.blame_line(true, {extra_args = '-w'})
```
(BTW the first argument `full` could be a part of the opts as well)

**Describe alternatives you've considered**

N/A

**Additional context**

I checked the implementation `lua/gitsigns/git.lua` and there is currently no such feature implemented. For example, [git-messenger](https://github.com/rhysd/git-messenger.vim) has this feature via `let g:git_messenger_extra_blame_args`.

**Comment by lewis6991** [comment]
The fact that Gitsigns uses the git cli is just an implementation detail and not foundational to the overall design. If [lua-git](https://github.com/creationix/lua-git) ever becomes production ready, we would plan to use that where possible.

So with that said, exposing configuration to append options on to specific git commands doesn't seem like the best idea. Git blame doesn't have a huge amount of options, so first class support for the features we want will be ok. From what I can tell, `-w` and `-M` seem like the only useful options.

I propose we add additional options to `blame_line` (and maybe mirror that to current_line_blame), to be something like:

```
blame_line({opts})                                     *gitsigns.blame_line()*

                Parameters: ~
                    {opts}   (table|nil):
                             Additional options:
                             • {full}: (boolean)
                               Display the full commit message.
                             • {ignore_whitespace}: (boolean)
                               Ignore whitespace when comparing the parent’s
                               version and the child’s to find where the lines 
                               came from.
```

For backwards compat, `blame_line(true)` would become an alias for `blame_line{full=true}`.

**Comment by wookayin** [comment]
I totally agree with you about the abstraction. Adding `ignore_whitespace` only also sounds great to me, and it's also open to extension.
