### ISSUE TITLE
Supporting the other VCS

### ISSUE THREAD

**Issue by ssbanerje** [lewis6991/gitsigns.nvim#401]
Thanks for the really awesome plugin! This really simplifies my workflow.

**Is your feature request related to a problem? Please describe.**
In addition to `git`, I sometimes have to work with other VCS systems, mainly `hg`. I was wondering if it will be possible to extend this plugin to deal with some of these other VCS. I understand that this plugin is primarily targeted at `git`, so I am not really talking about feature parity. Having basic functionality like displaying changed lines and the ability to preview/reset hunks will go a long way. 

**Describe the solution you'd like**
My cursory glance of the generated lua code seems to suggest that `gitsigns` interacts with the underlying repo using the standard CLI. Would it make sense to abstract away this interaction and then provide equivalent `hg` (or other VCS) commands and parse its output in a common format. This proposed abstraction layer can then be changed if the vim file is in a folder containing a `.git/` or `.hg/` folder.

In the case that a particular CLI is not implemented for a VCS, then it can just do something like a no-op. That way `git` will have the most complete set of features, but other VCS can reuse some of the awesome integration that this plugin has with Neovim.

**Comment by lewis6991** [comment]
`hg` is not something I use or have any experience with, so I don't have any interest in adding support for it. In fact adding support for other VCS's is kind of a non-goal. However, if someone wants to put the work in and draft a well-written PR, I can always be persuaded. Additionally, someone will need to commit to supporting that VCS longer term.

**Comment by lewis6991** [comment]
Added d413673a974d4323a9034f12a4c5f5c7f89ae24d

Will close this for now but can reopen if needed.

**Comment by clavia-lang** [comment]
gitsigns.nvim can works with [Jujutsu](https://github.com/jj-vcs/jj) with the ["co-locate"](https://jj-vcs.github.io/jj/latest/git-compatibility/#co-located-jujutsugit-repos) repository.

**Comment by jakubbortlik** [comment]
> [@clavium-lang](https://github.com/clavium-lang) how do you make it work with jujutsu workspaces (~git worktree) though? contrary to their colocated repo, they dont have a `.git` folder (only the first clone will).

It looks like a simple `ln -sn {MAIN_REPO}/.git` does the job. I haven't tested this thoroughly, but `gitsigns.nvim` seems to be working just fine in a jj workspace with this symlink.
