### ISSUE TITLE
Option to remove 'Hunk %d of %d' in preview_hunk()

### ISSUE THREAD

**Issue by Congee** [lewis6991/gitsigns.nvim#402]
![image](https://user-images.githubusercontent.com/2083950/141213661-0537b649-feee-4f4e-a838-6564b9ba469f.png)

Hi, thank you for this awesome plugin. I have used vim-signify, gitgutter, and coc-git. None of them shows the index of hunks when showing a diff preview. Is it possible to remove the first line?

https://github.com/lewis6991/gitsigns.nvim/blob/a2a18c69bfd7923c4be8a57ed91d5dd0e7e34a93/lua/gitsigns/actions.lua#L405-L408

**Comment by lewis6991** [comment]
No, currently this is hard coded.

**Comment by Congee** [comment]
Okie, thank you
