### ISSUE TITLE
feature: start disabled

### ISSUE THREAD

**Issue by comploplo** [lewis6991/gitsigns.nvim#420]
**Is your feature request related to a problem? Please describe.**

I call Gitsigns toggle_signs on VimEnter as an autocmd right now, that autocmd is causing me to get errors when gitsigns is loaded by packer asynchronously, the autocmd does not work if it's part of packer's config function for gitsigns. I'd like to start with it off and only enable it when I need it. Before switching to Packer this was not a problem, but now it appears to be.

**Describe the solution you'd like**

A config option that can be inputted into the setup function, something like 'enable_at_startup' which defaults to true but can be set to false.

**Describe alternatives you've considered**
autocmds in the packer config function(don't work), autocmds in a file loaded after gitsigns(works but creates a plenary error at startup)

**Additional context**

Thanks for a great plugin! I just want a way to have it start disabled which works between plugin managers.

**Comment by lewis6991** [comment]
> I call Gitsigns toggle_signs on VimEnter as an autocmd right now, ...

I think you want:

```lua
require('gitsigns').setup{
  signcolumn = false
  ...
}
```

**Comment by comploplo** [comment]
Thanks for the quick response, 
I tried that and gitsigns still opens on starting vim on a file which is in a git repo. [Here](https://github.com/comploplo/dots-and-scripts/blob/07716f7ae117eb13c181d1d5b5603910e81e279d/.config/nvim/lua/packages.lua#L160) is the relevant line in my config, I'd like gitsigns to be loaded but have none of it's ui show, not even a line in the signcolumn, perhaps it's a bug that it didn't disable as i described when I made the change you suggested?

**Comment by lewis6991** [comment]
Just tried, and `signcolumn=false` works for me. Make sure you run `PackerCompile`.

If you're still having issues then please raise a bug report with reproducible steps using a minimal config. The issue template will have more information on how to do this.
