### ISSUE TITLE
Left align all signs

### ISSUE THREAD

**Issue by artart222** [lewis6991/gitsigns.nvim#422]
I want to align all signs to left because of this 

![image](https://user-images.githubusercontent.com/55560437/144766844-ee76996a-6ad5-440d-a3c5-d51660da7515.png)
 
As you can see lsp diagnostics signs will move git signs to right I don't want this to be happened. I tried to fix this by myself by I have problems. It will be very good if you can implement this. I want to hear your thoughts Do you think is this possible? Thanks for you times.

**Comment by clason** [comment]
You have to set the priority of gitsigns so it will always be drawn first.

It is currently not possible in Neovim to assign signs to specific columns, so they will always be drawn from left to right according to priorities without leaving empty columns.

**Comment by artart222** [comment]
But it seems even with higher priority lsp will move it to right. I have setted priority to 1000 and when signcolumn is 1 we only have gitsigns so I'm sure priority of gitsigns is higher than lsp. But when I set signcolumn to 2 we first have lsp signs then we have gitsign

**Comment by clason** [comment]
You have to play with the exact value -- start with `1` and increase.

**Comment by lewis6991** [comment]
As @clason as said, this is entirely controlled with sign priority.
