### ISSUE TITLE
Changing color 

### ISSUE THREAD

**Issue by bryant-the-coder** [lewis6991/gitsigns.nvim#430]
how to change the color for current_line_blame? as it is not that vvisible for me ahaha

**Comment by lewis6991** [comment]
Try changing the highlight.

```vim
highlight link GitSignsCurrentLineBlame Visual
```

**Comment by bryant-the-coder** [comment]
`cmd[[ highlight link gitsignscurrentlineblame guibg=#191724 guifg=#ffffff]]`

y cant this work?

**Comment by bryant-the-coder** [comment]
as the visual is kinda... uhh kinda odd

**Comment by bryant-the-coder** [comment]
`  highlight link GitSignsCurrentLineBlame Insert`
this is what i got

**Comment by lewis6991** [comment]
Set it to whatever you want. Every colorscheme is different and everyone has different tastes.

**Comment by bryant-the-coder** [comment]
can i set guifg? cuz it gives me error

**Comment by lewis6991** [comment]
Remove the term `link`

**Comment by Wegt-meoh** [comment]
You can also do this, it works for me.
```lua
vim.api.nvim_set_hl(0, "GitsignsCurrentLineBlame", { fg = "#ff79c6", bg = "#282a36" }) 
```
