### ISSUE TITLE
Scroll or jump into hunk preview window

### ISSUE THREAD

**Issue by Saecki** [lewis6991/gitsigns.nvim#431]
Sometimes I have quite big diffs that span more than the height of the current window. It would be great if there was either a way to jump into the floating preview window, or scroll through it with some key mapping.
Jumping into the window could be done if `preview_hunk` is called a second time with the window still being visible, that would also allow copying some code etc.
Scrolling would need either a conditional remap of default key mappings like `<c-u>` and `<c-d>` that otherwise just propagates to the default action.

**Comment by lewis6991** [comment]
Use `<C-w>W` to focus onto the window.

**Comment by Saecki** [comment]
Oh wow, I didn't know about that. Thanks!
