### ISSUE TITLE
Incremental setup

### ISSUE THREAD

**Issue by SimonMandlik** [lewis6991/gitsigns.nvim#435]
Would it be possible to make `require('gitsigns').setup` incremental as many other plugins do?

That is, `setup` can be called multiple times and each new call adds new keys in configuration or rewrites existing keys if they were set before.

I like to keep my mappings in one place and have a special lua file for that. It would be great to be able to set just keybindings there. Thanks!

**Comment by lewis6991** [comment]
> That is, setup can be called multiple times and each new call adds new keys in configuration or rewrites existing keys if they were set before.

Is that not currently possible? Please be more specific on what you are observing and what you would prefer to happen.

> I like to keep my mappings in one place and have a special lua file for that. It would be great to be able to set just keybindings there. Thanks!

You can setup key bindings wherever you want to. Gitsigns just has it in the config so they can only be applied to specific buffers.

Also see `:help gitsigns-config-on_attach`

**Comment by SimonMandlik** [comment]
Sure, to keep it simple, if I place these two lines into e.g. `init.lua`, the first one doesn't have any impact:

```julia
require('gitsigns').setup { signcolumn = false, }
require('gitsigns').setup { numhl = true, }
```

I would expect this to be (more or less) equivalent to 

```lua
require('gitsigns').setup { signcolumn = false, numhl = true, }
```

This makes decoupling gitsigns key bindings and other config impossible.

I am quite new to lua + neovim, but the same thing works e.g. for [nvim-tree](https://github.com/kyazdani42/nvim-tree.lua).

**Comment by lewis6991** [comment]
`setup()` is expensive to run as it needs to initialize quite a few things: signs, config, highlights etc. Because of this it is highly recommended **not** to run it multiple times. I suggest you do something like the following instead:

```lua
local gitsigns_cfg = {}
gitsigns_cfg.signcolumn = false
gitsigns_cfg.numhl = true
require('gitsigns').setup(gitsigns_cfg)
```

I also suggest you adopt this style for all plugins you initialize this way. Think of `setup` functions more like a plugin reset, that's how Gitsigns setup function is intended to work.

**Comment by SimonMandlik** [comment]
Thank you! I will follow this advice
