### ISSUE TITLE
autocommand doesnt work

### ISSUE THREAD

**Issue by bryant-the-coder** [lewis6991/gitsigns.nvim#441]
this autocommand doesnt work :(

```lua
-- Gitsigns
cmd [[
  highlight GitSignsCurrentLineBlame gui=bold,italic guifg=#827e7e
]]

```
![image](https://user-images.githubusercontent.com/92417638/148952432-19fb6af0-96dc-4f4a-b14c-1e6bd7035f42.png)

**Comment by lewis6991** [comment]
Hi, If you have an issue, please fill out the issue template so reviewers have enough information to look into it.
