### ISSUE TITLE
autocommand doesnt work

### ISSUE THREAD

**Issue by bryant-the-coder** [lewis6991/gitsigns.nvim#442]
### Description

this autocommand doesnt work :(

`

### Neovim version

NVIM v0.6.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az152-430

### Operating system and version

windows

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ``lua
-- Gitsigns
cmd [[
  highlight GitSignsCurrentLineBlame gui=bold,italic guifg=#827e7e
]]

```
Have this in your config


### Expected behavior

The line blame should follow the autocommand color

### Actual behavior

![image](https://user-images.githubusercontent.com/92417638/148952432-19fb6af0-96dc-4f4a-b14c-1e6bd7035f42.png)

### Gitsigns debug messages

There is no output for debug_message.

my conf:
```lua
use({
		"lewis6991/gitsigns.nvim",
		config = function()
			require("gitsigns").setup({
				current_line_blame_opts = {
					virt_text = true,
					virt_text_pos = "right_align", -- 'eol' | 'overlay' | 'right_align'
					delay = 1000,
					ignore_whitespace = false,
				},
				current_line_blame = true,
				signs = {
					add = { hl = "GitSignsAdd", text = "│", numhl = "GitSignsAddNr", linehl = "GitSignsAddLn" },
					change = {
						hl = "GitSignsChange",
						text = "│",
						numhl = "GitSignsChangeNr",
						linehl = "GitSignsChangeLn",
					},
					delete = {
						hl = "GitSignsDelete",
						text = "│",
						numhl = "GitSignsDeleteNr",
						linehl = "GitSignsDeleteLn",
					},
					topdelete = {
						hl = "GitSignsDelete",
						text = "│",
						numhl = "GitSignsDeleteNr",
						linehl = "GitSignsDeleteLn",
					},
					changedelete = {
						hl = "GitSignsChange",
						text = "│",
						numhl = "GitSignsChangeNr",
						linehl = "GitSignsChangeLn",
					},
				},
				current_line_blame_formatter_opts = {
					relative_time = true,
				},
        debug_mode = true
			})
		end,
	})
 
```

### Minimal config

```Lua
-
```

**Comment by queensferryme** [comment]
Came across the same problem. Workaround:

```lua
vim.cmd [[autocmd BufEnter * highlight GitSignsCurrentLineBlame gui=italic]]
```

It seems highlights are set up only on or after `VimEnter`, so any of your highlight settings before `VimEnter` will be overriden.

https://github.com/lewis6991/gitsigns.nvim/blob/7aad5257fa043b9acf3d40ae064a1685003254da/teal/gitsigns.tl#L494-L501

**Comment by lewis6991** [comment]
@queensferryme the code you referenced only sets up the default values. If you have already defined the highlight, then that code shouldn't do anything.

What is likely happening is that your colorscheme is loading **after** setting `GitSignsCurrentLineBlame` and is clearing all the highlights.

If a proper bug report was provided, then I could look into this more, however the OP skipped the important sections and didn't even format the issue correctly.

**Comment by bryant-the-coder** [comment]
idk how to show the step. u can take a look in my config if u dont mind.

**Comment by bryant-the-coder** [comment]
[autocommand file](https://github.com/bryant-the-coder/NvHack/blob/d83446da848c6f640710050ffedf6ed2d221c456/lua/autocmd.lua#L103)

[gitsigns config](https://github.com/bryant-the-coder/NvHack/blob/main/lua/plugins.lua)
