### ISSUE TITLE
virt lines can't handle `\t`

### ISSUE THREAD

**Issue by kevinhwang91** [lewis6991/gitsigns.nvim#445]
### Description

^

### Neovim version

NVIM v0.6.1

### Operating system and version

ArchLinux

### Steps to reproduce

1. Open a file with `tab` as indent under git repo;
2. Enable `show_deleted`;
3. Delete the indented lines.

### Expected behavior

Respect `tabstop`.

### Actual behavior

Single space for `\t`.

### Minimal config

```Lua
None
```

**Comment by lewis6991** [comment]
Pretty sure this an issue with neovim core. I've raised https://github.com/neovim/neovim/issues/17148

Closing ticket as issue isn't due to Gitsigns
