### ISSUE TITLE
With `show_deleted = true`, undo delete operation remove syntaxt highlight

### ISSUE THREAD

**Issue by fitrh** [lewis6991/gitsigns.nvim#448]
### Description

https://user-images.githubusercontent.com/55179750/149979026-ef85cb01-2dd6-41cc-a1f7-23569fc05c43.mp4

### Neovim version

NVIM v0.7.0-dev+897-g0c0469c4f

### Operating system and version

Arch Linux, kernel 5.16.1-arch1-1

### Steps to reproduce

1. Add `show_deleted = true` into `setup` function
2. Delete a line
3. Undo the delete operation

### Expected behavior

The syntax highlight back to normal

### Actual behavior

No syntax highlight

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Gitsigns and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

-- Load plugins
require('packer').startup {
  {
    'wbthomason/packer.nvim',
    {
      'lewis6991/gitsigns.nvim',
      requires = { 'nvim-lua/plenary.nvim' },
    },
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
    display = { non_interactive = true },
  },
}

_G.load_config = function()
  require('gitsigns').setup{
    debug_mode = true,
    show_deleted = true,
  }
  vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by lewis6991** [comment]
I am unable to reproduce with your minimal config.

**Comment by lewis6991** [comment]
`show_deleted` simply adds/removes extmarks, so any issue here is unlikely to be caused by this plugin.

Assuming that you are using treesitter (which was omitted from the minimal config), I suspect that this is an issue with Neovim core's treesitter highlighter.

**Comment by fitrh** [comment]
You are right, the problem is in the treesitter, sorry, I forgot about the treesitter
