### ISSUE TITLE
line number overriden

### ISSUE THREAD

**Issue by kyazdani42** [lewis6991/gitsigns.nvim#45]
using nvim v0.5.0-dev+1007-g9223d1450 / git-signs master on archlinux
I use packer.nvim and i call git-signs.setup with no config option, in the `config` parameter of packer use function.

When i open a file in a repository containing changes, i've noticed the git signs will replace the line numbers. It happens if i have either signcolumn=yes set or not in my init.lua file.
If you `set signcolumn=yes`, the signs will properly be displayed in the signcolumn and the relative numbers will reappear.

Thanks to work on this, i'm not familiar with the codebase but if you point me in the right direction i will fix it :)

**Comment by lewis6991** [comment]
The codebase is fairly flat right now. The bulk of the plugin is just in `gitsigns.lua`. The update function is probably the best place to look in. 

The only other thing to be aware of is the async lib. `await` essentially acts like `pcall` but the functions it calls either need to wrapped in `async` or have a `callback` as its last argument. The return of `await` is just the return of the function of calls.

If you're able to fix it, could you also add a simple testcase in `test/gitsigns_spec.lua`? Should be straightforward but let me know if you need help.

**Comment by kyazdani42** [comment]
thanks, I will look into it soon

**Comment by lewis6991** [comment]
Are you sure you don't have `signcolumn=number` or something? I can't think of any reason how gitsigns would (or even could) override the number column.

**Comment by kyazdani42** [comment]
well indeed signcolumn was set on number on some cases (when i loaded CoC). thanks i've removed it and it workds just fine now...
