### ISSUE TITLE
Make diff splits configurable to open in horizontal or vertical split

### ISSUE THREAD

**Issue by bockel** [lewis6991/gitsigns.nvim#455]
**Is your feature request related to a problem? Please describe.**
diffthis and similar functions are hard coded to always open in a vertical split.
See [here](https://github.com/lewis6991/gitsigns.nvim/blob/f43cee333fdfeb27aae86bab73a38c5885d5c7f4/lua/gitsigns/actions.lua#L827)

**Describe the solution you'd like**
diffthis options should be configurable via the config diff_opts `:h gitsigns-config-diff_opts` and/or taken from `vim.opt.diffopt` settings

For example, my diffopt is currently set to `horizontal,internal,filler` and I'd expect that `:Gitsigns diffthis` would honor the split setting configuration like it does for the algorithm and internal diff_opts settings.

**Comment by lewis6991** [comment]
Fixed in #458
