### ISSUE TITLE
Abort early in update of line blame if the cursor doesn't move off the line

### ISSUE THREAD

**Issue by yioneko** [lewis6991/gitsigns.nvim#461]
**Is your feature request related to a problem? Please describe.**
The update triggers on `CursorMoved` and `CursorMovedI` but the cursor sometimes remains on the same line with only column having changed. This time I think we should abort early in update instead of reset and put the same extmark as before, which causes flickers.

**Describe the solution you'd like**
I've tried using this patch:
```diff
diff --git a/teal/gitsigns/current_line_blame.tl b/teal/gitsigns/current_line_blame.tl
index 2baa43c..2aeafd3 100644
--- a/teal/gitsigns/current_line_blame.tl
+++ b/teal/gitsigns/current_line_blame.tl
@@ -68,12 +68,8 @@ end
 
 -- Update function, must be called in async context
 M.update = void(function()
-  M.reset()
-  local opts = config.current_line_blame_opts
-
-  -- Note because the same timer is re-used, this call has a debouncing effect.
-  wait_timer(timer, opts.delay, 0)
-  scheduler()
+    -- wait_timer(timer, 10, 0) -- why we need to wait a certain ms time to pass the test?
+    -- scheduler()
 
   local bufnr = current_buf()
   local bcache = cache[bufnr]
@@ -82,6 +78,19 @@ M.update = void(function()
   end
 
   local lnum = api.nvim_win_get_cursor(0)[1]
+  local old_lnum = api.nvim_buf_get_extmark_by_id(bufnr, namespace, 1, {})[1]
+  if lnum - 1 == old_lnum then
+    -- Don't reset if the cursor hasn't moved off the current line
+    return
+  end
+
+  M.reset(bufnr)
+
+  local opts = config.current_line_blame_opts
+
+  -- Note because the same timer is re-used, this call has a debouncing effect.
+  wait_timer(timer, opts.delay, 0)
+  scheduler()
 
   BlameCache:init_or_invalidate(bufnr)
   local result = BlameCache:get(bufnr, lnum)

```

But the test fails on my local machine if I toggle the first two mysterious (to me) lines off.

**Comment by lewis6991** [comment]
@yioneko: can you try #465. It should avoid the flicker by removing and placing the extmark in the same event loop iteration. If it doesn't work then I'll explore you're idea of getting the old lnum.

**Comment by yioneko** [comment]
I've tried it and the flicker problem is gone. However, a new issue is introduced because the reset of extmark is postponed to next event loop when the cursor move off the line.

Before applying the changes:
![1](https://user-images.githubusercontent.com/65551246/152666705-1da4bdc6-599a-495d-9767-cbe8e3b2886f.gif)

After:
![2](https://user-images.githubusercontent.com/65551246/152666712-6ea48d6e-d2c2-448d-809d-972f971be9a8.gif)

**Comment by lewis6991** [comment]
Thanks for checking.

We can go with your idea of looking at the old lnum.

**Comment by lewis6991** [comment]
Just updated #465. Tweaked quite a bit and hopefully should work a lot better now.

**Comment by yioneko** [comment]
Thanks for your excellent work! There is no more issues on my side.
