### ISSUE TITLE
An API module to export git information 

### ISSUE THREAD

**Issue by man9ourah** [lewis6991/gitsigns.nvim#466]
**Is your feature request related to a problem? Please describe.**
Users wants to integrate Git information in all sorts of plugins: (statusline, tabline, file tree, Telescope .. etc). The problem is, those plugins obtain the git info in a suboptimal way, to say the least (not async, out of date, and not handling all the cases); and you cant blame them as it is not easy and not really their goal. 

**Describe the solution you'd like**
It would be very helpful if gitsigns can provide an api module, which any plugin (or user for that matter) can use to obtain the current repo info. 

For example, I once had the idea of making a telescope extension over gitsigns hunks. If there is an api I could use to do something like ‘require”gitsigns.api”.get_repo_hunks()’ it would be very easy. 

I also want to have the git info shown in my nvimtree; however its implementation is synchronous and will affect its performance. If gitsigns can have an api to query the git status of a file then it could be easily incorporated into nvimtree (or bufferline, or any plugin for that matter). 

Users of the api may also want to hook up to a User autocmd of gitsigns indicating an update: ‘autocmd User GitsignsUpdate :NvimTreeRefresh<CR>‘

This will positively impact the overall experience by having a single source, consistent, properly cached git information for all usage in neovim. Looking at gitsigns source, I can confidently say that your implementation for obtaining git information is probably one of the most efficient solutions in neovim eco system, and it would really nice to have it accessible from outside. 

Thanks!

**Describe alternatives you've considered**

**Additional context**

**Comment by lewis6991** [comment]
> For example, I once had the idea of making a telescope extension over gitsigns hunks. If there is an api I could use to do something like ‘require”gitsigns.api”.get_repo_hunks()’ it would be very easy.

We already have a `get_hunks()` function. See `:help gitsigns.get_hunks()`.

> I also want to have the git info shown in my nvimtree; 

Currently, Gitsigns can only provide information for attached buffers, so this won't work for a file browser.

But generally, I'm open to expanding the API for this stuff. The only issue is that API's can't just be changed once created, so it can make development harder. To justify it, I'd want to more specific requests on what users want.

For the meantime, users can use the private API's:

```lua
local git = require('gitsigns.git')
local git_obj = git.Obj.new(file)
```

But note this code only works in a async execution context using plenary's async lib. So you need to do something like:

```lua
local void = require('plenary.async.async').void
local git  = require('gitsigns.git')

local myfunc = void(function()
  local git_obj = git.Obj.new(file)
  ...
end)

myfunc()  -- non-blocking call
```

**Comment by lewis6991** [comment]
Not really an actionable proposal here so closing.
