### ISSUE TITLE
Enabling `word_diff` has bad performance in large file

### ISSUE THREAD

**Issue by kevinhwang91** [lewis6991/gitsigns.nvim#467]
### Description

https://github.com/lewis6991/gitsigns.nvim/blob/672482df3e80e4e30587c54d4c5e3a7f729ce039/lua/gitsigns/manager.lua#L186

`regions` may be continuous and has large range.

### Neovim version

NVIM v0.6.1

### Operating system and version

ArchLinux

### Steps to reproduce

1. Open a large Lua file with thousand lines;
2. Comment all lines with `--` prefix;

### Expected behavior

Smooth.

### Actual behavior

Lag.

### Minimal config

```Lua
vim.cmd [[set runtimepath=$VIMRUNTIME]]
vim.cmd [[set packpath=/tmp/nvim/site]]
local package_root = '/tmp/nvim/site/pack'
local install_path = package_root .. '/packer/start/packer.nvim'

if vim.fn.isdirectory(install_path) == 0 then
  print("Installing Gitsigns and dependencies.")
  vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/wbthomason/packer.nvim', install_path }
end

-- Load plugins
require('packer').startup {
  {
    'wbthomason/packer.nvim',
    {
      'lewis6991/gitsigns.nvim',
      requires = { 'nvim-lua/plenary.nvim' },
    },
    -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  },
  config = {
    package_root = package_root,
    compile_path = install_path .. '/plugin/packer_compiled.lua',
    display = { non_interactive = true },
  },
}

_G.load_config = function()
  require('gitsigns').setup{
    debug_mode = true, -- You must add this to enable debug messages
    -- GITSIGNS CONFIG THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  }

  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  -- ALSO INCLUDE GITSIGNS DEBUG MESSAGES
  vim.cmd('Gitsigns debug_messages')
end

require('packer').sync()

vim.cmd [[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]]
```

**Comment by lewis6991** [comment]
Do you have any suggestions on what we can do?

There isn't really any room to make this run quicker. I think all we can do is disable word-diff selectively.

One idea is that we introduce some thresholds on when to apply word diffs. Maybe disable it on hunks greater than some configurable amount, but default to something like 100-200 lines.

**Comment by lewis6991** [comment]
Actually, looking at the source, there's probably quite a few things we can do to improve perf:

- Cache word diff results.
- Run it in `on_win` instead of `on_line`.

**Comment by kevinhwang91** [comment]
Yes, cache the diff result should improve a lot. How about truncating the lines to be diff? I'm not familiar with diff algorithms, please correct me if I am wrong.

**Comment by lewis6991** [comment]
I guess that could work, but that would mean invalidating the cache much more frequently.

We can try caching for now and see how much better it becomes just from that.

**Comment by lewis6991** [comment]
@kevinhwang91 are you able to try #468? I found an easy way to make word diff more efficient without writing a cache.

**Comment by kevinhwang91** [comment]
Yes, I can confirm that PR can solve this issue. Close this issue if you have merged it.

**Comment by lewis6991** [comment]
Yes spotted that too. Fixed locally, will push update soon.
