### ISSUE TITLE
[Error] Cannot find index file: .../.git/index

### ISSUE THREAD

**Issue by tamago324** [lewis6991/gitsigns.nvim#47]
**Describe the bug**

Opening a file in a git project that has never been committed will result in an error
If `./git/index` does not exist, an error will occur.

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/.plugged'
set runtimepath^=$PLUGIN_DIRECTORY/plenary.nvim
set runtimepath^=$PLUGIN_DIRECTORY/gitsigns.nvim

lua << EOF
require('gitsigns').setup {
  -- config
}
EOF
```

1. Make empty git project: `$ mkdir sample_proj && cd $_ && git init`
2. Create file: `$ touch file.vim`
3. Start nvim: `$ nvim -u ~/tmp/init.vim -i NONE file.vim`

**Observed output**
Error messages, logs, etc

```
Error executing luv callback:
...onfig/nvim/.plugged/gitsigns.nvim/lua/gitsigns/async.lua:21: ...324/.config/nvim/.plugged/gitsigns.nvim/lua/gitsigns.lua:328: Cannot find index file: /home/tamago324/tmp/sample_proj/.git/index
```

**Screenshots**
If applicable, add screenshots to help explain your problem or to capture error messages.

**Additional context**
System: Linux
Neovim version: v0.5.0-dev+1012-gfe1ebea33

**Comment by tamago324** [comment]
You are making an error, explicitly. https://github.com/lewis6991/gitsigns.nvim/blob/b8ff5223a18791b662b93603e58d54435c3ac0af/lua/gitsigns.lua#L326-L330
I'm really sorry.
I am so embarrassed.

**Comment by tamago324** [comment]
As a suggestion, how about using print instead of error?
I was a little concerned about getting an error every time I open a file.

**Comment by tamago324** [comment]
In case of an `error()`, I had to press Enter each time, which I found annoying.

![image](https://user-images.githubusercontent.com/16581287/104793306-46b00480-57e5-11eb-87d4-d3111288c52d.png)

**Comment by lewis6991** [comment]
Thanks for this. I haven't considered this scenario. I'll reopen and try and fix this.

**Comment by tamago324** [comment]
Thank you very much.

Thanks to the issues template, I was able to quickly create issues.

**Comment by sunjon** [comment]
I'd noticed this bug too, but had been too busy to eliminate wether there was an issue in my setup (I'd been playing with the statusline handlers at the time). FWIW I believe the last commit before this issue was:

`9c49451bfd85f397b38ec2362674ac06bf9f3d36`

**Comment by lewis6991** [comment]
Could someone kindly try out https://github.com/lewis6991/gitsigns.nvim/pull/50, It should fix this issue.

**Comment by tamago324** [comment]
@lewis6991 Thank you! I have confirmed that it has been fixed 👍
