### ISSUE TITLE
After quitting diff window, BufEnter event cannot be triggered

### ISSUE THREAD

**Issue by yanzhang0219** [lewis6991/gitsigns.nvim#470]
### Description

After using `:q` to quit the window created by `:Gitsigns diffthis`, the cursor goes back to the original buffer, however, `BufEnter` event cannot not be trigger.

 Is this a bug? Thank you very much. 

### Neovim version

NVIM v0.7.0-dev+975-g4a96e7809

### Operating system and version

macOS 12.2 (the latest)

### Steps to reproduce

1. In init.vim, create an `autocmd` for demo:

	```
	autocmd BufEnter * echom "Hello"
	```

2. Then in any buffer, run `:Gitsigns diffthis`. A temp split window will be opened and the cursor is positioned in this temp window.
3. Run `:q` to quit the diff mode. The temp split window will be closed and the cursor goes back to the original window (buffer), however, "Hello" doesn't show in `:messages`, i.e., `BufEnter` event is not triggered. 

### Expected behavior

`BufEnter` event should be triggered after quitting the diff window.

### Actual behavior

See above

### Minimal config

Using gitsigns default config.

**Comment by yanzhang0219** [comment]
@lewis6991 Any ideas please? I am customizing my setup and this "issue" confuses me a lot. Thank you so much.

**Comment by lewis6991** [comment]
I've been able to reproduce the issue but have no idea why it occurs. My guess is that it is a quick of Neovim.

**Comment by yanzhang0219** [comment]
Many thanks. Does it mean this is a bug of Neovim? Because I don't know how you implement `diffthis()` internally, could you please open an issue in Neovim repo for me? Thank you very much.

**Comment by lewis6991** [comment]
It's just a guess, but it could be. Might even be intended behaviour.

I'll look into it at some point.

**Comment by yanzhang0219** [comment]
Okay. Thank you.

**Comment by yanzhang0219** [comment]
Nice! Thanks.
