### ISSUE TITLE
Git sign relative to split in diff

### ISSUE THREAD

**Issue by BonaBeavis** [lewis6991/gitsigns.nvim#475]
In diff splits the gitsigns from the nonworking tree version are not very helpful. Check out the gitsigns on the left side:

![Screenshot from 2022-02-13 17-37-23](https://user-images.githubusercontent.com/3330855/153767385-6e779294-c87a-4c70-92b8-ea5b6b57b808.png)

I guess because of this when calling `:Gitsigns diffthis` the sign are deactivated for the git file side of the split.

Would it be possible, that the gitsign on the left side reflect the information from the git specific line highlights?

**Comment by lewis6991** [comment]
I don't really understand this request. Can you explain in more detail?

**Comment by BonaBeavis** [comment]
The screenshot was done after calling: `:tabedit % \| Gdiff!`. The right split show the workings version and the left split the staged version. The thin lines on the left side of the splits are done with gitsigns.
While on the right side the gitsigins reflect the diff to the staged version on the left side, which is correct.
On the left side the gitsigns are relative to an empty file, which does not convey useful information.

My solution now is to disable gitsigns on fugitive buffers.

A enhancement would be that the gitsigns on the left side are identical to the gitsigns of the right side.

**Comment by lewis6991** [comment]
Ok, I understand. This is a bug in Gitsigns. It should parse fugitives paths and is failing for the diff case against the index (`commit='0'`).

If you do something like `:Gdiff <branch|sha>` (e.g. `Gdiff HEAD~2`), signs won't show up as the commit is being properly parsed.

**Comment by BonaBeavis** [comment]
> If you do something like :Gdiff <branch|sha> (e.g. Gdiff HEAD~2), signs won't show up as the commit is being properly parsed.

This is the case

**Comment by BonaBeavis** [comment]
Thanks a lot!
