### ISSUE TITLE
Not committed yet formatter

### ISSUE THREAD

**Issue by knpwrs** [lewis6991/gitsigns.nvim#476]
I have `current_line_blame_formatter = ' <author>, <author_time:%Y-%m-%d> - <summary>'`. The `` symbol (from nerd fonts, it's a source control symbol) helps to distinguish the virtual text from gitsigns from other text. The virtual text which says `Not Committed Yet` doesn't have any distinguishing characteristics, it would be really nice to be able to configure it to say ` Not Committed Yet` instead.

**Comment by lewis6991** [comment]
What do you propose?

**Comment by lewis6991** [comment]
Hmm, what about:

```lua
require('gitsigns').setup {
  ...
  current_line_blame_formatter = function(name, info)
    local text
    if info.author == 'Not Committed Yet' then
      text = ' '..info.author
    else    
      local fmt = ' <author>, <author_time:%Y-%m-%d> - <summary>'
      text = require('gitsigns.utils').expand_blame_format(fmt, name, info)
    end

    return {{ text, 'GitSignsCurrentLineBlame' }}
  end
}
```

We would just need to expose `expand_blame_format`.

**Comment by knpwrs** [comment]
That would work for me! As long as it's documented.

**Comment by knpwrs** [comment]
Sure would!
