### ISSUE TITLE
error on master due to autocmd api

### ISSUE THREAD

**Issue by jessfraz** [lewis6991/gitsigns.nvim#483]
### Description

Seem to be due to https://github.com/lewis6991/gitsigns.nvim/commit/865375407e794b7efcab7d28efc51955560d0aaa

<img width="883" alt="Screen Shot 2022-03-03 at 10 10 45 AM" src="https://user-images.githubusercontent.com/1445228/156625943-f1acf62b-228c-4e5d-92ac-ffc3f93fdae1.png">

### Neovim version

NVIM v0.7.0-dev+1158-g6732cd9e5 Build type: Release LuaJIT 2.1.0-beta3 Compiled by macinatormax@falkensmaze  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-6732cd9/share/nvim"  Run :checkhealth for more info

### Operating system and version

macosx monterey

### Expected behavior

no error

### Actual behavior

the error above

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  plenary  = 'https://github.com/nvim-lua/plenary.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2. ...

**Comment by mjlbach** [comment]
You need to update your neovim build to the latest nightly.

**Comment by jessfraz** [comment]
ah okay thanks!

**Comment by jessfraz** [comment]
that worked thanks! idk why brew upgrade wasn't working but I just reinstalled instead...

**Comment by mjlbach** [comment]
Glad to help 😁
