### ISSUE TITLE
undo hunk produces extra ^M on Windows

### ISSUE THREAD

**Issue by xubury** [lewis6991/gitsigns.nvim#492]
### Description

When I undo a modified hunk, it adds an extra ^M character.
Same neovim and git config on Linux doesn't have this bug.
The only difference in my .gitconfig is that I have autocrlf=true on my windows system and autocrlf =input on my linux system.

### Neovim version

NVIM v0.7.0-dev+920-g7e2ce35e3

### Operating system and version

Windows10

### Expected behavior

Undo a modified hunk without adding a ^M

### Actual behavior

![gitbug](https://user-images.githubusercontent.com/46261364/158984279-e9d06cd5-1c28-40dc-930f-742bd370ca97.gif)

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  plenary  = 'https://github.com/nvim-lua/plenary.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim -nu minimal.lua`
2.  Modifiy a git tracked file and undo the modified hunk.

**Comment by lewis6991** [comment]
I don't use Windows so this issue is difficult for me to look into.

**Comment by lewis6991** [comment]
@xubury: Can you try #439

**Comment by xubury** [comment]
> @xubury: Can you try #439

Yes, https://github.com/lewis6991/gitsigns.nvim/pull/493 fixe it.
