### ISSUE TITLE
[Feature] Show automatic preview when navigating hunks

### ISSUE THREAD

**Issue by pidgeon777** [lewis6991/gitsigns.nvim#494]
I think it would be nice to add an option to enable automatic preview of hunks when navigating them (next hunk, previous hunk), maybe this preview could be displayed if the resulting text diff shown wouldn't get too big, in that case, a `hunk too big for preview` or similar message could be displayed in the preview popup instead.

**Comment by gegoune** [comment]
Just so you know, once you open hunk preview is stays on while navigating between hunks.

**Comment by lewis6991** [comment]
> The problem is that when I change buffer, this automatic preview mode get disabled.

Is this **really** a problem?

> Maybe an option could be added to allow this automatic preview mode by default, instead of manually opening the preview window first?

This doesn't seem like a good idea and not something I think we should clutter the config with.

**Comment by pidgeon777** [comment]
> Is this really a problem?

A real problem, not, the plugin is working fine as it is. But an option to enable automatic preview without manually triggering the preview first could save some unnecessary keystrokes.

**Comment by lewis6991** [comment]
Can't you just create custom mappings?

```lua
  vim.keymap.set('n', ']v', function()
    gitsigns.next_hunk()
    vim.schedule(gitsigns.preview_hunk)
  end)

  vim.keymap.set('n', '[v', function()
    gitsigns.prev_hunk()
    vim.schedule(gitsigns.preview_hunk)
  end)

```

Slightly more hacky way...
```lua

  vim.keymap.set('n', ']v', function()
    vim.b._gitsigns_preview_open = true
    gitsigns.next_hunk()
  end)

  vim.keymap.set('n', '[v', function()
    vim.b._gitsigns_preview_open = true
    gitsigns.prev_hunk()
  end)
```

**Comment by lewis6991** [comment]
The latter relies on an implementation detail, so I wouldn't recommend it even though it works.

**Comment by pidgeon777** [comment]
I tried the new commit implementing the `preview` option, but automatic preview seems not to be working (no preview is shown when navigating through hunks):

```lua
vim.api.nvim_set_keymap("n", "<S-M-PageUp>",   ":lua require 'gitsigns'.prev_hunk({preview = true})<CR>", {noremap = true, silent = true})
vim.api.nvim_set_keymap("n", "<S-M-PageDown>", ":lua require 'gitsigns'.next_hunk({preview = true})<CR>", {noremap = true, silent = true})
```

**Comment by pidgeon777** [comment]
I've checked the repository copy of your plugin downloaded by Packer, it seems that for somewhat reason it didn't checkout to your latest push.

![image](https://user-images.githubusercontent.com/13739892/160397488-779dd3ff-eb91-43eb-9057-7e03e81a5899.png)

Do you know what the reason could be?

**Comment by pidgeon777** [comment]
Update: I deleted my local copy of your repository, re-downloaded with packer and now your latest commits are downloaded.

Tested and it works.

**Comment by vimscientist69** [comment]
On newest versions, it would look like this:

```
require("gitsigns").nav_hunk("next", { preview = true })
require("gitsigns").nav_hunk("prev", { preview = true })
```
