### ISSUE TITLE
Allow to disable keymaps

### ISSUE THREAD

**Issue by OkanEsen** [lewis6991/gitsigns.nvim#5]
I tried to disable the default keymaps by setting `keymaps = {}` but this doesn't seem to work, unfortunately.

I checked the place, where the configuration is being applied and it seems like there is actually no way to disable the bindings:
``` lua
  if cfg.keymaps and not vim.tbl_isempty(cfg.keymaps) then
    default_config.keymaps = {}
  end
```

Would be awesome, if you could provide a way (setting to `{}`, `nil` or `false`) to disable the bindings.

Everything else seem to work great, thank you for your hard work! :+1:

**Comment by lewis6991** [comment]
Give that a try. Feel free to reopen if it's not quite right.

**Comment by OkanEsen** [comment]
Thank you, works great!

**Comment by bsander** [comment]
@lewis6991 This seems to have been reverted somehow, I can't disable the built-in keymaps anymore.

**Comment by lewis6991** [comment]
```lua
      require('gitsigns').setup{
        keymaps = {}
      }
```
 Disables keymaps fine for me

**Comment by bsander** [comment]
It doesn't for me.. I set

```lua
          require("gitsigns").setup(
            {
              signcolumn = false,
              numhl = true,
              keymaps = {} -- No key mapping by default
            }
          )
```

and `[c` `]c` still move around hunks for me, which is what I wanted to get rid off.

Also the code that was removed to fix this in 279d496 seems to have been reintroduced when I look at https://github.com/lewis6991/gitsigns.nvim/blob/9fce5542045f78d720d01dd528c32c6f670b6ff3/lua/gitsigns.lua#L317

**Comment by conornewton** [comment]
@lewis6991 @bsander I'm having the same issue...

**Comment by kevintraver** [comment]
I also have the same experience 

Setting `keymaps = {}` does not remove the keymaps and returns the following warning: 
```
gitsigns: Ignoring invalid configuration field 'keymaps'
```

**Comment by lewis6991** [comment]
Gitsigns doesn't set any default keymaps and the `keymaps` field has been removed.
