### ISSUE TITLE
Update index diff when staging hunks in diff mode

### ISSUE THREAD

**Issue by daephx** [lewis6991/gitsigns.nvim#501]
While staging changes in diffsplit using `<leader>gs` for `stage_hunk` the index file doesn't update automatically, requiring an update of the index buffer, say with the `e` command to see what the new state of the index is.

This is true in fugitive's `Gdiffsplit` and `Gitsigns diffthis`.
Though, the buffer IS updated in "fugitive diff" if you use `diffput` command.

**Comment by lewis6991** [comment]
@daephx can you try #502 ?

**Comment by daephx** [comment]
@lewis6991 Quick response, thanks for addressing this! Yup, that appears to work in diffthis. 

Any chance it can also work with fugitive diff? I tend to rely on fugitive more often since it allows me to modify the index directly for really granular staging. I only just recently learned about diffthis and from what I can tell, it appears a lot more like vscode where the index is read-only?

**Comment by lewis6991** [comment]
I can have a look, It will just be a case of telling fugitive to update the whole thing.

Note that Gitsigns supports visual selection staging of partial hunks. This will also provide very granular staging.

> I only just recently learned about diffthis and from what I can tell, it appears a lot more like vscode where the index is read-only?

Yeah, pretty much. I haven't considered making it modifiable or what the semantics of that would be. I guess every buffer change of the index would require a stage.

**Comment by daephx** [comment]
Hopefully it proves simple enough!

> I guess every buffer change of the index would require a stage
If I understand correctly I'm pretty sure fugitive waits until buffer write before the stage is noticeable in a separate terminal.

> Note that Gitsigns supports visual selection staging of partial hunks. This will also provide very granular staging.
That much I'm aware of from use outside the diff mode. I use it very often indeed.
I was more alluding to the hyper-granularity (for lack of a better term) achievable by directly editing diff lines in the index.

**Comment by lewis6991** [comment]
> If I understand correctly I'm pretty sure fugitive waits until buffer write before the stage is noticeable in a separate terminal.

This makes sense and wouldn't be too hard to implement.

**Comment by lewis6991** [comment]
I've updated #502 to update fugitive buffers too. Not sure how robust it is, but seems to work.

Note, if you have unwritten changes in the fugitive buffer then they are wiped away.

**Comment by daephx** [comment]
Cool, It is updating the fugitive buffer now on my end.

> if you have unwritten changes in the fugitive buffer then they are wiped away

Wiping the changes doesn't sound great but is understandable, can those changes be retrieved with an  `undo` command within the index in the case they have been wiped?

I attempted to force this to check for myself, instead of wiping I get this error.
```
E5108: Error executing lua ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:68: The coroutine failed with this message: vim/shared.lua:0: attempt to index a nil value
stack traceback:
        vim/shared.lua: in function 'list_slice'
        ...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/actions.lua:151: in function <...e/pack/packer/opt/gitsigns.nvim/lua/gitsigns/actions.lua:131>
stack traceback:
        [C]: in function 'error'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:68: in function 'step'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:84: in function 'execute'
        ...ite/pack/packer/opt/gitsigns.nvim/lua/gitsigns/async.lua:115: in function 'fn'
        ...te/pack/packer/opt/gitsigns.nvim/lua/gitsigns/repeat.lua:15: in function 'repeat_fn'
        ...te/pack/packer/opt/gitsigns.nvim/lua/gitsigns/repeat.lua:22: in function 'stage_hunk'
        [string ":lua"]:1: in main chunk
```

**Comment by daephx** [comment]
A negitive side effect I noticed is that if you have another buffer open when in diff mode, when you stage a hunk it will bug out.

The bottom drawer is a terminal buffer using [toggleterm](https://github.com/akinsho/toggleterm.nvim).
![WindowsTerminal_3FxHa3bbSU](https://user-images.githubusercontent.com/36192863/161351370-35f6e1ad-145a-4de0-a6a9-125069741237.png)

**Comment by lewis6991** [comment]
@daephx give the latest update a go. I've made it so the index buffers are editable too.

**Comment by daephx** [comment]
Wow, that's working great, Good job!
I'll definitely keep working with it and see if anything crops up.

As a next set, do you have an idea if it's possible with how gitsigns currently handles hunks to prevent the buffer wiping unstaged changes? It appears fugitive `diffput` is capable of doing just that, so to me that's a decent sign it's possible.

**Comment by lewis6991** [comment]
Ok if fugitive can do it then I'll look into it.

**Comment by lewis6991** [comment]
The difference is that gitsigns `stage_hunk()` actually writes to the index, which causes the buffer to become out-of-date and need a reload, which then wipes the unsaved changes. `diffput` just applies the changes to the other buffer. As far as I can tell `diffput` with both fugitive and gitsigns works as it should.

**Comment by daephx** [comment]
Oh ok I see, so fugitive handles it within vim?
What on your thoughts on the safety of the current implementation? Keeping it "as-is", with the overwrites and let the user handle any issues? A simple `undo` can get the most basic things back in a pinch anyway. Or perhaps `stage_hunk` could providing a warning in the echo area and/or preventing further stages if there are unwritten changes to the index buffer?

**Comment by lewis6991** [comment]
@daephx I've worked on #502 a bit more. It no longer wipes unsaved changes and brings up a warning prompt instead. Can you give it a look?

**Comment by daephx** [comment]
@lewis6991 Thanks for the heads up! It's a good compromise given the limitation.
I just tested it; given the options [O]k and [L]oad, is it intended for [O] to do nothing? Just serve as a confirmation, much like saying No or Yes respectively? Other then that slight confusion it appears to work as expected. 👍
