### ISSUE TITLE
Add config option to use `current_line_blame_formatter` for uncommited changes

### ISSUE THREAD

**Issue by thomashoggard** [lewis6991/gitsigns.nvim#503]
**Is your feature request related to a problem? Please describe.**
Currently there isn't a way to specify the formatting of an uncommited line.  The code checks for a hardcoded string [here](https://github.com/lewis6991/gitsigns.nvim/blob/8fce869b67dd7e3b0284df71f70e2f8072e925a2/lua/gitsigns/current_line_blame.lua#L87).  

**Describe the solution you'd like**
It would be great to have the ability to specify the format of an uncommited line. Something like below,

Ideal result:
```
You, 1 hour ago • Uncommited changes
```

Potential config option:
```lua
  current_line_blame_formatter = '      <author>, <author_time> • <summary>',
  current_line_blame_formatter_opts = {
    include_uncommited_line = true
  },
```

**Describe alternatives you've considered**

**Additional context**
VSCode with the gitlens extension is a great place to reference this functionality.

**Comment by lewis6991** [comment]
I think this is a duplicate of #476 . 

> `You, 1 hour ago • Uncommited changes`

Note this isn't possible since it is impossible to know when the changes were introduced. I.e. `<author_time>` is unknown.

**Comment by thomashoggard** [comment]
@lewis6991 I think how VSCode works is that it looks at the last time the buffer was edited.  It then uses that time for all uncommitted code.   To be fair this doesn't add that much value, mostly just a UX thing where the blame looks consistent across all lines.
