### ISSUE TITLE
Supporting simultaneous toggles

### ISSUE THREAD

**Issue by rehno-lindeque** [lewis6991/gitsigns.nvim#506]
**Is your feature request related to a problem? Please describe.**
I would like to `toggle_deleted` and `toggle_word_diff` simultaneously without getting them out of sync.

**Describe the solution you'd like**
I was thinking that one possible easy solution might be to slightly modify [`toggle_*` functions](https://github.com/lewis6991/gitsigns.nvim/blob/2a107231d92fa37224efdbc475abfba71f94b5ee/lua/gitsigns/actions.lua#L75-L108) to take an optional boolean and also return a boolean:

```lua
map('n', '<leader>td', function()
  toggled = package.loaded.gitsigns.toggle_deleted()
  package.loaded.gitsigns.toggle_word_diff(toggled)
end)
```

**Describe alternatives you've considered**
It's possible to simply write

```lua
map('n', '<leader>td', function()
  package.loaded.gitsigns.toggle_deleted()
  package.loaded.gitsigns.toggle_word_diff()
end)
```
However, it's not obvious (to me) how `config.word_diff` and `config.show_deleted` should be kept in sync in such a way that it is clearly stable against the gitsigns api.

Thanks a lot for this lovely plugin!

**Comment by lewis6991** [comment]
@rehno-lindeque does #512 provide what you need?

**Comment by rehno-lindeque** [comment]
Thanks so much, I gave it a try [(in my dotfiles)](https://github.com/rehno-lindeque/wip/blob/461825dda7e1d0bed6c87739e1a242167ebe8497/my-nixos-configurations/nixos-modules/profiles/preferences/neovim/plugins/gitsigns.lua#L49-L59) and it works as advertised.
