### ISSUE TITLE
Git blame for whole file

### ISSUE THREAD

**Issue by timsofteng** [lewis6991/gitsigns.nvim#508]
**Is your feature request related to a problem? Please describe.**
Existing feature to show blame for only single line is slightly confused. Sometimes it's more informative to see whole blame for file.

**Describe the solution you'd like**
It would be nice to have ability to open service buffer on the left side to show the blame for all lines. Or whatever any better solution if you have any ideas.

**Describe alternatives you've considered**
Currently I'm using fugitive blame for this proposal and it is only one feature which I use in fugitive. It is possible to blame file from command line as well. But exception of highlighting is slightly disappointed and to find necessary lines is annoying in big file.

**Additional context**

**Comment by lewis6991** [comment]
What is the problem with using vim-fugitive? vim-fugitive's blame feature is likely better than anything I can implement and I use it all the time.

**Comment by timsofteng** [comment]
@lewis6991 It's slightly strange for me to keep plugin only for blame feature...

**Comment by lewis6991** [comment]
Sorry, that's not a strong enough justification. It is [already](https://github.com/lewis6991/gitsigns.nvim#implement-every-feature-in-vim-fugitive) an explicit non-goal to re-implement every feature of vim-fugitive unless there is a good reason.

**Comment by mboros1** [comment]
Your git annotations are a lot nicer then fugitive, this seems like it wouldn't be too difficult to implement. Would you accept a PR to add this feature?

**Comment by lewis6991** [comment]
There's already `:Gitsigns blame`

**Comment by mboros1** [comment]
> There's already `:Gitsigns blame`

Tried it out, exactly what I was looking for thank you
