### ISSUE TITLE
Add ability to add padding to the virtual text blame message

### ISSUE THREAD

**Issue by thomashoggard** [lewis6991/gitsigns.nvim#511]
**Is your feature request related to a problem? Please describe.**
I find having padding between the code and the virtual text makes parsing everything much easier.  Currently I added some extra spacing into the formatter option, but it feels a bit hacky.  Manually adding padding right now also doesn't work for uncommitted changes since it uses its own internal string.

```
  current_line_blame_formatter = '      <author>, <author_time> • <summary>',
```

**Describe the solution you'd like**
An option where you can specify padding that is applied to the blame formatter for committed and uncommitted changes.,.

**Comment by lewis6991** [comment]
We could add a way to specify padding, but honestly I think it would be bloat and the way you have done it is absolutely fine, IMO. Both would be a single line in your configuration.

For uncommitted lines, I've just opened #524.

**Comment by thomashoggard** [comment]
Perfect! Thank you @lewis6991
