### ISSUE TITLE
Feature: Git Blame priority

### ISSUE THREAD

**Issue by aspeddro** [lewis6991/gitsigns.nvim#513]
**Is your feature request related to a problem? Please describe.**
An option to control the priority of git blame over other visuals like `inlayHints` and `codeLens`.

**Describe the solution you'd like**
Git Blame should appear after the type hint.

**Describe alternatives you've considered**
I don't know if `vim.api.nvim_buf_set_extmark` allows controlling the priority. I tried increasing the `delay` to 2000, but it didn't work.

**Additional context**
![image](https://user-images.githubusercontent.com/16160544/162588081-243269a4-4ff9-4924-845d-71e4a4305024.png)
LSP: rust_analyzer

**Comment by lewis6991** [comment]
@aspeddro can you try #518?

**Comment by aspeddro** [comment]
I made some tests. 

Set `virt_text_priority = 500`. It didn't work, so I put a priority to inlayHints handler, so it worked.

```lua
vim.api.nvim_buf_set_extmark(ctx.bufnr, inlay_hints_ns, end_line, 0, {
   virt_text_pos = 'eol',
   priority = 200,
   virt_text = { { text, highlight } },
   hl_mode = 'combine',
})
```

At first it didn't work for codelens, so I added a priority to `200`.

https://github.com/neovim/neovim/blob/4bef2f02e8bd8d6daecb757fa2bef26a60998707/runtime/lua/vim/lsp/codelens.lua#L141-L142

https://user-images.githubusercontent.com/16160544/163034553-39b65976-85b5-42b2-a926-943ea4043dd8.mp4

**Comment by lewis6991** [comment]
So basically this is an issue with core?

**Comment by aspeddro** [comment]
Could be a issue. I don't know what the expected behavior is when `vim.api.nvim_buf_set_extmark` has no priority.

Some questions:

1. How is priority defined when `vim.api.nvim_buf_set_extmark` has no value?
2. Does it make sense for some core features like `vim.lsp.codelens` to have a priority?

You could test, to see if this behavior is repeated on your machine?

**Comment by clason** [comment]
There's no guarantee on behavior with overlapping extmarks with the same behavior. (This came up before with `vim.highlight.range`.)

**Comment by lewis6991** [comment]
Well from this side it seems the most we can do is expose priority in the config, so I'll just merge it.
