### ISSUE TITLE
No highlights in the signcolum

### ISSUE THREAD

**Issue by mhartington** [lewis6991/gitsigns.nvim#53]
**Describe the bug**

Not sure if this is user error (which it could be), but recently updated and now I'm no longer getting signs printed in my signcolum

**To Reproduce**

init.vim:

```vim
let $PLUGIN_DIRECTORY = '~/.config/nvim/bundle'
lua << EOF
    use {"nvim-lua/plenary.nvim"}   
    use {
      "lewis6991/gitsigns.nvim",
      config = function()
        require "gitsigns".setup {
          signs = {
            add          = {hl = 'DiffAdd'   , text = '│', numhl='GitSignsAddNr'},
            change       = {hl = 'DiffChange', text = '│', numhl='GitSignsChangeNr'},
            delete       = {hl = 'DiffDelete', text = '_', numhl='GitSignsDeleteNr'},
            topdelete    = {hl = 'DiffDelete', text = '‾', numhl='GitSignsDeleteNr'},
            changedelete = {hl = 'DiffChange', text = '~', numhl='GitSignsChangeNr'},

          }
        }
      end
    }
EOF

```

1. Go to a git repo
2. Open a file and edit it
3. See no signs in the column

**Observed output**
No error messages are printed,  it just fails silently

**Screenshots**
![](https://user-images.githubusercontent.com/2835826/107407827-261f5580-6ad8-11eb-8972-8469959d98f0.mp4)

**Additional context**
System: Mac, Linux, Windows: macOS 11.2
Neovim version: 

```
NVIM v0.5.0-dev+1065-g94cf7bba0                                                                      
Build type: Debug                                                                                    
LuaJIT 2.1.0-beta3
```

**Comment by lewis6991** [comment]
Thanks for raising, I'll take a look as soon as a get a chance.

**Comment by lewis6991** [comment]
As far as I can tell there aren't anything I can see that would cause this. We also have a testsuite that I'm sure would have caught something like this.

Perhaps add `debug_mode = true` into your gitsigns config and see if there is any `messages` output. If there isn't then that probably means the plugin isn't being loaded.

**Comment by mhartington** [comment]
Well this is odd. I had some old git status plugins for nerdtree installed at the same time. I removed those from my config and cleaned up my package path and it seems to work fine now. Not sure why though.
