### ISSUE TITLE
Allow Stashing of Individual Hunks

### ISSUE THREAD

**Issue by atomdmac** [lewis6991/gitsigns.nvim#543]
**Is your feature request related to a problem? Please describe.**
There is no way to stash individual hunks from within Neovim

**Describe the solution you'd like**
I would like to be able to stash hunks in a similar fashion to how they can be staged/unstaged

**Describe alternatives you've considered**
In a pinch, I can accomplish something similar using `git stash -p`

**Additional context**
N/A

**Comment by lewis6991** [comment]
Stash hunks is easy enough but how would/can we handle unstashing.

Also what exactly happens when a hunk is stashed. Do we create a new stash for each stashed hunk or do we append to an existing stash?

**Comment by lewis6991** [comment]
An alternative which might be preferable is to stage hunks as normal and then run:

```bash
:!git stash push --staged --message "hunks stashed from gitsigns"
```

**Comment by lewis6991** [comment]
Closing until response.
