### ISSUE TITLE
Hunks not gets reload after pressing `]c` (only with vim-css-color plugin installed)

### ISSUE THREAD

**Issue by UnkwUsr** [lewis6991/gitsigns.nvim#558]
### Description

Hunks gets reload only on movements like `j` and `k` (maybe some more), which results in behavior that when I open file and press `]c`, I get my cursor navigated to first hunk in file, but it is not yet highlighted. And to highlight I must press `j` or `k` at least once.

Also with bisecting I found that this behavior started on 7de953329ff696408bd38d3218b0239839d285e0, so latest commit with "expected behavior" was 5c487a804e462c284c159c800a803b8e0294d0a4.

And also plugin [ap/vim-css-color](https://github.com/ap/vim-css-color) is required to reproduce this issue.

### Neovim version

v0.7.0

### Operating system and version

archlinux

### Expected behavior

Hunks should be highlighted just after pressing `]c`.

https://user-images.githubusercontent.com/49063932/166744099-bba943f5-6147-40ec-920a-e22294a60ebb.mp4

### Actual behavior

Hunks is not highlighted after `]c` and I should press `j` or `k` to get it highlighted.

https://user-images.githubusercontent.com/49063932/166744012-1977d88b-89b4-4763-bbcd-38b6a90fb9de.mp4

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE

  csscolors = 'https://github.com/ap/vim-css-color'
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE

  on_attach = function(bufnr)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', ']c',  "&diff ? ']c' : '<cmd>Gitsigns next_hunk<CR>'", {expr=true})
  end
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua somefile`
2. Press `]c`
3. See your cursor on hunk, but it is not highlighted.

**Comment by lewis6991** [comment]
I can't debug this without being able to reproduce the issue and the information provided isn't sufficient.

Can you provide a tar of a minimised git repo with a file that produces the issue?

**Comment by UnkwUsr** [comment]
[test_repo.tar.gz](https://github.com/lewis6991/gitsigns.nvim/files/8626232/test_repo.tar.gz)

**Comment by lewis6991** [comment]
Thanks for the test_repo. I am able to reproduce the issue.

**Comment by lewis6991** [comment]
Debugged. I believe this is an issue with Neovim. Here is a reduced testcase that uses no plugins:


```lua
-- Fill the buffer with some text
local lines = {}
for i = 1, 200 do
  lines[i] = 'hello'
end
vim.api.nvim_buf_set_lines(0, 0, -1, false, lines)

-- Set up a basic decoration provide which sets a sign on line 100
local ns = vim.api.nvim_create_namespace('ns')
vim.api.nvim_set_decoration_provider(ns, {
  on_win = function(_, _, bufnr, top, bot)
    if top < 100 and bot > 100 then
      vim.api.nvim_buf_set_extmark(bufnr, ns, 99, -1, { sign_text = 'X' })
    end
  end
})

-- Autocmd command which shows the bug
vim.api.nvim_create_autocmd('CursorMoved', {
  callback = function()
    vim.fn.line('w$')  -- Prevents on_win from being called
  end
})

-- Move the cursor sometime after loading the buffer
vim.o.updatetime = 200
vim.api.nvim_create_autocmd('CursorHold', {
  once = true,
  callback = function()
    vim.api.nvim_win_set_cursor(0, {100,0})
  end
})
```

```
nvim --clean -u min.lua
```

Raised https://github.com/neovim/neovim/issues/18661
