### ISSUE TITLE
Integration with diffview.nvim

### ISSUE THREAD

**Issue by rafamadriz** [lewis6991/gitsigns.nvim#560]
**Is your feature request related to a problem? Please describe.**
It would be nice if there was an integration with [sindrets/diffview.nvim](https://github.com/sindrets/diffview.nvim), so when we do `Gitsigns diffthis` it opens the `Diffview` panel instead of the default vim diff tab, which doesn't have the same functionality.  

**Describe the solution you'd like**
Add option in `setup` to enable integration with `diffview`

**Describe alternatives you've considered**
https://github.com/TimUntersberger/neogit offers an integration with `diffview`.

**Comment by lewis6991** [comment]
This isn't integration, if you want to use diffview.nvim then just run `:Diffview`. This request doesn't seem to offer anything.
