### ISSUE TITLE
Incorporate `cursorline` highlighting in sign column

### ISSUE THREAD

**Issue by andmis** [lewis6991/gitsigns.nvim#563]
**Is your feature request related to a problem? Please describe.**

I use `set signcolumn=number` and have my cursor line highlighting extending across the number column like so:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/5308024/168128847-153e11da-99eb-437f-8e58-a38b3f8d1243.png">

I can't find a way to make the `CursorLine` background apply to the signs:

<img width="365" alt="image" src="https://user-images.githubusercontent.com/5308024/168129047-c82152e1-377d-430f-a7bc-4bb1ba04d630.png">

**Describe the solution you'd like**

I would like the lighter-shaded background to extend all the way to the left side of "Another new line".

**Describe alternatives you've considered**

I've played around with the Neovim and gitsigns highlighting a bunch and cannot get this to happen.

**Comment by lewis6991** [comment]
This will require passing the `culhl` argument to `sign_define()`, and also require us to define cursorline variants for all the required sign highlights.

**Comment by andmis** [comment]
Are you sure that this is actually possible/straightforward in Neovim as it currently is? As in, are you sure that the highlight group of the sign text is changed depending on whether the cursor is on the same line as the sign, when `cursorline=number`?

I am just asking because I've noticed that this is a common trend, that the cursorline highlighting does not get applied to the sign column (for example I observed the same thing with `nvim-dap` breakpoints).

**Comment by fwrs** [comment]
Here's a simple solution that makes all signs use the CursorLine background:

```lua
require("gitsigns").setup()
vim.defer_fn(function()
    local cl_bg = vim.api.nvim_get_hl(0, { name = "CursorLine", link = false }).bg
    for _, sign in ipairs(vim.fn.sign_getdefined()) do
        local hl = vim.api.nvim_get_hl(0, { name = sign.texthl, link = false })
        local name = sign.texthl .. "Cul"
        vim.api.nvim_set_hl(0, name, { fg = hl.fg, bg = cl_bg })
        vim.fn.sign_define(sign.name, { culhl = name })
    end
end, 100)
```

**Comment by m-wells** [comment]
I had to modify @fwrs solution slightly.
```lua
require 'gitsigns'.setup(opts)
vim.defer_fn(function()
  local bg = vim.api.nvim_get_hl(0, { name = "SignColumn", link = false }).bg
  local cl_bg = vim.api.nvim_get_hl(0, { name = "CursorLineSign", link = false }).bg
  for _, sign in ipairs(vim.fn.sign_getdefined()) do
    local hl = vim.api.nvim_get_hl(0, { name = sign.texthl, link = false })
    local name = sign.texthl
    vim.api.nvim_set_hl(0, name, { fg = hl.fg, bg = bg })
    name = name .. "Cul"
    vim.api.nvim_set_hl(0, name, { fg = hl.fg, bg = cl_bg })
    vim.fn.sign_define(sign.name, { culhl = name })
  end
end, 10)
```
With modification 
![image](https://github.com/lewis6991/gitsigns.nvim/assets/6752069/a9023ae3-0ff0-4889-af9d-e4dbff40981e)
Without modification
![image](https://github.com/lewis6991/gitsigns.nvim/assets/6752069/1687f59b-d4c2-49fb-8c71-e6a1de2274e9)

**Comment by m-wells** [comment]
I also have the following to get the `SignColumn` to follow `Normal` and `NormalNC`.
```lua
local bg = vim.api.nvim_get_hl(0, { name = "Normal", link = false }).bg
vim.api.nvim_create_autocmd({ "BufWinEnter", "WinEnter" }, {
  command = 'hi SignColumn guibg=' .. bg,
  desc = "For active window, set SignColumn background to Normal",
})
local nc = vim.api.nvim_get_hl(0, { name = "NormalNC", link = false }).bg
vim.api.nvim_create_autocmd("WinLeave", {
  command = 'hi SignColumn guibg=' .. nc,
  desc = "For inactive window, set SignColumn background to NormalNC",
})
```

**Comment by mizlan** [comment]
These solutions work for _signs_, but newer signs use extmarks and extmark namespaces instead. So the above doesn't quite work for me. Might write an updated solutions

**Comment by fwrs** [comment]
I would greatly appreciate a solution that incorporates extmarks!
At the moment I just do `require("gitsigns").setup { _extmark_signs = false }` while hoping that this issue will receive a proper fix 😬

**Comment by mizlan** [comment]
Fwiw I have given up on trying to get it, and I have disabled culhl for all signs

**Comment by lewis6991** [comment]
Done in #1097

**Comment by bluz71** [comment]
This is an excellent enhancement, thanks @apollo1321 and @lewis6991.

**Comment by cmvanb** [comment]
I've been waiting for this feature for a while, so I was excited to get the notification!

Sadly it's not working for me...

![2024-07-24--10-53-02](https://github.com/user-attachments/assets/6815dc3f-3e3c-4a37-aa44-21fa18264914)

**Comment by bluz71** [comment]
@cmvanb,

Your colorscheme needs to support the new `GitSigns*Cul` highlight groups.

In my experimentation, this feature works well.

**Comment by cmvanb** [comment]
Thanks, I added the new highlight groups and it works.

**Comment by mizlan** [comment]
Is anybody noticing breakage with [statuscol.nvim](https://github.com/luukvbaal/statuscol.nvim)? Works for me if I disable statuscol.nvim but breaks with it:
<img width="195" alt="Screenshot 2024-07-24 at 10 01 09 AM" src="https://github.com/user-attachments/assets/bbb73310-b98d-4302-962c-7660dcec1cc1">
<img width="203" alt="Screenshot 2024-07-24 at 10 00 55 AM" src="https://github.com/user-attachments/assets/c19013b0-538f-4b09-b8af-0503dc5839b1">

Might be statuscol.nvim issue

**Comment by apollo1321** [comment]
Created pr to fix this behavior: https://github.com/luukvbaal/statuscol.nvim/pull/133
