### ISSUE TITLE
Flashing signs when adding blank lines

### ISSUE THREAD

**Issue by andmis** [lewis6991/gitsigns.nvim#564]
**Is your feature request related to a problem? Please describe.**
When editing a file, if you add a new line (by pressing enter or some other way), there is a brief flash before the sign is added. See this GIF:

![Screen Recording 2022-05-12 at 2 45 59 PM](https://user-images.githubusercontent.com/5308024/168165849-4453b114-6af3-43ce-a770-7079790b47d3.gif)

**Describe the solution you'd like**
It would be great if the sign were guessed/assumed/inferred synchronously (or at least, synchronously-enough that there is no flash).

---

Edit: this is with `set signcolumn=number`.

**Comment by lewis6991** [comment]
This is probably too difficult to implement so closing.
