### ISSUE TITLE
Add separate highlight for `show_deleted`

### ISSUE THREAD

**Issue by andmis** [lewis6991/gitsigns.nvim#565]
### Description

Starting point:

<img width="367" alt="image" src="https://user-images.githubusercontent.com/5308024/168171886-62f3a503-15b9-4b6e-972b-95b896b1a863.png">

Delete the line with "c":

<img width="306" alt="image" src="https://user-images.githubusercontent.com/5308024/168171916-7141b9a3-71c4-4792-b6ea-6696349b81f8.png">

After `:Gitsigns toggle_deleted` (looks right)

<img width="352" alt="image" src="https://user-images.githubusercontent.com/5308024/168171968-c6d866a6-2072-4bf1-b1d1-ecc448173293.png">

After `:Gitsigns toggle_linehl`:

<img width="349" alt="image" src="https://user-images.githubusercontent.com/5308024/168172045-58ebdf05-b30a-4c3a-8d99-70bf435d6276.png">

### Neovim version

Built from source, `HEAD`

### Operating system and version

macOS 12

### Expected behavior

Just the deleted line should be highlighted.

### Actual behavior

The (still-present) line above the deleted line is highlighted, as well.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open a file with
```
a
b
c
d
e
```
which is part of a Git repo.
3. Follow the steps above.
4. (This works with your minimal config above.)

### Gitsigns debug messages

```
...
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
attach(1): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir=/Users/mishchea/tmp/git_repo/.git -c core.quotepath=o
ff ls-files --stage --others --exclude-standard --eol /Users/mishchea/tmp/git_repo/test.txt
watch_gitdir(1): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir=/Users/mishchea/tmp/git_repo/.git show :0:test.txt
update(1): updates: 1, jobs: 6
update(1): updates: 2, jobs: 6
setup_highlights: Highlight GitSignsAdd is already defined
setup_highlights: Highlight GitSignsChange is already defined
setup_highlights: Highlight GitSignsDelete is already defined
setup_highlights: Highlight GitSignsAddNr is already defined
setup_highlights: Highlight GitSignsChangeNr is already defined
setup_highlights: Highlight GitSignsDeleteNr is already defined
setup_highlights: Highlight GitSignsAddLn is already defined
setup_highlights: Highlight GitSignsChangeLn is already defined
setup_highlights: Highlight GitSignsDeleteLn is already defined
setup_highlights: Highlight GitSignsCurrentLineBlame is already defined
setup_highlights: Highlight GitSignsAddInline is already defined
setup_highlights: Highlight GitSignsDeleteInline is already defined
setup_highlights: Highlight GitSignsChangeInline is already defined
setup_highlights: Highlight GitSignsAddLnInline is already defined
setup_highlights: Highlight GitSignsChangeLnInline is already defined
setup_highlights: Highlight GitSignsDeleteLnInline is already defined
setup_highlights: Highlight GitSignsAddLnVirtLn is already defined
setup_highlights: Highlight GitSignsChangeVirtLn is already defined
setup_highlights: Highlight GitSignsDeleteVirtLn is already defined
setup_highlights: Highlight GitSignsAddLnVirtLnInLine is already defined
setup_highlights: Highlight GitSignsChangeVirtLnInLine is already defined
setup_highlights: Highlight GitSignsDeleteVirtLnInLine is already defined
run_job: git --no-pager --literal-pathspecs --git-dir=/Users/mishchea/tmp/git_repo/.git show :0:test.txt
update(1): updates: 3, jobs: 7
setup_highlights: Highlight GitSignsAdd is already defined
setup_highlights: Highlight GitSignsChange is already defined
setup_highlights: Highlight GitSignsDelete is already defined
setup_highlights: Highlight GitSignsAddNr is already defined
setup_highlights: Highlight GitSignsChangeNr is already defined
setup_highlights: Highlight GitSignsDeleteNr is already defined
setup_highlights: Highlight GitSignsAddLn is already defined
setup_highlights: Highlight GitSignsChangeLn is already defined
setup_highlights: Highlight GitSignsDeleteLn is already defined
setup_highlights: Highlight GitSignsCurrentLineBlame is already defined
setup_highlights: Highlight GitSignsAddInline is already defined
setup_highlights: Highlight GitSignsDeleteInline is already defined
setup_highlights: Highlight GitSignsChangeInline is already defined
setup_highlights: Highlight GitSignsAddLnInline is already defined
setup_highlights: Highlight GitSignsChangeLnInline is already defined
setup_highlights: Highlight GitSignsDeleteLnInline is already defined
setup_highlights: Highlight GitSignsAddLnVirtLn is already defined
setup_highlights: Highlight GitSignsChangeVirtLn is already defined
setup_highlights: Highlight GitSignsDeleteVirtLn is already defined
setup_highlights: Highlight GitSignsAddLnVirtLnInLine is already defined
setup_highlights: Highlight GitSignsChangeVirtLnInLine is already defined
setup_highlights: Highlight GitSignsDeleteVirtLnInLine is already defined
run_job: git --no-pager --literal-pathspecs --git-dir=/Users/mishchea/tmp/git_repo/.git show :0:test.txt
update(1): updates: 4, jobs: 8
Press ENTER or type command to continue
```

**Comment by lewis6991** [comment]
This is by design. When `linehl` is enabled is uses the highlights `GitSigns{Add,Delete,Change}Ln`

You simply need to define `GitSignsDeleteLn` Appropriately.

**Comment by andmis** [comment]
Ok, `GitSignsDeleteLn` controls the highlight of the line with the "b", but why? That line has not been deleted. That line is in the file, unmodified. By the way, the same HL group controls the highlight of the line with the "c", which _has_ been deleted, so I can't turn off highlighting for the line with "b" without affecting the HL of the line with "c".

**Comment by lewis6991** [comment]
> Ok, GitSignsDeleteLn controls the highlight of the line with the "b", but why? 

This is the way signs work in (neo)vim. The default config for signs is:

```lua
    require('gitsigns').setup {
      signs = {
        add          = {hl = 'GitSignsAdd'   , text = '│', numhl='GitSignsAddNr'   , linehl='GitSignsAddLn'},
        change       = {hl = 'GitSignsChange', text = '│', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
        delete       = {hl = 'GitSignsDelete', text = '_', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
        topdelete    = {hl = 'GitSignsDelete', text = '‾', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn'},
        changedelete = {hl = 'GitSignsChange', text = '~', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn'},
      },
      ...
    }
```

So for `delete` signs, the text used in the signcolumn is `_` and if `linehl` is enabled, then the `GitSignsDeleteLn` highlight is used on the line the sign is placed.

`show_deleted` was added much later when `virtual_lines` were added to Neovim. I didn't initially intend for `linehl` and `show_deleted` to be used together so I just re-used the same highlight. Gitsigns already defines a whole heap of highlights so I tried not to introduce any more.

> By the way, the same HL group controls the highlight of the line with the "c", which has been deleted, so I can't turn off highlighting for the line with "b" without affecting the HL of the line with "c".

As a workaround you can change what highlight is used for `delete.linehl` as show above. But I guess using the same highlight for both doesn't make much sense.

How about we introduce a new highlight `GitSignsDeleteVirtLn` which simply defaults to `GitssgnsDeleteLn`, but will allow both to be independently set?

**Comment by andmis** [comment]
I think adding a new highlight group -- to distinguish between the lines that have the `_` or `‾` deletion signs and the virtual lines that represent deleted text -- sounds like the right idea.

I am not sure I agree with `GitSignsDeleteVirtLn` defaulting to `GitSignsDeleteLn`, because of this screenshot:
![image](https://user-images.githubusercontent.com/5308024/169577022-4a8b9d01-32a9-4bb4-b037-9f0e42a94181.png)
In this screenshot, the line with the "c" is deleted, and the line with the "b" is still present in the file, but it's not really possible to tell that by looking at the screenshot.

Maybe `GitSignsDeleteLn` should default to `Normal` and `GitSignsDeleteVirtLn` should default to what is currently `GitSIgnsDeleteLn`?

---

But in any case, if you add the highlight groups, I will be able to solve the problem on my end in my config, and that would be great!

**Comment by lewis6991** [comment]
Turns out `GitSignsDeleteVirtLn` is already what is used and default links to `GitSignsDeleteLn` so if you set both then you get the behaviour you want. I will change the default of `GitSignsDeleteLn` so it is not set to anything.

**Comment by andmis** [comment]
Yay! TYVM!

<img width="226" alt="image" src="https://user-images.githubusercontent.com/5308024/169703709-b254e089-1c58-4277-83c9-4e1d102c8c58.png">
