### ISSUE TITLE
Make signs continuous in buffers with line wrapping enabled

### ISSUE THREAD

**Issue by andmis** [lewis6991/gitsigns.nvim#568]
**Is your feature request related to a problem? Please describe.**
If you are in a buffer with line wrapping, signs will appear only for the first screen line of an added/modified/deleted buffer line.

<img width="337" alt="image" src="https://user-images.githubusercontent.com/5308024/168834388-3b44427d-7b8e-47eb-88bb-f1590dde730e.png">

**Describe the solution you'd like**
The same sign should be present for every screen line of a modified buffer line.

Actually, the killer version of this would be for the Git sign to reflect the word-level situation, as in, if I add a single word in the middle of a wrapped line, to show an "added" sign only for the screen line where that word is. But that sounds like it may be hard.

**Describe alternatives you've considered**
None.

**Additional context**
I understand this may depend on core Neovim functionality which may not exist yet.

**Comment by antonok-edm** [comment]
Just wanted to mention that there's an open issue in Neovim to support repeating particular signs across wrapped lines. Could be useful to throw a :+1: on it: https://github.com/neovim/neovim/issues/12866
