### ISSUE TITLE
Use different indicator for untracked files instead of reusing "+"

### ISSUE THREAD

**Issue by amerlyq** [lewis6991/gitsigns.nvim#569]
**Is your feature request related to a problem? Please describe.**
I want to distinguish "untracked" files from "zero-length tracked files which I edited".
Showing untracked files as "added" is very misleading for me.

**Describe the solution you'd like**
Add new option to specify sign to use for untracked files.
I would very much preferred to have column of "U" or "#" instead of "+".

**Describe alternatives you've considered**
Option "detach for untracked" simply don't cut it, as I may "git add --patch" on the file, and expect it to be shown in gitsigns, when I return to vim.
I.e. part of the file added to index -- will be "no sign" (as per usual), but still untracked part will "#" -- not in index, not in workdir.

**Comment by lewis6991** [comment]
We can do something like this but note once `git add --patch` is run then the whole file will be marked with added signs again (except for the staged hunk), as `git add` will add the file entry into the index.

**Comment by amerlyq** [comment]
Ok, it's still better than marking whole untracked file with "+" even
before we added anything.
