### ISSUE TITLE
Moving cursor is lagging when folded lines across large value.

### ISSUE THREAD

**Issue by kevinhwang91** [lewis6991/gitsigns.nvim#575]
### Description

1. `nvim +'set foldmethod=manual' +'1000,5000fold' +'999' ./src/nvim/eval.c`
2. Move cursor up and down

Should skip handling folded line in `on_win`.  

My solution: If `(bot - top) > N * winheight` should detect whether the lines are folded or not.

### Neovim version

master

### Operating system and version

ArchLinux

### Expected behavior

should be as smooth as possible.

### Actual behavior

lagging

### Minimal config

```Lua
None
```

### Steps to reproduce

As description.

**Comment by lewis6991** [comment]
Can reproduce :+1:

**Comment by lewis6991** [comment]
This seems to only occur for me with `current_line_blame` enabled. Can you confirm?

**Comment by lewis6991** [comment]
Ok, two issues then.

**Comment by kevinhwang91** [comment]
I think it's the same issue. In diff mode two windows are scrollbind, moving a cursor is twice computation which is more obvious.

**Comment by lewis6991** [comment]
You're not being very clear.

Do you experience the issue with `current_line_blame` or not?

I have found the exact code causing the lag with `current_line_blame` so I know there is an issue there.

**Comment by kevinhwang91** [comment]
I have disabled `current_line_blame`. My nvim configuration is complex, I am not sure what the situation in my ENV similar to `current_line_blame` is eanbled.

**Comment by kevinhwang91** [comment]
Using mini.lua can't feel a lagging. However, if the cursor crosses the folded line, `on_win` will be fired. I just added `print(top, bot)` under `on_win`. Gitsigns should improve the perf itself. Users can feel lagging in real ENV.

**Comment by lewis6991** [comment]
> Gitsigns should improve the perf itself. Users can feel lagging in real ENV.

We need to determine that the issue is actually coming from Gitsigns, which you have not provided relevant information for. Yes `on_win` will be called, but there are lots of plugins which use the decoration provider.

Please provide an actual testcase. Not an unproven hypothesis.

**Comment by kevinhwang91** [comment]
OK, free feel to close the issue and I will fix myself.

**Comment by kevinhwang91** [comment]
After debugging, found that is not related to gitsigns. `Gitsigns detach` will ease the lagging. Disable treesitter highlight is fast now, sorry to waste your time.

**Comment by lewis6991** [comment]
No worries. I realised what you were trying to say about `on_win` and I've raised #576 that should attempt to relieve the issue.

Could you test it?

We might be able to apply the same thing to treesitter aswell.

**Comment by kevinhwang91** [comment]
Improve very limited. Look like adding signs is fast but will fire a lot of events about redrawing. treesitter should be improved, but not gitsigns for now.

**Comment by kevinhwang91** [comment]
https://github.com/neovim/neovim/pull/18760
