### ISSUE TITLE
sign_priority doesn't seem to work

### ISSUE THREAD

**Issue by Isos9** [lewis6991/gitsigns.nvim#577]
### Description

I have set the priority to 100 but I still have the lsp diagnostics first, I don't have priority related settings for my lsp configs so I guess it's the default.

### Neovim version

v0.7.0

### Operating system and version

Arch

### Expected behavior

To override lsp diagnostics

### Actual behavior

not overriding  lsp sign column

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by Isos9** [comment]
Sorry I don't have a minimal config right now but here is the packages I have for lsp
```
	use {
		'neovim/nvim-lspconfig',
		'williamboman/nvim-lsp-installer',
	}
	use 'onsails/lspkind-nvim'
	use 'tami5/lspsaga.nvim'
```

**Comment by lewis6991** [comment]
I can check, but the priority is just sent to the sign commands. We don't do anything complicated with them.

You can try running `sign_getplaced` to see what signs and priorities are being applied.

**Comment by Isos9** [comment]
I tested `sign_getplaced` with one modification in my file, and this what it returns me : `[{'signs': [], 'bufnr': 2}]`

**Comment by Isos9** [comment]
Ok, I see that the priority is still set at 6 even though I have these params : 
```
require('gitsigns').setup {
	sign_priority = 100,
	debug_mode = true,
}
```

**Comment by Isos9** [comment]
after the update I still get the same group 
```
{ {
    bufnr = 2,
    signs = { {
        group = "gitsigns_ns",
        id = 122,
        lnum = 122,
        name = "GitSignsChange",
        priority = 6
      } }
  } }
  ```

**Comment by Isos9** [comment]
Ok I was based on the tag release, now it works ! , priority at 100, Thanks !
