### ISSUE TITLE
Refactor gitsigns to use vim.notify everywhere for consistent notifications

### ISSUE THREAD

**Issue by andrewferrier** [lewis6991/gitsigns.nvim#581]
### Description

Gitsigns does not use vim.notify everywhere where it wants to emit a user message. Specifically, in these code locations:

* https://github.com/lewis6991/gitsigns.nvim/blob/c18e016864c92ecf9775abea1baaa161c28082c3/teal/gitsigns/actions.tl#L436
* https://github.com/lewis6991/gitsigns.nvim/blob/c18e016864c92ecf9775abea1baaa161c28082c3/teal/gitsigns/actions.tl#L446
* https://github.com/lewis6991/gitsigns.nvim/blob/c18e016864c92ecf9775abea1baaa161c28082c3/teal/gitsigns/actions.tl#L469
* https://github.com/lewis6991/gitsigns.nvim/blob/c18e016864c92ecf9775abea1baaa161c28082c3/teal/gitsigns/debug.tl#L129
* https://github.com/lewis6991/gitsigns.nvim/blob/c18e016864c92ecf9775abea1baaa161c28082c3/teal/gitsigns/debug.tl#L136

... use `nvim_echo` instead. This means that using plugins like [nvim-notify](https://github.com/rcarriga/nvim-notify) don't work for these notifications; they are still emitted to the status line.

(Incidentally, I've started noticing this since using the recent `set cmdheight=0`, although the principle applies more widely).

### Neovim version

NVIM v0.7.0

### Operating system and version

MacOS 12.1

### Expected behavior

Messages should be emitted via `vim.notify()` using an appropriate logging level.

### Actual behavior

Messages are emitted by `nvim_echo()`

### Minimal config

N/A

### Steps to reproduce

N/A

**Comment by lewis6991** [comment]
I intentionally avoided using `vim.notify` as most of these messages don't work well https://github.com/rcarriga/nvim-notify.

E.g:

![image](https://user-images.githubusercontent.com/7904185/173845830-0b4208a4-79d4-4a78-9439-72a770c1adcd.png)

There are also many builtin messages to Neovim that don't use `vim.notify` either.

**Comment by andrewferrier** [comment]
Yeah, I guess this is a more general problem about what to do with messages now that `cmdheight=0` has been merged. I tried to start a debate on this [here](https://www.reddit.com/r/neovim/comments/vc7nei/techniques_for_viewing_messages_emitted_whilst/). At the moment, this makes `cmdheight=0` difficult to use in practice, not that that has much do with `gitsigns` itself. I guess you can lose this. Sorry for the poorly-thought-through request.

**Comment by lewis6991** [comment]
No problem at all. A lot of this stuff is still in its infancy.

I'll close this ticket for now, but rest assured I'm aware of the general situation.
