### ISSUE TITLE
No longer works on Windows

### ISSUE THREAD

**Issue by ir-ae** [lewis6991/gitsigns.nvim#584]
### Description

Previously this plugin did not work in msys2 but was functional using cmd. However as of the recently change to path conversion ( https://github.com/lewis6991/gitsigns.nvim/commit/329539e061579d1cfd01401d862f146f0927b965 ), I cannot get it working in either.

### Neovim version

NVIM v0.7.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az320-113  Features: -acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "C:/Program Files/nvim/share/nvim"  Run :checkhealth for more info

### Operating system and version

Windows 10 Home Version 21H2

### Actual behavior

![image](https://user-images.githubusercontent.com/45274235/174389817-67eb43a3-41da-4f82-a66b-3b2571f0e7fc.png)

### Minimal config

```Lua
vim.o.packpath = 'C:/Users/i/AppData/Local/nvim/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
}

for name, url in pairs(plugins) do
  local install_path = 'C:/Users/i/AppData/Local/nvim/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true,
}
```

### Steps to reproduce

`nvim --clean -u minimal.lua`

### Gitsigns debug messages

signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --version
fn: Highlight GitSignsAdd is already defined
fn: Highlight GitSignsChange is already defined
fn: Highlight GitSignsDelete is already defined
fn: Highlight GitSignsAddNr is already defined
fn: Highlight GitSignsChangeNr is already defined
fn: Highlight GitSignsDeleteNr is already defined
fn: Highlight GitSignsAddLn is already defined
fn: Highlight GitSignsChangeLn is already defined
fn: Highlight GitSignsCurrentLineBlame is already defined
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from GitGutterDeleteLine
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD

**Comment by lewis6991** [comment]
The fact you are getting that specific error indicates it didn't even work before as the paths weren't being calculated.

**Comment by lewis6991** [comment]
Also, I don't have access to a Windows machine so I'm very limited in being able address Windows related issues.

**Comment by lewis6991** [comment]
@lll9p are you able to assist at all?

**Comment by ir-ae** [comment]
From experimenting a bit more I have discovered that it does not crash when opening nvim in a directory that has a valid HEAD. However when opening in a non git directory or a just 'git init'-ed directory I get the crash. I think this is due to 'git rev-parse --show-toplevel --git-dir --abbrev-ref HEAD' returning fatal in those directories when called from here: https://github.com/lewis6991/gitsigns.nvim/blob/329539e061579d1cfd01401d862f146f0927b965/teal/gitsigns/git.tl#L255.

**Comment by lewis6991** [comment]
Ok, thanks for having a look into it.

Opening in a non git repo works on Mac/Linux (as it is tested via CI), so git is behaving differently on Windows.

I've submitted 5ce7db00d4c24ab090c87df985764d69d331b20f which adds a `nil` check, but it won't fix the issue.

**Comment by ir-ae** [comment]
Thanks for the quick patch. I updated and while I'm not sure if its the right fix or not for now it seems to have got it working again.

**Comment by lewis6991** [comment]
@dundargoc are you able to check that gitsigns works with msys2 and cmd?

**Comment by dundargoc** [comment]
I had some trouble installing neovim on msys2, I suspect the neovim installation wiki might need an update. It works perfectly on cmd though, and I'm willing to believe if it works on cmd then there's nowhere it won't work :).

**Comment by lewis6991** [comment]
Good enough for me.

**Comment by lewis6991** [comment]
Actually OP mentioned:

> Previously this plugin did not work in msys2 but was functional using cmd. 

So there might be a specific issue with msys2

**Comment by dundargoc** [comment]
@ir-ae have you encountered this problem recently?

**Comment by ir-ae** [comment]
Everything has been working smoothly both in msys2 and cmd recently for me.

**Comment by lewis6991** [comment]
Great! We can close this then.
