### ISSUE TITLE
Gutter for git-crypted files is borked

### ISSUE THREAD

**Issue by WhyNotHugo** [lewis6991/gitsigns.nvim#590]
### Description

`git-crypt` allows transparently encrypting files with git, where the checked-out file is decrypted, but the on in the repository itself is encrypted.

Files encrypted in such way always show that lines have been modified/added in the gutter.

Under the hood, this uses `.gitattributes` with `filter=git-crypt diff=git-crypt`, but I think this is not taken into account by gitsigns.

### Neovim version

NVIM v0.7.0

### Operating system and version

Linux 5.18.7-arch1-1 GNU/Linux

### Expected behavior

Files should show correct gutter, or perhaps none if unsupported?

### Actual behavior

Gutter shows wrong. Likely the result of not taking gitattributes/diff into account.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Just set up a repo with git-crypt: https://github.com/AGWA/git-crypt#using-git-crypt
2. Create a text file, make sure it's set to be encrypted.
3. Commit it
4. Open the file with neovim.

### Gitsigns debug messages

(no output)

**Comment by lewis6991** [comment]
This looks like a duplicate of #480

**Comment by WhyNotHugo** [comment]
Yeah, they seem to be quite related. Not entirely the same, but it's likely possible to fix both together.

Let's continue on #480.
