### ISSUE TITLE
Docs issue: is max file length lines or bytes/chars?

### ISSUE THREAD

**Issue by andrewferrier** [lewis6991/gitsigns.nvim#596]
### Description

In both the README and the help file, it's not clear whether `max_file_length` represents lines, or bytes/chars in the file.

### Neovim version

N/A

### Operating system and version

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Minimal config

```Lua
N/A
```

### Steps to reproduce

N/A

### Gitsigns debug messages

N/A

**Comment by andrewferrier** [comment]
(I figured out from reading the source code it was number of lines).

**Comment by lewis6991** [comment]
PR welcome if you want to improve the docs.
