### ISSUE TITLE
FS events instead of polling

### ISSUE THREAD

**Issue by will** [lewis6991/gitsigns.nvim#598]
Do you think it'd be both A) possible and B) worth it to use https://github.com/luvit/luv/blob/master/docs.md#uv_fs_event_t--fs-event-handle instead of polling the git directory for changes?

The libuv bindings all works for me on macOS, haven't tried on a linux yet, but the docs seem to say that they make it work for every platform

```lua
local fse = vim.loop.new_fs_event()
local path = vim.fn.expand("%:p")

vim.loop.fs_event_start(fse, path, {}, function(err, filename, events)
  vim.notify(vim.inspect(err) .. vim.inspect(filename) .. vim.inspect(events))
end)
```

**Comment by lewis6991** [comment]
I initially tried fs events, however I found they were causing 100% CPU utilisation on my Mac.

This was over a year a go so `libuv` may have fixed this issue by now, but will need to check.

**Comment by will** [comment]
Oooo exciting :)
