### ISSUE TITLE
Neovim crashes

### ISSUE THREAD

**Issue by kuator** [lewis6991/gitsigns.nvim#599]
### Description

Neovim crashes

### Neovim version

0.8-dev

### Operating system and version

Ubuntu 22.4

### Expected behavior

Neovim doesn't crash

### Actual behavior

Neovim crashes

### Minimal config

```Lua
Install gitsigns.nvim
```

### Steps to reproduce

Open many files, I guess?

### Gitsigns debug messages

Unfortunately, I didn't have debug_mode set. I only have a screenshot: ![Screenshot from 2022-08-01 16-38-00](https://user-images.githubusercontent.com/25168308/182131203-335f5dfa-c483-412d-8543-d8ac5cf613b1.png)

**Comment by lewis6991** [comment]
Looks like the libuv poll object is causing the crash. I suspect this is a platform issue, or either your Neovim build is broken.

**Comment by kuator** [comment]
> Looks like the libuv poll object is causing the crash. I suspect this is a platform issue, or either your Neovim build is broken.

fwiw, I use neovim's unstable [ppa](https://launchpad.net/~neovim-ppa/+archive/ubuntu/unstable). I'm gonna try building neovim myself and see if the problem persists.

**Comment by kuator** [comment]
Tried building myself, a few crashes happened :cry:. Not sure where to look, gonna turn it off  temporarily

**Comment by lewis6991** [comment]
I've committed ca6b3220b3985284271c0852296d681578ecceb1 so you can disable the watcher.

**Comment by kuator** [comment]
Thanks! I'm gonna try it out
