### ISSUE TITLE
Default branch name breaks update functionality in packer.nvim

### ISSUE THREAD

**Issue by OkanEsen** [lewis6991/gitsigns.nvim#6]
Is there any reason the default branch is called `main` and not `master`? I'm not sure about other package managers but packer.nvim seems to look for the `master` branch which is not available in this repository if you run `PackerUpdate`.

I fixed it for now by specifying the default branch via:
``` lua
    use {
      "lewis6991/gitsigns.nvim",
      branch = "main",
      requires = {
        "nvim-lua/plenary.nvim"
      }
    }
```

Maybe this is a packer.nvim issue though and other package mangers are handling it "better".

**Comment by lewis6991** [comment]
All new projects on github now default with a `main` branch as opposed to `master`: https://github.com/github/renaming

Looks like this is already a confirmed packer issue: https://github.com/wbthomason/packer.nvim/issues/86

**Comment by lewis6991** [comment]
I've adjusted the README instructions to account for this. Thanks for raising.

**Comment by OkanEsen** [comment]
This is no longer needed as of: https://github.com/wbthomason/packer.nvim/commit/a68b21be60a08a2ea1eb6c8964891d8611719d85
