### ISSUE TITLE
Silence output from Status:clear when detaching if buffer doesn't exist

### ISSUE THREAD

**Issue by levouh** [lewis6991/gitsigns.nvim#60]
**Is your feature request related to a problem? Please describe.**
When detaching, the scheduled callback still tries to act on buffers even if they don't exist, spitting out something like:

```
Error executing vim.schedule lua callback: .../pack/packer/start/gitsigns.nvim/lua/gitsigns/status.lua:21: Invalid buffer id: 17
```

notably when using something like `:h bwipeout` to remove the buffers.

**Describe the solution you'd like**
Huck this in a `local success, result = pcall(...)`, and check whether or not it was a success before continuing. This will silence the output, and the functionality remains unchanged. Something like:

```
function Status:clear(bufnr)
   vim.schedule(function()
      local buf_vars = {
        'gitsigns_head',
        'gitsigns_status_dict',
        'gitsigns_status',
      }

      for _, buf_var in ipairs(buf_vars) do
        pcall(api.nvim_buf_del_var, bufnr, buf_var)
      end
   end)
end
```

**Describe alternatives you've considered**
`¯\_(ツ)_/¯` 

**Additional context**
See above, but I would imagine this has something to do with the forceful nature of `:h bwipeout`, regardless, it doesn't hurt to add.

**Comment by lewis6991** [comment]
Many thanks for raising. This was already raised in #58 and there's already a PR open (#59) to fix it.

**Comment by levouh** [comment]
Ahh dammit, the first issue on the list of open ones as well. Apologies for not digging a bit deeper.
