### ISSUE TITLE
W18: Invalid character in group name

### ISSUE THREAD

**Issue by deathmaz** [lewis6991/gitsigns.nvim#604]
### Description

`W18: Invalid character in group name` error when opening neovim

### Neovim version

NVIM v0.8.0-dev

### Operating system and version

Latest stable Manjaro Linux

### Expected behavior

No error when starting neovim

### Actual behavior

When opening neovim i get this error:
```sh
Error detected while processing /tmp/minimal.lua:
W18: Invalid character in group name
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true,
}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`

### Gitsigns debug messages

```sh

signs.init: Using vimfn signs                                                                                                                                                           
run_job: git --no-pager --literal-pathspecs --version
fn: Deriving GitSignsAdd from DiffAdd
fn: Deriving GitSignsChange from DiffChange
fn: Deriving GitSignsDelete from DiffDelete
fn: Deriving GitSignsAddNr from GitSignsAdd
fn: Deriving GitSignsChangeNr from GitSignsChange
fn: Deriving GitSignsDeleteNr from GitSignsDelete
fn: Deriving GitSignsAddLn from DiffAdd
fn: Deriving GitSignsChangeLn from DiffChange
fn: Deriving GitSignsCurrentLineBlame from NonText
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from DiffDelete
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
```

**Comment by lewis6991** [comment]
Not able to reproduce. Are you able to bisect to the point the error beings to appear?

**Comment by lewis6991** [comment]
Issue introduce with https://github.com/neovim/neovim/pull/19645

**Comment by fmoda3** [comment]
@lewis6991 I am still getting this error, even when using the latest master commit of gitsigns (commit 1e107c91c0c5e3ae72c37df8ffdd50f87fb3ebfa)

**Comment by lewis6991** [comment]
Are you sure Gitsigns is causing it?

**Comment by fmoda3** [comment]
Yes, when I comment out `require('gitsigns').setup()` in my config, the error goes away

**Comment by lewis6991** [comment]
Ok, are you able to find which LOC is causing it?

**Comment by fmoda3** [comment]
Im trying to find it, but having trouble because the error doesn't print the line number, or even the file its in.  Just a generic
```
Error detected while processing /Users/fmoda3/.config/nvim/init.lua:
W18: Invalid character in group name
```

**Comment by henrykaplan** [comment]
I'm also still getting it on launch. Verbose mode gave me this:
```
Error detected while processing VimEnter Autocommands for "*":
W18: Invalid character in group name
Error detected while processing VimEnter Autocommands for "*":
E5108: Error executing lua Keyboard interrupt
stack traceback:
	[C]: in function 'sign_define'
	...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/signs.lua:56: in function 'define'
	...pack/packer/start/gitsigns.nvim/lua/gitsigns/manager.lua:353: in function 'setup_signs_and_highlights'
	[string ":lua"]:1: in main chunk
```
I think it's a timing issue, since It runs fine after launch.

**Comment by lewis6991** [comment]
It's not a timing issue. The message only appears once and appear again since the highlight group is already defined.

Are you able to produce a testcase. At the very least provide your Gitsigns config.

**Comment by fmoda3** [comment]
I figured out my issue.  I use Nix to build my environment, which subsequently sets up neovim and its plugins.  While I thought I was using a fixed version specified here:
https://github.com/NixOS/nixpkgs/blob/f994d00dafef6ec634d48db383f99597cc1d720d/pkgs/applications/editors/vim/plugins/generated.nix#L3163

The git rev was in fact being overridden to an older version behind the scenes:
https://github.com/NixOS/nixpkgs/blob/6898b758b69222959b16a96412a572bd341a4bc7/pkgs/development/lua-modules/generated-packages.nix#L514

After force overriding the version in my config to latest, the error goes away.  I'll talk to the Nixpkgs devs as to why this override is hidden.

**Comment by henrykaplan** [comment]
> It looks like you're not using the latest version of Gitsigns. Please use the `main` branch if you use Neovim dev builds.

That was my issue, thank you. Apologies for the confusion.
