### ISSUE TITLE
Prioritize Git Blame's virtual text under Neovim's diagnostics

### ISSUE THREAD

**Issue by thedaviddelta** [lewis6991/gitsigns.nvim#605]
**Is your feature request related to a problem? Please describe.**
Option to set Git Blame's virtual text priority under Neovim's builtin diagnostics.

**Describe the solution you'd like**
Git Blame should disappear on the lines where there is a diagnostic virtual text message (or at least appear after it).

**Describe alternatives you've considered**
I've tried every priority but it didn't work.
I then took a look at #513 as it's a similar issue, and learnt that `nvim_buf_set_extmark` is the way extensions add virtual text.
After that I navigated through Neovim's repo looking for their diagnostic `nvim_buf_set_extmark` call and found [this](https://github.com/neovim/neovim/blob/master/runtime/lua/vim/diagnostic.lua#L1018), so it seems they don't use the priority param.
Then I found the `nvim_buf_set_extmark` [C implementation](https://github.com/neovim/neovim/blob/a27756cc2463139343aa3c214ad20908d42f67a6/src/nvim/api/extmark.c#L678) and released they don't even set a default value for the param if empty.
So maybe there's no way of prioritizing Neovim's diagnostics over Gitsigns' Blame right now, but as you are also a Neovim contributor you have more experience with both codes and maybe can give some better insights.

**Additional context**
Everything was described in the previous section.

**Comment by lewis6991** [comment]
#513 summarises this. The extmarks set by `vim.diagnostic` aren't setting a priority.

The issue needs to be addressed in core, not here.

**Comment by lewis6991** [comment]
> Then I found the nvim_buf_set_extmark [C implementation](https://github.com/neovim/neovim/blob/a27756cc2463139343aa3c214ad20908d42f67a6/src/nvim/api/extmark.c#L678) and released they don't even set a default value for the param if empty.

If default value is set here https://github.com/neovim/neovim/blob/a27756cc2463139343aa3c214ad20908d42f67a6/src/nvim/decoration.h#L11 to `0x1000`.

**Comment by thedaviddelta** [comment]
Oh, I missed that header, thanks!

I just tested the priority field with `5000` and it works! It shows after the diagnostics. It also seems to work correctly by using the same `4096` value.

But it seems strange to me that they're using the single bit value (`0x1000`/`4096`) as a default, instead of any other arbitrary smaller number. I'm not proficient in C but maybe they're using it as a special code or something? I've been taking a look at the repo for some time and haven't found any strange usage but I don't know.

**Comment by lewis6991** [comment]
I think it is just an arbitrarily large number.

**Comment by thedaviddelta** [comment]
I see. I will just use `4096` for the moment. Thanks for everything!
