### ISSUE TITLE
Calling setup in packer.startup breaks things

### ISSUE THREAD

**Issue by nkhlmn** [lewis6991/gitsigns.nvim#606]
### Description

Issue is documented in this issue for packer: https://github.com/wbthomason/packer.nvim/issues/941

It seems that this was being caused by gitsigns (for me at least). Fix for me was to move the setup call into `after/`. Haven't had this issue with any other plugins i'm using with packer that is getting setup in the `config` callback.

### Neovim version

0.7.2

### Operating system and version

macos 12.4

### Actual behavior

See error documented in packer issue.

### Minimal config

```Lua
local fn = vim.fn
local install_path = fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
if fn.empty(fn.glob(install_path)) > 0 then
  PACKER_BOOTSTRAP = fn.system {
    'git',
    'clone',
    '--depth',
    '1',
    'https://github.com/wbthomason/packer.nvim',
    install_path,
  }
end

local function on_startup(use)
  use {
    -- packer
    { 'wbthomason/packer.nvim' },

    { 'lewis6991/gitsigns.nvim', config = function() require('gitsigns').setup() end },
  }

  if packer_bootstrap then
    require('packer').sync()
  end
end

require('packer').startup(on_startup)
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Run `PackerSync`

**Comment by lewis6991** [comment]
This appears to be an issue with packer, not Gitsigns.
