### ISSUE TITLE
Sometimes hunks not gets reload immediately on start

### ISSUE THREAD

**Issue by UnkwUsr** [lewis6991/gitsigns.nvim#614]
### Description

This bug is very similar to https://github.com/lewis6991/gitsigns.nvim/issues/558, but this time no need in other plugins.
... and test file is a little bit different. Strange thing: test file from linked issue works normally (meaning have no bug), but to reproduce THIS issue I just cut few lines from the previous one.

Hope it will be reproducible (tested in docker).
[test_repo_v2.tar.gz](https://github.com/lewis6991/gitsigns.nvim/files/9435542/test_repo_v2.tar.gz)

### Neovim version

NVIM v0.7.2

### Operating system and version

archlinux 

### Actual behavior

See https://github.com/lewis6991/gitsigns.nvim/issues/558

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE

  on_attach = function(bufnr)
    vim.api.nvim_buf_set_keymap(bufnr, 'n', ']c',  "&diff ? ']c' : '<cmd>Gitsigns next_hunk<CR>'", {expr=true})
  end
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua asdf.c`
2. Press `]c`
3. See your cursor on hunk, but it is not highlighted
4. Press `j`
5. See hunks get highlighting

**Comment by lewis6991** [comment]
Thanks, was able to reproduce.

Are you able to test #619?

**Comment by UnkwUsr** [comment]
Yeah, it works. Thanks!
