### ISSUE TITLE
Error in neovim-nightly

### ISSUE THREAD

**Issue by NEX-S** [lewis6991/gitsigns.nvim#616]
### Description

Gitsigns error in nvim-nightly, this time I didn't find any newest branch :(

### Neovim version

Error detected while processing CursorHold Autocommands for "*": E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/ site/pack/packer/opt/packer.nvim/lua/packer/load.lua:155: Vim(append):Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:20: Vim(append):Error e xecuting lua callback: vim/keymap.lua:0: E31: No such mapping stack traceback:         [C]: in function 'cmd'         ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>         [string ":lua"]:1: in main chunk

### Operating system and version

Manjaro Linux Gnome

### Expected behavior

NO ERROR

### Actual behavior

packer.nvim: Error running config for gitsigns.nvim: ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: Vim:E5248: Invalid character in group
name

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

```
packer.nvim: Error running config for gitsigns.nvim: ...pack/packer/opt/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: Vim:E5248: Invalid character in group
name
```

**Comment by lewis6991** [comment]
Please confirm you are running the latest version of Gitsigns.

**Comment by lewis6991** [comment]
If you are running neovim nightly then you must use the `main` branch. The `release` tag is only for official Neovim releases.
