### ISSUE TITLE
Missing `GitSignsDeleteLnInline` (word diff in line) highlight at the end of the line

### ISSUE THREAD

**Issue by younger-1** [lewis6991/gitsigns.nvim#634]
### Description

This is the origin line. The added text `--` is at the start, which is highlighted correctly.
![图片](https://user-images.githubusercontent.com/45989017/192139644-115d77f4-14a3-4d38-81d4-aaed8c9588bd.png)

Then I delete the text `young.lsp`, and the deleted part is highlighted correctly with `GitSignsDeleteLnInline` highlight.
![图片](https://user-images.githubusercontent.com/45989017/192139656-4c9ef30d-56f9-4739-83cc-6ff9a2fb5dff.png)

But when I delete the text `done()`, which is at the end of line, the `GitSignsDeleteLnInline` highlight do not appear at the end of the line
![](https://matrix-client.matrix.org/_matrix/media/r0/download/matrix.org/mOhoiTDgwvizbakAzOilqmvi)

### Neovim version

0.7.2

### Operating system and version

Arch Linux 5.10.102.1-microsoft-standard-WSL2

### Expected behavior

Show `GitSignsDeleteLnInline` highlight for deleted text at the end of line

### Actual behavior

See above pictures

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

`nvim --clean -u minimal.lua`

**Comment by younger-1** [comment]
@lewis6991 The PR works fine but find a small problem: when the deletion text including the last but one char of a line, the `GitSignsDeleteLnInline` highlight will override the last char of that line.

e.g. I only delete the `(` char, but `)` char was also disappear.
![图片](https://user-images.githubusercontent.com/45989017/194371209-46b1d0d0-f828-4d9c-9a81-795cecd277ec.png)

**Comment by lewis6991** [comment]
Thanks, fixed that.
