### ISSUE TITLE
Keep extmarks as much as possible when reset hunk

### ISSUE THREAD

**Issue by kevinhwang91** [lewis6991/gitsigns.nvim#637]
**Is your feature request related to a problem? Please describe.**
`reset_hunk` with range (maybe total buffer content) and `reset_buffer` will replace range lines with lines in hunks.

**Describe the solution you'd like**
Find all hunks and set lines one by one in the range. Maybe can set a limited value if the hunks are Intensive in the range.

**Additional context**
TBH, semantic tokens of coc.nvim and nvim-ufo use a lot of extmarks, that's the reason I want to replace `Gread` in fugitive with `reset_buffer` in gitsigns.

**Comment by kevinhwang91** [comment]
```lua
function _G.resetBuffer(bufnr)
    bufnr = bufnr or vim.api.nvim_get_current_buf()
    local gs = require('gitsigns')
    local hunks = gs.get_hunks(bufnr)
    for i = #hunks, 1, -1 do
        local hunk = hunks[i]
        local added = hunk.added
        gs.reset_hunk({added.start, added.start + math.max(0, added.count - 1)})
    end
end
```
This script works for me, feel free to close the issue if you want.

**Comment by lewis6991** [comment]
Sorry, I really don't understand the feature you are asking for. Can you explain? I don't understand what `reset_buffer` is doing that you don't like.

**Comment by kevinhwang91** [comment]
`nvim_buf_set_lines(0, s, e, true, {lines})` will clear extmarks from `s` to `e`. If the range has only a hunk under `{hs, he}`, I expect to invoke `nvim_buf_set_lines(0, hs, he, true, {hunk_lines})` instead. This will keep extmarks under ranges `{s, hs - 1}` and `{he + 1, e}`.
