### ISSUE TITLE
'show_deleted' doesn't update cursor position for nvim-cmp

### ISSUE THREAD

**Issue by filipgodlewski** [lewis6991/gitsigns.nvim#639]
### Description

Hi, first of all, thank you very much for this great plugin :)

I have an issue with how 'show-deleted' works with nvim-cmp. I think it is rather related to gitsings, but if not, just let me know and I will open this issue on nvim-cmp.

### Neovim version

0.8.0

### Operating system and version

macOS Monterey 12.6

### Expected behavior

The 'show_deleted' option should move cursor by as many lines the deleted hunk high is.

### Actual behavior

The 'show_deleted' option potentially doesn't update the cursor position on insert, and thus completion engines, like nvim-cmp still think that the cursor is 'above' the deleted hunk.

See the screenshot:
![obraz](https://user-images.githubusercontent.com/54432731/194039047-e2597d95-a5f1-41ab-b327-9d93ca1119da.png)

Note: I increased the col_offset in nvim-cmp so that the floating window is moved to the right a little. Of course, this is not sufficient enough.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  cmp = 'https://github.com/hrsh7th/nvim-cmp',
  buffer = 'https://github.com/hrsh7th/cmp-buffer',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  show_deleted = true,
}

require('cmp').setup({
  sources = {
    { name = "buffer" },
  }
})
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Make sure that nvim-cmp is enabled
3. Toggle deleted lines to be visible
4. Open a buffer and delete some lines, or just edit one
5. While typing notice that nvim-cmp thinks that the cursor position is still above the deleted virtual lines
6. Notice also that depending on how many deleted lines are displayed, the nvim-cmp's floating window might be hiding the text you're typing.

**Comment by lewis6991** [comment]
Honestly, I would say this is an issue with nvim-cmp. Gitsigns is just setting extmarks, it shouldn't be expected to worry about handling of floating windows from other plugins.
