### ISSUE TITLE
diffthis not working

### ISSUE THREAD

**Issue by curiousponge** [lewis6991/gitsigns.nvim#647]
### Description

The diffthis functionality `:Gitsigns diffthis` not working since commit 5df4ac570e796f3ccf1d9c0445c131f6225bde8c. I discovered that the change on lua/gitsigns/action.lua line 900 `base = tostring(base)` is causing this. When I remove that line, which initially came with the specified commit, the diffthis behaviour returns to behave as expected. 

I wonder if I am missing something or whether I am alone with this issue.

Regards.

### Neovim version

NVIM v0.7.2 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wsuggest-attribute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include Compiled by runner@fv-az395-591  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: " /home/runner/work/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

Ubuntu 20.04

### Expected behavior

The `:Gitsigns diffthis` command  should show current changes on splitview on the buffer, which is in a git repository

### Actual behavior

Gitsigns throws "fatal: invalid object name: 'nil'" error and opens an empty buffer while deleting the buffer you were working on.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim'
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua file_you_want_to_view_git_diff`
2. ...

### Gitsigns debug messages

fatal: invalid object name 'nil'.
signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --version
fn: Deriving GitSignsAdd from DiffAdd
fn: Deriving GitSignsChange from DiffChange
fn: Deriving GitSignsDelete from DiffDelete
fn: Deriving GitSignsAddNr from GitSignsAdd
fn: Deriving GitSignsChangeNr from GitSignsChange
fn: Deriving GitSignsDeleteNr from GitSignsDelete
fn: Deriving GitSignsAddLn from DiffAdd
fn: Deriving GitSignsChangeLn from DiffChange
fn: Deriving GitSignsAddPreview from DiffAdd
fn: Deriving GitSignsDeletePreview from DiffDelete
fn: Deriving GitSignsCurrentLineBlame from NonText
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from DiffDelete
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
attach(1): Attaching (trigger=setup)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /home/sencer/.local/share/nvim/plugged/nerdtree/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /home/sencer/.local/share/nvim/plugged/nerdtree/plugin/NERD
_tree.vim
watch_gitdir(1): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /home/sencer/.local/share/nvim/plugged/nerdtree/.git show :0:plugin/NERD_tree.vim
update(1): updates: 1, jobs: 5
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /home/sencer/.local/share/nvim/plugged/nerdtree/.git show nil:plugin/NERD_tree.vim
detach(1): Detached

**Comment by matteematt** [comment]
I am having the same issue with `diffthis` not working

**Comment by lewis6991** [comment]
Ah, it's just broken if no arguments are provided. Should work if you specify a base.

I'll fix this tomorrow.

**Comment by coffebar** [comment]
Hi. I have a similar issue. diffthis throws errors and doesn't work

```
E5108: Error executing lua: ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua
:76: The coroutine failed with this message: vim/_editor.lua:0: nvim_exec2()..BufEnter
Autocommands for "*": Vim(lua):E5108: Error executing lua ...k/packer/start/project.nvi
m/lua/project_nvim/project.lua:76: attempt to index local 'dir' (a nil value)
stack traceback:
        ...k/packer/start/project.nvim/lua/project_nvim/project.lua:76: in function 'ma
tch'
        ...k/packer/start/project.nvim/lua/project_nvim/project.lua:133: in function 'f
ind_pattern_root'
        ...k/packer/start/project.nvim/lua/project_nvim/project.lua:223: in function 'g
et_project_root'
        ...k/packer/start/project.nvim/lua/project_nvim/project.lua:263: in function 'o
n_buf_enter'
        [string ":lua"]:1: in main chunk
        [C]: in function 'resume'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:71: in function 'st
ep'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:102: in function 'd
iffthis'
```

**Comment by lewis6991** [comment]
The errors there are happening in project.nvim, not Gitsigns.

**Comment by coffebar** [comment]
@lewis6991 you're right, diffthis works for me without that plugin
