### ISSUE TITLE
Invalid character in group name in function 'sign_define'

### ISSUE THREAD

**Issue by pannet1** [lewis6991/gitsigns.nvim#649]
### Description

![image](https://user-images.githubusercontent.com/12350276/194868386-dd1d352b-4476-4f63-a7e5-490ce2799649.png)

### Neovim version

NVIM v0.8.0-dev

### Operating system and version

EndeavourOS Linux x86_64 

### Expected behavior

Error free vim window

### Actual behavior

Invalid character in group name in function 'sign_define'

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
This is already fixed in the 0.5 release of Gitsigns and on both the `release` and `main` branches.

Please update

**Comment by pannet1** [comment]
:PackerUpdate does not seems to do the trick. How to update to the latest GitSigns, then

**Comment by lewis6991** [comment]
`git pull`

**Comment by lewis6991** [comment]
Sounds like a packer problem. Please raise an issue there.

**Comment by aceforeverd** [comment]
The problem happens to me recently and it turns out I have a old version of gitsigns in another pack path installed. No problem for this plugin.
