### ISSUE TITLE
Gitsigns QFListOpts error

### ISSUE THREAD

**Issue by maximyurevich** [lewis6991/gitsigns.nvim#655]
### Description

Error with command QFListOpts 
https://imgur.com/x23aeB5.png

### Neovim version

0.8

### Operating system and version

Arch Linux

### Expected behavior

No error 

### Actual behavior

Error

### Minimal config

```Lua
require('gitsigns').setup{}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
QFListOpts is not a valid command

**Comment by maximyurevich** [comment]
> QFListOpts is not a valid command

What it's mean?

**Comment by lewis6991** [comment]
It's a type used in the code.

**Comment by maximyurevich** [comment]
> It's a type used in the code.
This function not implemented?
https://imgur.com/5sBABYo.png

**Comment by lewis6991** [comment]
That just an error in the completion. It isn't a function.

**Comment by lewis6991** [comment]
It is not a function. Don't call it.

**Comment by jiachengxu** [comment]
> It is not a function. Don't call it.

But there are only two options for calling `:Gitsigns` in my case:
![image](https://user-images.githubusercontent.com/18415314/200969626-76e65477-c8a1-43ff-bd29-7a4f7f064acc.png)
I can verify from `:PackerStatus` that gitsigns is loaded.

**Comment by jiachengxu** [comment]
> It is not a function. Don't call it.

But there are only two options for calling `:Gitsigns` in my case:
![image](https://user-images.githubusercontent.com/18415314/200969626-76e65477-c8a1-43ff-bd29-7a4f7f064acc.png)
I can verify from `:PackerStatus` that gitsigns is loaded.

**Comment by lewis6991** [comment]
Update. I forgot to negate a condition in the completion code.
