### ISSUE TITLE
Some files have different lines in the signcolumn

### ISSUE THREAD

**Issue by B4mbus** [lewis6991/gitsigns.nvim#679]
### Description

I noticed that some files have the normal, contiguous lines in the signcolumn:
![image](https://user-images.githubusercontent.com/75364377/202318710-f45cb1aa-042a-470f-80b6-d00f951e1a08.png)

And some don't:
![image](https://user-images.githubusercontent.com/75364377/202318737-c2ce80aa-c92e-4b0c-923f-d19468a610e7.png)

I did a little testing and I think it only happens with files that are completely new, not tracked by git before.

Here is also a screenshot from minimal config:
![image](https://user-images.githubusercontent.com/75364377/202321963-ad8c3d61-445a-4d38-b9d0-e6d694eace09.png)

### Neovim version

NVIM v0.8.0 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=fo rmat-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack- protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack -clash-protection -fcf-protection -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS _HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow  -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrou gh -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE - DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/builddir/build/BUILD/neovim-0.8.0/redhat-linux -build/cmake.config -I/builddir/build/BUILD/neovim-0.8.0/src -I/usr/include -I/usr/include/luajit-2.1 -I/builddir/build /BUILD/neovim-0.8.0/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.8.0/redhat-linux-build/include Compiled by mockbuild@koji  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

Fedora 36

### Expected behavior

The files should have green contiguous lines instead of not contiguous ones.

### Actual behavior

What was shown in the description, new files have not-contiguous lines, only changed files have contiguous lines:
(new at the top, not new at the botttom)
![image](https://user-images.githubusercontent.com/75364377/202319105-f47af1d9-e229-4397-b9c9-69748e04aa7a.png)

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open a repository with some new, untracked file and one that is already tracked, add some changes to the tracked file, the new one will have different lines than the previously tracked one.

### Gitsigns debug messages

signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --version
fn: Deriving GitSignsAdd from DiffAdd
fn: Deriving GitSignsChange from DiffChange
fn: Deriving GitSignsDelete from DiffDelete
fn: Deriving GitSignsAddNr from GitSignsAdd
fn: Deriving GitSignsChangeNr from GitSignsChange
fn: Deriving GitSignsDeleteNr from GitSignsDelete
fn: Deriving GitSignsAddLn from DiffAdd
fn: Deriving GitSignsChangeLn from DiffChange
fn: Deriving GitSignsAddPreview from DiffAdd
fn: Deriving GitSignsDeletePreview from DiffDelete
fn: Deriving GitSignsCurrentLineBlame from NonText
fn: Deriving GitSignsAddInline from TermCursor
fn: Deriving GitSignsDeleteInline from TermCursor
fn: Deriving GitSignsChangeInline from TermCursor
fn: Deriving GitSignsAddLnInline from GitSignsAddInline
fn: Deriving GitSignsChangeLnInline from GitSignsChangeInline
fn: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
fn: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
fn: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
fn: Deriving GitSignsDeleteVirtLn from DiffDelete
fn: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
fn: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
fn: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
: Running action 'nil' with arguments {}
attach(10): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /mnt/data/prv/dev/forks/cpplangnet/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /mnt/data/prv/dev/forks/cpplangnet/content/docs/std/containers/other/stack.mdx
watch_gitdir(10): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /mnt/data/prv/dev/forks/cpplangnet/.git show :0:content/docs/std/containers/other/stack.mdx
update(10): updates: 1, jobs: 6
attach(11): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /mnt/data/prv/dev/forks/cpplangnet/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /mnt/data/prv/dev/forks/cpplangnet/content/docs/std/containers/other/index.mdx
watch_gitdir(11): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /mnt/data/prv/dev/forks/cpplangnet/.git show :0:content/docs/std/containers/other/index.mdx
update(11): updates: 2, jobs: 10
update(11): updates: 3, jobs: 10
update(11): updates: 4, jobs: 10
update(11): updates: 5, jobs: 10
update(11): updates: 6, jobs: 10
update(11): updates: 7, jobs: 10
update(11): updates: 8, jobs: 10
update(11): updates: 9, jobs: 10
update(11): updates: 10, jobs: 10
update(11): updates: 11, jobs: 10
update(11): updates: 12, jobs: 10
update(11): updates: 13, jobs: 10
update(11): updates: 14, jobs: 10
update(11): updates: 15, jobs: 10
update(11): updates: 16, jobs: 10
: Running action 'debug_messages' with arguments {}
: Running action 'debug_messages' with arguments {}

**Comment by serhez** [comment]
@B4mbus did you solve this?

**Comment by lewis6991** [comment]
This is an intended feature. Untracked files get a different sign.

**Comment by B4mbus** [comment]
@serhez exactly as @lewis6991 says. I just didn't read the docs carefully enough. You can always change the sign for untracked files.

**Comment by serhez** [comment]
Thank you both 👍
