### ISSUE TITLE
Add option to disable attaching to untracked files

### ISSUE THREAD

**Issue by lewis6991** [lewis6991/gitsigns.nvim#68]
_Originally posted by @clason in https://github.com/lewis6991/gitsigns.nvim/issues/63#issuecomment-787425873_

Implement `config.attach_to_untracked`

**Comment by richban** [comment]
Is this why I get this error. It tries to attach to an untracked file?

```
Error executing luv callback:
...ite/pack/packer/start/gitsigns.nvim/lua/gitsigns/git.lua:33: attempt to compare nil with number
```

**Comment by lewis6991** [comment]
Not quite, though related.

The code is:

```
        local line = cmd("git ls-files --stage --others --exclude-standard "..file)
        local parts = vim.split(line, '%s+')
        if #parts > 1 then
          stage = tonumber(parts[3])
          if stage <= 1 then
              mode_bits   = parts[1]
              object_name = parts[2]
              relpath     = parts[4]
          else
              has_conflict = true
          end
        else
          relpath = parts[1]
        end
```

For tracked files attributes are returned (`#parts == 4`), for untracked files the filename is returned (`#parts == 1`), for ignored files nothing is returned (`#parts == 0`). For the error you have `#parts == 2`. Could you tell me the output out:

```bash
git ls-files --stage --others --exclude-standard <file causing error>
```

**Comment by richban** [comment]
The file is untracked

```sh
❯ git ls-files --stage --others --exclude-standard Finance/Blockchain\ Basics\ \&\ Cryptography.md
Finance/Blockchain Basics & Cryptography.md
```

**Comment by lewis6991** [comment]
Oh no, spaces in the file name...

Thanks for reporting, I'll get this fixed.

**Comment by richban** [comment]
Awesome! Thanks a lot!

**Comment by lewis6991** [comment]
FIxed in https://github.com/lewis6991/gitsigns.nvim/commit/29fb4a3d84fbfa2572a33f9def5206c78c994bf3
