### ISSUE TITLE
Untracked files break signcolumn=number

### ISSUE THREAD

**Issue by ldelossa** [lewis6991/gitsigns.nvim#681]
### Description

When using gitsigns with `signcolumn=number` opening an untracked file places a dotted line on the entire left side of the window and hides all numbers. Should this occur?

![image](https://user-images.githubusercontent.com/5642902/202552808-97abf6f9-fbb9-4318-b16d-8fda8cd8674d.png)

### Neovim version

v0.8.0

### Operating system and version

Fedora 36

### Expected behavior

No signs are panted for new file.

### Actual behavior

![image](https://user-images.githubusercontent.com/5642902/202552856-53f5921a-5fff-46f7-b5c5-6e4cc774bc44.png)

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Create a new untracked file
2. Configure vim with `signcolumn=number` 
3. View that all numbers are missing due to entire sign column having a dotted line.

**Comment by gegoune** [comment]
Yes, I believe this is for untracked files.

**Comment by ldelossa** [comment]
If this is the intended UI, feel free to close.

**Comment by lewis6991** [comment]
This is exactly what `signcolumn=number` does. If you don't want these signs then you can either configure `config.attach_to_untracked = false` or `config.signs = { untracked = { text = ' ' }` might work too.
