### ISSUE TITLE
Cannot preview hunk inline when delete lines at the beginning of file

### ISSUE THREAD

**Issue by sunn4room** [lewis6991/gitsigns.nvim#684]
### Description

example:
```
aaa
bbb
ccc
```
delete the `aaa`
```
bbb
ccc
```
Now I cannot preview hunk inline for this change, because the cursor cannot focus this hunk.

### Neovim version

0.8.0

### Operating system and version

Archlinux

### Actual behavior

xxx

### Minimal config

```Lua
require('gitsigns').setup {}
```

### Steps to reproduce

same as description

**Comment by lewis6991** [comment]
You need to press `<C-y>` to scroll the viewport up.
