### ISSUE TITLE
Nvim crash on startup with `git config --global core.autocrlf input` on W10

### ISSUE THREAD

**Issue by Acelya-9028** [lewis6991/gitsigns.nvim#69]
**Describe the bug**

Nvim crash on startup with `git config --global core.autocrlf input` on W10. See https://github.com/lewis6991/gitsigns.nvim/pull/64#issuecomment-786811813. Finally, I got an error message after several attempts to start nvim without crashing.

**Observed output**

![autocrlf-input](https://user-images.githubusercontent.com/45818681/109400232-cafab900-7947-11eb-9737-61d59163896a.png)

**Additional context**

It's caused by https://github.com/lewis6991/gitsigns.nvim/blob/cfc8728782b1bcb45410b3616dbf0820e60f292b/teal/gitsigns/git.tl#L221

I think the reason is the same as https://github.com/lewis6991/gitsigns.nvim/blob/926eb0602a5245839fe1feae754c76603b9a49ea/teal/gitsigns.tl#L469-L470

So, as the crash is initially caused by `staged` which uses `\r\n` instead of `\n`, I searched to fix that and I found [this](https://stackoverflow.com/a/43967013). I tested `with(open(file, 'wb'), function(writer: FILE)` in https://github.com/lewis6991/gitsigns.nvim/blob/cfc8728782b1bcb45410b3616dbf0820e60f292b/teal/gitsigns.tl#L68

And it works, `staged` uses `\n` now. So, `wb` fix the root of the previously broken diff and `--ignore-space-at-eol` seems no longer useful.

But there is still the problem of print in `on_stderr` which causes nvim to crash. With `wb`, `git config --global core.autocrlf input` no longer returns an error, so nvim don't crash, but I don't think it's enough, an error may be caused by some other problem and if there is an error, there is a crash.

```diff
diff --git a/teal/gitsigns.tl b/teal/gitsigns.tl
index 17b258b..36ec4b4 100644
--- a/teal/gitsigns.tl
+++ b/teal/gitsigns.tl
@@ -65,7 +65,8 @@ local function dirname(file: string): string
 end
 
 local function write_to_file(file: string, content: {string})
-  with(open(file, 'w'), function(writer: FILE)
+  -- On windows 'w' mode use \r\n instead of \n, see: https://stackoverflow.com/a/43967013
+  with(open(file, 'wb'), function(writer: FILE)
     for _, l in ipairs(content) do
       writer:write(l..'\n')
     end
diff --git a/teal/gitsigns/git.tl b/teal/gitsigns/git.tl
index e3d3514..82eb1c4 100644
--- a/teal/gitsigns/git.tl
+++ b/teal/gitsigns/git.tl
@@ -203,7 +203,6 @@ function M.run_diff(staged: string, text: {string}, diff_algo: string): cb_funct
         '--diff-algorithm='..diff_algo,
         '--patch-with-raw',
         '--unified=0',
-        '--ignore-space-at-eol', -- On windows 'staged' has \r\n instead of \n
         staged,
         '-'
       },
```

However, I don't know how to fix the print issue.

Thank you.

**Comment by lewis6991** [comment]
You could try wrapping the `print` with `vim.schedule`:

```lua
vim.schedule(function()
  print(...)
end)
```

**Comment by Acelya-9028** [comment]
Yes, this fixes the crash and displays the message correctly.

Here is the final diff:

```diff
diff --git a/teal/gitsigns.tl b/teal/gitsigns.tl
index 17b258b..36ec4b4 100644
--- a/teal/gitsigns.tl
+++ b/teal/gitsigns.tl
@@ -65,7 +65,8 @@ local function dirname(file: string): string
 end
 
 local function write_to_file(file: string, content: {string})
-  with(open(file, 'w'), function(writer: FILE)
+  -- On windows 'w' mode use \r\n instead of \n, see: https://stackoverflow.com/a/43967013
+  with(open(file, 'wb'), function(writer: FILE)
     for _, l in ipairs(content) do
       writer:write(l..'\n')
     end
diff --git a/teal/gitsigns/git.tl b/teal/gitsigns/git.tl
index e3d3514..438212b 100644
--- a/teal/gitsigns/git.tl
+++ b/teal/gitsigns/git.tl
@@ -203,7 +203,6 @@ function M.run_diff(staged: string, text: {string}, diff_algo: string): cb_funct
         '--diff-algorithm='..diff_algo,
         '--patch-with-raw',
         '--unified=0',
-        '--ignore-space-at-eol', -- On windows 'staged' has \r\n instead of \n
         staged,
         '-'
       },
@@ -218,7 +217,9 @@ function M.run_diff(staged: string, text: {string}, diff_algo: string): cb_funct
         end
       end,
       on_stderr = function(_, line: string)
-        print('error: '..line, 'NA', 'run_diff')
+           vim.schedule(function()
+              print('error: ' .. line, 'NA', 'run_diff')
+           end)
       end,
       on_exit = function()
         callback(results)
```

**Comment by lewis6991** [comment]
Do you want me to apply this again or do you want another stab at the PR yourself? I don't mind, I just feel a bit guilty committing and taking credit for other peoples work as the change goes under my name 😝.

**Comment by Acelya-9028** [comment]
I can try, `git config --global core.autocrlf input` is supposed to convert my hideous `\r\n` xD. As long as the problem is fixed, I'm happy :p

**Comment by Acelya-9028** [comment]
Fixed https://github.com/lewis6991/gitsigns.nvim/pull/70.
