### ISSUE TITLE
Can setqflist() consider the changed base?

### ISSUE THREAD

**Issue by delphinus** [lewis6991/gitsigns.nvim#692]
**Is your feature request related to a problem? Please describe.**

`setqflist()` can throw diffs into qflist but the diffs are not changed after I call `change_base()` and `setqflist()` again.

**Describe the solution you'd like**

`setqflist()` should consider the base changed by calling `change_base()`. This is so useful in reviewing PRs, I think.

```vim
" show diffs after HEAD
Gitsigns setqflist
" change the base to main
Gitsigns change_base main true
" show the whole diffs against main
Gitsigns setqflist
```

**Describe alternatives you've considered**

nothing

**Additional context**

vim-fugitive has the similar feature: `Git difftool {revision}`

**Comment by taras-biletskyi** [comment]
This would actually be pretty handy
