### ISSUE TITLE
Add a "ignore-space-change" Toggle switch

### ISSUE THREAD

**Issue by phgz** [lewis6991/gitsigns.nvim#696]
Sometimes, I wrap code around a function or conditional, and then apply indentation. The diff marks and preview show that all the block has been modified, and that does not help me when I want to know if something has been changed inside that block or not.

Solution:
Add a toggle option to switch between regular and "ignore-space-change" modes.

Alternatives:
At the moment, I simple do a "git diff --ignore-space-change" on the command line to have a better view of non-space changes.

I can try a PR if I'm given hints for directions!

**Comment by lewis6991** [comment]
We should make sure to inherit any whitespace settings in `'diffopt'`. We already do this for `algorithm`, `linematch` and `indent heuristic`

**Comment by phgz** [comment]
Ok I see, it should not be too complicated. I will start when I have time, thanks!
