### ISSUE TITLE
`blame_line` doesn't display blame info if used with property `full = true`

### ISSUE THREAD

**Issue by heygarrett** [lewis6991/gitsigns.nvim#697]
### Description

```lua
vim.api.nvim_create_user_command(
	"Blame",
	function() gitsigns.blame_line({ full = true }) end,
	{}
)
```

Setting property `full = true` causes the `blame_line` function to seemingly not do anything.

### Neovim version

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"  Run :checkhealth for more info

### Operating system and version

macOS 13.1

### Expected behavior

A floating window would display the blame info.

### Actual behavior

The floating window doesn't appear. Nothing seems to happen.

Though with the minimal config I get this error:

```
Error executing luv callback:
...vim/site/pack/test/start/gitsigns/lua/gitsigns/async.lua:64: The coroutine failed with this message: .../nvim/site/pack/test/start/gitsigns/lua/gitsigns/git.lua:364: bad argument #2 to 'iconv' (expect
ed string)
stack traceback:
        [C]: in function 'iconv'
        .../nvim/site/pack/test/start/gitsigns/lua/gitsigns/git.lua:364: in function 'get_show_text'
        ...m/site/pack/test/start/gitsigns/lua/gitsigns/actions.lua:818: in function 'get_blame_hunk'
        ...m/site/pack/test/start/gitsigns/lua/gitsigns/actions.lua:904: in function <...m/site/pack/test/start/gitsigns/lua/gitsigns/actions.lua:869>
stack traceback:
        [C]: in function 'error'
        ...vim/site/pack/test/start/gitsigns/lua/gitsigns/async.lua:64: in function 'callback'
        .../nvim/site/pack/test/start/gitsigns/lua/gitsigns/git.lua:204: in function 'callback'
        ...ite/pack/test/start/gitsigns/lua/gitsigns/subprocess.lua:74: in function <...ite/pack/test/start/gitsigns/lua/gitsigns/subprocess.lua:59>
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. `:lua require("gitsigns").blame_line({ full = true })`

### Gitsigns debug messages

signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --version
derive: Deriving GitSignsAdd from DiffAdd
derive: Deriving GitSignsChange from DiffChange
derive: Deriving GitSignsDelete from DiffDelete
derive: Deriving GitSignsAddNr from GitSignsAdd
derive: Deriving GitSignsChangeNr from GitSignsChange
derive: Deriving GitSignsDeleteNr from GitSignsDelete
derive: Deriving GitSignsAddLn from DiffAdd
derive: Deriving GitSignsChangeLn from DiffChange
derive: Deriving GitSignsStagedAdd from GitSignsAdd
derive: Deriving GitSignsStagedChange from GitSignsChange
derive: Deriving GitSignsStagedDelete from GitSignsDelete
derive: Deriving GitSignsStagedAddNr from GitSignsAddNr
derive: Deriving GitSignsStagedChangeNr from GitSignsChangeNr
derive: Deriving GitSignsStagedDeleteNr from GitSignsDeleteNr
derive: Deriving GitSignsStagedAddLn from GitSignsAddLn
derive: Deriving GitSignsStagedChangeLn from GitSignsChangeLn
derive: Deriving GitSignsAddPreview from DiffAdd
derive: Deriving GitSignsDeletePreview from DiffDelete
derive: Deriving GitSignsCurrentLineBlame from NonText
derive: Deriving GitSignsAddInline from TermCursor
derive: Deriving GitSignsDeleteInline from TermCursor
derive: Deriving GitSignsChangeInline from TermCursor
derive: Deriving GitSignsAddLnInline from GitSignsAddInline
derive: Deriving GitSignsChangeLnInline from GitSignsChangeInline
derive: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
derive: Deriving GitSignsAddLnVirtLn from GitSignsAddLn
derive: Deriving GitSignsChangeVirtLn from GitSignsChangeLn
derive: Deriving GitSignsDeleteVirtLn from DiffDelete
derive: Deriving GitSignsAddLnVirtLnInLine from GitSignsAddLnInline
derive: Deriving GitSignsChangeVirtLnInLine from GitSignsChangeLnInline
derive: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
attach(1): Attaching (trigger=setup)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
new: Not in git repo
attach(1): Empty git obj
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
attach(6): Attaching (trigger=BufRead)
run_job: git --no-pager --literal-pathspecs config user.name
run_job: git --no-pager --literal-pathspecs rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git -c core.quotepath=off ls-files --stage --others --exclude-standard --eol /Users/garrett/.config/nvim/lua/settings/session
s.lua
watch_gitdir(6): Watching git dir
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git show :0:nvim/lua/settings/sessions.lua
update(6): updates: 1, jobs: 8
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git blame --contents - -L 32,+1 --line-porcelain /Users/garrett/.config/nvim/lua/settings/sessions.lua
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git blame --contents - -L 32,+1 --line-porcelain /Users/garrett/.config/nvim/lua/settings/sessions.lua
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git show -s --format=%B 28b8867eb95fbaf59e826ecf32a2e070c149a246
run_job: git --no-pager --literal-pathspecs --git-dir /Users/garrett/.config/.git show 57a2e9eca4bf4aef177e1db741f62e5d4137d70d:nvim/lua/settings/sessions.lua
: Running action 'debug_messages' with arguments {}
: Running action 'debug_messages' with arguments {}

**Comment by hermitmaster** [comment]
Seeing the same thing here. I had to pin to commit 683187285385a0dde6c62e2e6b16e325effdcf04 to restore blame functionality.
