### ISSUE TITLE
Allow to centralize cursor after navigating hunks

### ISSUE THREAD

**Issue by lucassperez** [lewis6991/gitsigns.nvim#699]
First of all, great job on making such a nice plugin!

And about my idea, I think it would be nice to put the cursor in the middle of the screen after navigating through hunks, just like the standard `zz` command in vim. I tried to make both these remaps with no avail:

```lua
vim.keymap.set('n', '[c', ':Gitsigns prev_hunk<CR>zz')
vim.keymap.set('n', '[c', ':lua require("gitsigns").prev_hunk()<CR>zz')
```

Maybe the `prev_hunk` and `next_hunk` functions could accept an option like "centralize" that would act like a `zz` after the navigation. Them we could have a mapping like this, easily combining all the options:

```lua
local gitsigns = require('gitsigns')
-- ...
vim.keymap.set('n', '[C', function() gitsigns.prev_hunk({ wrap = false, preview = true, centralize = true}) end)
```

I have also tried a remap just like the first one, but with `O` instead of `zz`, and it actually did the "O" action before navigating through hunks. Maybe the navigation function is async and the `zz` was performed on the line before moving the cursor, so thats why it did not work. I tried some clunky `:sleep 100m` before the `zz` in the keymaps, and then it worked, but it does not work very well with the `preview` option set to true, not to mention that adding this sleep kinda makes it feels laggy and it was more of a test then a solution.

Thanks a bunch again for all your work! (:

**Comment by seblj** [comment]
Something like this could work as an okay workaround I think

```lua
vim.keymap.set("n", "[C", function()
    gitsigns.prev_hunk({...})
    vim.schedule(function()
        vim.api.nvim_feedkeys("zz", "n", false)
    end)
end)
```

**Comment by lucassperez** [comment]
Yeah, this actually looks pretty good. I've used here and it seems to just work.

**Comment by lewis6991** [comment]
Solution above seems good enough to me.

**Comment by Iskustvo** [comment]
Hi everyone,
[Proposed workaround](https://github.com/lewis6991/gitsigns.nvim/issues/699#issuecomment-1364753473) doesn't work for me (also with newer interfaces - `nav_hunk("prev")`).
Are there still no plans to support something like this natively?

I'd also appreciate other workarounds (other than random sleep interval :smile:) that would force these commands to execute synchronously, if anyone knows them.

**Comment by Iskustvo** [comment]
Looks like new API comes with `then` callback which will be executed right after the command, so if anyone still needs this, it can cleanly be achieved with:
```lua
gitsigns.nav_hunk("next", {...}, function() vim.fn.feedkeys("zz", "n") end)
```
