### ISSUE TITLE
attempt to index local 'cfg' error

### ISSUE THREAD

**Issue by katsika** [lewis6991/gitsigns.nvim#7]
Hey,
installed with (version 3581f2d):
```
use {
  'lewis6991/gitsigns.nvim',
  branch = 'main',
  config = [[require('gitsigns').setup()]
}
```
and getting
```
E5108: Error executing lua ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:717: attempt to index local 'cfg' (a nil value)
```

on startup.

Same happens without `config` key and initialised with `:lua require('gitsigns').setup()`.

BTW, https://github.com/lewis6991/gitsigns.nvim/commit/5d3f324749b57ef49c46c7a94b4ed67a3d4474eb might be irrelevant due to https://github.com/wbthomason/packer.nvim/commit/a68b21be60a08a2ea1eb6c8964891d8611719d85.

**Comment by OkanEsen** [comment]
Try to call it via: `lua require('gitsigns').setup {}`

The setup function should still be updated like this though:

``` lua
local function setup(cfg)
  cfg = cfg or {}

  if cfg.keymaps then
    default_config.keymaps = {}
  end

  config = vim.tbl_deep_extend("keep", cfg, default_config)
```

**Comment by lewis6991** [comment]
Sorry about that. I desperately need to add some regression tests to avoid silly issues like these.
