### ISSUE TITLE
How to set this highlighting?

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/gitsigns.nvim#700]
I have a colorscheme that can show this beautiful inline-change effect:

<img src="https://user-images.githubusercontent.com/24765272/209944017-f8c8796c-4306-4d31-9019-a8b711f6e9fd.png" width="400">

so I want to mimic the same for another one, here it's the current result:

<img src="https://user-images.githubusercontent.com/24765272/209944161-51f7d2af-8ec6-4aee-9a90-2fda95a2bda9.png" width="400">

I have tried to use this `GitSignsChangeInline guifg=#b9fbc0`, and I got:

<img src="https://user-images.githubusercontent.com/24765272/209944316-d1cc9f4e-198f-4885-841f-fb50353c36a9.png" width="400">

But how to get those brown coloring? I know that it's the `Normal guifg` color and there seems to be some highlight group linking to `TermCursor`, so that `guifg` now used as the `guibg` for some unknown highlight group. Really need your help! (I did saw there is a gitter link but I didn't have a account, and I don't like many people getting notified for this tiny coloring issue, so posting here. It would be great if you could create a GitHub Discussion or something...)

**Comment by lewis6991** [comment]
I think you need `GitSignsDeleteInline`

**Comment by nyngwang** [comment]
It seems that `GitSignsDeleteInline` doesn't work. Maybe `toggle_deleted` could provide more clues on this problem...

<img src="https://user-images.githubusercontent.com/24765272/209967059-7d0ec3e8-b298-497a-bfc5-170454424548.png" width="400">

**Comment by nyngwang** [comment]
And if I call `:hi Normal guibg=NONE` then I got the effect I want:

<img src="https://user-images.githubusercontent.com/24765272/209990601-c9644065-3cb7-47a2-86e0-9cb2cc5dd036.png" width="400">

**Comment by nyngwang** [comment]
Aha! I just resolved it :) Thanks for your help.
