### ISSUE TITLE
Textobject's behaviour if not in hunk

### ISSUE THREAD

**Issue by XXiaoA** [lewis6991/gitsigns.nvim#702]
### Description

I used `map({'o', 'x'}, 'ih', ':<C-U>Gitsigns select_hunk<CR>')` which from readme to create textobject. It's useful but when we not in a hunk and then press `cih`, we will enter insert mode, it's a different behaviour from built-in textobject, which don't enter insert mode.(try `ci"` in a line with "quotes)

### Neovim version

Nightly

### Operating system and version

Arch Linux

### Expected behavior

Do nothing, like the built-in textobject

### Actual behavior

Enter insert mode

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.keymap.set({'o', 'x'}, 'ih', ':<C-U>Gitsigns select_hunk<CR>')
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. press `cih` outside a hunk

### Gitsigns debug messages

None

**Comment by lewis6991** [comment]
I'm not sure if this can be considered a bug.

- `ciw`, `cw` puts you in insert mode on blank lines
- `cip` puts you in insert mode on blank lines
- `cis` puts you in insert mode on blank lines
- `ci'` does just looks for the last and next `'` even if the cursor is not in a quoted string.
