### ISSUE TITLE
Wrong text symbol shown in signs column of some buffers

### ISSUE THREAD

**Issue by l00sed** [lewis6991/gitsigns.nvim#703]
### Description

For some reason my specified git column symbol isn't being used in some buffers--- specifically, I'm noticing it's wrong in `.js`/`.jsx` files?
![image](https://user-images.githubusercontent.com/23065167/210161354-3ee29224-6ff6-4acd-a6fa-eb9dd76d23ea.png)

Here's how I'm expecting it to look (screenshot from editing a `.lua` file in another buffer):
![image](https://user-images.githubusercontent.com/23065167/210161361-3334e642-6b96-4665-b16d-f420fff3820f.png)

### Neovim version

0.9.0-dev

### Operating system and version

Linux - Ubuntu 20.04

### Expected behavior

Expecting the set git-column character to be consistent across all buffers.

### Actual behavior

Seeing a different character used by some buffers.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  signs = {
    add          = { hl='GitSignsAdd'   , text='┃', numhl='GitSignsAddNr'   , linehl='GitSignsAddLn'    },
    change       = { hl='GitSignsChange', text='┃', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn' },
    delete       = { hl='GitSignsDelete', text='┃', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn' },
    topdelete    = { hl='GitSignsDelete', text='━', numhl='GitSignsDeleteNr', linehl='GitSignsDeleteLn' },
    changedelete = { hl='GitSignsChange', text='╋', numhl='GitSignsChangeNr', linehl='GitSignsChangeLn' },
  },
  on_attach = function(bufnr)
    local gs = package.loaded.gitsigns
  end
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. Open a `.js` file in neovim
2. Verify sign column using correct character

### Gitsigns debug messages

signs.init: Using vimfn signs
run_job: git --no-pager --literal-pathspecs --ver
sion
fn: Highlight GitSignsAdd is already defined
fn: Highlight GitSignsChange is already defined
fn: Highlight GitSignsDelete is already defined
derive: Deriving GitSignsAddNr from GitSignsAdd
derive: Deriving GitSignsChangeNr from GitSignsCh
ange
derive: Deriving GitSignsDeleteNr from GitSignsDe
lete
derive: Deriving GitSignsAddLn from DiffAdd
derive: Deriving GitSignsChangeLn from DiffChange

derive: Deriving GitSignsStagedAdd from GitSignsA
dd
derive: Deriving GitSignsStagedChange from GitSig
nsChange
derive: Deriving GitSignsStagedDelete from GitSig
nsDelete
derive: Deriving GitSignsStagedAddNr from GitSign
sAddNr
derive: Deriving GitSignsStagedChangeNr from GitS
ignsChangeNr
derive: Deriving GitSignsStagedDeleteNr from GitS
ignsDeleteNr

**Comment by lewis6991** [comment]
This is the sign used for untracked files. It's an intended feature.

**Comment by l00sed** [comment]
Thanks, I just took another look at the example config and realized I hadn't configured that highlight character. This is absolutely what's going on. Sorry for the noise.
