### ISSUE TITLE
The float window of `blame_line` will be moved when move cursor in it

### ISSUE THREAD

**Issue by YangEfei** [lewis6991/gitsigns.nvim#708]
### Description

Hi there.
I was trying to call `blame_line()` and move my cursor to the float window of it. And then I moved my cursor by typing `j` and `k` in it, and strange things happened, the float window moved right when the cursor move.
I think it was caused by some updates since `683187285385a0dde6c62e2e6b16e325effdcf04`, because it worked well before.

### Neovim version

v0.8.0

### Operating system and version

Linux

### Actual behavior

My cursor is on the top of the float window
![image](https://user-images.githubusercontent.com/54932475/210568620-2b1e1d59-c911-4cfd-a7cf-5fca1a7eabe9.png)

And when I move it down, the window will move to right...
![image](https://user-images.githubusercontent.com/54932475/210568724-964ce7e9-122d-4a26-9d5f-59278ebee2f9.png)

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

As mention above.

**Comment by lewis6991** [comment]
This was an intentional change done in: https://github.com/lewis6991/gitsigns.nvim/pull/705

Why do you consider this a bug?
