### ISSUE TITLE
Show signs in netrw for files

### ISSUE THREAD

**Issue by WuerfelDev** [lewis6991/gitsigns.nvim#711]
**Is your feature request related to a problem? Please describe.**
In netrw it is not possible to see files that were modified/created staged/unstaged

**Describe the solution you'd like**
The solution is to show git signs in netrw 

**Describe alternatives you've considered**
well `:Git status` but it's not the same as 

**Additional context**
Not sure how complicated it is to integrate with netrw

**Comment by lewis6991** [comment]
Sorry this isn't something I'm interested in.
