### ISSUE TITLE
GitSignsStagedxxx highlights do not working

### ISSUE THREAD

**Issue by rockyzhang24** [lewis6991/gitsigns.nvim#716]
### Description

After the newest commit (https://github.com/lewis6991/gitsigns.nvim/commit/e272fcfc99003caada48bbcea7a6f95966799ceb) to refactor the highlight groups, all `GitSignsStagedxxx` highlights work abnormally. They become white instead of the fading colors.

### Neovim version

NVIM v0.9.0-dev-663+ga09a0b6eb (built from the latest commit)

### Operating system and version

macOS 13.1

### Actual behavior

The colors of the signs for staged lines are white. They should be the colors with fading.

Thank you very much.

**Comment by gegoune** [comment]
https://github.com/lewis6991/gitsigns.nvim/issues/453#issuecomment-1377417220

**Comment by rockyzhang24** [comment]
@gegoune I know it. I mean the GitStaged related highlight groups (e.g., GitSignsStagedAdd), not the other normal ones. Even though you configure them, they still cannot come into effect. You can try to define GitSignsStagedAdd to test it. BTW, don't forget to set `_signs_staged_enable` to `true`.

**Comment by lewis6991** [comment]
Can reproduce. Will fix asap.

**Comment by lewis6991** [comment]
Should be fixed in 414aa7bc08f688bc5b10c0a70d78c39008fda0ef

**Comment by vince6794** [comment]
Is this confirmed to be fixed ?
I'm on the latest commit : f29f0b2

![image](https://user-images.githubusercontent.com/31125013/218110314-11502857-99fc-4fb7-b880-f7b2432c7cf2.png)

May I do anything to help?

**Comment by lewis6991** [comment]
Yes, this should be fixed.

**Comment by vince6794** [comment]
My bad, it was a misconfiguration, I confirm it's fixed

> The screenshot doesn't provide any information. Why did you include it?

I was showing the configuration of the highlight group and the problem of the signs column symbols appearing white

For anyone  that encounters this problem with a transparent background configuration, I solved manually setting the default value for the highlight group : 

```
local function get_color(group, attr)
    local fn = vim.fn
    return fn.synIDattr(fn.synIDtrans(fn.hlID(group)), attr)
end

vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = get_color("GitSignsAdd", "fg"), bg = color.base00 })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = get_color("GitSignsChange", "fg"), bg = color.base00 })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = get_color("GitSignsDelete", "fg"), bg = color.base00 })
vim.api.nvim_set_hl(0, "GitSignsChangeDelete", { fg = get_color("GitSignsChangeDelete", "fg"), bg = color.base00 })

```
