### ISSUE TITLE
expose api function to get sign for a certain line

### ISSUE THREAD

**Issue by rebelot** [lewis6991/gitsigns.nvim#717]
With the introduction of `'statuscolumn'` it would be great if there was a function like `get_sign(v:lnum) -> kind, glyph` able to fetch the symbol and kind for a specific line. This could be used, for example, to customise the position of signs before/after line numbers, i.e. diagnostics on the left and gitsigns on the right

**Comment by lewis6991** [comment]
I'm not too sure about adding this kind of API. Signs are really low level. You can already do `get_hunks` which will return a list of hunks you can use to deduce the signs.

**Comment by rebelot** [comment]
Yes it's possible to deduce them via `get_hunks`, I felt a bit unsure how to handle the data structure tho.
