### ISSUE TITLE
The Neovim process has crashed when open .xm file

### ISSUE THREAD

**Issue by peter-lyr** [lewis6991/gitsigns.nvim#722]
### Description

The Neovim process has crashed when open `.xm` file.
It's ok if I rename the `.xm` file to `.txt`.

### Neovim version

0.8.0, 0.8.2

### Operating system and version

Windows 10

### Expected behavior

`.xm` file opened successfully and I can edit it.

### Actual behavior

The Neovim process has crashed.
![image](https://user-images.githubusercontent.com/55801796/212283407-82727148-a043-4690-bbab-55715bdd62b4.png)

### Minimal config

```Lua
local status, gitsigns = pcall(require, "gitsigns")
if not status then
  return
end

-- 打开.xm文件意外退出是以下导致的
gitsigns.setup({})
```

### Steps to reproduce

1. unzip `nvim-win64` to my %home%.
2. clone `https://github.com/lewis6991/gitsigns.nvim` to `share\nvim\runtime\pack\packer\start`
3. double click `bin\nvim-qt.exe` to open it.
4. drag my `app.xm` file to it.
5. it crashed.

![image](https://user-images.githubusercontent.com/55801796/212284601-58cdc4fa-a1ff-459e-925e-b44f01ef0f81.png)
![image](https://user-images.githubusercontent.com/55801796/212284754-2f0325e5-60ce-45bb-819b-46a469a01c21.png)

### Gitsigns debug messages

I can't see any debug messages.

**Comment by lewis6991** [comment]
Sorry, there's no information here I can use to look into anything. If Neovim crashes, it is usually a problem with Neovim itself and with such cases a backtrace is required to investigate anything.

**Comment by peter-lyr** [comment]
Thanks, Neovim crashes if the `.xm` file is in a git working directory. But when I copy the same `.xm` file to somewhere else, it will not crash.

**Comment by lewis6991** [comment]
Can you share a minimal `.xm` files that crashes?

**Comment by peter-lyr** [comment]
It woud crash even though I delete all lines in the file named `.xm`. 
[app.zip](https://github.com/lewis6991/gitsigns.nvim/files/10412571/app.zip)

**Comment by peter-lyr** [comment]
It woud crash even though I delete all lines in the file named `app.xm`.
[app.zip](https://github.com/lewis6991/gitsigns.nvim/files/10412760/app.zip)

**Comment by lewis6991** [comment]
Ok, it crashed for me too.

It is having trouble because the encoding of the file is `utf-16le`.

**Comment by lewis6991** [comment]
I've raised https://github.com/neovim/neovim/pull/21924 to re-implement iconv to handle `utf-16` better.

**Comment by ianhomer** [comment]
Thank you. That stabilises it for me. No crash on opening up utf-16le

**Comment by peter-lyr** [comment]
Thanks! It's OK for me too.
