### ISSUE TITLE
Add hunk preview in a split layout? (not only unified)

### ISSUE THREAD

**Issue by bew** [lewis6991/gitsigns.nvim#723]
**Is your feature request related to a problem? Please describe.**
The current hunk preview is nice and simple, but a bit too simple for my taste.
I find it hard to make sense of what the hunk in question looked like before the change.

**Describe the solution you'd like**
Something similar to [vgit's hunk preview](https://github.com/tanvirtin/vgit.nvim):
![](https://user-images.githubusercontent.com/25164326/149684229-6fc1422a-3db2-4e17-88f9-eb5897ca5ddc.png)

(The summary of added/removed lines would be nice as well!)

Would be nice to be able to toggle between unified/split layout when the view is opened

**Describe alternatives you've considered**
Open a full file diff (but I'd prefer to peek at a single hunk).
Using git diff (I have configured [delta](https://github.com/dandavison/delta) for split view) outside of nvim.
Try to make sense of the unified view.

**Comment by lewis6991** [comment]
There's quite a lot of UI work involved to implement something like this, and I don't really think it's worth the complexity.

If you can think of a good way to implement this simply, then we can look into it.

**Comment by lewis6991** [comment]
Closing as this is too complex. Will reconsider if core adds splits in floating windows.
