### ISSUE TITLE
Unable to assignment custom keymaps

### ISSUE THREAD

**Issue by AlphabetsAlphabets** [lewis6991/gitsigns.nvim#734]
### Description

The issue is the title. I have tried using the snippet shown in the README [this](https://github.com/lewis6991/gitsigns.nvim#keymaps) one and it just doesn't work.

I dug around the docs and found this
```
map("n", "[c", "<cmd>lua require'gitsigns'.next_hunk()<CR>", {})
```

I want a preview window to open by default so I made this change.

```
map("n", "[c", "<cmd>lua require'gitsigns'.next_hunk({preview = True})<CR>", {})
```
This works fine, but the preview window doesn't open. I've tried other methods but they all don't work. Such as using `:call` to see if I can find a function by gitsigns. I went through the whole list but couldn't tell which belonged to gitsigns.

### Neovim version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

LSB Version:    n/a Distributor ID: ManjaroLinux Description:    Manjaro Linux Release:        22.0.1 Codename:       Sikaris

### Expected behavior

I go from hunk to hunk and a preview window opens.

### Actual behavior

I can go from hunk to hunk but no preview window.

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  on_attach = function(bufnr)
    local gs = package.loaded.gitsigns

    local function map(mode, l, r, opts)
      opts = opts or {}
      opts.buffer = bufnr
      vim.keymap.set(mode, l, r, opts)
    end

    -- Navigation
    map('n', ']c', function()
      if vim.wo.diff then return ']c' end
      vim.schedule(function() gs.next_hunk() end)
      return '<Ignore>'
    end, {expr=true})

    map('n', '[c', function()
      if vim.wo.diff then return '[c' end
      vim.schedule(function() gs.prev_hunk() end)
      return '<Ignore>'
    end, {expr=true})

    -- Actions
    map({'n', 'v'}, '<leader>hs', ':Gitsigns stage_hunk<CR>')
    map({'n', 'v'}, '<leader>hr', ':Gitsigns reset_hunk<CR>')
    map('n', '<leader>hS', gs.stage_buffer)
    map('n', '<leader>hu', gs.undo_stage_hunk)
    map('n', '<leader>hR', gs.reset_buffer)
    map('n', '<leader>hp', gs.preview_hunk)
    map('n', '<leader>hb', function() gs.blame_line{full=true} end)
    map('n', '<leader>tb', gs.toggle_current_line_blame)
    map('n', '<leader>hd', gs.diffthis)
    map('n', '<leader>hD', function() gs.diffthis('~') end)
    map('n', '<leader>td', gs.toggle_deleted)

    -- Text object
    map({'o', 'x'}, 'ih', ':<C-U>Gitsigns select_hunk<CR>')
  end
}
```

### Steps to reproduce

Sorry I'm not sure how to minimal vimrc works. I'll update it as needed.

1. Install GitSigns
2. Copy and paste the [snippet](https://github.com/lewis6991/gitsigns.nvim#keymaps) provided
3. Try any of the keybindings.

**Comment by lewis6991** [comment]
> ```
> map("n", "[c", "<cmd>lua require'gitsigns'.next_hunk({preview = True})<CR>", {})
> ```

This is wrong. `True` is not valid Lua, it should be:

```lua
map("n", "[c", "<cmd>lua require'gitsigns'.next_hunk({preview = true})<CR>", {})
```

**Comment by AlphabetsAlphabets** [comment]
Could you tell me why I'm unable to setup keymaps the normal way?

**Comment by lewis6991** [comment]
What is the normal way to you?

**Comment by AlphabetsAlphabets** [comment]
> What is the normal way to you?

In the way shown by the snippet shown in the README, are there equivalent functions for vimscript? Or another way to set keymaps aside from this?

```lua
map("n", "[c", "<cmd>lua require'gitsigns'.next_hunk({preview = true})<CR>", {})
```

**Comment by lewis6991** [comment]
> In the way shown by the snippet shown in the README

What is wrong with the README, it should work just fine. You haven't provided any information as to why it doesn't work.

> are there equivalent functions for vimscript?

No
