### ISSUE TITLE
Show blame info line by line in split window

### ISSUE THREAD

**Issue by leaxoy** [lewis6991/gitsigns.nvim#735]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/8556349/216560157-ea6a44c1-4f3d-4fb1-8f20-7b405b8af74b.png">

It's a awesome feature to show blame info line by line in split window like vscode does.

**Comment by lewis6991** [comment]
This is one of the remaining things I still use vim-fugitive for.

I do want to add this to Gitsigns, but it will be a lot of work.

**Comment by lewis6991** [comment]
See #1038

**Comment by leaxoy** [comment]
> See #1038

@lewis6991  Great work! 👍👍👍
