### ISSUE TITLE
Failed to handle fugitive buffer if fugitive is lazy loaded

### ISSUE THREAD

**Issue by ray-x** [lewis6991/gitsigns.nvim#752]
### Description

It is related to session restore and lazy loading fugitive.

1) have session enabled so the last session will be autoload
2) fugitive will be lazyloaded with command `Git`, `G`, `Gvdiff`....
2) leave fugitive buffer open and `:qa` nvim
3) reopen nvim and auto load session, this will reopen an empty fugitive buffer
4) see errors

The root cause is somewhere here:
```lua
  if vim.fn.exists('*FugitiveReal') == 0 then
    dprint('Fugitive not installed')
    return
  end
```
and
```
path = uv.fs_realpath(path)
```
As fugitive is lazy load,  parse_fugitive_uri returns nil and fs_realpath failed.

I am not sure why checking `fugitive` installed or not if the buffer URI is `fugitive:///file/path/.git/....`

Should be an easy fix to skip plugin check or check path before fs_realpath. 

### Neovim version

NVIM v0.9.0-dev-1024+gd1b34b745 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/cc -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wno-unused-result -Wimplicit-fallthrough -Wvla -fno-common -fdiagnostics-color=auto -fstack-protector-strong -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DMIN_LOG_LEVEL=2 -DNVIM_UNIBI_HAS_VAR_FROM -"$VIM/sysinit.vim"   fall-back for $VIM: "/usr/local/share/nvim"  Run :checkhealth for more info

### Operating system and version

archlinux/MacOs

### Expected behavior

Should not print error messages

### Actual behavior

```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...ay/.local/share/nvim/lazy/gitsigns.nvim/l
ua/gitsigns.lua:125: bad argument #1 to 'fs_realpath' (string expected, got nil)
stack traceback:
        [C]: in function 'fs_realpath'
        ...ay/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:125: in function 'get_buf_path'
        ...ay/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:247: in function 'fn'
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:76: in function 'attach_throttled'
        ...ay/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:359: in function 'attach'
        ...ay/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:454: in function <...ay/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:413>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:140: in function <...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:139>
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1) I enabled session autosave and autoload
2) Open fugitive status buffer
3) without close fugitive buffer, quit neovim
4) reopen neovim
5) see errors

**Comment by lewis6991** [comment]
Don't lazy load fugitive. There's no need.

**Comment by ray-x** [comment]
It can be loaded on startup, but there is no guarantee that fugitive will be loaded before gitsigns.

**Comment by lewis6991** [comment]
It doesn't need to. That code in question runs on buffer attach.

**Comment by alextes** [comment]
This has been bothering me a lot. Fixed it by adding fugitive as a dependency of gitsigns. It'd be neat if gitsigns could somehow detect and warn that it wants fugitive to load before gitsigns or not at all.

Thanks for the plugin! 🙏

**Comment by alextes** [comment]
@lewis6991 I'm not trying to lazy load fugitive. Any suggestion for what it means not to lazy load it?

I use lazy.nvim, my config is basically:
```lua
return {
	{
		"tpope/vim-fugitive",
		keys = {
			{ "<leader>gs", "<cmd>vertical Git <cr>", desc = "[G]it [s]tatus" },
			{ "<leader>gc", "<cmd>Git commit --quiet<cr>", desc = "[G]it [s]tatus" },
			{ "<leader>gfp", "<cmd>Git push<cr>", desc = "[G]it [p]ush" },
			{ "<leader>gfP", "<cmd>Git pull<cr>", desc = "[G]it [P]ull" },
		},
	},
	{
		"lewis6991/gitsigns.nvim",
		dependencies = {
			"tpope/vim-fugitive",
		},
		opts = {
			-- See `:help gitsigns.txt`
			-- signs = {
			--   add = { text = '+' },
			--   change = { text = '~' },
			--   delete = { text = '_' },
			--   topdelete = { text = '‾' },
			--   changedelete = { text = '~' },
			-- },
			on_attach = function(bufnr)
				local gs = package.loaded.gitsigns
	
				local function map(mode, l, r, opts)
					opts = opts or {}
					opts.buffer = bufnr
					vim.keymap.set(mode, l, r, opts)
				end
	
				-- Navigation
				map("n", "]c", function()
					if vim.wo.diff then
						return "]c"
					end
					vim.schedule(function()
						gs.next_hunk()
					end)
					return "<Ignore>"
				end, { expr = true })
	
				map("n", "[c", function()
					if vim.wo.diff then
						return "[c"
					end
					vim.schedule(function()
						gs.prev_hunk()
					end)
					return "<Ignore>"
				end, { expr = true })
	
				-- Actions
				map({ "n", "v" }, "<leader>gt", ":Gitsigns stage_hunk<CR>")
				map({ "n", "v" }, "<leader>gr", ":Gitsigns reset_hunk<CR>")
				map({ "n", "v" }, "<leader>ge", ":Gedit<CR>")
				map("n", "<leader>gS", gs.stage_buffer)
				map("n", "<leader>gu", gs.undo_stage_hunk)
				map("n", "<leader>gR", gs.reset_buffer)
				map("n", "<leader>gp", gs.preview_hunk)
				map("n", "<leader>gb", function()
					gs.blame_line({ full = true })
				end)
				map("n", "<leader>tb", gs.toggle_current_line_blame)
				map("n", "<leader>gd", gs.diffthis)
				map("n", "<leader>gD", function()
					gs.diffthis("~")
				end)
				map("n", "[gd", gs.toggle_deleted)
	
				-- Text object
				map({ "o", "x" }, "ih", ":<C-U>Gitsigns select_hunk<CR>")
			end,
		},
	}
}
```

I've had to add the `dependencies = { "tpope/vim-fugitive" }` in there to avoid the error.

**Comment by lewis6991** [comment]
You are lazy loading Fugitive with the `keys` option.

**Comment by alextes** [comment]
Thank you. Had no idea "keys" in lazy.nvim was "turn on lazy load and use these keys to load".

Keep up the great work 💛
