### ISSUE TITLE
:Gitsigns diffthis

### ISSUE THREAD

**Issue by I-Own-You** [lewis6991/gitsigns.nvim#769]
### Description

1. i have a buffer with some modifications 
2. i open it
3. i type :Gitsigns diffthis
4. it opens in the right my modified buffer and in the left the unmodified buffer
5. i make some modifications on modificated buffer in the right, save, then close
6. i go to my buffer, and yes, the modifications are saved
7. but now i stage the buffer with git add <buffer_name>
8. i again open my staged buffer
9. i type :Gitsigns diffthis
10. it opens in the right and left the same buffer because its stage (everything fine)
11. i make some changes to right buffer as i should
12. in the left buffer chanes appeared
13. but they are shown as new hunks
14. i also checked the index tree with git status, and it wasnt modified, i had the same file in staged area, but in modified area appeared the file, but as gitsigns.txt says : 
                                                                                    "If {base} is the index, then the opened buffer is editable and
                                                                                     any written changes will update the index accordingly."

Am i lacking some knowledge about git or is it a bug or it is intended to only change in modified area ?

### Neovim version

NVIM v0.9.0-dev

### Operating system and version

Ubuntu 22.04.2 LTS (Xubuntu)

### Expected behavior

when i make some changes in the right buffer that opens with diffthis, after saving it, my buffer should stage the new modification i added like with stage_hunk

### Actual behavior

it only changes the modified area

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

gitsigns.setup {
    debug_mode = true,
    signs = {
        add = { hl = "GitSignsAdd", text = "▎", numhl = "GitSignsAddNr", linehl = "GitSignsAddLn" },
        change = { hl = "GitSignsChange", text = "▎", numhl = "GitSignsChangeNr", linehl = "GitSignsChangeLn" },
        delete = { hl = "GitSignsDelete", text = "契", numhl = "GitSignsDeleteNr", linehl = "GitSignsDeleteLn" },
        topdelete = { hl = "GitSignsDelete", text = "契", numhl = "GitSignsDeleteNr", linehl = "GitSignsDeleteLn" },
        changedelete = { hl = "GitSignsChange", text = "▎", numhl = "GitSignsChangeNr", linehl = "GitSignsChangeLn" },
    },
    signcolumn = true, -- Toggle with `:Gitsigns toggle_signs`
    numhl = true, -- Toggle with `:Gitsigns toggle_numhl`
    linehl = false, -- Toggle with `:Gitsigns toggle_linehl`
    word_diff = false, -- Toggle with `:Gitsigns toggle_word_diff`
    watch_gitdir = {
        interval = 1000,
        follow_files = true,
    },
    attach_to_untracked = true,
    current_line_blame = true, -- Toggle with `:Gitsigns toggle_current_line_blame`
    current_line_blame_opts = {
        virt_text = true,
        virt_text_pos = "eol", -- 'eol' | 'overlay' | 'right_align'
        delay = 100,
        ignore_whitespace = false,
    },
    current_line_blame_formatter_opts = {
        -- relative_time = false,
    },
    sign_priority = 6,
    update_debounce = 100,
    status_formatter = nil, -- Use default
    max_file_length = 40000,
    preview_config = {
        -- Options passed to nvim_open_win
        border = "single",
        style = "minimal",
        relative = "cursor",
        row = 0,
        col = 1,
    },
    yadm = {
        enable = false,
    },
}
```

### Steps to reproduce

1. make a modification in a buffer
2. stage it
3. open it
4. diffthis on the staged buffer
5. make some changes in the right buffer
6. see that modifications appeared as unstaged hunks
7. the staged area didnt update it, only the modified one

**Comment by lewis6991** [comment]
Did you save the buffer?

**Comment by I-Own-You** [comment]
the changes appeared on the left, so yes, i saved

**Comment by I-Own-You** [comment]
> Did you save the buffer?

**Comment by lewis6991** [comment]
The reproduction steps are too vague. Please provide more exact instructions. E.g. "stage it" is ambiguous, how **exactly** did you stage it?

**Comment by I-Own-You** [comment]
<h2> Here is a video, so you could understand what i am doing <h2>

https://user-images.githubusercontent.com/91146968/225310933-fb24a907-1f1f-4794-95a5-37290c0be3b1.mp4

**Comment by lewis6991** [comment]
I did not ask for a video. I don't want to waste time (nor do I have time) trying to figure out other peoples issues. Please just provide basic reproduction steps.
