### ISSUE TITLE
Attach onto telescope's git previews.

### ISSUE THREAD

**Issue by zoriya** [lewis6991/gitsigns.nvim#770]
**Is your feature request related to a problem? Please describe.**
I often use Telescope's git panels and they use the git diff default syntax highlight with the +- symbols and so on.

**Describe the solution you'd like**
It would be nice to use this plugin to instead add sign columns in the preview buffer and use a correct syntax highlight for the file.
Previews affected by this are `git_status`, `git_commits`, `git_bcommits`, and`git_stash`.
Using the correct syntax highlight might be a bit hard if all lines are not displayed, I haven't really thought about that in details.

**Describe alternatives you've considered**
Keep the default git diff.

**Comment by lewis6991** [comment]
You need to provide more information. Don't assume people to understand exactly how you use Telescope.

**Comment by zoriya** [comment]
Running `:Telescope git_status`, we get something like this:
![image](https://user-images.githubusercontent.com/32224410/225339636-5a889e16-33de-4731-85f1-827805ab90e0.png)

I would like gitsigns to replace +,- and other symbols with signs.

**Comment by lewis6991** [comment]
They are not proper diffs of two buffers. Gitsigns cannot attach to this format.
