### ISSUE TITLE
Strange empty lines in `lua/gitsigns/config.lua`

### ISSUE THREAD

**Issue by simplepad** [lewis6991/gitsigns.nvim#774]
What is the purpose of these empty lines in `config.lua`?

https://github.com/lewis6991/gitsigns.nvim/blob/ca473e28382f1524aa3d2b6f04bcf54f2e6a64cb/lua/gitsigns/config.lua#L9-L26

and

https://github.com/lewis6991/gitsigns.nvim/blob/ca473e28382f1524aa3d2b6f04bcf54f2e6a64cb/lua/gitsigns/config.lua#L28-L138

**Comment by lewis6991** [comment]
The lua code in Gitsigns is generated by teal which has comments in those areas.
