### ISSUE TITLE
Show staged and unpushed changes

### ISSUE THREAD

**Issue by rolag** [lewis6991/gitsigns.nvim#775]
**Is your feature request related to a problem? Please describe.**
It would be nice if we could also see the changes that are staged but not yet committed, and the changes that have not yet been pushed to the remote branch that the current branch is tracking.

**Describe the solution you'd like**
We could add more signs in an additional sign column:
1) `staged` for changes in `git diff --staged`
2) `unpushed` for changes that have been committed but are not yet pushed to the tracked branch, similar to setting the `base` to `@{upstream}`.

Or alternatively allow the user to configure multiple bases with a custom git diff command.

**Describe alternatives you've considered**
1) staged: It doesn't look like this is possible by changing the `base` option.
2) unpushed: Setting `base = "@{upstream}"` can show unpushed changes but then you can't differentiate between unstaged code and committed code. Setting `base = "HEAD..@{upstream}"` can show unpushed commits but then you can't see unstaged code.

**Comment by ryouiki-tenkai** [comment]
yes, `git diff --staged` is what I need as well

**Comment by no-more-secrets** [comment]
Gitsigns already seems to have support for showing staged changes, but I can't seem to get it to work... is it still experimental?

**Comment by lewis6991** [comment]
Try `_signs_staged_enable = true`.

It should show staged hunks in a dimmer color.

![image](https://github.com/lewis6991/gitsigns.nvim/assets/7904185/af6a3970-c888-47e9-a1bd-e9a93d09e9d4)

**Comment by alex35mil** [comment]
@lewis6991 For some reason, it doesn't work for me. A sign simply disappears after the stage. Is there anything else is required to make it work?

**Comment by no-more-secrets** [comment]
Why does the `_signs_staged_enable` start with an underscore?  To me that would signal that it is not intended to be used publicly in that way, and/or it is experimental?

**Comment by lewis6991** [comment]
Yes, that is correct. It is still experimental and hence is not documented.

**Comment by samerickson** [comment]
@lewis6991 `_signs_staged_enable` works great for me. Thanks so much. This is one of my favorite plugins!

**Comment by justgook** [comment]
is there way to get show info about staged changes also in statusline?

**Comment by lewis6991** [comment]
Resolved with #1039
