### ISSUE TITLE
blame_line throwing error on a specific repo

### ISSUE THREAD

**Issue by jrbenriquez** [lewis6991/gitsigns.nvim#776]
### Description

Hello, whenever I run `blame_line` on this one repo (which happens to be the main repo i'm working on) it throws an error but for other repos it works fine.

```
Error executing luv callback:
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:912: attempt
to index local 'result' (a nil value)
stack traceback:
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:888>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:140: in function 'callback'
        ...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:93: in function <...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:83>
```

This error only occurs with this specific repository, and not with others. I would appreciate some guidance to help me figure out what could be causing this error, or if it is indeed a bug.

Thanks

### Neovim version

0.8.3

### Operating system and version

macOS 12.4

### Expected behavior

Show git blame details properly

### Actual behavior

Throwing out an error

```
Error executing luv callback:
...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:912: attempt
to index local 'result' (a nil value)
stack traceback:
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:888>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:140: in function 'callback'
        ...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:93: in function <...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:83>
 ```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`

### Gitsigns debug messages

(ERROR) ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua(216): Received stderr when running command
'git --git-dir /Users/xxx/Code/xxx/.git blame --contents - -L 36,+1 --line-porcelain /Users/xxx/Code/xxx/django-root/xxx/tests/xxx.py --ign
ore-revs-file /Users/xxx/Code/xxx/.git-blame-ignore-revs':
fatal: invalid object name: e84cabb80

(ERROR) ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/git.lua(216): Received stderr when running command
'git --git-dir /Users/jr/Code/xxx/.git blame --contents - -L 36,+1 --line-porcelain /Users/jr/Code/xxx/django-root/xxx/tests/xxx.py --ign
ore-revs-file /Users/xxx/Code/xxx/.git-blame-ignore-revs':
fatal: invalid object name: e84cabb80

**Comment by jrbenriquez** [comment]
aggh my bad thought this was a git generated file. All good. Learned about the debug messages as well.

Thaaanks!

**Comment by lewis6991** [comment]
No worries.

I'll keep this open so we can improve the error message.
