### ISSUE TITLE
Inherit special colors in `setup_highlights`

### ISSUE THREAD

**Issue by boltlessengineer** [lewis6991/gitsigns.nvim#780]
Currently gitsigns only use fallback color's `foreground` and `background` values after calculating fg/bg factors.
This removes all styles like `underline` and `special` colors.

I prefer red underline for `GitSignsChangedelete` hl group than using special sign texts like `~`.
I can just set hl group with `nvim_set_hl` because then I have to rewrite all codes in `lua/gitsigns/highlight.lua` in my config to handle the `fg_factor` and `bg_factor` values.

Edit: typo

**Comment by lewis6991** [comment]
I think this is resolved now.
