### ISSUE TITLE
Toggle stage hunk

### ISSUE THREAD

**Issue by axieax** [lewis6991/gitsigns.nvim#788]
**Is your feature request related to a problem? Please describe.**

When I accidentally stage the hunk my cursor is under, it's frustrating that I can't use the same keybind / command to toggle the staged status of the hunk. I know that `undo_stage` exists, but it's on a separate keybind, and I couldn't find a way to make a custom mapping which performs one of the actions based on whether the current hunk is staged or not.

**Describe the solution you'd like**

A `hunk_toggle_staged` action which stages the hunk under the cursor if unstaged, and vice versa.

**Describe alternatives you've considered**

Registering a custom command; using the cmdline to find out whether the current line is staged.

**Additional context**

**Comment by hinell** [comment]
It's gonna be tricky to implement...

**Comment by hinell** [comment]
It's gonna be tricky to implement. Git doesn't keep track of hunks staged. It's a pile fo staged hunks of a given file.

**Comment by lewis6991** [comment]
Gitsigns can already track staged hunks if you set ` _signs_staged_enable = true` in `setup()`. It works by running an extra diff against `HEAD` and subtracting the hunks.

**Comment by leiteg** [comment]
@lewis6991 Is there any particular reason for this option to not be documented?

**Comment by lewis6991** [comment]
Because it isn't finished.

**Comment by leiteg** [comment]
Fair enough!

**Comment by lewis6991** [comment]
Done in #1039
