### ISSUE TITLE
Generate permalinks

### ISSUE THREAD

**Issue by aspeddro** [lewis6991/gitsigns.nvim#790]
It would be great if this plugin generates permalinks. Similar to command `GBrowser` in vim-fugitive plugin.

Example: [`https://github.com/lewis6991/gitsigns.nvim/blob/e5edefd9976039f5352e0c900f35206770b33a2d/lua/gitsigns.lua#L7`](https://github.com/lewis6991/gitsigns.nvim/blob/e5edefd9976039f5352e0c900f35206770b33a2d/lua/gitsigns.lua#L7)

**Comment by lewis6991** [comment]
Please use https://github.com/ruifm/gitlinker.nvim
