### ISSUE TITLE
Is it possible to support defining keymaps only when inside a git repo?

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/gitsigns.nvim#792]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It will be great if those keymaps provided/recommended by gitsigns.nvim could be defined only when my current working directory is at a git repo.

**Describe alternatives you've considered**
No.

**Additional context**
No.

**Comment by lewis6991** [comment]
This is what the `on_attach` callback is for.

**Comment by nyngwang** [comment]
My bad, let me close this!
