### ISSUE TITLE
Error: `module 'gitsigns.attach' not found

### ISSUE THREAD

**Issue by stefanfrede** [lewis6991/gitsigns.nvim#795]
### Description

I just updated my config and now I get this error whenever I open a file in a repo with changes in it:

[![Screenshot-from-2023-05-15-14-32-11.png](https://i.postimg.cc/nzhBv0KV/Screenshot-from-2023-05-15-14-32-11.png)](https://postimg.cc/3yzkhjbz)

Here is a link to my config:
https://github.com/stefanfrede/dotfiles/blob/feature/change-neovim-config/nvim/lua/user/gitsigns.lua

### Neovim version

NVIM v0.9.0-dev-593+gf60cff8f9

### Operating system and version

Ubuntu 20.04.6 LTS

### Expected behavior

No error.

### Actual behavior

[![Screenshot-from-2023-05-15-14-32-11.png](https://i.postimg.cc/nzhBv0KV/Screenshot-from-2023-05-15-14-32-11.png)](https://postimg.cc/3yzkhjbz)

### Minimal config

```Lua
https://github.com/stefanfrede/dotfiles/blob/feature/change-neovim-config/nvim/lua/user/gitsigns.lua
```

### Steps to reproduce

The moment there is are changes in my repo I get the error message from above when I open a file.

**Comment by lewis6991** [comment]
There's nothing here to indicate this is an issue with Gitsigns. Maybe try reinstalling?

If you can't resolve this then I'll need minimal steps to reproduce the issue as per the issue template.
