### ISSUE TITLE
Ability to jump to the first and the last hunk

### ISSUE THREAD

**Issue by dtcyganok** [lewis6991/gitsigns.nvim#800]
**Is your feature request related to a problem? Please describe.**
It's pretty common to have the comprehensive navigation through a set of items. Usually it includes:

- prev item
- next item
- first item
- last item

Many plugins' authors follow that pattern. For instance [unimpaired.vim](https://github.com/tpope/vim-unimpaired) and [ale](https://github.com/dense-analysis/ale).

**Describe the solution you'd like**
My suggestion is to add the api functions `first_hunk` and `last_hunk`.

**Describe alternatives you've considered**
To write my own functions `first_hunk` and `last_hunk`.

**Comment by lewis6991** [comment]
I would do `gg]c` for the first hunk and `G[c` for the last

**Comment by dtcyganok** [comment]
Thanks, i already tried that. And it doesn't work correctly, if the first hunk starts from the first line. Similarly, the situation with the last hunk is the same

**Comment by dtcyganok** [comment]
I wrote those functions, but i'm not sure that's correct:

```lua
local function opts()
  return {
    buffer = bufnr,
    unique = true,
  }
end

vim.keymap.set('n', '[G', function()
  local hunks = gitsigns.get_hunks()
  local hunk = hunks[1]
  local line = math.min(hunk.added.start, hunk.removed.start)
  vim.api.nvim_win_set_cursor(0, { line, 0 })
end, opts())

vim.keymap.set('n', ']G', function()
  local hunks = gitsigns.get_hunks()
  local hunk = hunks[#hunks]
  local line = math.max(hunk.added.start, hunk.removed.start)
  vim.api.nvim_win_set_cursor(0, { line, 0 })
end, opts())
```

**Comment by lewis6991** [comment]
It's close. The buffer indices are in `hunk.added`. `hunk.removed` is what you're comparing too.

Try `hunk.added.start + hunk.added.count`

**Comment by ribru17** [comment]
What about `G]c` for first hunk and `gg[c` for last hunk? I tested this and it works when hunks are at the first and last lines thanks to the wrap-around functionality. For the last hunk if you want your cursor to be at the beginning of the changes then it would be `gg[c[c]c`.

**Comment by dtcyganok** [comment]
@ribru17 `gg[c` doesn't work properly if the first line has been changed, as i mentioned before. There is the bug with `wrap` option. I've already created the related [issue](https://github.com/lewis6991/gitsigns.nvim/issues/806)

**Comment by lewis6991** [comment]
Done in #976
