### ISSUE TITLE
The coroutine failed with this message: [...]gitsigns.nvim/lua/gitsigns/hunks.lua:190: assertion failed!

### ISSUE THREAD

**Issue by nyngwang** [lewis6991/gitsigns.nvim#802]
### Description

I got the error provided below when I called `:FzfLua git_status` provided by [ibhagwan/fzf-lua](https://github.com/ibhagwan/fzf-lua) in a PyTorch project on a remote machine I connected via ssh. I sincerely don't know how to provide a simple reproducible script for this.

I suspect that the floating window created by fzf-lua might not satisfy the assertion in the given line indicated by the error message. When this error happened, Neovim went frozen about 1 sec before the error was shown.

### Neovim version

NVIM v0.10.0-dev-395+g8e6971695

### Operating system and version

ubuntu 20.04

### Expected behavior

No error.

### Actual behavior

error.

```
   Error  01:01:58 AM msg_show.lua_error Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:190: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:190: in function 'calc_signs'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:64: in function 'apply_win_signs0'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:81: in function 'apply_win_signs'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:413: in function 'fn'
	.../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:80: in function 'update'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:531: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:493>
stack traceback:
	[C]: in function 'error'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:140: in function 'cb'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:48: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:46>
```

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by n3wborn** [comment]
Same error here (using same minimal config file) when I `Gitsigns stage_hunk` 
reset,next/prev/diffthis seems working as usual, but when I try to stage, nothing happens (with my own config) and this error is thrown using minmal config

![image](https://github.com/lewis6991/gitsigns.nvim/assets/10246722/445ec8a7-e1b1-44a3-84ef-da9fb5797312)

**Comment by mortezadadgar** [comment]
getting same error on creating new file and while using cmp
sorry I hit this error four or three times in a day it's really not easy to reproduce
![Screenshot-230617-1043-07](https://github.com/lewis6991/gitsigns.nvim/assets/27911493/49ea3418-ce1f-496a-9acd-ead35b6ffcb7)

**Comment by mortezadadgar** [comment]
@lewis6991 I have not faced this issue anymore

**Comment by dietrichm** [comment]
Me neither!

**Comment by lewis6991** [comment]
Ok thanks, I'll close this then. Please open a fresh issue if this happens again.
