### ISSUE TITLE
Extra attach to an already attached buffer

### ISSUE THREAD

**Issue by dtcyganok** [lewis6991/gitsigns.nvim#805]
### Description

`:edit` command for opened buffers causes extra `on_attach` calls. It leads to bugs, especially if there are mappings with the `unique = true` flag.

### Neovim version

0.9.1

### Operating system and version

Linux (rolling)

### Expected behavior

`on_attach` calls only once for the same buffer

### Actual behavior

`on_attach` calls for the same buffer after each `:edit` command

### Minimal config

```Lua
vim.o.packpath = '/tmp/nvim/site'

local plugins = {
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
}

for name, url in pairs(plugins) do
  local install_path = '/tmp/nvim/site/pack/test/start/'..name
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
  on_attach = function(buffer)
    local gitsigns = require('gitsigns')
    vim.keymap.set('n', '<Leader>hp', gitsigns.preview_hunk, {unique = true})
  end,

}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open a file
3. Call command `:edit` for the same file

**Comment by lewis6991** [comment]
Gitsigns will try to attach to any buffer in `BufRead`, `BufNewFile`, `BufWritePost` autocmd events. If the buffer is already attached then `on_attach()` won't be recalled.

What issues are you seeing?

**Comment by dtcyganok** [comment]
I intentionally use the `unique` flag on all my mappings to ensure consistency across many plugins. And i often get errors "E227: mapping already exists for ..." with this plugin.

Sometimes attachment occurs many times for the same buffer. It doesn't seem correct, does it?

**Comment by lewis6991** [comment]
on_attach will be called for each buffer. If it is already attached then it won't be called again.

It sounds like a problem on your side.

**Comment by dtcyganok** [comment]
"If it is already attached then it won't be called again." That's not true. I can prove it easily. Just call the `edit` command for the same file twice:

```lua
  --
  on_attach = function(buffer)
    print('on_attach ' .. buffer)
  end,
  --
```

```text
edit path/to/somefile
edit path/to/somefile
```

**Comment by lewis6991** [comment]
When you run `:edit` it detaches and attaches again. This is expected.

**Comment by dtcyganok** [comment]
But what about mappings? Buffer mappings remain after a detach. And during a new attachment, the on_attach function creates new ones. Is this expected too?

**Comment by lewis6991** [comment]
I don't use `unique` in my mappings, and AFAIK it doesn't cause any problems. Is there some that I should be made aware of?

**Comment by dtcyganok** [comment]
The problem is that the plugin's behavior is incompatible with "unique" mappings...

**Comment by dtcyganok** [comment]
An extra on_attach call for the same buffer doesn't seem reasonable

**Comment by lewis6991** [comment]
I suppose, not sure why that should be a requirement.

If you need to use unique mappings (for whatever reason), then you'd need to implement the tracking logic yourself.

I don't really think unique mappings make sense here. I think they are mainly useful to stop mappings being created in multiple sources for different things, but in general they don't provide much value.

**Comment by dtcyganok** [comment]
In my opinion the tracking logic should be part of the plugin. Especially if the plugin performs multiple attach/detach operations. But the final decision, of course, is yours.

**Comment by lewis6991** [comment]
> An extra on_attach call for the same buffer doesn't seem reasonable

That's how it works. When you run `:edit` it is like reading the file again and Gitsigns does a complete refresh by detaching and re-attaching.

See `nvim_buf_attach` for more details.

It doesn't seem like there's an actual problem here.

If you can outline problems which unique mappings solve, then we can reconsider adding something like an `on_detach` hook. Otherwise it just seems like bloat without good enough justification.

**Comment by lewis6991** [comment]
Also do you not have the same problem when you restart an LSP client? That should basically do the same thing and re-run the on_attach.

**Comment by dtcyganok** [comment]
To me the main point of unique mappings is that's really helpful to maintain consistency across hundreds of key bindings. It facilitates vim/nvim configuration maintainance.

And i don't have any problems with LSP client. But maybe for a while...
