### ISSUE TITLE
Allow toggling "watch_gitdir" or dynamically changing watch interval

### ISSUE THREAD

**Issue by mars90226** [lewis6991/gitsigns.nvim#822]
**Is your feature request related to a problem? Please describe.**
I work for the project that consisted of many small git repos. Usually I open each neovim instance for each git repo and switch between them. I would like to avoid or lower the CPU usage of gitsigns.nvim "watch_gitdir" in background neovim instances.

**Describe the solution you'd like**
A command to toggle "watch_gitdir" or change "watch_gitdir" interval.

**Describe alternatives you've considered**
Automatically disable "watch_gitdir" in background neovim instances.

**Additional context**
I've tried to implement this in [my config](https://github.com/mars90226/dotvim/blob/master/lua/vimrc/plugins/gitsigns.lua#L74-L107) by trying to change directory to non-git directory on FocusLost and changing back on FocusGained. But the debounced `update_cwd_head` function seems not called when triggered this way.

**Comment by lewis6991** [comment]
Can't you just disable `config.watch_gitdir`?

I'm really not interested in adding a dynamic. Having a poll object for each open buffer shouldn't use much CPU.

**Comment by mars90226** [comment]
Well, the watcher does create many `epoll_pwait()`s on my machine and raise the load averages quite a lot if I open many neovim instances. Maybe I just raise the interval to 60 seconds to workaround this. Thanks anyway!

**Comment by lewis6991** [comment]
Are you talking about the cwd_watcher or the gitdir watcher? The gitdir_watcher can be disabled.

**Comment by mars90226** [comment]
I know I can disable `watch_gitdir` with `enable = false`. But I want to enable it when I'm actually using the neovim (it's in the foreground).

**Comment by lewis6991** [comment]
There are a few improvements we can make:
- Use fs_events instead of polling. I've started this in #660 
- Share watchers across buffers apart from the same repository. Currently, each buffer gets its own watcher.
- Stop the watchers when nvim is backgrounded. Or better: stop watchers after the first trigger when nvim is backgrouned since any subsequent callbacks aren't doing anything useful.

**Comment by mars90226** [comment]
Thanks! I'm not familiar with libuv, but I can try stopping watchers when nvim is backgrounded when I have free time.
