### ISSUE TITLE
Detect and use yadm when makes sense

### ISSUE THREAD

**Issue by leiserfg** [lewis6991/gitsigns.nvim#83]
**Is your feature request related to a problem? Please describe.**
I was planning to move to `gitsigns`, but coming from `mhinz/vim-signify`, I noticed that it misses `yadm` support. 

**Describe the solution you'd like**
I know that `gitsigns` is more tied to `git` than signify, but `yadm` is only a git wrapper, so it's enough to:  

1.  Detect when the current file is being managed by yadm .
2. Call `git` with the `GIT_DIR` set as the output of `yadm enter 'echo $GIT_DIR'` in that case.

**Comment by lewis6991** [comment]
I've never used `yadm` so I have s couple of questions.

1. How can you detect if a file is managed by `yadm`?
2. What does `yadm` support specifically mean? If it is just a git wrapper then why isn't the current git support enough? All my dotfiles are symlinks to a dotfile git workspace and I specifically made gitsigns resolve symlinks so signs work. How is `yadm` different?

If there isn't too much collateral then I'm happy to add support but I'll need precise details so I know what need to implement.

**Comment by lewis6991** [comment]
Please try #84

**Comment by leiserfg** [comment]
@lewis6991  #84  works well, but I'm losing the new fixes and features, when will it get merged?

**Comment by lewis6991** [comment]
Sorry, this has been on my todo list for a while. The PR needs quite a bit of work still. I'll try and work on it soon.

**Comment by lewis6991** [comment]
Once #137 goes in, adding yadm support will be trivial. I basically needed to refactor so every git command has the gitdir and toplevel passed in but done in a way that doesn't cause bloated function arguments on every git command.
