### ISSUE TITLE
Bottom border is missing when the commit message is too long

### ISSUE THREAD

**Issue by rockyzhang24** [lewis6991/gitsigns.nvim#841]
### Description

First enable the border for preview window
```lua
require('gitsigns').setup {
  preview_config = {
    border = 'single',
  },
}
```

Then open an arbitrary file and run `:lua require('gitsigns').blame_line({ full = true })` on a certain line with a long enough (longer than the screen height) commit message. The bottom border of the floating window is missing. 

<img width="1728" alt="Screenshot 2023-07-17 at 19 48 53" src="https://github.com/lewis6991/gitsigns.nvim/assets/11582667/20f058ac-0813-4bb8-bd65-d9326446c320">

(Just FYI: the file I was using in the pic is https://github.com/junegunn/fzf/blob/master/src/core.go)

### Neovim version

NVIM v0.10.0-dev-551+ge27377e33

### Operating system and version

macOS 13.4.1

### Expected behavior

The bottom border should be shown as normal

### Actual behavior

The bottom border of the floating window is missing

### Minimal config

```Lua
require('gitsigns').setup {
  preview_config = {
    border = 'single',
  },
}
```

### Steps to reproduce

See the "Description" section above please.

**Comment by lewis6991** [comment]
Is this really a problem?

**Comment by rockyzhang24** [comment]
Not exactly, but just want to make gitsigns as perfect as possible. 🥳

**Comment by lewis6991** [comment]
I'll accept a PR, but this isn't something I'll have time to fix.

**Comment by rockyzhang24** [comment]
Already opened a [PR](https://github.com/lewis6991/gitsigns.nvim/pull/842) to fix this. Thank you.
