### ISSUE TITLE
Load `trouble` lazily

### ISSUE THREAD

**Issue by MariaSolOs** [lewis6991/gitsigns.nvim#844]
**Is your feature request related to a problem? Please describe.**
Not an issue per se, just a nice-to-have.
This plugin will attempt to load `trouble.nvim` when resolving the config's defaults, erasing my lazy-loading efforts. I've configured `trouble` to load when using the `Trouble` command, but because `gitsigns` will be loaded on `BufReadPre`/`BufNewFile`, `trouble` will be unnecessarily loaded at that point as well.

**Describe the solution you'd like**
I would like this plugin to require `trouble` only when it is about to open the quickfix/location list, instead of during configuration time.

**Describe alternatives you've considered**
I looked at the code and I guess that an easy fix would be to set `opts.trouble` to nil and do a lazy initialization [here](https://github.com/lewis6991/gitsigns.nvim/blob/adcf2c7f2f495f5df148683764bf7cba6a70f34c/lua/gitsigns/actions.lua#L1140). However that would kind of mess up with the clean setup that this plugin has when [resolving the configuration](https://github.com/lewis6991/gitsigns.nvim/blob/adcf2c7f2f495f5df148683764bf7cba6a70f34c/lua/gitsigns/config.lua#L812)...

**Comment by lewis6991** [comment]
Sorry I won't really have time for this.

**Comment by MariaSolOs** [comment]
I understand. Thank you nonetheless!
