### ISSUE TITLE
attempt to call field 'scheduler_if_buf_v alid' (a nil value)

### ISSUE THREAD

**Issue by haomingw** [lewis6991/gitsigns.nvim#856]
### Description

I hit this error after updating the plugin, it seems to be related to the latest commit

### Neovim version

v0.9.1

### Operating system and version

macOS Sonoma

### Actual behavior

Error executing luv callback:
...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:105: The coroutine failed with this message: ...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:303: attempt to call field 'scheduler_if_buf_v
alid' (a nil value)
stack traceback:
        ...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua: in function 'fn'
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:76: in function 'attach_throttled'
        ...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:426: in function 'attach'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:132: in function 'setup_attach'
        ...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:191: in function <...im/site/pack/packer/start/gitsigns.nvim/lua/gitsigns.lua:167>
stack traceback:
        [C]: in function 'error'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:105: in function 'cb'
        ...e/pack/packer/start/gitsigns.nvim/lua/gitsigns/async.lua:140: in function 'callback'
        ...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:98: in function <...hare/nvim/lazy/gitsigns.nvim/lua/gitsigns/subprocess.lua:86>

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua <file>` where the `file` can be any file inside a git repo

**Comment by lewis6991** [comment]
Something is broken with your config as it is pulling in two different installs of Gitsigns:

```
.../pack/packer/start/gitsigns.nvim
.../share/nvim/lazy/gitsigns.nvim
```
