### ISSUE TITLE
Error When Selecting Hunk in VS Code

### ISSUE THREAD

**Issue by kevintraver** [lewis6991/gitsigns.nvim#860]
### Description

When using this keymap:

```vim.keymap.set({ "o", "x" }, "ih", ":<C-U>Gitsigns select_hunk<CR>")```

I get the following error when using VS Code with **vscode-neovim**

It works fine in regular neovim without any issues.

### Neovim version

NVIM v0.10.0-dev

### Operating system and version

Mac OS Monterey 12.6.8

### Expected behavior

Selection of git hunk

### Actual behavior

```
Error executing Lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:157: attempt to index a nil value
stack traceback:
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function 'get_cursor_hunk'
	...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:759: in function 'f'
	...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/cli.lua:104: in function <...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/cli.lua:72>
stack traceback:
	[C]: in function 'error'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'step'
	...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:102: in function 'run'
	...in/.local/share/nvim/lazy/git

```

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
  "lewis6991/gitsigns.nvim",
  event = "VeryLazy",
  config = function()
    require("gitsigns").setup({})
    vim.keymap.set({ "o", "x" }, "ih", ":<C-U>Gitsigns select_hunk<CR>")
  end,
})
```

### Steps to reproduce

Try to select hunk using keymap in vscode-neovim

**Comment by lewis6991** [comment]
It looks like you ignored the template. Minimal configs should never use lazy.nvim.

**Comment by lewis6991** [comment]
Looking at the error message. It looks like Gitsigns isn't attached to the buffer. Are you sure the signs in the column are coming from Gitsigns?

**Comment by kevintraver** [comment]
It still happens when I remove `event = "VeryLazy"`

**Comment by kevintraver** [comment]
I think this just might be a limitation of **vscode-neovim**, so I will close this issue.

**Comment by lewis6991** [comment]
> It still happens when I remove `event = "VeryLazy"`

In your case, I don't think `VeryLazy` does anything since you're requiring Gitsigns in `config`.

**Comment by searleser97** [comment]
@kevintraver is it actually a limitation on vscode-neovim ? I would like to use the "next/prev hunk" features, I think it should be supported since it just involves moving the cursor to a different position, but for some reason it just does not work, and there is no error in the console.
