### ISSUE TITLE
gitsigns show failed

### ISSUE THREAD

**Issue by yimingwangdell** [lewis6991/gitsigns.nvim#866]
### Description

![image](https://github.com/lewis6991/gitsigns.nvim/assets/121928908/5de627ae-899a-4e8e-aa94-c83934da44c0)

### Neovim version

NVIM v0.10.0-dev-835+gdd09630a2

### Operating system and version

manjaro

### Actual behavior

error happened.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by lewis6991** [comment]
Fixed in https://github.com/lewis6991/gitsigns.nvim/commit/44adf808ace6cb65a3353bd61fa585a2d8fe0db3

In the future, please provide reproduction steps. I had to guess for this.
