### ISSUE TITLE
Do not show changes for BOM and final newline, when there are none

### ISSUE THREAD

**Issue by kmoschcau** [lewis6991/gitsigns.nvim#875]
### Description

When I have a file that's usually also touched by the likes of Visual Studio, for example a C# or Razor file, those tools usually save them with the following properties:
- set a BOM (byte order mark)
- CRLF line endings
- no final newline

I have set up my neovim to handle this properly for these file types:
- `set bomb`
- `set fileformat=dos`
- `set noendofline`
- `set nofixendofline`

Further my git is set up via global attributes for these file extensions with `eol=crlf`.

When I run `git diff` in a shell, it does not show any changes.
When I use https://github.com/sindrets/diffview.nvim, it does show a supposedly removed BOM, but no added final newline. This only happens for files with actual changes on disk, though. (Now file there as https://github.com/sindrets/diffview.nvim/issues/416)

However gitsigns shows me a changed line in the first line (I guess for the BOM) and in the last line (I guess for the final newline). It seems to me that gitsigns compares the file on disk with some internal buffer representation of neovim, where the BOM is removed (You never see the control character, even with `set bomb`.) and a final newline internally added, even though it is not written out.

### Neovim version

NVIM v0.10.0-dev-798+g72e619ca9

### Operating system and version

MS Win 22H2 (OS Build 22621.2134)

### Expected behavior

Gitsigns should not show changes in the first and last line respectively.

### Actual behavior

Gitsigns does show changes in the first and last line respectively.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
}

vim.opt.fileformat = "dos";
vim.opt.endofline = false;
vim.opt.fixendofline = false;
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua foo.cs`
2. `:set bomb`
3. add some content to the file, so it's at least 3 lines long
4. `:wq`
5. `git init`
6. `git add .`
7. `git commit -m 'Test'`
9. `nvim --clean -u minimal.lua foo.cs`
10. observe that gitsigns now shows a changed line in the first and last line
11. check with `:%!xxd`, that the BOM is in fact still there (the first bytes are [`EF BB BF`](https://en.wikipedia.org/wiki/Byte_order_mark#UTF-8))

(I am fairly sure that changing the git attributes is not needed, as that should only affect checkout.)

**Comment by lewis6991** [comment]
I am unable to reproduce this on MacOS

**Comment by lewis6991** [comment]
Ok, I think I've fixed this in #885.

Would appreciate if someone could test it.

**Comment by kmoschcau** [comment]
I will get back to you with test results on Monday when I'm back on my Windows machine.

**Comment by kmoschcau** [comment]
@lewis6991 I tested it now and this fixed both lines showing up as changed when they are not.

Just as a side note: using either `set bomb` or `set eol` and saving the file now shows changes in the git diff output, but no changes in gitsigns. Not sure if it was like this before. But I can live with that. I would rather have less things showing up in gitsigns compared to the actual diff than more.

**Comment by lewis6991** [comment]
Ideally gitsigns should be consistent with `git status`. When you run either of those `set` commands and save the buffer does `git status` still report clean?

**Comment by lewis6991** [comment]
Ah wait. I see. Gitsigns doesn't get notified when either of those options are set.

**Comment by kmoschcau** [comment]
`git status` does change when setting those options and writing the file. I now realize I did not try a forced read afterwards to check what would happen though.

**Comment by kmoschcau** [comment]
@lewis6991 I just checked again, force reading the file afterwards updates gitsigns.

**Comment by lewis6991** [comment]
> Just as a side note: using either set bomb or set eol and saving the file now shows changes in the git diff output, but no changes in gitsigns. 

This should be fixed in 73a95e68f1b27e8ac65ef2f3e6ed27308bba91d2

**Comment by kmoschcau** [comment]
I will give it a look after lunch.

**Comment by kmoschcau** [comment]
@lewis6991 This now works immediately on changing `'bomb'`. The last line diff sign updates after changing `'endofline'` and writing once. I suspect this just has to do with how this option behaves in general. Thanks a lot!
