### ISSUE TITLE
`current_line_blame` is too CPU intensive

### ISSUE THREAD

**Issue by WhyNotHugo** [lewis6991/gitsigns.nvim#877]
### Description

From what I'm understanding, `current_line_blame` runs an instance of git each time that the cursor moves to another line in order to extract blame information for the new line.

This is a problem for large repositories, where a single execution can spike CPU to 100% for a few seconds.

This becomes a terrible problem when scrolling; if I press `j` five times, then 5 `git` processes are spawned each one taking 100% of a CPU core. If I just hold `j` for a short while, this is what `top` looks like:

![image](https://github.com/lewis6991/gitsigns.nvim/assets/730811/cf353bba-2a67-4cd2-b954-7ff9a7cc53c1)

These can take around 20-30s to complete, given that they're all competing for CPU usage.

### Neovim version

NVIM v0.9.1

### Operating system and version

Linux 6.5.1-0-edge x86_64 Linux

### Expected behavior

CPU usage should not spike due to blame calculation

### Actual behavior

CPU usage spikes to 100% for each line change on large repositories.

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require("gitsigns").setup({
  current_line_blame = true,
  current_line_blame_opts = {
    delay = 0,
  },
})
```

### Steps to reproduce

1. `git clone https://gitlab.alpinelinux.org/alpine/aports.git` (or any other large repository)
2. Open any file in the repository (e.g.: `community/xdg-desktop-portal/APKBUILD`)
1. CPU will now spike once.
2. Open `top` in another terminal
3. Press j or k in neovim. Note how each keypress spawns a `git` process that takes a few seconds to exit.

**Comment by lewis6991** [comment]
To solve this we will need to kill unfinished `git blame` commands when the cursor moves.

**Comment by lewis6991** [comment]
@WhyNotHugo can you try #878.

It doesn't cancel any processes, but will prevent git blames from running concurrently.

**Comment by WhyNotHugo** [comment]
Given that `git blame` calculates blame for the whole file, can't its entire output be kept in memory? So when the cursor moves, the blame data can be read from memory, rather than running `git blame` which needs to do a lot of work.

**Comment by lewis6991** [comment]
Gitsigns doesn't fetch the blame for the entire file, it does it per line instead. I don't know if doing it for the entire file will be more efficient or not, but I would guess it wouldn't be.
