### ISSUE TITLE
git add -p support - Go to the next file when at the last hunk in a file

### ISSUE THREAD

**Issue by ColinKennedy** [lewis6991/gitsigns.nvim#882]
**Is your feature request related to a problem? Please describe.**
I'd like to use gitsigns.nvim as a sort of interactive replacement for `git add -p`. When the hunks of one file end, `git add -p` will start inspecting the hunks of the next file. So far I haven't found a way to replicate that easily with gitsigns.nvim

**Describe the solution you'd like**
A next/prev hunk command or something similar that will advance to the next file, rather than wrap to the start of the file or stop advancing.

**Describe alternatives you've considered**
Writing a custom function that is essentially ...

```
if not at_last_hunk:
    next_hunk()
    return

file = get_next_unstaged_file_in_the_git_repository()

if not file:
    stop
    return

:e file
```

"if at the end of the hunks in this file, look up what the next unstaged git file path may be and switch the window to there" function.

**Comment by lewis6991** [comment]
You can try `:Gitsigns setqflist all` but other than that this is out of scope.

**Comment by dudicoco** [comment]
@lewis6991 is there a way to automatically run `:Gitsigns preview_hunk_inline` when entering an item in the qflist?
