### ISSUE TITLE
Error when opening an untracked file with base = "HEAD"

### ISSUE THREAD

**Issue by Saecki** [lewis6991/gitsigns.nvim#888]
### Description

I am getting the following error when opening a file with the same name as a file that has previously been moved and staged. See repro instructions.

```
Error executing vim.schedule lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: The coroutine failed with this message: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:172: Invalid hunk with untracked
=true hunk="@@ -1,15 +1,6 @@"
stack traceback:
        [C]: in function 'assert'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/hunks.lua:172: in function 'calc_signs'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:49: in function 'apply_win_signs0'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:72: in function 'apply_win_signs'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:466: in function 'fn'
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'update'
        ...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:365: in function 'fn'
        .../share/nvim/lazy/gitsigns.nvim/lua/gitsigns/debounce.lua:68: in function 'attach_throttled'
        ...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:426: in function <...al/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/attach.lua:425>
stack traceback:
        [C]: in function 'error'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:76: in function 'cb'
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:113: in function 'cb'
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:416: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/manager.lua:401>
```

### Neovim version

NVIM v0.9.2 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /usr/bin/gcc -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wvla -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -fno-common -Wno-unused-result -Wimplicit-fallthrough -fdiagnostics-color=auto -fstack-protector-strong -DUNIT_TESTING -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/usr/include/luajit-2.1 -I/usr/include -I/usr/include/luv -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux-build/src/nvim/auto -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux-build/include -I/builddir/build/BUILD/neovim-0.9.2/redhat-linux-build/cmake.config -I/builddir/build/BUILD/neovim-0.9.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

Fedora 38

### Expected behavior

Operation as usual

### Actual behavior

The error above

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
  base = "HEAD",
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. be inside a git repository
2. create a file with some text in it `echo "some text" > Cargo.toml`
3. `git add Cargo.toml`
4. `git commit -m "message"`
5. `mv Cargo.toml` into a directory for example `subdir`
6. `git add .`
7. `nvim --clean -u minimal.lua Cargo.toml`
8. add some text and save the file
9. now the error should appear constantly

**Comment by emmanueltouzery** [comment]
I got that exact same stack too now. I'm not sure what I did, multiple branch switching...

**Comment by Saecki** [comment]
I could only get it to work with this inside my `.gitconfig`:

```gitconfig
[init]
    defaultBranch = main
```

Maybe there are some assumptions made about the default branch somewhere?

**Comment by lewis6991** [comment]
Most of my repo's use `main` so I doubt that.

**Comment by Saecki** [comment]
Maybe it's a bug within git itself, since it's not too long ago that they added the config option to change the default branch.

**Comment by lewis6991** [comment]
I'm not sure why the default init branch has anything to do with this.

**Comment by emmanueltouzery** [comment]
I have to mention that I got this issue too, and I'm using fedora 38 exactly like @Saecki which seems like a big coincidence.

I have the default fedora git: `git version 2.41.0`.

**Comment by lewis6991** [comment]
If you can make the repro steps precise and in a script then that will probably allow me to repro this.

Ideally this could be added as a testcase in the current suit.

**Comment by Saecki** [comment]
Ok so it seems I don't even need to change the `.gitconfig` this script does the trick for me. If you can reproduce the error I can create a proper test case.

```sh
#!/bin/sh

# init git repo
REPRO_DIR="untracked_file_madness"
rm -f "$REPRO_DIR"
mkdir "$REPRO_DIR"
cd "$REPRO_DIR"
git init --initial-branch=main

# first commit
echo "some text" > Cargo.toml
git add Cargo.toml
git commit -m "message"

# move Cargo.toml and stage move
mkdir subdir
mv Cargo.toml subdir
git add Cargo.toml subdir

# open file in neovim with minimal config
MINIMAL_CONFIG="for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
  base = \"HEAD\",
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
vim.defer_fn(function() vim.cmd(\"w\") end, 1000)
"
echo "$MINIMAL_CONFIG" > minimal.lua
nvim -u minimal.lua Cargo.toml

```

**Comment by Saecki** [comment]
I think the cause of this is just a faulty assertion in `hunks.lua:172`:
```lua
assert(
    not untracked or hunk.type == 'add',
    string.format('Invalid hunk with untracked=%s hunk="%s"', untracked, hunk.head)
)
```
Since `git status` returns this
```
❯ git status
On branch master
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        renamed:    Cargo.toml -> subdir/Cargo.toml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Cargo.toml
        gitsigns_issue/
        minimal.lua
```

Removing the assertion seems to work just fine. Do you know why it was there in the first place? Otherwise could we just remove it?

**Comment by lewis6991** [comment]
Repro'd it!

Thanks for scripting this.
