### ISSUE TITLE
gitsigns reports not existing changes

### ISSUE THREAD

**Issue by katsika** [lewis6991/gitsigns.nvim#9]
Hey,

got a file which has no changes made to it yet gitsigns reports a lot of them (~1 -1293) (file is 1425 lines long). `git diff <file>` returns nothing.

How could I debug it?

Thanks for great plugin!

**Comment by lewis6991** [comment]
You could try setting `debug_mode = true` in your setup config. Not sure how useful that will be to you without being familiar with the code.

Is there any way you can sandbox the issue so I can reproduce it?

**Comment by lewis6991** [comment]
I've managed to debug this. Issue is due to a bug in `plenary.nvim`. Got a fix ready, just need to raise a PR.

**Comment by lewis6991** [comment]
https://github.com/nvim-lua/plenary.nvim/pull/23

**Comment by katsika** [comment]
Ah, sorry for not coming back to you earlier. Busy day. Glad you figured it out!

**Comment by lewis6991** [comment]
Applied a workaround for the time being. Shout out if the issue still occurs.
