### ISSUE TITLE
Cannot resolve symbol 'xdl_diff'

### ISSUE THREAD

**Issue by Shatur95** [lewis6991/gitsigns.nvim#90]
**Describe the bug**
On Windows after a98df1518063adb00de4f482f07b6405d09b2dbb the plugin doesn't work.

**To Reproduce**

Just install plugin and run Neovim, you will see the following error:

```bash
...im\pack\plugins\opt\gitsigns.nvim\lua\gitsigns\async.lua:53: ...vim\pack\plugins\opt\gitsigns.nvim\lua\gitsigns\diff.lua:130: cannot resolve symbol 'xdl_diff'.
```

**Observed output**
Error messages, logs, etc

**Screenshots**
If applicable, add screenshots to help explain your problem or to capture error messages.

**Additional context**
System: Windows
Neovim version: gf5daf55c1 (latest master at the time of writing).

**Comment by lewis6991** [comment]
Looks like your windows install doesn't have access to xdl_diff which is interesting. As a workaround you can revert to the old behavior with:

`config.use_internal_diff = false`.

**Comment by lewis6991** [comment]
Looks like ffi on windows is a bit tricky: https://stackoverflow.com/questions/5919743/how-to-use-luajits-ffi-module-when-embedding

For now we can automatically disable internal diff on windows.

**Comment by Shatur95** [comment]
Interesting. As I know, https://github.com/kyazdani42/nvim-tree.lua uses ffi two and works for me on Windows.

But thanks for the reasonable default for now :)
