### ISSUE TITLE
Allow File history walking

### ISSUE THREAD

**Issue by DMunkei** [lewis6991/gitsigns.nvim#905]
Sometimes I want to go through the history of a specific file to see if there are any specific changes to a file. So I end up using the command `Gitsigns diffthis @~1`. This however shows me the comparison with the last commit. This makes it comparing differences with older commits a hassle, first having to find the commit sha and then passing it to `Gitsigns diffthis @..commitsha`

I would like to somehow merge the feature from fugitive `0Gclog` which shows the current file history of the file. And display it how `diffthis` does. That means, the bottom half of the buffer would show the entries inside of the quicklist, selecting/walking one of these commits in would then compare that commit hash with the current version of the file in the buffer.

![image](https://github.com/lewis6991/gitsigns.nvim/assets/17084284/30604c38-7fca-46d7-97d0-91097065f870)

Here's an example of how it could look like.

**Comment by lewis6991** [comment]
Sorry not accepting complicated feature requests.

I may or not implement something like this if I decide to.

**Comment by eliasdarruda** [comment]
@DMunkei have you managed to solve this somehow?
