### ISSUE TITLE
diff_this not working well on newline from d8590288 commits

### ISSUE THREAD

**Issue by peter-lyr** [lewis6991/gitsigns.nvim#909]
### Description

require 'gitsigns'.diff_this() not working well, in from d8590288417fef2430f85bc8b312fae8b1cf2c40 and later commits.

### Neovim version

0.9.2

### Operating system and version

Windows 10

### Expected behavior

d8590288417fef2430f85bc8b312fae8b1cf2c40 and later

not working well:

![image](https://github.com/lewis6991/gitsigns.nvim/assets/55801796/e3fcec78-e2e0-49a7-a114-3d6712f5c942)

### Actual behavior

79127db3b127f5d125f35e0d44ba60715edf2842

is ok:

![image](https://github.com/lewis6991/gitsigns.nvim/assets/55801796/54d1bc6a-0cda-489a-9c20-3d448ba91c65)

### Minimal config

```Lua
require 'gitsigns'.setup {
  numhl         = true,
  linehl        = false,
  word_diff     = true,

  signs         = {
    add = { text = '+', },
    change = { text = '~', },
    delete = { text = '_', },
    topdelete = { text = '‾', },
    changedelete = { text = '', },
    untracked = { text = '?', },
  },
  sign_priority = 100,
}
```

### Steps to reproduce

sorry, I had only normal config, no minimal config.

**Comment by lewis6991** [comment]
Sorry there isn't enough information here for me to debug.

**Comment by peter-lyr** [comment]
79127db3b127f5d125f35e0d44ba60715edf2842 work find.
but later not.

I am using 79127db3b127f5d125f35e0d44ba60715edf2842, don't worry about it.

thx.
