### ISSUE TITLE
Calculate width for floating window

### ISSUE THREAD

**Issue by weilbith** [lewis6991/gitsigns.nvim#911]
Hey 👋🏾 

**Is your feature request related to a problem? Please describe.**
I would like to have more fine control over the look and feel of the plugin. Something I'm currently trying to tweak is the look of the floating window. It can be configured  via the `preview_config` options. These support the basic options as for the `nvim_open_win` function arguments. But I would like to be able to do some pre-processing first. So for example I would like to align the floating window with the currently active window. Should mean it takes the exact same width and the left and right border aligns with it. But in case the width falls below a threshold, the width should increase to the full editor size and align with it.
I use this kind of "style" also for a few other plugins and like it quite a lot. Unfortunately this needs some more flexibility rather than just setting a fixed numeric value for the window width.

**Describe the solution you'd like**
I would love to have the plugin accept a function as value for the `preview_config.width` option. The plugin then checks the type of the value and if it is a function, it calls it before opening the window and takes its return value as width.

**Describe alternatives you've considered**
Setting the width to a very high number at least ensures it is always as big as the editor width.

What do you think? Is that too much customization asked for? 🙈

**Comment by lewis6991** [comment]
Not a fan of this.

I'm not keen on adding **very** specific points of configuration to satisfy a **very** small fraction of users.

I'm open to more general proposals, however I believe the proposal here is way too [XY](https://xyproblem.info/)

**Comment by weilbith** [comment]
I understand your point that it is too specific. See my final question. All fine. :+1:

Though I must admit your final statement might be a little harsh. I made a quite clear point about my intends to customize the look and in which manner exactly. There is no higher intend here as it is about visual preferences. No XY.

Anyhow, thanks for all the hard work and time you invested into this plugin. 🙏🏾
