### ISSUE TITLE
Make blame_line work for git mergetool

### ISSUE THREAD

**Issue by mortezadadgar** [lewis6991/gitsigns.nvim#919]
**Is your feature request related to a problem? Please describe.**
i have configured nvim as a editor for mergetool like this:
```config
[merge]
	tool = vimdiff
[mergetool]
	keepBackup = false
[mergetool "vimdiff"]
	cmd = nvim -d $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
``` 
wondering if it's feasible to treat the file suffixed by `_local` as main file? so blame line would work there as well; blaming the main window is not useful on lines which has git conflicts notations are treated as not commited yet

**Describe the solution you'd like**
treat the local file as like the main window

**Comment by lewis6991** [comment]
I don't understand the request here.

**Comment by mortezadadgar** [comment]
sorry for confusion I try again; for instance this the window I'm getting by running `git mergetool` the button window is the main file that I'm editing which includes git conflicts notations(`<<<<..HEAD`) I can't get `blame_line` to work on lines that has conflicts as they're modified by git  
but file before this conflict is on the left which is named `dwl_local_xxx.c` i can't get `blame_line` to work there as it's a untracked  file to git, now I'm asking is there a way to make `blame_line` work of this file? 
![image](https://github.com/lewis6991/gitsigns.nvim/assets/27911493/e3e6c323-136f-4d41-b46c-c37b0d330bf8)
