### ISSUE TITLE
CRLF on Windows

### ISSUE THREAD

**Issue by Shatur95** [lewis6991/gitsigns.nvim#92]
**Describe the bug**

With `use_internal_diff = false` on Windows on every diff I see a warning message about CRLF.

**To Reproduce**

Just run with the default settings on Windows and you will get the following message on every change:

```
error: warning: LF will be replaced by CRLF in AppData\Local\Temp\s1x8.0. NA run_diff
```

**Additional context**
System: Windows
Neovim version: gf5daf55c1 (latest master at the time of writing).

**Comment by lewis6991** [comment]
Is this caused by the new changes? Is there an older version of the plugin that works?

Note I don't have access to a Windows machine so I won't be able to test any changes on that platform.

**Comment by Shatur95** [comment]
No, this problem has existed before, I just did not report it :(

> Note I don't have access to a Windows machine so I won't be able to test any changes on that platform.

I can test any PR on my Windows machine.

**Comment by lewis6991** [comment]
Relates to #69.

Does it work if you run: `git config --global core.autocrlf input`?

**Comment by Shatur95** [comment]
Oh, sorry, missed that issue. Thank you, fixes the problem for me.

**Comment by lewis6991** [comment]
Your welcome 🙂

I think I know how to prevent this warning alltogether so will try and fix it now.

**Comment by Shatur95** [comment]
Thank you!
