### ISSUE TITLE
feature request: reset_hunk_index

### ISSUE THREAD

**Issue by wookayin** [lewis6991/gitsigns.nvim#922]
### Description

Hi, first of all thanks again for the greating plugin.

I wish there was a gitsigns operation something like "reset_hunk_index" which works like "reset_buffer_index", but only on a hunk rather on the entire buffer.

Note that:

- The expected behavior is: reset the stage (index) to the "HEAD", leaving the working copy intact (`git reset HEAD -- <file>` but on the hunk)
- Similar to doing `do` (diff obtain) on the index buffer from the git HEAD

Alternatives considered:

- undo_stage_hunk: This can "undo" staging hunk, but only when staging hunk is done via gitsigns in the current sign (which does not persist). So it's a different operation.
- reset_buffer_index: This works exactly the same as `git reset HEAD -- <file>`, reverting and resetting all the changes in the git index. But it's on the entire buffer.

**Comment by wookayin** [comment]
Hmm, I find doing `Gitsigns stage_hunk` somehow toggles the hunk, when `_signs_staged_enable 
 = false` is enabled. I find this behavior is confusing because

- (i) The behavior is different and inconsistent than when staged signs are disabled.
- (ii) The `stage_hunk` operation is supposed to "stage" a hunk, not toggle staging/unstaging a hunk.

Nevertheless, it'd be great if we have separate actions for staging & unstaging (or toggling) a hunk.

**Comment by lewis6991** [comment]
`_signs_staged_enable` is not public yet. When it is, the documentation for `stage_hunk` will be updated, and I'll also consider removing `undo_stage_hunk`.

I don't plan on having a separate action for this.

**Comment by wookayin** [comment]
`reset_hunk_index` could be implemented and considered even if `_signs_staged_enable` is not used, and regardless of that. If exists `reset_hunk_buffer`, why not `reset_hunk_index` ?

**Comment by lewis6991** [comment]
What problems does that solve other than increasing API surface area?

**Comment by wookayin** [comment]
Because there's no **easy way to "unstage" a hunk** (when the experimental feature is not used). One can do `Gitsigns reset_hunk_buffer` to revert all the changes in the git index (equivalent to `git reset HEAD -- FILE`). Wouldn't this be a reasonable feature request?

-----

One may think implementing "unstaging a hunk" can be hard without staged signs. When the staged sign is available: I think the following three operations would be all useful

- `stage_hunk` (an idempotent operation)
- `unstage_hunk` (an idempotent operation)
- `toggle_hunk`

Note that `stage_hunk` is currently (without the staged sign) idempotent, it doesn't work like toggling.
