### ISSUE TITLE
^M not stripped off in Windows

### ISSUE THREAD

**Issue by aloknigam247** [lewis6991/gitsigns.nvim#927]
### Description

I am using neovim in windows and in `Gitsigns diffthis` ^M is not stripped off from the buffer.
I have debugged the code and found that the check fails here
https://github.com/lewis6991/gitsigns.nvim/blob/6e05045fb1a4845fe44f5c54aafe024444c422ba/lua/gitsigns/util.lua#L199C5-L199C35

Somehow lines read from git have a extra entry in array which is empty and for the last item in the array this check fails as #xs0[i] is 0.

I fixed this case locally by adding the check as
```lua
    if #xs0[i] > 0 and xs0[i]:sub(-1) ~= '\r' then
```

I am not sure if this location is correct for fix.

### Neovim version

NVIM v0.10.0-dev-1801+g2ebd328a7

### Operating system and version

Windows

### Expected behavior

^M should be stripped off in windows.
![image](https://github.com/lewis6991/gitsigns.nvim/assets/45559588/39f7aecf-5f04-4e16-ba4e-412efce0ce44)

### Actual behavior

^M remains if the buffer which makes `Gitsigns diffthis` command not useful.
![image](https://github.com/lewis6991/gitsigns.nvim/assets/45559588/b242041b-7883-485c-8060-8955f08686c7)

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. Open any file in WIndows which have some git diff
3. Gitsigns diffthis

**Comment by aloknigam247** [comment]
I find similar issue in other commands too like when I enable `toggle_deleted` text has ^M.
![image](https://github.com/lewis6991/gitsigns.nvim/assets/45559588/76e4f404-22b4-45b2-a16c-1082a8974b7c)

**Comment by lewis6991** [comment]
Can you provide a minimal example file that causes this? What do the CRLF line endings look like? Is CR (`\r`) omitted for consecutive LF (`\n`).

**Comment by aloknigam247** [comment]
This issue is common on all the files I have in my git repo.
Reproducible for my [README](https://github.com/aloknigam247/dotfiles/blob/master/README.md) as well.
![image](https://github.com/lewis6991/gitsigns.nvim/assets/45559588/5f622b5d-df99-47c2-8921-2ed10f055941)

"What do the CRLF line endings look like" -> The issue is not in checked out file but the file fetched by gitsigns. This needs a strip off which is skipped for an empty line which did existed in original file. If this extra line wasn't added by gitsigns then util.strip_cr() works fine.

**Comment by lewis6991** [comment]
>  The issue is not in checked out file but the file fetched by gitsigns. This needs a strip off which is skipped for an empty line which did existed in original file. If this extra line wasn't added by gitsigns then util.strip_cr() works fine.

Yes, I'm aware, but the checked in file is still a file.

Can you answer my original question please and show me how the CRLF's are arranged in a **minimal** file.

I don't have a windows machine so I can't easily find this out.

**Comment by lewis6991** [comment]
I am able to reproduce by doing `set ff=dos` and committing the file.
