### ISSUE TITLE
[Enhencement] Option to open preview in split like vim-gitgutter

### ISSUE THREAD

**Issue by Bekaboo** [lewis6991/gitsigns.nvim#930]
Firstly thank you for making this plugin! I have used it for a while and it is always stable and performant.

It will be great to have the option to open a preview in a small split below the current window, like [vim-gitgutter's UI shown in this picture](https://github.com/airblade/vim-gitgutter/blob/main/screenshot.png?raw=true).

With a split layout one can have multiple previews of different files or different previews of the same files shown at the same time and navigation between them will be easier.

Thanks in advance.

**Comment by lewis6991** [comment]
Sorry. Not taking feature requests.
