### ISSUE TITLE
Errors when removing certain modules from `require()` cache

### ISSUE THREAD

**Issue by echasnovski** [lewis6991/gitsigns.nvim#933]
### Description

There are errors when trying to edit file after removing certain `require()` cache from `package.loaded`. In particular, cache for 'gitsigns.async' and 'gitsigns.diff_int'.

### Neovim version

NVIM v0.10.0-dev-2143+g3f188bc53 and 0.9.4

### Operating system and version

EndeavourOS Linux x86_64 (6.7.0-arch3-1)

### Expected behavior

Actual values in `package.loaded` should not affect usability of the plugin. According to the documentation (`:h package.loaded` and `:h require()`), it is used as a cache table to store modules for faster `require()` usage, which implies that it is mostly there for speed reasons.

The use case for setting entries of `package.loaded` to `nil` is to reload plugins by forcing them to execute (presumably new) code inside `require()` instead of using cache from `package.loaded`.

### Actual behavior

The following error:

```
Error executing vim.schedule lua callback: ...fig/nvim/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:85: The coroutine failed with this message: .../nvim/gitsigns_issue/gitsigns//lua/gitsig
ns/diff_int.lua:98: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        .../nvim/gitsigns_issue/gitsigns//lua/gitsigns/diff_int.lua:98: in function 'run_diff'
        ...g/nvim/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:485: in function 'fn'
        .../nvim/gitsigns_issue/gitsigns//lua/gitsigns/debounce.lua:68: in function <.../nvim/gitsigns_issue/gitsigns//lua/gitsigns/debounce.lua:54>
stack traceback:
        [C]: in function 'error'
        ...fig/nvim/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:85: in function 'cb'
        ...fig/nvim/gitsigns_issue/gitsigns//lua/gitsigns/async.lua:127: in function 'cb'
        ...g/nvim/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:450: in function <...g/nvim/gitsigns_issue/gitsigns//lua/gitsigns/manager.lua:435>
```

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
}

_G.uncache_gitsigns = function()
  package.loaded['gitsigns.async'] = nil
  package.loaded['gitsigns.diff_int'] = nil
end
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua -- minimal.lua`
2. `:lua uncache_gitsigns()`.
3. Press `o`.

### Gitsigns debug messages

<details><summary>Output of <code>:Gitsigns debug_messages</code></summary>

```
signs.init: Using extmark signs
dprintf: Deriving GitSignsAdd from DiffAdd
dprintf: Deriving GitSignsChange from DiffChange
dprintf: Deriving GitSignsDelete from DiffDelete
dprintf: Deriving GitSignsChangedelete from GitSignsChange
dprintf: Deriving GitSignsTopdelete from GitSignsDelete
dprintf: Deriving GitSignsUntracked from GitSignsAdd
dprintf: Deriving GitSignsAddNr from GitSignsAdd
dprintf: Deriving GitSignsChangeNr from GitSignsChange
dprintf: Deriving GitSignsDeleteNr from GitSignsDelete
dprintf: Deriving GitSignsChangedeleteNr from GitSignsChangeNr
dprintf: Deriving GitSignsTopdeleteNr from GitSignsDeleteNr
dprintf: Deriving GitSignsUntrackedNr from GitSignsAddNr
dprintf: Deriving GitSignsAddLn from DiffAdd
dprintf: Deriving GitSignsChangeLn from DiffChange
dprintf: Deriving GitSignsChangedeleteLn from GitSignsChangeLn
dprintf: Deriving GitSignsUntrackedLn from GitSignsAddLn
dprintf: Deriving GitSignsStagedAdd from GitSignsAdd
dprintf: Deriving GitSignsStagedChange from GitSignsChange
dprintf: Deriving GitSignsStagedDelete from GitSignsDelete
dprintf: Deriving GitSignsStagedChangedelete from GitSignsChangedelete
dprintf: Deriving GitSignsStagedTopdelete from GitSignsTopdelete
dprintf: Deriving GitSignsStagedAddNr from GitSignsAddNr
dprintf: Deriving GitSignsStagedChangeNr from GitSignsChangeNr
dprintf: Deriving GitSignsStagedDeleteNr from GitSignsDeleteNr
dprintf: Deriving GitSignsStagedChangedeleteNr from GitSignsChangedeleteNr
dprintf: Deriving GitSignsStagedTopdeleteNr from GitSignsTopdeleteNr
dprintf: Deriving GitSignsStagedAddLn from GitSignsAddLn
dprintf: Deriving GitSignsStagedChangeLn from GitSignsChangeLn
dprintf: Could not derive GitSignsStagedDeleteLn
dprintf: Deriving GitSignsStagedChangedeleteLn from GitSignsChangedeleteLn
dprintf: Could not derive GitSignsStagedTopdeleteLn
dprintf: Deriving GitSignsAddPreview from DiffAdd
dprintf: Deriving GitSignsDeletePreview from DiffDelete
dprintf: Deriving GitSignsCurrentLineBlame from NonText
dprintf: Deriving GitSignsAddInline from TermCursor
dprintf: Deriving GitSignsDeleteInline from TermCursor
dprintf: Deriving GitSignsChangeInline from TermCursor
dprintf: Deriving GitSignsAddLnInline from GitSignsAddInline
dprintf: Deriving GitSignsChangeLnInline from GitSignsChangeInline
dprintf: Deriving GitSignsDeleteLnInline from GitSignsDeleteInline
dprintf: Deriving GitSignsDeleteVirtLn from DiffDelete
dprintf: Deriving GitSignsDeleteVirtLnInLine from GitSignsDeleteLnInline
dprintf: Deriving GitSignsVirtLnum from GitSignsDeleteVirtLn
attach(1): Attaching (trigger=setup)
run_job: git --version
run_job: git --version
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 config user.name
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 rev-parse --show-toplevel --absolute-git-dir --abbrev-ref HEAD
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir <PATH/TO/GITDIR> --work-tree <PATH/TO/WORKTREE> -c core.quotepa
th=off ls-files --stage --others --exclude-standard --eol <PATH/TO/WORKTREE>/minimal.lua
watch_gitdir(1): Watching git dir
run_job: git --no-pager --literal-pathspecs -c gc.auto=0 --git-dir <PATH/TO/GITDIR> --work-tree <PATH/TO/WORKTREE> show :0:minimal
.lua
update(1): updates: 1, jobs: 7
cli.run: Running action 'debug_messages' with arguments {}
cli.run: Running action 'debug_messages' with arguments {}
```

</details>

**Comment by lewis6991** [comment]
First I've got to ask why are you messing with `package.loaded`? Doing anything with that is going to lead to undefined behaviour and not something I plan to design around.

**Comment by echasnovski** [comment]
> First I've got to ask why are you messing with `package.loaded`? Doing anything with that is going to lead to undefined behaviour and not something I plan to design around.

From the issue:

> The use case for setting entries of `package.loaded` to `nil` is to reload plugins by forcing them to execute (presumably new) code inside `require()` instead of using cache from `package.loaded`.

**Comment by echasnovski** [comment]
> Modules need to be initialised so if you clear `package.loaded` then they need to be setup again.

Updating uncaching function to this doesn't help:
```lua
_G.uncache_gitsigns = function()
  package.loaded['gitsigns.async'] = nil
  package.loaded['gitsigns.diff_int'] = nil
  require('gitsigns').setup()
end
```

**Comment by echasnovski** [comment]
> > According to the documentation (:h package.loaded and :h require()), it is used as a cache table to store modules for faster require() usage, which implies that it is mostly there for speed reasons.
> 
> Despite what the documentation says, this isn't correct.

Would you mind helping to find a better way to reload 'gitsigns.nvim' *without* restarting Neovim?

**Comment by echasnovski** [comment]
> > The use case for setting entries of package.loaded to nil is to reload plugins by forcing them to execute (presumably new) code inside require() instead of using cache from package.loaded.
> 
> This just isn't going to work, since clearing `package.loaded` isn't going to reset any state applied to Nvim, autocmds, keymaps, etc.

It *does* work in the sense of using new code in the current session. If autocommands and keymaps use `require()`, then they will use new code.

**Comment by lewis6991** [comment]
> > > According to the documentation (:h package.loaded and :h require()), it is used as a cache table to store modules for faster require() usage, which implies that it is mostly there for speed reasons.
> > 
> > Despite what the documentation says, this isn't correct.
> 
> Would you mind helping to find a better way to reload 'gitsigns.nvim' *without* restarting Neovim?

No sorry. This isn't a design goal. This also applies to anything in Nvim cores Lua subsystem. Hot reloading has never been a design requirement/goal.
