### ISSUE TITLE
Problem with colour of signs

### ISSUE THREAD

**Issue by simonsmith** [lewis6991/gitsigns.nvim#939]
### Description

Hey,

When updating to the latest version of the plugin I see rendering issues with the colours of the signs in the gutter.

I've located [this commit](https://github.com/lewis6991/gitsigns.nvim/commit/300a306da9973e81c2c06460f71fd7a079df1f36) as the culprit. Checking out the commit before resolves the issue

### Neovim version

0.9.5

### Operating system and version

macOS Ventura

### Expected behavior

It should look like this:

![image](https://github.com/lewis6991/gitsigns.nvim/assets/360703/639287a2-91ee-44dd-9f01-6440a153921d)

### Actual behavior

It renders like this:

![image](https://github.com/lewis6991/gitsigns.nvim/assets/360703/ce16413c-eda9-4166-a695-6ffb2d2b4513)

### Minimal config

```Lua
require('gitsigns').setup({
  signs = {
    add          = { text = '█' },
    change       = { text = '█' },
    delete       = { text = '█' },
    topdelete    = { text = '█' },
    changedelete = { text = '█' },
    untracked    = { text = '┆' },
  },
  on_attach = function(bufnr)
    local gs = package.loaded.gitsigns

    local function map(mode, l, r, opts)
      opts = opts or {}
      opts.buffer = bufnr
      vim.keymap.set(mode, l, r, opts)
    end

    -- Navigation
    map('n', ']c', function()
      if vim.wo.diff then return ']c' end
      vim.schedule(function() gs.next_hunk() end)
      return '<Ignore>'
    end, {expr=true})

    map('n', '[c', function()
      if vim.wo.diff then return '[c' end
      vim.schedule(function() gs.prev_hunk() end)
      return '<Ignore>'
    end, {expr=true})
  end
})
```

### Steps to reproduce

Make a change to any version controlled file

**Comment by lewis6991** [comment]
This change is due to changes in Nvim v0.10. I'll add a guard for the old behaviour.

**Comment by simonsmith** [comment]
Thanks for the quick fix!
