### ISSUE TITLE
Having problems with `gitsigns` and `nvim-colorizer`

### ISSUE THREAD

**Issue by daUnknownCoder** [lewis6991/gitsigns.nvim#947]
### Description

I have these plugins: [lewis6991/gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) and [NvChad/nvim-colorizer.lua](https://github.com/NvChad/nvim-colorizer.lua)

I like the `linehl` feature of gitsigns, but when i use it with `nvim-colorizer`, the bg highlighting of colorizer is overridden by the `linehl`

configs for both (using lazy.nvim)

`nvim-colorizer`

      {
        "NvChad/nvim-colorizer.lua",
        event = "BufReadPost",
        config = function()
          local colorizer_status_ok, colorizer = pcall(require, "colorizer")
          if not colorizer_status_ok then
            print("colorizer not found!")
          end
          colorizer.setup({
            user_default_options = {
              css = true,
            },
          })
        end,
        lazy = true,
      },
    

`gitsigns`

    {
      "lewis6991/gitsigns.nvim",
      event = { "BufReadPost", "BufWritePost", "BufNewFile" },
      keys = {
        { ";j", "<cmd>lua require('gitsigns').next_hunk()<CR>", desc = "Next Hunk" },
        { ";k", "<cmd>lua require('gitsigns').prev_hunk()<CR>", desc = "Prev Hunk" },
        { ";p", "<cmd>lua require('gitsigns').preview_hunk()<CR>", desc = "Preview Hunk" },
        { ";b", "<cmd>lua require('gitsigns').blame_line()<CR>", desc = "Blame Line" },
        { ";s", "<cmd>lua require('gitsigns').stage_hunk()<CR>", desc = "Stage Hunk", mode = "n" },
        {
          ";s",
          "<cmd>lua require('gitsigns').stage_hunk({vim.fn.line('.'), vim.fn.line('v')})<CR>",
          desc = "Stage Hunk",
          mode = "v",
        },
        { ";u", "<cmd>lua require('gitsigns').undo_stage_hunk()<CR>", desc = "Undo Stage Hunk" },
        { ";r", "<cmd>lua require('gitsigns').reset_hunk()<CR>", desc = "Reset Hunk" },
        {
          ";r",
          "<cmd>lua require('gitsigns').reset_hunk({vim.fn.line('.'), vim.fn.line('v')})<CR>",
          desc = "Reset Hunk",
          mode = "v",
        },
        { ";d", "<cmd>lua require('gitsigns').diffthis()<CR>", desc = "Diff" },
      },
      ft = { "gitcommit", "diff" },
      init = function()
        vim.api.nvim_create_autocmd({ "BufRead" }, {
          group = vim.api.nvim_create_augroup("GitSignsLazyLoad", { clear = true }),
          callback = function()
            vim.fn.system("git -C " .. '"' .. vim.fn.expand("%:p:h") .. '"' .. " rev-parse")
            if vim.v.shell_error == 0 then
              vim.api.nvim_del_augroup_by_name("GitSignsLazyLoad")
              vim.schedule(function()
                require("lazy").load({ plugins = { "gitsigns.nvim" } })
              end)
            end
          end,
        })
      end,
      config = function()
        local icons_ok, icons = pcall(require, "NeutronVim.core.icons")
        if not icons_ok then
          print("Unable to import icons!")
        end
        local gitsigns_status_ok, gitsigns = pcall(require, "gitsigns")
        if not gitsigns_status_ok then
          print("Gitsigns not found!")
        end
        gitsigns.setup({
          signs = {
            add = { text = icons.kind.Event },
            change = { text = icons.ui.Pencil },
            delete = { text = icons.ui.Trash },
            topdelete = { text = icons.ui.Close },
            changedelete = { text = icons.ui.Close },
            untracked = { text = icons.ui.Plus },
          },
          signcolumn = true,
          numhl = true,
          linehl = true,
          word_diff = false,
          watch_gitdir = {
            follow_files = true,
          },
          attach_to_untracked = true,
          current_line_blame = true,
          current_line_blame_opts = {
            virt_text = true,
            virt_text_pos = "eol",
            delay = 1000,
            ignore_whitespace = true,
          },
          current_line_blame_formatter = " <author>, <author_time:%R | %x> - <summary>",
          sign_priority = 6,
          update_debounce = 100,
          status_formatter = nil,
          max_file_length = 40000,
          preview_config = {
            border = "rounded",
            style = "minimal",
            relative = "cursor",
            row = 0,
            col = 1,
          },
          yadm = {
            enable = false,
          },
        })
      end,
    }

so what am i doing wrong here?

![no linehl](https://github.com/lewis6991/gitsigns.nvim/assets/84800625/d4141446-2241-4325-8548-39c776926545)
![with linehl](https://github.com/lewis6991/gitsigns.nvim/assets/84800625/c3d5382e-941a-4a70-8016-ccff7fa5c56d)

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1702233742     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"  Run :checkhealth for more info

### Operating system and version

Hyprland, built from branch main at commit 927da86e3e76a8465c8b45fd7a87a34f25401b37  (hyprctl: fix dispatchBatch() treating empty curitem as last request (4681)). Date: Mon Feb 12 20:46:00 2024 Tag: v0.35.0-16-g927da86e  flags: (if any)

### Expected behavior

i should be able to see the color on top of linehl

### Actual behavior

linehl overrides (most probable cause) the nvim-colorizer color settings and i also tried updating nvim-colorizer with `ColorizerAttachToBuffer()` which does not do anything, like it reloads but linehl is dominant

### Minimal config

```Lua
require("gitsigns").setup({
    linehl = true,
})
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`

**Comment by lewis6991** [comment]
Not a Gitsigns issue, `linehl` cannot be overridden.

**Comment by daUnknownCoder** [comment]
> Not a Gitsigns issue, `linehl` cannot be overridden.

possible solution?
