### ISSUE TITLE
QUESTION: Can gitsigns and LSP diagnostic marks co-exist?

### ISSUE THREAD

**Issue by hahuang65** [lewis6991/gitsigns.nvim#95]
RIght now, if I have `gitsigns` and the default `nvim-lsp`, one overwrites the other if both SHOULD be on a line. Looks like the LSP overwrites the git sign for me.

Attached is a picture of it happening.
![Screen Shot 2021-03-16 at 21 13 24](https://user-images.githubusercontent.com/280972/111414074-99e6ec00-869c-11eb-8af7-3298a1d539c0.png)

Do you know of a way where both can exist in the `signcolumn` for the same line?

**Comment by lewis6991** [comment]
Checkout `:help 'signcolumn'`

**Comment by Shatur95** [comment]
@hahuang65, how did you fix this? I tried `set signcolumn=auto:4`, but I still have the following:
![изображение](https://user-images.githubusercontent.com/22453358/113789624-22125b80-9748-11eb-963e-72943d3c1b3d.png)

**Comment by hahuang65** [comment]
@Shatur95 I've set the `sign_priority`:

```
require('gitsigns').setup {
  sign_priority=100
}
```
Which I'm not sure is actually needed for this,
and I set `signcolumn=auto:4`, same as you.

It could be that your signs (if you're using different plugins than me) are coded different so the `auto:4` didn't do anything for you.

**Comment by Shatur95** [comment]
>  and I set signcolumn=auto:4, same as you.

It was a mistake on my side, it worked, thanks!

**Comment by winkee01** [comment]
How do you make `gitsign`'s signs align in the same column?
![image](https://user-images.githubusercontent.com/49930785/167247411-6a10eb36-ca77-4e81-86b8-b5d6e43e4bac.png)

**Comment by lewis6991** [comment]
You can't. It's a current limitation of multi signs in Neovim. Best you can do is adjust the priorities so Gitsigns marks always appear on the left.

**Comment by winkee01** [comment]
@lewis6991 I set it's priority to 100 (highest), but it does not change, it still appears in the rightmost

**Comment by lewis6991** [comment]
Try 0 then

**Comment by winkee01** [comment]
@lewis6991 that might work, but depends on how many diagnostic signs, otherwise it will be overlapped. 
Take an example, if `:set signcolumn=auto:2`, and there are two diagnostic signs, only diagnostics signs will be shown, `gitsign`'s sign will be covered. if there is only one diagnostic sign, then `gitsign`'s sign can be shown on the leftmost side(therefore align). 

![image](https://user-images.githubusercontent.com/49930785/167253919-43bcacaa-ff9c-412c-81c8-a3d2344755bb.png)

Looks like there isn't a decent solution.

**Comment by lewis6991** [comment]
Like I said, no. This is a limitation with neovim. Any solution is going to have issues.
