### ISSUE TITLE
gitsign cannot attach if nvim starts from "run" window

### ISSUE THREAD

**Issue by Jaehaks** [lewis6991/gitsigns.nvim#955]
### Description

thank you for your effort

i am windows 10 user
the problem is described below

1. execute "windows terminal"
2. enter "nvim" or "nvim-qt" and run 
3. gitsigns work properly

1. execute "run" window .   win+R
2. enter "nvim" or "nvim-qt" and run
3. gitsigns doest not work
(it means that if i modify some code, addbar does not display in signcolumn. without any messege)

1. execute "cmd" prompt
2. enter "nvim" or "nvim-qt" and run
3. gitsigns doest not work

### Neovim version

0.9.5

### Operating system and version

windows 10

### Expected behavior

gitsign is shown in signcolum at any starting point 

### Actual behavior

it only works in windows terminal

### Minimal config

```Lua
same as default config. not changed
```

### Steps to reproduce

describe above 

### Gitsigns debug messages

none

**Comment by lewis6991** [comment]
I guess this isn't supported. Gitsigns just calls `git` underneath.

I don't run Windows so I won't be able to look into this.

**Comment by Jaehaks** [comment]
> I guess this isn't supported. Gitsigns just calls `git` underneath.
> 
> I don't run Windows so I won't be able to look into this.

@lewis6991   OK, I get your point, 
In order to record about it,    the problem is git config 

In Windows, the ownership is different between terminal and run window
when I command ":!git status" in nvim-qt ,     ownership error is generated if I open nvim-qt from "run" window.   
But The error does not exist if I open nvim-qt from windows terminal because I execute "git init" in windows terminal (My guess)

So, If I enter this command like 
`git config --global --add safe.directory <working directory>`

The problem is solved.
