### ISSUE TITLE
Syntax highlighting fails after opening linehl

### ISSUE THREAD

**Issue by Charliego3** [lewis6991/gitsigns.nvim#958]
### Description

Using NvChad

https://github.com/lewis6991/gitsigns.nvim/assets/26761592/65202dcf-8390-4e23-bfdf-ae9f076f533c

### Neovim version

v0.9.5

### Operating system and version

macOS Ventura 13.6.5

### Expected behavior

When linehl is turned on, the background color changes, but the syntax highlighting remains unchanged.

### Actual behavior

When linehl is turned on, syntax highlighting is disabled and there is no background color.

### Minimal config

```Lua
require('gitsigns').setup {
    linehl = true,
}
```

### Steps to reproduce

1. `:Gitsigns toggle_linehl`

**Comment by lewis6991** [comment]
You need to configure the highlight `GitSignsAddLn` to not set a foreground.
