### ISSUE TITLE
Configuring git blame

### ISSUE THREAD

**Issue by Cih2001** [lewis6991/gitsigns.nvim#959]
I had to change this line in my local copy

https://github.com/lewis6991/gitsigns.nvim/blob/078041e9d060a386b0c9d3a8c7a7b019a35d3fb0/lua/gitsigns/git.lua#L642

to

```lua
  local args = { 'blame', '--contents', '-', '--incremental', '-C', '-C', '-C' }
```
I think It would have been nice if we could add settings to git blame command, to optionally add `-C` on blame. More info on `-C` with git blame: https://youtu.be/aolI_Rz0ZqY?si=0UGEs5VI6GGijyl1&t=713

**Comment by Cih2001** [comment]
I realized this is related to #953

**Comment by rubiin** [comment]
maybe something like an optional gitblame command option. The default being the one used now
