### ISSUE TITLE
Git current line blame overlap with text when split windows

### ISSUE THREAD

**Issue by ray-x** [lewis6991/gitsigns.nvim#966]
### Description

It is similar to https://github.com/lewis6991/gitsigns.nvim/issues/870
But the issue I saw is when I have split windows and `virt_text_pos` is `right_align`
See the recorded video on how to reproduce.

### Neovim version

NVIM v0.10.0-dev-2698+g00e71d3da

### Operating system and version

Mac

### Expected behavior

When resize the split, the current line blame should not overlap text

### Actual behavior

When resizing nvim screen split, the blame will overlap text

https://github.com/lewis6991/gitsigns.nvim/assets/1681295/ff1ef1e5-8b98-456e-9e09-83d636c7461e

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  current_line_blame = true, 
  current_line_blame_opts = {
    virt_text = true,
    virt_text_pos = 'right_align', -- 'eol' | 'overlay' | 'right_align'
    delay = 1000,
    ignore_whitespace = false,
    virt_text_priority = 100,
  },
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. split screen with `vp`
3. resize the screen size
4. see issue

Please refer to the screen shot

**Comment by lewis6991** [comment]
I've partially fixed this by adding `WinResized` to the main autocmd.

The issue still exists if the same buffer is in both splits. This can't be fixed until 0.10 is released with scoped extmarks.
