### ISSUE TITLE
error in executing `:Gitsigns preview_hunk_inline `

### ISSUE THREAD

**Issue by kumarvivek1752** [lewis6991/gitsigns.nvim#979]
### Description

when i try to run this command `:Gitsigns preview_hunk_inline `

it gives me error

```
Error executing Lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this messa
ge: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...l/share/nvim/lazy/g
itsigns.nvim/lua/gitsigns/actions.lua:221: attempt to index local 'bcache' (a nil value)                                          
stack traceback:                                                                                                                  
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function 'get_hunks'                                      
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:231: in function 'get_hunk'                                   
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:790: in function 'get_hunk_with_staged'                       
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:805: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsi
gns/actions.lua:802>                                                                                                              
stack traceback:                                                                                                                  
        [C]: in function 'error'                                                                                                  
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'f'                                          
        ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/cli.lua:100: in function <...local/share/nvim/lazy/gitsigns.nvim/lua/g
itsigns/cli.lua:65>                                                                                                               
stack traceback:                                                                                                                  
        [C]: in function 'error'                                                                                                  
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'run'                                        
        ...ek/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:112: in function <...ek/.local/share/nvim/lazy/gitsigns.nvim/l
ua/gitsigns.lua:111>                                                                                                              
Press ENTER or type command to continue  
```

### Neovim version

0.9.5

### Operating system and version

pop_os_22.4

### Actual behavior

error

```
Error executing Lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this messa
ge: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...l/share/nvim/lazy/g
itsigns.nvim/lua/gitsigns/actions.lua:221: attempt to index local 'bcache' (a nil value)                                          
stack traceback:                                                                                                                  
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function 'get_hunks'                                      
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:231: in function 'get_hunk'                                   
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:790: in function 'get_hunk_with_staged'                       
        ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:805: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsi
gns/actions.lua:802>                                                                                                              
stack traceback:                                                                                                                  
        [C]: in function 'error'                                                                                                  
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'f'                                          
        ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/cli.lua:100: in function <...local/share/nvim/lazy/gitsigns.nvim/lua/g
itsigns/cli.lua:65>                                                                                                               
stack traceback:                                                                                                                  
        [C]: in function 'error'                                                                                                  
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
        ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'run'                                        
        ...ek/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:112: in function <...ek/.local/share/nvim/lazy/gitsigns.nvim/l
ua/gitsigns.lua:111>                                                                                                              
Press ENTER or type command to continue  
```

### Minimal config

```Lua
return {

    'lewis6991/gitsigns.nvim',

    config=function ()
        require('gitsigns').setup()
        
    end
}
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. run this command in command mode `:Gitsigns preview_hunk_inline  `

**Comment by tribhuwan-kumar** [comment]
> Error executing Lua callback: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this messa
> ge: ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: The coroutine failed with this message: ...l/share/nvim/lazy/g
> itsigns.nvim/lua/gitsigns/actions.lua:221: attempt to index local 'bcache' (a nil value)                                          
> stack traceback:                                                                                                                  
>         ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua: in function 'get_hunks'                                      
>         ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:231: in function 'get_hunk'                                   
>         ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:790: in function 'get_hunk_with_staged'                       
>         ...l/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/actions.lua:805: in function <...l/share/nvim/lazy/gitsigns.nvim/lua/gitsi
> gns/actions.lua:802>                                                                                                              
> stack traceback:                                                                                                                  
>         [C]: in function 'error'                                                                                                  
>         ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
>         ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'f'                                          
>         ...local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/cli.lua:100: in function <...local/share/nvim/lazy/gitsigns.nvim/lua/g
> itsigns/cli.lua:65>                                                                                                               
> stack traceback:                                                                                                                  
>         [C]: in function 'error'                                                                                                  
>         ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:85: in function 'step'                                        
>         ...cal/share/nvim/lazy/gitsigns.nvim/lua/gitsigns/async.lua:112: in function 'run'                                        
>         ...ek/.local/share/nvim/lazy/gitsigns.nvim/lua/gitsigns.lua:112: in function <...ek/.local/share/nvim/lazy/gitsigns.nvim/l
> ua/gitsigns.lua:111>                                                                                                              
> Press ENTER or type command to continue  
> ```

This error is only appearing in non-buffer windows as an example when you try to execute `:Gitsigns preview_hunk_inline` in [`harpoon`](https://github.com/ThePrimeagen/harpoon) pop-up window or `no name` tab of Nvim. 
Kindly provide all the details about bug.

**Comment by lewis6991** [comment]
Sorry but this isn't a minimal config. Please follow the issue template.
