### ISSUE TITLE
null-ls format panic when apply path PR#983

### ISSUE THREAD

**Issue by 3Xpl0it3r** [lewis6991/gitsigns.nvim#986]
### Description

when I upgrade gitsigns to the latest version, then formatter supplied by none-ls was broken

### Neovim version

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

### Operating system and version

macos 14.2.1 (23C71)

### Actual behavior

<img width="1439" alt="image" src="https://github.com/lewis6991/gitsigns.nvim/assets/62287907/9fd19af8-7b73-4f52-9a32-e4f6369cfcc4">

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
  -- ADD OTHER PLUGINS _NECESSARY_ TO REPRODUCE THE ISSUE
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

require('gitsigns').setup{
  debug_mode = true, -- You must add this to enable debug messages
  -- ADD GITSIGNS CONFIG THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
}

-- ADD INIT.LUA SETTINGS THAT IS _NECESSARY_ FOR REPRODUCING THE ISSUE
```

### Steps to reproduce

1. `nvim --clean -u minimal.lua`
2. ...

**Comment by josuetorr** [comment]
got the same issue

**Comment by sinkr** [comment]
Same issue here.

**Comment by meronogbai** [comment]
dropping back to that commit fixed it for me too
